CMakeLists.txt, ext/bdwgc.cmake, ext/gdtoa.cmake, ext/hashmap.cmake, ext/onigmo.cmake, lib/natalie/compiler.rb
Heya!
I'm not much of a CMake expert, but I figured I might as well help towards #7.
As it stands, my additions are based off the `Makefile` in the master branch, so the intermediate external library builds spew out a lot of logs, this is not immediately fixable without cmake hacks, so I left that out.
Here's an overview of what this PR changes:
- Move all (needed) built external libraries and includes to build dir
- Make root CMakeFiles less verbose ('fancy')
- 'Fix' `compiler_command` to be explicit about library dependencies
- Swap out LIB_PATHS to LIB_NAMES for the compiler invocation
Also, might I interest you in `cmake .. -GNinja` for faster and more reliably incremental builds?
=> Build: General CMake-y improvements

include/natalie/kernel_module.hpp, lib/natalie/compiler/binding_gen.rb, src/bindings.cpp, src/kernel_module.cpp, test/natalie/loop_test.rb
This closes #4. "good first issue" indeed, made me look around the codebase :D 
Not sure whether the tests are sufficient, but that's all I could think of.
irrelevant idea: could this stuff be generated too? I know some stuff is implemented in ruby (`Array#permutations` for instance), so I'd think something as straightforward as `Kernel#loop` can too be generated?
=> Kernel: Add 'loop'

CMakeLists.txt
My CMake raises an error because `test` is a name that is reserved for internal use.
=> Change test target name

CMakeLists.txt, Makefile, ext/bdwgc.cmake, ext/gdtoa.cmake, ext/onigmo.cmake, include/natalie/io_value.hpp, lib/natalie/compiler.rb, src/kernel_module.cpp, src/main.cpp, src/natalie.cpp
Requires `gmake` to be installed, along with the `automake` and `autoconf` versions specified in the environment.
`-ldl` is not needed on OpenBSD, and I think is only used on Linux.  `RUBY_PLATFORM.match(/linux/)` would probably be nicer than shelling out to `uname` but I don't think that exists in Natalie yet. 
```
$ env AUTOCONF_VERSION=2.69 AUTOMAKE_VERSION=1.16 gmake
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -S . -B build -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="gmake"
-- The C compiler identification is Clang 10.0.1
-- The CXX compiler identification is Clang 10.0.1
[...]
[ 96%] Building CXX object CMakeFiles/natalie.dir/generated/struct.cpp.o
[ 98%] Linking CXX static library libnatalie.a
[100%] Built target natalie
cp build/compile_commands.json .
$ uname -srp
OpenBSD 6.8 …
```
=> Build on OpenBSD

Makefile, ext/bdwgc-openbsd.patch, ext/bdwgc.cmake, src/class_value.cpp
The bdwgc patch is kind of broad, but it fixes the crashing binary during tests.
The other two get all non-skipped tests passing without `dmesg` chatter, except for the first REPL test which seems to be a completely separate issue.
=> More OpenBSD fixes

lib/natalie/repl.rb, test/ruby/repl_test.rb
The failure of this test on OpenBSD was due to some differences in Readline/TTY handling which caused Readline to not echo the input back to the output when not on a TTY.  I spent some time trying to figure out why and how to force the echoing by using a PTY in `ReplWrapper`, but I couldn't get it to work properly.
In the end, I'm not sure it's that useful to test Readline's behavior anyway, so maybe the REPL should just print its output when STDOUT isn't a TTY, and the test can just check for the expected output.
🎄 🎁 🎅 
```
Finished in 496.087667s, 0.4334 runs/s, 0.5826 assertions/s.
215 runs, 289 assertions, 0 failures, 0 errors, 54 skips
```
=> Repl: If we don't have a TTY, don't use Readline

include/natalie/macros.hpp
This adds a new NAT_RUN_BLOCK_GENERIC macro that is called from
NAT_RUN_BLOCK_AND_POSSIBLY_BREAK_WITH_CLEANUP, NAT_RUN_BLOCK_AND_POSSIBLY_BREAK and NAT_RUN_BLOCK_WITHOUT_BREAK.
Disclaimer: This might be the first C++ code I've written, so not sure if I've made a stupid mistake...
=> deduplicate some NAT_RUN_BLOCK_* macros

include/natalie/value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/enumerable/tally_spec.rb, spec/core/hash/transform_values_spec.rb, spec/core/kernel/itself_spec.rb, src/enumerable.rb, src/hash.rb
This PR implements Enumerable#tally. To make the specs work I also needed to implement Object#itself and Hash#transform_values.
I'm kind of unsure about the implementation of Object#itself in CPP and about Hash#transform_values being in hash.rb instead of the HashValue class. Feel free to correct me if there are any mistakes 😅 
I also skipped Hash#transform_values! for now because it was not relevant to make the tally spec working.
=> Implement Enumerable#tally

test/support/spec.rb
Previously when running a test that throws an error, the summary message
of the spec reporter would report one passed and one errored spec. This
fixes this behavior by substracting the number of errored specs from the
passed spec count.
=> Fix "spec(s) passed" count if some specs errored

spec/core/enumerable/select_spec.rb, src/enumerable.rb
This PR fixes Enumerable#select so that the select_spec.rb passes.
=> Fix Enumerable#select

lib/natalie/compiler/method_args.rb, src/natalie.cpp, test/natalie/method_test.rb
This commit tries to fix #60, by calculating the `total_count` of arguments differently. 
Previously we only rejected keyword arguments which results in splats being counted into the total number of arguments.
This results in choosing the default value even though an argument is passed. 
See the following example:
```ruby
def foo(a = 2, *args)
puts [a, args]
end
foo(1)
```
The [if-condition](https://github.com/seven1m/natalie/blob/fix-default-with-splat/src/natalie.cpp#L122) evaluates to `true` because `remain` is calculated by subtracting the number of arguments passed and the number of required arguments which is calculated by the `total_count` passed. 
Here `ary_len` would be 1, `total_count` would be 2, which results in `required_count` being 1.
`remain` would then evaluate to 0, …
=> Trying to fix the argument count when calling a method with a splat

spec/core/enumerable/first_spec.rb, spec/core/enumerable/slice_when_spec.rb, src/enumerable.rb, src/kernel.rb
This also fixes `Enumerable#first`, sets the default argument for `Kernel#enum_for` and adds an alias to `Kernel#to_enum`.
=> Implement Enumerable#slice_when

spec/core/enumerable/filter_spec.rb, spec/core/enumerable/find_all_spec.rb, src/enumerable.rb
[#19]
Adds a couple of method aliases for `#find_all` and `#filter`
[ruby 2.7.3 Enumerable#filter](https://ruby-doc.org/core-2.7.3/Enumerable.html#method-i-filter)
[ruby 2.7.3 Enumerable#find_all](https://ruby-doc.org/core-2.7.3/Enumerable.html#method-i-find_all)
=> Adds aliases for Enumerable#find_all and Enumerable#filter

spec/core/enumerable/slice_before_spec.rb, src/enumerable.rb, test/support/spec.rb
This patch implements Enumerable#slice_after, Enumerable#slice_before and some more stuff in spec.rb.
I'm particularly not happy with the argument checking... Also I do not really get the issue with the FIXME above it. When moving the condition directly into the if-statement some specs are not passing...
=> Implement Enumerable#slice_after and Enumerable#slice_before

spec/core/enumerable/entries_spec.rb, spec/core/enumerable/shared/entries.rb, src/enumerable.rb
[#19]
Let me know if this is a stretch. Looking over the ruby [`#entries`](https://ruby-doc.org/core-2.7.3/Enumerable.html#method-i-entries) documentation, it seemed like the entries implementation didn't seem to far off from `#to_a`.
=> Implement Enumerable#entries

spec/core/enumerable/max_by_spec.rb, spec/core/enumerable/min_by_spec.rb, src/enumerable.rb
The "min/max n elements" implementation is not the most efficient, but their implementations within Enumerable#max and Enumerable#min did not seem the veryefficient either, so I figured this was "good enough"
=> Add Enumerable#max_by and Enumerable#min_by methods

spec/core/enumerable/minmax_by_spec.rb, spec/core/enumerable/minmax_spec.rb, src/enumerable.rb
The simplest way would be to use `Enumerable#sort` here, but one spec requires that objects that appear first will be returned first in case of a tie, which is not guaranteed with `Enumerable#sort`.
[#19]
=> Implement Enumerable#minmax and Enumerable#minmax_by

spec/core/enumerable/find_index_spec.rb, src/enumerable.rb, test/support/spec.rb
One quick note: Ideally we would return directly from the `each` block but somehow one spec is failing when doing so...
=> Implement Enumerable#find_index

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/flatten_spec.rb, src/array_value.cpp, test/support/spec.rb
Partially implements Array::flatten from #39 with the exception of:
- Returning an instance of a subtype of Array when flatten is invoked on said subtype
- Make use of respond_to_missing and method_missing in value for when respond_to would otherwise return false. These methods seem to be more something we should implement in Value and in a separate PR/Issue, but if preferred I'll gladly cover both in this PR.
I'm quite new to both Ruby and C++ so I'll be extremely glad to take any suggestion and critique :)
=> Implement Array::flatten

include/natalie/array_value.hpp, include/tm/vector.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/flatten_spec.rb, src/array_value.cpp
Partially implements Array::flatten! from #39 with the exception of:
- Make use of respond_to_missing and method_missing in value for when respond_to would otherwise return false. These methods seem to be more something we should implement in Value and in a separate PR/Issue, but if preferred I'll gladly cover both in this PR.
Followed suggestion from #75 and replaced vector with Hashmap.
=> Array flatten in place

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/compact_spec.rb, src/array_value.cpp
Implement Array::compact! from #39 and adds the spec for both compact and compact!
compact was already implemented and I kept it as it easy as it is much simpler to add elements to a new array rather than creating a copy of the current one and then compacting that.
=> add spec for Array::compact and compact! and implement Array compact!

include/natalie/range_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/enumerator/lazy/chunk_spec.rb, spec/core/enumerator/lazy/drop_spec.rb, spec/core/enumerator/lazy/drop_while_spec.rb, spec/core/enumerator/lazy/shared/collect.rb, spec/core/enumerator/lazy/shared/collect_concat.rb, spec/core/enumerator/lazy/shared/select.rb, spec/core/enumerator/lazy/shared/to_enum.rb, spec/core/range/first_spec.rb, spec/core/range/shared/begin.rb, src/enumerator.rb, src/range_value.cpp, test/support/spec.rb
This also removes the binding for Range#first, because Range includes the Enumerable module that provides this method.
=> Implement Enumerator::Lazy#drop and Enumerator::Lazy#drop_while

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/reverse_each_spec.rb, spec/core/array/shared/enumeratorize.rb, src/array_value.cpp
Skipping the recursion guarding tests as those make use of append, which hangs on forever when used recursively, thus making the tests fail. Since append is part of the specs in #39 I'll leave that implementation for later and skip those tests right now.
=> Implement Array::reverse_each

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/zip_spec.rb, src/array_value.cpp, src/enumerable.rb
Array::zip from #39 
The implementation itself is trivial as it relies on zip from enumerable, but that and some good old investigation on MRI revealed that in fact, the ruby spec was not explicitly covering the scenario where calling :each would return a non-array value, which is in fact supported by MRI
```ruby
class E 
include Enumberable
def each
yield 1
yield 2
yield 3
end
end
irb(main):025:0> E.new.zip(E.new)
=> [[1, 1], [2, 2], [3, 3]]
```
=> Array zip implementation

include/natalie/array_value.hpp, spec/core/array/fixtures/encoded_strings.rb, spec/core/array/inspect_spec.rb, spec/core/array/shared/inspect.rb, spec/core/array/shared/join.rb, spec/core/array/to_s_spec.rb, src/array_value.cpp
Implement Array::to_s and inspect from #39 
Added spec for to_s and inspect. To_s really just calls inspect so I made inspect spec compliant. Classical case of to_birds with one stone. Sorry...
=> Array to_s and make inspect spec-compliant

include/natalie.hpp, include/natalie/array_value.hpp, include/natalie/recursion_guard.hpp, src/array_value.cpp, src/hash_value.cpp
Added a simple and probably naive mechanism to handle recursion guarding across various objects. Can handle the now infamous dirty_inspect.rb case described in #97 
% ./bin/natalie ./dirty_inspect.rb 
"[[Up and counting 1]]"
"It went boom!"
"[[Up and counting 3]]"
=> Generic recursion guard

spec/core/array/eql_spec.rb, spec/core/array/equal_value_spec.rb, spec/core/array/shared/eql.rb, src/array_value.cpp
Implemented both eql? and == from #39 .
The test "compares with an equivalent Array-like object using #to_ary" highlighted an issue on how we use respond_to? in natalie's standard library. We rely on calling the method on the c++ impl rather than send the event "respond_to? :method_name" so mocks won't be able to correctly override such value and neither will anything else :) We should replace all the direct respond_to with the ruby method and maybe create a utility that wraps `send(env, Symbol::intern("respond_to?")...)` so the ergonomics won't change much for us but natalie will in fact behave correctly. What do you think about this?
=> Array equality

include/tm/defer.hpp
Just a minor thing I noticed while watching @seven1m's latest video, nothing too major :)
This is not going to make a difference in most cases, but there are some
possible scenarios where copying the callable object would not be
possible (e.g. when the lambda captures a smart pointer that doesn't
allow copying, like `std::unique_ptr`).
=> defer: Forward the callback object instead of copying it

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/map_spec.rb, spec/core/array/shared/collect.rb, src/array_value.cpp
Implements map! from #39, adds the spec for both map and map! and makes map use its inplace counterpart under the hood to reduce the duplication
=> add Array::map! and make map use it under the hood

lib/natalie/compiler/binding_gen.rb, spec/core/array/deconstruct_spec.rb
Hardest method from #39 . Interestingly enough this seems to be only available only on ruby < 3
=> implement Array::deconstruct

spec/core/array/reverse_each_spec.rb, spec/core/array/reverse_spec.rb
specs for #39 for all the reverse mehods. Uncomment excluded tests with recursion since now recursive equality is supported :^)
=> add spec for array's reverse methods

spec/core/array/sort_spec.rb, spec/core/array/to_a_spec.rb, spec/core/array/to_ary_spec.rb, spec/core/array/uniq_spec.rb, spec/core/array/zip_spec.rb
follow up to #105 , now that proper recursive equality is in place, we can get rid of all the exclusions we had in Array specs. I have not included reverse_each since it's addressed by #130 (that was actually what made me notice this :^) )
PS: this was extremely relaxing and soothing, skipping tests always makes me feel really uncomfortable!
=> Array remove recursive spec check exclusions

src/main.cpp
Hey I'm finally back 👋
I found a small issue that I wanted to fix. When running code that compiles but throws an exception when running, Natalie will exit with a zero status instead of a non-zero one (1 for MRI).
Example:
```
bin/natalie -e "1.bar"
echo $?
``` 
If an exception occurred that is not handled by the user, we returned a `NilValue` from `EVAL` which resulted in returning a zero return code. I'm not sure if my solution to this problem is appropriate, so please tell me if there is a better way for this!
=> Fix return code if an unhandled exception occurrs

spec/core/array/first_spec.rb, src/array_value.cpp
Added spec to Array::first and made it compliant as per #39 . Currently ignoring the test using replace as that is not implemented yet and the one using bignum_value as that would not even compile.
[bignum_value](https://rubydoc.org/gems/rhodes/Object:bignum_value) implementation
Leads to:
```
/tmp/natalie.cpp20210912-722288-brxn2a:1103:54: error: integer constant is so large that it is unsigned [-Werror]
1103 |     ValuePtr ValuePtrinteger1357 = ValuePtr::integer(9223372036854775808);
|                                                      ^~~~~~~~~~~~~~~~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors
4: from …
```
=> make Array first spec compliant

.github/workflows/run_all_specs.yml, Gemfile, Gemfile.lock, spec/support/ruby_spec_runner.rb
We are constantly working on improving spec compliance for Natalie. I think it is very interesting to see the progress we are making with this. This Github Action workflow will run one time each day and run all specs from ruby/spec against Natalie. 
The current results are:
```
Success: 2525
Failures: 1389
Errors: 6202
Compile Errors: 1403
Crashes: 847
Timeouts: 7
```
Compile Errors, Crashes and Timeouts count per file while Success, Failures and Errors count per example. The results can only be seen manually by looking at the action log for now.
=> Add a Github Action workflow to run all ruby specs

spec/core/hash/to_proc_spec.rb, src/hash.rb, test/support/spec.rb
Please not that this targets Ruby 2.7. With Ruby version > 3 this should return a lambda instead of a proc.
=> Implement Hash#to_proc

include/natalie/hash_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/hash/except_spec.rb, src/hash_value.cpp
I do not know if there is an easier way of copying the hash. I cannot use the constructor like `new HashValue { *this }`, because it expects the new Hash to be of class Hash (and not of a sub class). Is there an easier way to do it?
=> Implement Hash#except

include/natalie/hash_value.hpp, lib/natalie/compiler/binding_gen.rb, src/hash.rb, src/hash_value.cpp, test/natalie/hash_test.rb
Noticed this bug while working on `Hash#slice`:
Previously we double-negated the returned key from `Hash#key`. However,
this method returns `nil` when no key is found. As hash keys can also
be `nil`, we cannot differentiate between a found key that's `nil` and
no found key.
=> Fix behavior of Hash#value? if value is falsey

include/natalie/hash_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/hash/keep_if_spec.rb, src/hash_value.cpp
This also fixes a small bug in Hash#delete_if, where the wrong method is sent to Kernel#enum_for if no block is passed.
=> Implement Hash#keep_if

include/natalie/hash_value.hpp, include/natalie/value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/hash/compare_by_identity_spec.rb, spec/core/hash/rehash_spec.rb, src/hash_value.cpp, test/support/spec.rb
Instead of using the `hash` method I'm using the `object_id` when `Hash#compare_by_identity` is called as the hash for the hash map. This seems to be working fine....
I'm not sure about the `rehash` implementation. Maybe we can make this more elegant?
=> Implement Hash#rehash and Hash#compare_by_identity(?)

spec/core/hash/deconstruct_keys_spec.rb, src/hash.rb
The method does not seem to have any use and the spec only runs for
rubies with version 2.7, so I'm not sure what the purpose is. However,
here it is :^)
=> Implement Hash#deconstruct_keys

include/natalie/module_value.hpp, include/natalie/value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/hash/initialize_spec.rb, src/hash_value.cpp, src/value.cpp
I did not see another way of defining a private method, then defining it and making it private afterwards. Is there better way to do this?
=> Make Hash#initialize spec compliant

spec/core/hash/shared/eql.rb, src/hash_value.cpp
This adds support for recursive Hashes. Thanks to the example in ArrayValue this was easier than I could have thought 😄
=> Make Hash#eql? and Hash#== spec compliant

CONTRIBUTING.md
Just noticed this little leftover from make when github suggested me to review the new contribution guidelines ;)
=> Replace make with rake in contribution guidelines

spec/core/array/take_spec.rb, spec/core/array/take_while_spec.rb
#39 
I believe this just uses the `Enumerable#take` and `Enumerable#take_while`, methods. Is that okay to do here or would it be preferable for array_value.cpp to have take and take_while methods defined?
=> Add specs for Array#take and Array#take_while

test/natalie/array_test.rb, test/support/spec.rb
The test is still quite naive and only generates around 50k test cases and those are all very short arrays, so it is quite biased. Regardless it is still nice to have and see that we actually outperform MRI in this scenario (0.9190165737176968% vs 11.5%), which implies that this is 'good enough' for ruby and in theory won't need any further improvement in the foreseeable future. With this we should be able to close #188
=> Implement test to check that our collision rate for Array::hash is comparable or lower MRI's collision rate

include/natalie/hash_builder.hpp, include/natalie/hash_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/hash/hash_spec.rb, src/hash_value.cpp
Implement hash::hash from #96 . As per Array, we won't yet implement recursive hashes through arrays (test case "returns the same hash for recursive hashes through arrays"), but instead those will be separately tracked as they are both rather intertwined and may require some intervention on the eql? methods of both.
=> implement Hash::hash

spec/core/hash/ruby2_keywords_hash_spec.rb
This is just for completeness. In ruby 3 this method does not exist anymore.
=> Add spec for Hash#ruby2_keywords_hash?

spec/core/array/clone_spec.rb, spec/core/array/shared/clone.rb, src/kernel_module.cpp
Added spec for Array::clone from #39 and added the 'copy singleton methods' behaviour MRI has. Since this does not look restricted to just Array, I've done that in Kernel itself and said behaviour does not exist with dup, so it's just for clone :)
=> make Array::clone spec compliant

include/natalie/value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/comparable/between_spec.rb, spec/core/comparable/clamp_spec.rb, spec/core/comparable/equal_value_spec.rb, spec/core/comparable/fixtures/classes.rb, spec/core/comparable/gt_spec.rb, spec/core/comparable/gte_spec.rb, spec/core/comparable/lt_spec.rb, spec/core/comparable/lte_spec.rb, src/comparable.rb, src/kernel.rb, src/value.cpp, test/natalie/comparable_test.rb
This also moves `Kernel#<=>` from Object to the Kernel module and makes it spec compliant as well. I'm not sure about the `!is_a?(Comparable)` but I do not know how to prevent the possible infinite recursion otherwise.
=> Make Comparable spec compliant

include/natalie.hpp, lib/natalie/compiler/method_args.rb, src/natalie.cpp, test/natalie/method_test.rb
Fix "FIXMEs" of natalie's method test. This contains fixes for the following scenarios:
When passed a Hash to a method that has default arguments, we would assign the hash to the default argument even if it has keyword arguments that should be matched to the hash.
```ruby
def foo(a, b = 'b', **c)
[a, b, c]
end
foo(1, c: 'c', d: 'd').should == [1, 'b', { c: 'c', d: 'd' }
```
The second scenario is that keyword arguments that were successfully extracted from the keyword hash, should not be present in the "rest" (when using double-splats).
```ruby
def foo(a: 'a', **b)
[a, b]
end
foo(a: 1, b: 2, c: 3).should == [1, { b: 2, c: 3 }] 
```
=> Try to fix keyword argument processing

include/natalie/array_packer/integer_handler.hpp, include/natalie/array_packer/packer.hpp, include/natalie/array_packer/string_handler.hpp, include/natalie/array_packer/tokenizer.hpp, spec/core/array/pack/shared/unicode.rb, spec/core/array/pack/u_spec.rb, src/array_value.cpp, test/support/spec.rb
Added support for the u/U directives for Array#pack (#195):
- u -> uu-encoding of a string (https://en.wikipedia.org/wiki/Uuencoding)
- U -> UTF-8 encoding of a number
There is quite a bit going on in here :) 
- I've simplified the index tracking in StringHandler as in fact only a single index was needed to begin with
- Now be_computed_by expands the subject if it contains args to be passed to the method to test (an example of this can be found in the u spec ;) )
- Added an IntegerHandler that only currently supports the U directive
- Packer now returns a StringValue instead of a String so directives can now change the encoding (both u and U do, but u uses an ASCII encoding we do not support yet)
- When parsing tokens we now skip the count modifier of a directive if it is a zero byte (MRI …
=> Array pack u directive

include/natalie/gc/allocator.hpp, src/gc.cpp
Previously we were looping through each block to find the next one with
a free cell. We had a early return but on some measurements I did the
loop ran on a average 60 iterations.
This patch introduces a list for keeping track which block has free
cells. Each time we want to allocate something we can just use the last
block of this list and do not have to iterate anymore.
Right now I use `push` and `pop` to add and remove from the vector. However, this means that a block newly pushed to the list will be picked first (LIFO). I made this decision because adding to and removing from the end of a vector is much more efficient but I'm not sure if the above is a problem for us. What do you think?
I've looked at two scripts:
```ruby
ary = []
(0..100_000).each { |n| ary << n + 1 }
```
Execution …
=> Don't look through all blocks when allocating new cells

lib/natalie/compiler.rb
Trying to use Natalie in different directory then one with project was raising an error:
```console
$ ~/repos/natalie/bin/natalie
/home/robert/repos/natalie/lib/natalie/compiler.rb:2:in `require': cannot load such file -- ./lib/sexp_processor (LoadError)
from /home/robert/repos/natalie/lib/natalie/compiler.rb:2:in `<top (required)>'
from /home/robert/repos/natalie/lib/natalie.rb:1:in `require_relative'
from /home/robert/repos/natalie/lib/natalie.rb:1:in `<top (required)>'
from /home/robert/repos/natalie/bin/natalie:12:in `require_relative'
from /home/robert/repos/natalie/bin/natalie:12:in `<main>'
```
This changed fixed this isssue, but I'm not Ruby developer so this may be wrong solution
=> Fix wrong require_relative path

include/natalie/bignum_value.hpp, include/natalie/integer_value.hpp, spec/core/integer/divide_spec.rb, spec/core/integer/lt_spec.rb, spec/core/integer/minus_spec.rb, spec/core/integer/multiply_spec.rb, src/big_int.cpp, src/bignum_value.cpp, src/integer_value.cpp
This makes `Integer#-`, `Integer#*` and `Integer#/` spec compliant and fixes a bad bug that I introduced with BigInt!
I'm currently quite busy with university which is why I could not contribute that much in the last weeks 😞
=> Make Integer calculations spec compliant

spec/core/array/bsearch_index_spec.rb, spec/core/array/shared/slice.rb, src/integer_value.cpp, test/natalie/integer_test.rb, test/support/spec.rb
Yesterday I messed up the overflow detection of some of the new Integer calculation methods. This should fix now...
This also adds tests to check if the detection works correctly.
=> Fix overflow calculation of Integer#* and Integer#-

.github/workflows/build.yml, test/support/spec.rb
And here it is: My own little helper to prevent mistakes with focused specs 😅
=> Raise an error if a focused spec is running in CI

include/natalie/bignum_value.hpp, include/natalie/integer_value.hpp, spec/core/integer/odd_spec.rb
This should tick one more box in #201. @TheGrizzlyDev I've decided to open this PR just so we don't pollute the issue thread. Like I said in discord, this is all quite new to me.
I'm also making this a draft just to make it clear this is not ready for reviewing and merging.
That being said, I did try to lookup how to make odd work for Bignums by looking at the MRI, but I don't think I'm actually implementing odd right even for a simple Fixnum
~Basing myself on the other methods, I added and IntegerValue argument to odd, in order to test wether it's a bignum, but I'm unsure if that's the correct thing to do.~
~I've not actually implemented an `odd` method for Bignum because I'm still trying to understand what a Bignum is and what does it mean to ask wether it is an odd number or not, in …
=> Implement `odd?` for the `Integer`

README.md
This is to address some of the questions in #269.
=> Add some docs about specs/tests

include/natalie/value_ptr.hpp, src/integer_value.cpp, src/value_ptr.cpp
Hello friends! :^)
Here are some patches to keep us on the happy path more often (by avoiding hydrating `Type::Integer` `ValuePtr`s)
With these changes, a simple increment loop runs ~twice as fast (from ~300ms to ~150ms):
```ruby
i = 0
while i < 1000000
i += 1
end
```
=> Less integer hydration

spec/core/string/shared/to_s.rb, spec/core/string/to_s_spec.rb, spec/core/string/to_str_spec.rb
Bit of a cheeky contribution since these are already spec-compliant but were missing, figured I'd add them in :)
Related to #217.
=> Add String#to_s and String#to_str specs

Rakefile, include/natalie/constants.hpp, src/integer_value.cpp, test/natalie/integer_test.rb
By moving the checks before the actual overflow can happen when doing multiplications. This pattern could be applied more extensively and will also be needed for pow when we do implement it.
I've also updated the constants for min and max finums in Natalie.
=> Handle behaviours of Integer over when swapping between fixnum/bignum

spec/support/ruby_spec_runner.rb
Beforehand, we were checking if the spec process exited normally. If not
we assumed that it would have timeouted.
However, some specs exit with an SIGABRT, which means they did not exit
normally. This led to them not being marked as crashed.
With this patch, instead of relying on the status, we use the current
spec details to determine whether the process timed out.
=> Try to detect crashed specs better

.github/workflows/run_all_specs.yml, spec/support/nightly_ruby_spec_runner.rb
This patch renames the spec runner to make it clearer that this file is used in CI. It also adds a comment on top of the file to document that further.
I'm obviously open to other names for the runner but I think this one would make it clear enough already.
Also my editor seemed to auto-re-format the github workflow file. Hope that's fine...
=> Make purpose of our spec runner clearer

spec/core/integer/shared/next.rb, spec/core/integer/succ_spec.rb, src/integer_value.cpp
Related to #201.
Looks like the `Bignum` related test cases don't appreciate the user of negative `Bignum`s, is this something has come across before (leaving as draft due to this) [related test case](https://github.com/seven1m/natalie/pull/274/files#diff-30318ffd0c8ee8a305d9881b674ebb39a69910b54cc6a74303478ff9edb991d6R14).
=> Make Integer#succ spec compliant

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, src/array_value.cpp
Previously we only had the in-place variant and said difference might have been overlooked by the specs, so I have the non-in-place version which just uses uniq! under the hood.
=> Add Array::uniq to Array

include/natalie.hpp, lib/natalie/compiler/base_pass.rb, lib/natalie/compiler/method_args.rb, lib/natalie/compiler/multiple_assignment.rb, lib/natalie/compiler/pass1.rb, lib/natalie/compiler/pass4.rb, src/natalie.cpp
This worked on clang, but not on gcc. Trying to get the syntax right...
=> Clean up arguments to {arg,array}_value_by_path

include/natalie/array_object.hpp, src/natalie.cpp
Cool project! Was playing around with the fib example and noticed that it was taking a while to run. I profiled it and found that most of the time was being spent in the `args_to_array()` method. It seems like there's a lot of GC traffic because of the allocations/frees when resizing the array. I didn't dig too deep into the root cause for that but figured giving the array an initial size would mitigate it for now.
Before:
```
ohadrau@SurfaceBook2:~/projects/lang/natalie$ time ./fib.old
75025
real    0m0.632s
user    0m0.602s
sys     0m0.030s
```
After:
```
ohadrau@SurfaceBook2:~/projects/lang/natalie$ time ./fib
75025
real    0m0.173s
user    0m0.135s
sys     0m0.038s
```
=> Speed up `args_to_array()`

include/natalie/gc/allocator.hpp, src/gc.cpp
Heap::collect() previously spent a lot of its time checking
whether a candidate block was a member of an allocator (when
collecting roots). This was an O(n) operation, where n is the
number of blocks in the allocator. To speed this up, we can
use a Hashmap as a set to quickly check in O(1). This brings
Heap::collect() down from 27.71% of dynamic instrs to 10.47%
in examples/boardslam.rb and probably benefits other code as
well.
The new code is a little funky and could benefit from a
Hashset class instead of a Hashmap in a future change.
=> Use Hashmap to store Allocator blocks instead of Vector

src/symbol_object.cpp
This should avoid a strcmp for the equal case
This would be even better if we could avoid strcmp all along for most comparisons
There does not seem to be a significant impact on performance
With just the pointer compare only one test would fail, so there seems to be some more gains we can get from this:
```
Failed specs:
instance variables
#instance_variables
returns an array of all instance variable names
[:@y, :@x] should be == to [:@x, :@y] (line 15)
6 spec(s) passed.
1 spec(s) failed.
0 spec(s) errored.
FAIL Natalie tests::test/natalie/ivar_test.rb#test_0001_has the same output in ruby and natalie (417.22s)
Expected #<Process::Status: pid 13758 exit 1> to be success?.
/home/leon/natalie/test/support/compare_rubies.rb:9:in `run_nat' …
```
=> Use the fact that equal Symbols have equal addresses for comparisons

include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/case_compare_spec.rb, src/integer_object.cpp
According to ruby documentation and the specs the two methods are equivalent so we can remove the old implementation of Integer#===.
[#201]
=> Make Integer#=== an alias to Integer#==

include/natalie/env.hpp, include/natalie/fiber_object.hpp, src/env.cpp, src/fiber_object.cpp, src/value.cpp
This bug was discovered as a result of layout/size change of `Value` in #296. Something about that PR exposed a flaw in our GC, when compiler optimizations are enabled, that resulted in some variables being collected too early.
I wrote up a more detailed explanation in the commit b64f58a7d8f408b08b2eda9521adeafaa23faf74.
As a bonus, I also found and fixed [a bug](6a211b67062b74eedf8aa32e835f719d87bd2dbd) in our Fiber aarch64 assembly when compiler optimizations are enabled.
=> Fix bugs walking captured variables from stack-allocated Envs

include/natalie/value.hpp, src/value.cpp
This decreases the size of Value by unionising the Object* and the fast_integer.
The test-performance does not seem to be affected significantly by this, but it
is still nice to decrease the memory footprint a bit.
=> Unionise Value

src/range_object.cpp, test/natalie/range_test.rb
This is a small optimization for Range#include? when operating on numeric values. Previously, the method would iterate over all values from begin to end and compare them to the argument. Thankfully, the [Ruby spec](https://ruby-doc.org/core-3.0.3/Range.html#include-3F-method) allows us to implement this as equivalent to Range#cover? for numbers. In other words, we're able to simply do `arg >= begin && arg <= end`, which is a lot faster :) This PR also goes a little further and optimizes for fast integers whenever possible
=> Optimize Range's include? method for numeric values

include/natalie.hpp, spec/core/integer/comparison_spec.rb, src/big_int.cpp, src/integer_object.cpp, src/natalie.cpp
I do not like the way I have to use the same if-condition twice in IntegerObject::cmp. Does somebody have an idea how this code could be done in a nicer way? 🤔 
[#201]
=> Make Integer#<=> spec compliant

include/natalie/symbol_object.hpp, src/symbol_object.cpp
I am not yet satisfied with the semantics of the constructor, but as a first draft this should suffice.
The impact on performance of the tests seems to be small.
=> Don't allocate copies of compile-time c-strings in Symbol

include/natalie/kernel_module.hpp, include/natalie/string.hpp, include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/coerce_spec.rb, spec/core/integer/comparison_spec.rb, spec/core/kernel/Float_spec.rb, src/integer_object.cpp, src/kernel_module.cpp, src/string_object.cpp
This patch also implements `Kernel#Float` as it is needed to implement `Integer#coerce` for String arguments.
Also while working on this I noticed that our keyword argument handling seems to be pretty broken. I might look into this next 😄 
[#201]
=> Make Integer#coerce spec compliant

include/natalie/lexer.hpp, include/natalie/parser.hpp, include/natalie/token.hpp, src/parser.cpp, test/natalie/parser_test.rb
For example:
```rb
class Matrix
def Matrix.[](*rows)
rows
end
end
Matrix[1,2,3] # => [1,2,3]
Matrix.[](1,2,3) # => [1,2,3]
```
=> Parse method names with `[]` and `[]=`

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/concat_spec.rb, spec/core/string/shared/concat.rb, src/string_object.cpp
There's quite a few encodings being used here that we don't support at the moment so I'm skipping those and adding a `NATFIXME` comment above.
The rest of the spec is passing though. Not entirely sure what it takes to add support for other encodings.
=> Make `String#concat` (mostly) spec compliant

spec/grab
This adds a small CLI app at `spec/grab` that can be used to quickly grab specification files from the `ruby/spec` repo.
Here's the basic usage:
```bash
./spec/grab core/integer/floor_spec.rb
```
This command will retrieve the `core/integer/floor_spec.rb` file from the repository and attempt to write to to `./spec/core/integer/floor_spec.rb`.
If the file already exists, it'll panic and fail. You can force the file to be created by providing a `--force` option, i.e. `./spec/grab core/integer/floor_spec.rb --force`.
If the spec can't be found, it'll panic too and show you the URL it was trying to hit.
> **NOTE:** This CLI requires system Ruby to be used because we're relying on the `net/http` and `uri` packages from the runtime library.
=> Introduce a Ruby Specification Grabber tool

include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/size_spec.rb, src/integer_object.cpp
> **NOTE:** Skipping over Bignums for now. We won't likely be able to match the spec for `Integer#size` since it's an internal implementation detail.
=> Make `Integer#size` (mostly) spec compliant

spec/core/kernel/Array_spec.rb, src/kernel_module.cpp
Removed special case for `nil` to match MRI:
```rb
Array(nil) # => []
if NilClass.respond_to? :undef_method
NilClass.undef_method :to_a
Array(nil) # => [nil]
end
NilClass.define_method :to_a do
[1,2,3]
end
Array(nil) # => [1,2,3]
```
=> Make `Kernel#Array` spec-compliant

include/natalie/array_packer/packer.hpp, include/natalie/method_object.hpp, include/natalie/module_object.hpp, src/array_object.cpp, src/class_object.cpp, src/exception_object.cpp, src/file_object.cpp, src/float_object.cpp, src/hash_object.cpp, src/io_object.cpp, src/kernel_module.cpp, src/module_object.cpp, src/natalie.cpp, src/object.cpp, src/string_object.cpp
Error using `class_name_or_blank`:
```rb
anonymous_class = Class.new
'string'.force_encoding anonymous_class.new # => TypeError (no implicit conversion of  into String)
```
Error using `inspect_str`:
```rb
anonymous_class = Class.new
'string'.force_encoding anonymous_class.new # => TypeError (no implicit conversion of #<Class:0x7fcf44827020> into String)
```
=> Fix error messages that may reference anonymous classes

lib/natalie/compiler/pass0c.rb, lib/natalie/compiler/pass1.rb, test/natalie/case_when_test.rb, test/natalie/compiler_test.rb
This adds the ability to coalesce constant arithmetic and if-statements to pass0c
With this we should save some send calls on primitive data types
Here follows a quick demonstration
<details>
<summary>input</summary>
```ruby
x = 1 unless true
1 & 3
2 | 1
3 ^ 2
1 << 4
32 >> 3
[1, 2, 3].max
[-1,2,3].min
1 < 2
-1 < 1
defined?(1 + 1)
1 + 1 + 1
1 * 2
3 * 4
6 / 3
1.0 + 3
3.0 + 1.0
3.0 * 6
1.0 / 2
1.0 / 0
1.0 % 0.5
5 % 3
16 % 9
12.349 % 1
2 <=> 3
1 === 0.0
!false
if (1+1 == 0)
do_something
elsif (1+1 == 2)
do_something_else
else
do_nothing
end
```
</details>
<details>
<summary>ast</summary>
```ruby
s(:block,
s(:if, s(:true), nil, s(:lasgn, :x, s(:lit, 1))),
s(:call, s(:lit, 1), :&, s(:lit, 3)),
s(:call, s(:lit, 2), :|, s(:lit, 1)),
s(:call, s(:lit, 3), :^, s(:lit, 2)),
s(:call, s(:lit, 1), :<<, …
```
=> Some more canary features [basic constant evaluation in p0c]

spec/core/integer/even_spec.rb
Adds the `Integer#even?` spec. This passes for fixnums, but no bignums. I imagine #345 will likely resolve that.
=> Add `Integer#even?` spec

Rakefile, include/natalie/big_int.hpp, include/natalie/bignum_object.hpp, include/natalie/constants.hpp, include/natalie/integer_object.hpp, spec/core/array/bsearch_index_spec.rb, spec/core/float/round_spec.rb, spec/core/integer/divide_spec.rb, spec/core/integer/exponent_spec.rb, spec/core/integer/odd_spec.rb, spec/core/integer/shared/exponent.rb, spec/core/integer/to_f_spec.rb, src/big_int.cpp, src/bignum_object.cpp, src/integer_object.cpp, src/string_object.cpp
This was some fun 😅 
There are some points to take a closer look here:
* Ruby does not allow pow-ing that results in *really* large numbers. There seems to be some threshold related to the size the resulting bigint would need. I tried to replicate the behavior but the boundary is different between natalie and MRI for now.
* I'm not sure if the constant definition in natalie/constants.hpp is ok? I wanted to use constexpr but I can not because sqrt is not a constexpr... Please correct me if we should use something else.
* BigInt's division algorithm seems to be doing something different that what MRI does. I did not want to investigate further for this PR but we might want to look at this (basically `-100000000000000000000000000000000000000000000000000 / …
=> Make Integer#** spec compliant

test/support/spec.rb
These lines should be referencing the local variable `value` not the instance variable `@value`
=> Fix variable names in IncludeExpectation methods

include/natalie/method.hpp, include/natalie/method_info.hpp, include/natalie/module_object.hpp, spec/language/fixtures/private.rb, spec/language/private_spec.rb, src/module_object.cpp, src/object.cpp
For example:
```rb
class A
def foo
"bar"
end
end
class B < A
private :foo
end
A.new.foo # => "bar"
B.new.foo # => NoMethodError
B.remove_method :foo
B.new.foo # => "bar"
```
=> Make `Module#private` spec-compliant

include/natalie/constant.hpp, include/natalie/module_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/constants_spec.rb, spec/core/module/deprecate_constant_spec.rb, src/bignum_object.cpp, src/env.cpp, src/module_object.cpp, src/natalie.cpp, test/support/spec.rb
This PR also adds support for deprecated constants by implementing `Module#deprecated_constant` and improves our `warn` method on the Env class to match ruby's behavior with warnings.
=> Make Fixnum and Bignum deprecated constants

lib/natalie/compiler/pass4.rb
Just something small to get rid of some variables that are immediately reassigned to another one.
There are probably more instances of this behavior,
like when creating or assigning a local-variable.
=> Prevent temporary "new" value creation in variable declaration in Pass4

include/natalie/module_object.hpp, include/natalie/object.hpp, spec/core/kernel/send_spec.rb, spec/shared/basicobject/send.rb, src/module_object.cpp, src/natalie.cpp, src/object.cpp, test/natalie/class_test.rb
From [Calling Methods ¶ Method Lookup](https://ruby-doc.org/core-3.0.0/doc/syntax/calling_methods_rdoc.html#label-Method+Lookup):
> Here is the order of method lookup for the receiver's class or module `R`:
> 
> - The prepended modules of `R` in reverse order
> - For a matching method in `R`
> - The included modules of `R` in reverse order
> 
> If `R` is a class with a superclass, this is repeated with `R`'s superclass until a method is found.
On Natalie's `master` branch, included modules are actually looked up in _forward_ order. This can be fixed by adding them to `m_included_modules` at the index that is right after the class into which they are included (instead of adding them at the end of the list).
Additionally, the `after_method` parameter of `find_method` only keeps its change …
=> Make `Kernel#send` spec-compliant

include/natalie/object.hpp, include/natalie/symbol_object.hpp, spec/core/kernel/instance_variable_get_spec.rb, src/kernel_module.cpp, src/object.cpp
Some follow up changes to #358
In order to make `Kernel#instance_method_get` spec compliant I've added a new `Object::to_instance_variable_name` method to encapsulate the necessary type checking and conversion, and I've changed `SymbolObject::is_ivar_name` so that names like `@`, `@@`, and `@0` aren't considered valid ivar names when passed as strings.
I've also changed `instance_variable_defined` and `instance_variable_set` to use the new `to_instance_variable_name` method for consistency.
=> Make Kernel#instance_method_get spec compliant

lib/natalie/compiler/pass4.rb
This stops us from always creating ValueInteger\d variables, just to
reassign and discard them in the next statement.
This also applies the same new-call inlining to variable assignment,
which we already had for variable declaration.
---
This makes 
```rb
a = 1
a = 2
a = [1, 2 , 3]
```
compile to
```c++
Value a2 = Value { NilObject::the() };
env->set_file(source_files[0]); env->set_line(1);
a2 = Value::integer(1);
env->set_file(source_files[0]); env->set_line(2);
a2 = Value::integer(2);
Value arr1 = new ArrayObject {  };
env->set_file(source_files[0]); env->set_line(3);
arr1->as_array()->push(Value::integer(1));
env->set_file(source_files[0]); env->set_line(3);
arr1->as_array()->push(Value::integer(2));
env->set_file(source_files[0]); env->set_line(3); …
```
=> Inline Value::integer call statements in pass4

include/natalie/string.hpp, include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/include_spec.rb, src/string_object.cpp, test/natalie/string_test.rb
=> Implement String#include?

lib/natalie/compiler/pass1.rb, src/array_object.cpp
This removes a chain of push calls we would do otherwise.
This can circumvent useless reallocation and copies in the underlying
vector.
=> Initialize arrays with an initializer list when applicable in pass 1

spec/core/range/inspect_spec.rb, src/range_object.cpp
Currently it doesn't handle a nil begin value:
$ bin/natalie
nat> (..3).inspect
"nil..3"
$ irb
irb(main):001:0> (..3).inspect
=> "..3"
I've re-implemented `RangeObject::inspect` to use append instead of `StringObject::format` in order to avoid nesting the ifs and eliminate the duplication between them.
=> Make Range#inspect spec compliant

src/range_object.cpp
Revert back to using `StringObject::format` in `RangeObject::inspect` as per https://github.com/seven1m/natalie/pull/385#discussion_r780618382
=> Use StringObject::format in RangeObject::inspect

include/natalie/string.hpp, lib/socket.rb, spec/library/socket/shared/pack_sockaddr.rb, spec/library/socket/socket/pack_sockaddr_in_spec.rb, spec/library/socket/socket/pack_sockaddr_un_spec.rb, spec/library/socket/socket/sockaddr_un_spec.rb, spec/library/socket/socket/unpack_sockaddr_in_spec.rb, spec/library/socket/socket/unpack_sockaddr_un_spec.rb, spec/library/socket/spec_helper.rb, test/support/mspec.rb, test/support/platform_guard.rb, test/support/spec.rb
My goal is to get the [Socket](https://ruby-doc.org/stdlib-2.5.3/libdoc/socket/rdoc/Socket.html) library sufficient enough that I can build a web server. Packing and unpacking sockaddrs seemed like a good place to start...
=> Socket: pack and unpack sockaddrs

.github/workflows/format.yml
I don't know why this [sometimes doesn't work](https://github.com/seven1m/natalie/actions/runs/1672238073), but I hope removing the `ref` fixes it.
=> Fix checkout action

include/natalie.hpp, lib/natalie/compiler.rb, lib/natalie/compiler/pass1.rb, lib/natalie/repl/legacy.rb, spec/language/case_spec.rb, src/natalie.cpp, src/object.cpp, test/support/spec.rb
Also, raise syntax errors (in `eval` strings) at runtime instead of immediately raising parse errors at compile time.
=> Allow `when` clause in `case` statement to contain splats.

spec/core/numeric/comparison_spec.rb, spec/core/numeric/fdiv_spec.rb, spec/core/numeric/finite_spec.rb, spec/core/numeric/imag_spec.rb, spec/core/numeric/imaginary_spec.rb, spec/core/numeric/infinite_spec.rb, spec/core/numeric/integer_spec.rb, spec/core/numeric/nonzero_spec.rb, spec/core/numeric/numeric_spec.rb, spec/core/numeric/phase_spec.rb, spec/core/numeric/polar_spec.rb, spec/core/numeric/real_spec.rb, spec/core/numeric/rect_spec.rb, spec/core/numeric/rectangular_spec.rb, spec/core/numeric/remainder_spec.rb, spec/core/numeric/shared/imag.rb, spec/core/numeric/shared/quo.rb, spec/core/numeric/shared/rect.rb, spec/core/numeric/to_int_spec.rb, src/numeric.rb, test/support/spec.rb
Remaining Numeric methods:
- `#denominator`, `#numerator`, and `#quo` require Rational
- `#to_c` and `#i` require Complex
- `#step` requires `Enumerator::ArithmeticSequence`
- `#singleton_method_added`
=> Implement Numeric methods

lib/natalie/compiler/pass0c.rb, lib/natalie/compiler/pass1.rb
This is just a neat way of ensuring a variable exists, so we can replace
it with just a declare_var statement.
This works, by replacing the non assigning path with a `var = var`
statement to ensure that the variable it is allocated.
---- 
This now allows us to fold
```rb
x = 1 unless false
```
to
```rb
x = 1
```
=> Allow folding of simple conditional assignments

include/natalie/string.hpp, include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/prepend_spec.rb, src/string_object.cpp
Mostly based around String#concat with some very minor differences
References: #217
=> Implement String prepend

bin/natalie, include/natalie.hpp, include/natalie/module_object.hpp, lib/natalie/compiler.rb, lib/natalie/compiler/pass4.rb, lib/tempfile.rb, spec/core/integer/plus_spec.rb, src/env.cpp, src/main.cpp, src/module_object.cpp, src/natalie.cpp, test/natalie/define_method_test.rb, test/support/spec.rb
This PR prints a warning when trying to overwrite optimized methods like Integer#+ or Array#min. To allow those sorts of overwrites a new flag `--allow-overwrites` was introduced with disables the canary compiler step and the warning.
To test this I also implement the `ruby_exe` helper from mspec.
I'm not really happy with how I pass the new flag from the compiler to our code. If there are better options for this I'd be happy to change it 😄
=> Disallow overwriting optimized methods

src/gc.cpp
Gain: 1.05-1.10 faster across variously configured benchmarks of various scripts
Changes:
-  Automatically unmark cells during collection so that we completely remove the global unmarking from the marking phase
- Do not check again cells that have already been gathered from gather_conservative_roots()
=> Some small GC improvements

include/natalie/class_object.hpp, include/natalie/kernel_module.hpp, include/natalie/module_object.hpp, include/natalie/object.hpp, src/kernel_module.cpp, src/object.cpp
An object's singleton class is a subclass of the object's regular class, so only one of the two is needed to find methods.
This change also revealed that `Object::dup` was incorrectly copying the singleton class (which hadn't been implemented yet).
=> Clean up Object::find_method

test/support/formatters/yaml_formatter.rb
Instead of expecting an Array (the error backtrace) to be converted to a
String we have to call #to_s on it :^)
=> Fix YamlFormatter

include/tm/vector.hpp, src/array_object.cpp
This especially crafted script measures up to a 10% improvement in speed 
```ruby
a = []
100_000.times { a << 1 }
100_000.times { a.pop }
```
Having said that, we shouldn't expect the same speed-up anywhere else.
=> Vector improvements - improve relocation of existing entries in insert and remove

lib/natalie/compiler2/instructions/define_class_instruction.rb, lib/natalie/compiler2/pass1.rb, src/natalie.cpp
Error:
```sh-session
> bin/natalie -c2 -e "class Foo; end"
error: non-void function does not return a value [-Werror,-Wreturn-type]
}
^
```
Expected:
```rb
p (class Foo; end) # => nil
p (class Bar; :bar; end) # => :bar
```
=> Compiler2: Allow class definition to have empty body

include/natalie_parser/node.hpp, include/natalie_parser/parser.hpp, src/natalie_parser/parser.cpp, src/parser_object.cpp, test/natalie/parser_test.rb
Assignment expression as call argument:
```rb
foo(a = b, c)
```
Multiple assignment with comma-separated values:
```rb
x, y = 1, 2
```
=> Parser: fix some issues with assignment expressions

spec/core/enumerable/tally_spec.rb, src/enumerable.rb
Ruby 3.1 adds an optional hash argument: https://bugs.ruby-lang.org/issues/17744
=> Make Enumerable#tally spec compliant

include/natalie/array_packer/packer.hpp, include/natalie/big_int.hpp, include/natalie/bignum_object.hpp, include/natalie/integer_object.hpp, include/natalie/object.hpp, include/natalie/rounding_mode.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/float/round_spec.rb, spec/core/integer/round_spec.rb, spec/shared/string/times.rb, src/array_object.cpp, src/big_int.cpp, src/bignum_object.cpp, src/hash_object.cpp, src/integer_object.cpp, src/match_data_object.cpp, src/object.cpp, src/random_object.cpp, src/range_object.cpp, src/rounding_mode.cpp, src/string_object.cpp, test/natalie/integer_test.rb, test/support/spec.rb
This implements `Integer#round`. However the PR got a bit larger than anticipated. I added new helper methods to `IntegerObject` to convert a `Object` to a `nat_int_t` using the `to_int` method. I think I could remove a lot of redundancy there and also all places now can benefit from fast integers and have correct unified error handling. I'd love to have feedback on how to improve the helpers (for example some cases need specific logic for handling bignums, see `IntegerObject::left_shift` for example)!
[#201]
=> Implement Integer#round and some new Integer helpers

spec/core/float/coerce_spec.rb, spec/core/float/divmod_spec.rb, spec/core/float/minus_spec.rb, spec/core/float/multiply_spec.rb, spec/core/float/plus_spec.rb, spec/core/integer/bit_and_spec.rb, spec/core/integer/bit_or_spec.rb, spec/core/integer/bit_xor_spec.rb, spec/core/integer/complement_spec.rb, spec/core/integer/div_spec.rb, spec/core/integer/divide_spec.rb, spec/core/integer/divmod_spec.rb, spec/core/integer/left_shift_spec.rb, spec/core/integer/minus_spec.rb, spec/core/integer/multiply_spec.rb, spec/core/integer/plus_spec.rb, spec/core/integer/right_shift_spec.rb, spec/core/integer/shared/abs.rb, spec/core/integer/shared/exponent.rb, spec/core/integer/shared/modulo.rb, spec/core/integer/to_f_spec.rb, spec/core/integer/to_s_spec.rb, spec/core/integer/uminus_spec.rb, test/natalie/integer_test.rb, test/support/spec.rb
The ruby spec suite changed this helper recently
Related commits: [728915c2f2f8743b530dc941d2f4ed28409da8a0](https://github.com/ruby/spec/commit/728915c2f2f8743b530dc941d2f4ed28409da8a0) and [49adc2f1640c8f6f86d26a9e4ea78cc6829700fc](https://github.com/ruby/mspec/commit/49adc2f1640c8f6f86d26a9e4ea78cc6829700fc)
=> Update bignum_value helper

include/natalie/parser_object.hpp, include/natalie_parser/token.hpp, src/natalie_parser/node.cpp, src/natalie_parser/parser.cpp, src/parser_object.cpp, test/natalie/parser_test.rb
For example:
```rb
A, B::C = 1, 2
A, ::B = 1, 2
```
=> Parser: fix multiple assignment with namespaced/top-level constant

spec/core/integer/left_shift_spec.rb, spec/core/integer/right_shift_spec.rb, src/big_int.cpp, src/integer_object.cpp, test/support/spec.rb
This also adds the `ruby_bug` method to the spec library. I figured we just want to skip over specs for ruby bugs. What do you think? @seven1m
=> Fix integer shift operations

spec/core/integer/remainder_spec.rb, src/integer.rb
Integer#remainder behaves the same as Numeric#remainder but is a method
on Integer. This means Numeric#rational can be overwritten without
affecting Integer#remainder.
[#201]
=> Copy implementation of Numeric#remainder to Integer

lib/observer.rb, spec/library/observer/add_observer_spec.rb, spec/library/observer/count_observers_spec.rb, spec/library/observer/delete_observer_spec.rb, spec/library/observer/delete_observers_spec.rb, spec/library/observer/fixtures/classes.rb, spec/library/observer/notify_observers_spec.rb
This pull request introduces the `observer` module into Natalie and makes it spec-compliant too.
I'm not really sure what our takes are on implementing gems as first-party libraries - I know we already have some basic impl of the `strscan` gem too, so figured this would be okay.
=> Implement `observer` module

include/natalie_parser/node.hpp, src/natalie_parser/node.cpp, src/natalie_parser/parser.cpp, src/parser_object.cpp, test/natalie/parser_test.rb
For example:
```rb
a.b, c = 1, 2
```
=> Parser: fix multi-assign that includes attribute assignment

include/natalie/array_packer/packer.hpp, include/natalie/array_packer/string_handler.hpp, lib/base64.rb, spec/library/base64/decode64_spec.rb, spec/library/base64/encode64_spec.rb, spec/library/base64/strict_decode64_spec.rb, spec/library/base64/strict_encode64_spec.rb, spec/library/base64/urlsafe_decode64_spec.rb, spec/library/base64/urlsafe_encode64_spec.rb
This pull requests lays the groundwork for the Base64 module.
Both the Base64#encode_64 and Base64#strict_encode64 methods are spec-compliant (minus encoding tests). The Base64#urlsafe_encode64 method needs some work still.
NOTE: This code could definitely be optimised a little too, i.e. global arrays etc.
I've also started work on Array.pack("m") which made implementing this module very simple. At the time of writing this PR description, 11 tests in the m_spec.rb file are now passing!
**TODO:**
Implementing the `decode*` methods will also mark the beginnings of `String.unpack`!
(Re-open of #513)
=> Implement the `base64` module

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/center_spec.rb, src/string_object.cpp
Feels like the code for this could be squashed a little - feels quite verbose... maybe it's okay since there's a little bit of math required to calculate the correct padding.
Related to #217.
=> Make `String#center` spec-compliant

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/clear_spec.rb, src/string_object.cpp
Encoding problems skipped for now.
#217.
=> Make `String#clear` spec-compliant

lib/natalie/compiler/binding_gen.rb, spec/core/string/intern_spec.rb, spec/core/string/shared/to_sym.rb, spec/core/string/to_sym_spec.rb
This is just an alias for `String#to_sym` which partially works. Just some encoding cases that are being skipped since they're always going to fail until we have the encoding.
#217.
=> Progress on `String#intern`

spec/core/string/ljust_spec.rb, src/string_object.cpp
As per, some encoding specs are commented out.
I think once this is merged in, I'll open a separate PR that adds a `to_str` method on `Object` so that we can abstract some of the conversion code (used in `String#center` too and afterwards `String#rjust`).
#217
=> Make `String#ljust` spec-compliant

include/natalie/integer.hpp, include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/bit_length_spec.rb, src/big_int.cpp, src/integer.cpp, src/integer_object.cpp
Integer#bit_length uses conversion from BigInts zu a binary string. Sadly this is very slow on large numbers (like 2**10000) that the specs are using. I tried to improve performance of different BigInt operators used by `BigInt::to_binary` but it is not good enough to handle those large numbers yet.
=> Implement Integer#bit_length and try to optimize BigInt

spec/core/kernel/initialize_dup_spec.rb, src/kernel.rb
Following on from #530 this implements the Kernel#initialize_dup method. Further work required to call this method from `Object::dup` to make that spec compliant.
=> Implement Kernel#initialize_dup

test/support/spec.rb
There are some specs in ruby/spec with expectations like `a.should.equal?(b)` which as-is will always pass.
For example, with the following code in `spec/example_spec.rb`:
require_relative 'spec_helper'
describe 'Matcher#equal?' do
it 'always passes' do
1.should.equal?(1)
1.should.equal?(2)
end
end
The second expectation should fail, but the spec passes:
$ bin/natalie spec/example_spec.rb
.
1 spec(s) passed.
Fixing by undefining the #equal? method on the Matcher class so that Matcher#method_missing is called, which implements the correct behavior for testing.
=> Fix Matcher spec class

include/natalie/encoding_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/encoding/default_internal_spec.rb, spec/core/integer/chr_spec.rb, src/encoding_object.cpp, src/integer_object.cpp
Those are needed for various methods and objects. Right now only
Integer#chr supports Encoding::default_internal.
=> Implement Encoding::default_internal (and it's setter)

lib/natalie/compiler/binding_gen.rb, spec/core/range/include_spec.rb, spec/core/range/member_spec.rb, spec/core/range/shared/cover_and_include.rb, spec/core/range/shared/include.rb, src/range_object.cpp, test/natalie/range_test.rb
This revealed a small bug in our `String#succ` method that I was not able to fix. Maybe somebody has an idea:
```ruby
"\u09b9".succ
```
[#555]
=> Make Range#include? spec compliant

include/natalie.hpp, include/natalie/backtrace.hpp, include/natalie/env.hpp, include/natalie/exception_object.hpp, include/natalie/forward.hpp, src/backtrace.cpp, src/env.cpp, src/exception_object.cpp, src/kernel_module.cpp, src/natalie.cpp
Previously, we were building a backtrace array when initializing an
exception object. Sometimes though we do not want to print the backtrace
which makes generating it useless.
This patch tries to delay building the backtrace array, until it will
actually be used.
This should impact a lot of code slightly, because exceptions are
sometimes used for control-flow in the language itself (LocalJumpError
for example).
Benchmark:
```ruby
10000.times do |n|
begin
raise Exception, 'message'
rescue Exception
end
end
```
On MRI: 
```
real    0m0.100s
user    0m0.080s
sys     0m0.020s
```
On Natalie (master):
```
real    0m0.247s
user    0m0.237s
sys     0m0.010s
```
On Natalie (with this patch):
```
real    0m0.190s
user    0m0.189s
sys     0m0.000s
```
=> Delay building an exception backtrace array

include/natalie/float_object.hpp, include/natalie/value.hpp, lib/natalie/compiler/pass1.rb, lib/natalie/compiler/pass4.rb, src/float_object.cpp, src/integer_object.cpp, src/math.rb, src/object.cpp, src/value.cpp
I temporarily removed the previous implementation of it, to narrow down on some errors.
Current errors include:
=> Teaching the compiler about internal Floats and fixing them up

spec/core/string/chomp_spec.rb, src/string_object.cpp
to pass tests from Ruby source
Changed spec/core/string/chomp_spec.rb
to contain tests from ruby source.
Skipped tests of unimplemented String#chomp
=> Fixed String#chomp

include/natalie/value.hpp, lib/natalie/compiler/pass4.rb, spec/core/range/max_spec.rb, spec/core/range/min_spec.rb, spec/core/range/minmax_spec.rb, src/enumerable.rb, src/env.cpp, src/object.cpp, src/range.rb, src/value.cpp, test/natalie/range_test.rb, test/natalie/super_test.rb, test/support/spec.rb
This also fixes some issues with our spec library and a bug with implicit block passing for `super`.
[#555]
=> Implement Range#min, #max and #minmax

include/natalie.hpp, include/natalie/range_object.hpp, include/natalie/string_upto_iterator.hpp, include/tm/string.hpp, spec/core/range/shared/cover_and_include.rb, spec/core/range/to_a_spec.rb, src/range_object.cpp, src/string_upto_iterator.cpp
I don't know about the code-duplication in #iterate_over_string_range and #iterate_over_symbol_range. We could add some kind of macro or maybe there is another idea?
I also was not sure about the location of StringUptoIterator. I decided for a new class but am open to other suggestions. If we decided on the approach we can adjust String#upto to use the iterator as well.
[#555]
=> Make Range#to_a spec-compliant

.clang-tidy, .github/workflows/lint.yml, Dockerfile, Rakefile, include/natalie/string_upto_iterator.hpp, include/tm/string.hpp, src/array_object.cpp, src/big_int.cpp, src/encoding_object.cpp, src/env.cpp, src/integer.cpp, src/natalie.cpp, src/string_upto_iterator.cpp
I was able to fix a few warnings, and a few of the others I had to ignore for now.
The main point was to get clang-tidy in our CI workflow so that we can catch new bad habits before they land in `master`. 😄
=> Fix clang-tidy warnings (and add clang-tidy to CI)

lib/json.rb, test/natalie/json_test.rb
Useful for compatibility with existing code.
=> Implement symbolize_names argument for JSON.parse

lib/natalie/compiler/macro_expander.rb
Open to feedback on the name of the macro (borrowed the name from Rust since Ruby allows `!` in method names I thought it looked cool), but this is fully functional.
**Usage:**
```rb
html = include_str! './public/index.html'
puts html
```
It will get the contents of the file at compile time (relative to the current file) and include the contents as a string inside of the resulting binary.
**Generated C++:**
=> Add support for `include_str!` macro

src/array_object.cpp, test/natalie/array_test.rb
I feel like (correct me if I'm wrong) that the previous implementation
wasn't a binary search. It just moved the window used to determine the
middle of the array by one. However a binary search should continue it's
search in the left/right half of the array. This change also improves
performance of the bsearch method:
```ruby
p (0..100_000).to_a.bsearch { |x| x >= 73 }
```
master:
```
$ time ./find-min
73
real    0m0.524s
user    0m0.513s
sys     0m0.011s
```
with fix:
```
$ time ./find-min-2
73
real    0m0.455s
user    0m0.414s
sys     0m0.041s
```
When measuring the iteration count in the while-loop we can see that it
dropped from 99856 using master to only 17.
=> Try to fix Array#bsearch

include/natalie/object.hpp, lib/socket.cpp, lib/socket.rb, spec/library/socket/ipsocket/addr_spec.rb, spec/library/socket/socket/getaddrinfo_spec.rb, spec/library/socket/tcpserver/new_spec.rb, src/object.cpp
This is one of the last few steps for getting a working TCPServer in #598. After this, I think we just need `Socket#accept`.
I cannot easily break this work into smaller pieces, so I'm pushing this up to a branch and will chip away at it as I have time
TODO:
=> Final push for TCPServer.new

include/natalie/enumerator/arithmetic_sequence_object.hpp, include/natalie/natalie_parser/natalie_creator.hpp, include/natalie/range_object.hpp, lib/natalie/compiler/binding_gen.rb, lib/natalie/compiler/instructions/push_range_instruction.rb, spec/core/range/percent_spec.rb, spec/core/range/step_spec.rb, src/enumerator/arithmetic_sequence_object.cpp, src/range.rb, src/range_object.cpp, test/support/spec.rb
This also fixes a bug in Range construction with the (x..y)-syntax. We were not checking if constructing the Range should be possible.
[#555]
=> Implement Range#step and Range#%

spec/core/range/clone_spec.rb, src/object.cpp
This uses the underlying implementation of Object#clone.
Object#clone should freeze the duplicate if the original was frozen too.
[#555]
=> Make Range#clone spec-compliant

lib/natalie/compiler/env_builder.rb, lib/natalie/compiler/instruction_manager.rb, lib/natalie/compiler/instructions/base_instruction.rb, lib/natalie/compiler/pass2.rb, lib/natalie/compiler/pass3.rb, lib/natalie/compiler/pass4.rb
This reduces transformation time by ~50%
Before:
After:
With label as class method:
=> Memoize label of a compiler instruction

Gemfile, Gemfile.lock, bin/natalie, lib/natalie/compiler.rb
This patch adds two new options to bin/natalie:
`--transform-only` - Only transform the given ruby code to cpp code without writing it to a file. This is useful for measuring the time needed by the compiler to transform ruby code to cpp.
`-pc` - Profiles the compiler using the stackprof gem. When speedscope is installed, the profile will be opened using speedscope!
Let me know what you think. We could definitely add more here. I'm thinking profiling the different passes for example.
=> Add possibility to profile Natalie's compiler using StackProf

include/natalie/rational_object.hpp, include/natalie/time_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/time/to_r_spec.rb, src/time_object.cpp, test/natalie/time_test.rb
First commit adds support for `Rational` arguments to `Time.at` which is necessary for `spec/core/time/to_r_spec.rb`
=> Implement Time#to_r

include/natalie/time_object.hpp, lib/natalie/compiler/binding_gen.rb, src/time_object.cpp, test/natalie/time_test.rb
Implements addition for time objects:
$ bin/natalie
nat> Time.utc(1970) + 3723
1970-01-01 01:02:03 UTC
Further work required to make it fully spec compliant (floats, fixed offsets, zones, Time#<=>).
=> Implement Time#+

lib/natalie/compiler/instructions/push_float_instruction.rb, test/natalie/float_test.rb
This allows parsing numbers like `1e1020` to be Infinity.
=> Compiler: Compile positive and negative infinity floats

spec/core/float/divide_spec.rb, test/support/spec.rb
Hi all! Love what you are building here! Wanted to help get more specs green.
I noticed a couple of skipped / failing specs on `divide_spec` for Float. Fixed by adding the missing matchers (inspired by https://github.com/ruby/mspec/blob/master/lib/mspec/matchers/infinity.rb) and updated the spec to the latest from `ruby/spec` (https://github.com/ruby/spec/blob/master/core/float/divide_spec.rb)
=> Add Float Infinity expectation & unskip related tests

.github/workflows/build.yml, .github/workflows/format.yml, .github/workflows/lint.yml, Dockerfile, Rakefile, include/natalie.hpp, include/natalie/abstract_method_object.hpp, include/natalie/args.hpp, include/natalie/array_packer/integer_handler.hpp, include/natalie/array_packer/packer.hpp, include/natalie/big_int.hpp, include/natalie/binding_object.hpp, include/natalie/block.hpp, include/natalie/constant.hpp, include/natalie/exception_object.hpp, include/natalie/fiber_object.hpp, include/natalie/gc/heap.hpp, include/natalie/gc/heap_block.hpp, include/natalie/hash_object.hpp, include/natalie/method_info.hpp, include/natalie/string_object.hpp, include/natalie/symbol_object.hpp, src/big_int.cpp, src/constant.cpp, src/env.cpp, src/exception_object.cpp, src/global_env.cpp, src/method.cpp, src/object.cpp, test/gc_lint.rb
We have a bad habit of adding class member variables without informing the GC how to visit those members. This bit of (hacky) linter code should help us catch those mistakes earlier in the future.
In fact, I was able to find quite a few GC bugs with it, so *worth it!* :100:
=> Fix missing GC visits of member variables and add GC linter

Dockerfile, Rakefile, include/natalie/backtrace.hpp, include/natalie/time_object.hpp, src/array_object.cpp, src/env.cpp, src/integer.cpp, src/module_object.cpp, src/time_object.cpp
This fixes #592 and a few more warnings that have popped up since that issue was created.
When I added the clang-tidy linter, I didn't realize it would not fail the build for warnings. So, this PR configures clang-tidy to treat warnings as errors, so they should fail the build from now on.
=> Fix remaining clang-tidy warnings and configure warnings as errors in clang-tidy

Gemfile.lock
Bundler adds this every time I run `bundle` (via `rake` or directly)
=> Add arm64-darwin-20 platform to Gemfile.lock

include/natalie/float_object.hpp, lib/natalie/compiler/binding_gen.rb, src/float_object.cpp, src/kernel_module.cpp, test/natalie/float_test.rb
There isn't any spec coverage provided by `spec/core/float/to_r_spec.rb` so I've added some examples from Ruby's Float#to_r documentation to `test/natalie/float_test.rb` for now
I had to change how `KernelModule::Rational` constructed the float object to get it to work—without any change that was resulting in the "This object is stack allocated..." failure from `NAT_GC_GUARD_VALUE`
=> Implement Float#to_r

spec/core/float/shared/to_i.rb, src/float_object.cpp
Float `to_i` should raise a `FloatDomainError` when `NaN`
There is no test for this in the `to_i` example in spec/core . I added one and will then try upstream it to `ruby/spec`
I notice that the change recommended for the stack allocated Float has been fixed by a similar commit so did not include it
It was:
```
auto significand = Value::floatingpoint(std::frexp(arg, &exponent));
Value x = significand.send(env, "*"_s, { y })->as_float()->to_i(env);
```
vs what is now in master
=> Float `to_i` should raise a `FloatDomainError` when `NaN`

lib/csv.rb, lib/csv/parser.rb, spec/library/csv/each_spec.rb, spec/library/csv/headers_spec.rb
Adds `each` and `headers` specs for #551.
Also adds basic support for headers when parsing csv. Most notably, `ruby/csv` allows setting separate converters for headers which is not implemented in this PR.
=> Add partial CSV headers parsing support, add CSV#each spec

include/natalie/time_object.hpp, spec/core/time/usec_spec.rb, src/time_object.cpp, test/natalie/time_test.rb
Time#usec is already implemented, but a couple of changes required to get the spec passing:
* Float microseconds argument to `Time.at` e.g. `Time.at(0, 3.75)`
* Rational second argument to `Time.local` e.g. `Time.local(1,2,3,4,5,Rational(6.78))`
(second argument is documented as integer, but the implementation accepts other numeric values)
I've added `TimeObject::convert_rational` to handle the repeated type conversion logic, and changed the `TimeObject::build_time_struct` helper function so that it can store the subseconds.
=> Add Time#usec spec

include/natalie/string_object.hpp, spec/core/string/each_byte_spec.rb, spec/core/string/each_char_spec.rb, src/array_object.cpp, src/string_object.cpp
Return string size/byte size (not nil) as an enumerator size when `#each_char`/`#each_byte` are called without a block.
Example:
```ruby
enum = "abc".each_char
enum.size # => 3
```
=> Fix enumerator size for String#each_char and String#each_byte

include/natalie/array_packer/integer_handler.hpp, include/natalie/array_packer/packer.hpp, spec/core/array/pack/v_spec.rb
This PR adds the Array#pack directives 'V' and 'v'. Related to issue #195.
The pack directives 'v' and 'V' pack an array of integers into 16-bit unsigned and 32-bit unsigned little endian byte order respectively. I tested my code with different inputs in the Natalie REPL and compared the outputs with the `irb`. It seems that everything is working fine.
Before merging this, I would like to confess that a spec gets skipped when I try to run the `v_spec.rb` file. 
I did some debugging in `test/support/spec.rb` and placed some inspections. It seems like the spec `encodes a Float truncated as an Integer` gets skipped because the `fn` for it is `nil`. Does this mean that this particular spec hasn't been implemented for 'v' and 'V' directives? 
This is my first time ever working on compilers and …
=> Add Array#pack directives 'V' and 'v'

src/array_object.cpp, src/kernel_module.cpp, src/string_object.cpp
Changes:
- fixed an error message when implicit conversion to String fails because `#to_str` doesn't return String
- fixed several other (not related) error messages (unfortunately they aren't covered with specs)
A common pattern to convert an argument to String:
```ruby
auto to_str = "to_str"_s;
if (!arg->is_string() && arg->respond_to(env, to_str))
arg = arg->send(env, to_str);
arg->assert_type(env, Object::Type::String, "String");
```
leads to an error message
```
(repl):3:in `include?': no implicit conversion of Integer into String (TypeError)
```
But expected message usually is the following:
```
(irb):59:in `include?': can't convert Object to String (Object#to_str gives Integer) (TypeError)
```
Source code to reproduce the issue (for `String#include?`):
```ruby
a = Object.new
def …
```
=> Use Object::to_str(Env *) for implicit conversion to String

src/integer_object.cpp, test/natalie/integer_test.rb
This makes expressions like `0 < Rational(1, 2)` and `0 <=> Rational(1, 2)` correct/compliant—comparison in this direction doesn't appear to be covered by ruby/spec yet, so I've added tests to `test/natalie/integer_test.rb`
=> Implement comparison between Integer and Rational objects

include/natalie/array_packer/packer.hpp, spec/core/array/pack/x_spec.rb
This PR implements array pack directives 'X' and 'x'. Related to issue #195.
The 'x' directive packs `count` amount of null bytes. Null bytes are packed irrespective of the length of the array.
```ruby
nat> [1,2,3].pack('xxxx')
"\x00\x00\x00\x00"
nat>
```
The 'X' directive pops the rightmost `count` amount of characters from the string. `count` is 1 by default.
```ruby
nat> [65,66,67].pack('C*X2')
"A"
nat>
```
Asterisk modifiers have no effect on either of the directives. 
All specs seem to pass! :)
=> Add Array#pack directives 'X' and 'x'

lib/socket.cpp, test/natalie/socket_test.rb
Together with #700 this makes `examples/webserver.rb` work for me on macOS 😎
=> Fix Addrinfo.new with packed sockaddr string argument

src/string_object.cpp, test/natalie/string_test.rb
127 should be escaped as `\x7F` and 128 as `\x80`, for example with irb:
irb(main):001:0> [127, 128].pack('C*')
"\x7F\x80"
=> Fix String#inspect

src/object.cpp, test/natalie/kernel_test.rb
In the general case where the receiver and the argument are the same value this should return false, but there's an edge case for the `Module` object where it should return true:
$ irb
irb(main):001:0> Module.is_a?(Module)
=> true
This also fixes Kernel#instance_of? which currently raises an error with `Module` as an argument, for example:
$ bin/natalie
nat> Enumerable.instance_of?(Module)
2: from (repl):1:in `<main>'
1: from src/kernel.rb:40:in `instance_of?'
src/kernel.rb:40:in `raise': class or module required (TypeError)
=> Fix Kernel#is_a? for comparing Module to itself

src/module_object.cpp, test/natalie/module_test.rb
Currently this is returning nil:
$ bin/natalie
nat> Object.const_get(:FOO)
nil
=> Raise NameError in Module#const_get if name is not defined

include/natalie/regexp_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/regexp/encoding_spec.rb, src/regexp_object.cpp
Not fully implemented / spec compliant... from what I can tell we only support US-ASCII regexps currently?
=> Implement Regexp#encoding for default encoding of US-ASCII

include/natalie/encoding/us_ascii_encoding_object.hpp, include/natalie/encoding/utf8_encoding_object.hpp, spec/core/string/setbyte_spec.rb, src/encoding/utf8_encoding_object.cpp, src/natalie.cpp
There was one failing spec in `spec/core/string/setbyte_spec.rb`. I've investigated it and found out that current implementation of `Utf8EncodingObject::next_char` is not comprehensive and allows false positives.
Changes:
- fixed String#valid_encoding? for UTF-8
- added missing aliases for UTF-8 and US-ASCII
Specs are added to RubySpec here https://github.com/ruby/spec/pull/975.
=> Fix String#valid_encoding? for UTF-8

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/shared/dedup.rb, spec/core/string/uminus_spec.rb, src/string_object.cpp
Added String unary minus method.
Currently, there does not appear to be any support for deduplication of frozen strings in Natalie, so some related tests have been skipped for now.  Moves test coverage in a positive direction.
=> Add support for String#-@

include/natalie/time_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/struct/element_reference_spec.rb, spec/core/struct/fixtures/classes.rb, spec/core/time/shared/gmt_offset.rb, spec/core/time/utc_offset_spec.rb, spec/core/time/wday_spec.rb, src/struct.rb, src/time_object.cpp, test/support/spec.rb
This implements some random time stuff. 
The `Struct#[]` method is actually needed to implement `Time#new` (the specs depend on the Struct method). However, I could not finish the work on `Time#new`, because there seems to be a bug in how we dispatch the `new`-method if redefined.
The following code should print `String` but with Natalie it prints `MethodHolder`. Maybe somebody has an idea 😅 
```ruby
class MethodHolder
class << self
define_method(:new, &String.method(:new))
end
end
p MethodHolder.new.class
```
=> Implement some time stuff

include/natalie/string_unpacker.hpp, spec/core/string/unpack/s_spec.rb
Addressing `String#unpack` 'S' and 's' directives from #667 
If this looks okay, I can take a look at the other longer-integer variants.
=> Add String#unpack 'S' and 's' directives

include/natalie/big_int.hpp, include/natalie/encoding/ascii_8bit_encoding_object.hpp, include/natalie/encoding/us_ascii_encoding_object.hpp, include/natalie/encoding/utf8_encoding_object.hpp, include/natalie/encoding_object.hpp, include/natalie/process_module.hpp, include/tm/string.hpp, spec/core/string/encode/ascii_8bit_spec.rb, spec/core/string/encode/us_ascii_spec.rb, spec/core/string/encode/utf_8_spec.rb, spec/core/string/valid_encoding/utf_8_spec.rb, src/big_int.cpp, src/encoding/ascii_8bit_encoding_object.cpp, src/encoding/us_ascii_encoding_object.cpp, src/encoding/utf8_encoding_object.cpp, src/encoding_object.cpp
Implemented strings encoding in two-steps - convert a character to Unicode and then to the destination encoding.
Changes:
- reimplemented `String#encode`
- fixed compiling issues on MacOS
- added specs for `String#valid_encoding?` for UTF-8 (that were merged into RubySpec [here](https://github.com/ruby/spec/pull/975))
=> Reimplement String#encode

include/natalie/big_int.hpp, include/natalie/string_unpacker.hpp, include/tm/string.hpp, spec/core/string/unpack/i_spec.rb, spec/core/string/unpack/j_spec.rb, spec/core/string/unpack/q_spec.rb, src/big_int.cpp
This PR seeks to address parts of #667, namely to add support for `String#unpack` of integer/pointer-types:
+ Modify the `unpack_s` function to handle more generic types, which replaces the existing `unpack_i` and `unpack_j` functions and was renamed `unpack_int`.
+ Add support for `i` `I`, `j`, `J`, `q`, `Q` directives.  These directives pass their respective specs.
+ Add tentative support for `l`, `L` directives using the same function as above - these do not pass all of the `l_spec` tests yet, I think the underlying code is valid, there is some weirdness in how platform-specific longs are treated in the tests, or an interaction with the `platform_is` function.  Ruby documentation says these directives correspond to `int32_t` and `uint32_t`, yet the spec would indicate otherwise 😞 
To …
=> Add String#unpack i/j/q

include/natalie/string_unpacker.hpp, spec/core/string/unpack/d_spec.rb, spec/core/string/unpack/e_spec.rb, spec/core/string/unpack/f_spec.rb, spec/core/string/unpack/g_spec.rb
Per #667 Implements `String.unpack` directives d,D,e,E,f,F,g,G to support double/float types using a templated function.
=> Add float/double support for String.unpack, directives d/e/f/g

include/natalie/string_unpacker.hpp, spec/core/string/unpack/at_spec.rb, spec/core/string/unpack/comment_spec.rb, spec/core/string/unpack/percent_spec.rb, spec/core/string/unpack/x_spec.rb
Add String#unpack `x`, `X`, and `@` directives and specs.
Add specs for unpack's comment and '%' directives, which passed but were not previously included.
=> Add String#unpack 'x','X','@' directives and specs

spec/core/marshal/float_spec.rb, src/marshal.rb
The encoding of floats in `Marshal.dump` is different to Float#to_s, for example:
$ irb
irb(main):001:0> 123.0.to_s
=> "123.0"
irb(main):002:0> Marshal.dump(123.0)[4..-1]
=> "123"
irb(main):003:0> 0.00000000123.to_s
=> "1.23e-09"
irb(main):004:0> Marshal.dump(0.00000000123)[4..-1]
=> "1.23e-9"
This fixes the 3 currently failing specs in spec/core/marshal/float_spec.rb
=> Make Marshal.dump spec compliant

spec/core/complex/quo_spec.rb, src/complex.rb
This checks off one of the items of #608
It turned out to be an alias of `Complex#/`, which was implemented, but not yet checked off in #608
=> Implement Complex#quo

include/tm/string.hpp, src/big_int.cpp
Mostly implementing (and using) move semantics. This can prevent some memory moves.
=> Some minor optimizations for TM::String

include/tm/string_view.hpp
C++ can make this boilerplate code by itself.
=> Use default copy constructor/assignment in StringView

include/tm/optional.hpp
The documentation showed the use of the copy constructor, not the move constructor.
=> Update docs for move constructor of TM::Optional

Dockerfile, include/natalie/dir_object.hpp, include/natalie/file_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/dir/delete_spec.rb, spec/core/dir/empty_spec.rb, spec/core/dir/fixtures/common.rb, spec/core/dir/home_spec.rb, spec/core/dir/shared/delete.rb, spec/core/dir/unlink_spec.rb, src/dir_object.cpp, src/file_object.cpp
This PR adds class methods and tests for `Dir.home`, `Dir.empty?`, `Dir.delete` and `Dir.unlink`.
`Dir.rmdir` is the same as delete/unlink, but for some reason the tests are different, and it does not pass dependencies on code not yet written - so that test was not included.
Also, a common helper function on the C++ side (`convert_using_to_path`) was pushed into a namespace and shared between `FileObject` and `DirObject`.  Unsure if this is where it should go or how it should be done (maybe a static method on `FileObject` instead?
=> Dir: Add home empty? delete unlink

include/natalie/parser_object.hpp, src/parser_object.cpp
The body of the method did not use the shared pointer semantics, it just needed a value. This change is according to [rule F.7 of the C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f7-for-general-use-take-t-or-t-arguments-rather-than-smart-pointers).
=> Convert ParserObject::node_to_ruby to use a const reference

spec/shared/rational/Rational.rb
This has been fixed upstream (https://github.com/ruby/spec/pull/982).
=> Remove FIXME marker in spec of Rational about nesting inside String

include/tm/optional.hpp
This one was still missing. It reduces the number of copies.
=> Add converting move constructor for TM::Optional

include/tm/tests.hpp
Some code snippets in the TM library are using the move constructor of Thing, so it might be a good idea to actually speficy that.
I've made this PR over here instead of at https://github.com/seven1m/tm, since this repository contains all the other updates for `TM` as well, so this is the most up to date version that can be copied over to the other locations.
=> Complete the constructors and assignment operators of Thing

lib/natalie/compiler/backends/cpp_backend.rb
The old code did export the symbols array as a public symbol in the .o file, as can be seen with `objdump -t array.rb.o`:
```
0000000000000000 g     O .bss	0000000000000240 array_symbols
```
(Please mind the two different uses of the term symbols: the first occurence talks about Ruby symbols, the second occurence talks about symbols in object files)
This change marks them as non exported.
It is now possible to remove the method `symbols_var_name` and just use the constant `symbols` instead, this does not result in any more name clashes.
=> Don't export the SymbolObject array in generated C++ code

spec/shared/rational/Rational.rb, src/kernel_module.cpp
I'm not sure if this is the idiomatic way to do an `is_a` call from C++ code. The code feels a bit clunky compared to the `respond_to` in the same line, but something like `x->is_a?("Numeric"_s)` does not appear to be working.
=> Implement Rational(NumericSubclass)

include/natalie/string_object.hpp, test/support/spec.rb, test/support/spec_helpers/fs.rb
Add `be_true_or_false` test method.
Provide workaround of issue #742 for `test/support/spec_helper/fs.rb`
=> Small fixes to test support

spec/core/array/pack/x_spec.rb
This is the latest upstream version. The spec passes, so this one can be checked off in #195 too
=> Import array/pack/x_spec from ruby-spec

spec/core/string/to_i_spec.rb, src/string_object.cpp
The first steps to get `string/to_i_spec` to pass (#217). I was actually trying to build support for Bigint in the method, but this was an easy yak shave (and given the amount of specs that are failing, I guess it's easier to fix those issues before moving to the bigint parsing, since that might get a better view on the other issues that have to be fixed).
There are a few markers like this:
```ruby
xit "ignores underscores in between the digits" do
```
I added the `NATFIXME` to make it easier to discover the issues. I didn't feel the need to repeat the text of the spec in the FIXME, unless there was actually some extra information to be added.
=> Check base argument in String#to_i

include/tm/optional.hpp, include/tm/string.hpp
* string.hpp:
This was a compile error, there were two variables named `str`.
* optional.hpp:
The value from ob2 was moved. Thing has been updated to reset the value after a move operation, so we need a new Thing object to validate the Thing inside the optional.
I've found these by copying the files to a checkout of the `tm` repo and running the unit tests over there. I'm fixing them here, since this repository contains the latest version of the tm headers.
=> Fix unit tests of include/tm

spec/core/array/keep_if_spec.rb, spec/core/float/divmod_spec.rb, spec/core/kernel/singleton_class_spec.rb, spec/core/regexp/initialize_spec.rb, spec/language/case_spec.rb
I went through the chore of upstreaming all these FIXME statements. I tried to give credit to the original author, but since I just used git blame this might sometimes be the wrong person (in case did a minor change to the line after the FIXME was added). All the FIXME statements now have the upstream pull requests listed in them, so it's easier to match them.
I marked this pull request as a draft, response time from ruby-spec is generally pretty quick, so I guess I can update the PR later today with the FIXMEs removed.
=> Update some specs, resolve the "NATFIXME: bug in spec" entries

spec/language/case_spec.rb, src/regexp_object.cpp
The \ character might need some extra escaping, but not when it's used for a character class. The old code had the following output:
/\d+/.to_s == "(?-mix:\\\\d+)"
This changed the behaviour: instead of matching one of more decimals, this regex would match a literal \ followed by one or more d's. This made it impossible to embed these kind of regexes into another regexp.
This scenario was not defined in the regex specs, but it did accidentally get caught in the spec for the case statement.
=> Fix escaping of \ in string output of Regex

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/pack/shared/unicode.rb, spec/core/enumerable/grep_spec.rb, spec/core/enumerable/sum_spec.rb, spec/core/enumerator/lazy/grep_spec.rb, spec/core/enumerator/rewind_spec.rb, spec/core/float/constants_spec.rb, spec/core/process/constants_spec.rb, spec/core/string/shared/eql.rb, spec/core/string/unpack1_spec.rb, src/string_object.cpp
It's the simple and slow implementation: call `String#unpack` with the original arguments, and call `first` on the result of that call. I left a FIXME as a reminder that this can be optimized.
This resolves an issue from #667
=> Implement String#unpack1

spec/language/array_spec.rb, test/support/spec.rb
And enable the one line in the spec that needs it.
=> Implement respond_to matcher

spec/language/alias_spec.rb, spec/language/array_spec.rb, spec/language/fixtures/block.rb
These changes are a side effect of #785, which means they're pretty much unrelated.
The changes in block and array actually improve something. The changes in alias are wording or putting back commented code where the spec itself has been disabled already.
=> Various spec syncs with upstream

spec/language/alias_spec.rb, spec/language/and_spec.rb, spec/language/array_spec.rb, spec/language/block_spec.rb, spec/language/fixtures/array.rb, spec/language/fixtures/block.rb
There is a generic spec/LICENSE file. Removing this duplication reduces the number of changes between this checkout and upstream.
=> Remove explicit copyright notices from ruby spec files

src/encoding_object.cpp
This removes a few copy operations.
=> Use constrefs when looping through the names of encoding_objects

src/big_int.cpp
TM::String::prepend_char does result in a memory allocation + move. Just create the string with an extra zero, then replace the first character with a 1.
=> Optimize Bigint::big_pow10

include/natalie/big_int.hpp, include/natalie/integer.hpp, include/natalie/integer_object.hpp, include/natalie/string_unpacker.hpp, src/big_int.cpp, src/integer.cpp, src/integer_object.cpp, src/string_unpacker.cpp
This reduces the number of objects created (and destroyed).
=> Implement move semantics for IntegerObject and underlying data types

test/support/spec.rb
Integer#size is implemented. The old and new code yields the same results.
=> Update max_long and min_long in spec runner

spec/core/string/shared/each_line.rb, src/string_object.cpp
This fixes the "does not care if the string is modified while substituting" spec
=> Use copy of self in String#lines

spec/core/file/constants/constants_spec.rb, src/file_object.cpp
Besides these entries from fnmatch.h, Ruby also adds three other FNM_ constants. These appear to be unique to Ruby, and have not been added in this patch. These values probably have to be hardcoded.
=> Import constants from fnmatch.h into File namespace

lib/natalie/compiler/pass1.rb, test/natalie/argument_test.rb
Calling a method like this:
```ruby
foo(*args, **kwargs)
```
caused the keyword arguments to be added to the positional arguments. This appears to fix it (I added a bunch of tests, and they all pass), but the fix almost looks too simple to be true.
This started out as an attempt to implement `String#each_line`, and quite a few yaks have lined up to be shaved.
=> Some fixes for splat and double splat operations

src/string_object.cpp
The sign char was stripped before the string gets passed to the BigInt constructor, so the result was always the absolute value of the input.
Without this patch:
```
nat> bigint = '-245789127594125924165923648312749312749327482'
"-245789127594125924165923648312749312749327482"
nat> bigint.to_i
-245789127594125924165923648312749312749327482
nat> Integer(bigint)
245789127594125924165923648312749312749327482
```
=> Fix Kernel.Integer for negative BigInt String values

test/support/spec.rb
This is used by a number of specs to add extra arguments to the executable (not the script itself). Natalie probably doesn't support these options, but this way the error message will become a bit clearer.
Example of it being used: https://github.com/ruby/spec/blob/master/command_line/backtrace_limit_spec.rb#L7 (which is the first error on the specs result page of Natalie)
=> Add options keyword to ruby_exe spec helper

spec/core/string/shared/concat.rb
This encoding has been implemented. Most of these specs can be enabled, the remaining ones have been updated to the actual issue.
=> Updated NATFIXME markers waiting for US-ASCII

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/each_line_spec.rb, spec/core/string/shared/each_line_without_block.rb, src/string_object.cpp
Or at least like 99% of it. It does not pass the keyword argument `chomp` to the enumerator, the underlying issue is described in # #816
=> Implement String#each_line

test/support/spec.rb
This is used in some specs, and should just return the executable.
As an example: https://github.com/ruby/spec/blob/master/command_line/dash_e_spec.rb#L21
=> Support ruby_exe without arguments

spec/core/rational/to_r_spec.rb, src/kernel_module.cpp
This does not have a dependency on the argument being a numeric type. It should raise a TypeError if the result of the to_r call is not a Rational.
As a side effect, this required an additional check for the argument being nil, since `nil.to_r` does return a Rational(0, 1).
There was a slight change needed in the spec, since Rational(String) is not implemented.
=> Fix Rational(obj) where obj has a to_r method

src/string_object.cpp, test/natalie/Integer_test.rb
Found this one by accident while I was looking at tests for #827
=> Fix whitespace after sign mark check in Kernel.Integer

include/natalie/array_object.hpp, include/natalie/array_packer/integer_handler.hpp, include/natalie/array_packer/packer.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/pack/u_spec.rb, src/array_object.cpp, src/array_packer/integer_handler.cpp, src/array_packer/packer.cpp
This implements the 'q' and 'Q' directives for `Array#pack` and also implements the `buffer:` keyword arg which allows an existing buffer to be manipulated rather than starting from an empty new buffer and returning the new object.
Also, one extra `xit`ed NATFIXME was removed.
This should close issue #195 , as the percent_spec was already passing.
=> Array#pack q/Q and buffer: kwarg support

spec/core/enumerable/sum_spec.rb
And disable the new spec for Kahan's compensated summation algorithm.
I had this change in the branch of #825, but I think it's better to merge it separately. It keeps the other branch a bit more focused on the actual problem it's trying to solve.
=> Sync enumerable/sum_spec with upstream

src/string_object.cpp, test/natalie/string_test.rb
The statement `"\n".chomp!`` tried to check if there was a `\r` before the `\n`, which caused an out of buffer read
=> Fix out of bounds read in String#chomp!

spec/core/kernel/Integer_spec.rb, src/kernel_module.cpp, test/natalie/Integer_test.rb
There was an explicit check for this in the spec for `String#to_i`, but not in the spec of `Kernel.Integer`. It turned out MRI does this conversion.
I added https://github.com/ruby/spec/pull/997 as an upstream request to add this to the spec.
=> Convert base argument to integer in Kernel.Integer using to_int

spec/core/integer/coerce_spec.rb, spec/shared/rational/coerce.rb
This fixes two crashes in the nightly overview of the specs, which means we can now run the other tests in the file, and get more specific error messages in the failed tests.
=> Add stub file for lib/bigdecimal.rb

src/file_object.cpp, test/natalie/file_test.rb
These don't do anything on *nix as far as I can tell. And we don't support Windows anyway. So let's just ignore them for now.
=> Allow "b" and "t" modes for File open

lib/optparse.rb
Don't require a space between the short switch and the value. This makes the natalie executable more compatible with the ruby executable.
This should fix some crashes in the nightly spec run.
=> Accept the syntax "-rset" in optparse

spec/core/array/pack/shared/float.rb, src/array_packer/packer.cpp
This looks like it is an explicit conversion in Ruby, not using Float or Object#coerce. A String '0.75' does not work.
=> Pack rational as float

spec/core/numeric/i_spec.rb, src/complex.rb, src/numeric.rb
And remove it from Complex. Even if there is no spec for it, this looks like the behaviour of MRI.
MRI still enables to rebind the method to call it:
irb(main):001:0> Numeric.instance_method(:i).bind(Complex(1)).call
=> (0+1i)
irb(main):002:0> Numeric.instance_method(:i).bind(Complex(1, 2)).call
=> (-2+1i)
This does not work in Natalie, it tries to call `#negative?` on the Complex value. Given that there is no spec for it, and the MRI behaviour seems a bit weird given the method `Complex#i` is explicitly removed, I'm just going to assume this is undefined behaviour.
=> Implement Numeric#i

spec/core/string/ascii_only_spec.rb, src/string_object.cpp
If the encoding is not ASCII compatible, the string is not, even if it is empty.
Update the tests accordingly, and fix a type (Implemet => Implement) as well.
=> Query encoding in String#ascii_only?

include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/numeric/quo_spec.rb, src/integer_object.cpp, src/numeric.rb
Both the specs and the MRI implementation showed this method should be defined on `Numeric` instead of `Integer`. Some subclasses like `Rational` and `Float` still have their own implementation (just like MRI).
Moving the code just happened to fix all the failing specs.
=> Fix Numeric#quo

Rakefile
Now you can simply do `rake test_folder[spec/core/integer]` and run all the specs from the folder. The syntax is a bit finicky, but that's how Rake works.
=> Add test_folder command to rake

include/natalie/complex_object.hpp, include/natalie/object.hpp, include/natalie/rational_object.hpp, spec/language/singleton_class_spec.rb, src/object.cpp, test/natalie/complex_test.rb, test/natalie/rational_test.rb, test/natalie/singleton_class_test.rb
A fine example of yak shaving when I was looking into fixing the spec of [Singleton method on Numeric](https://github.com/ruby/spec/blob/master/core/numeric/singleton_method_added_spec.rb). I found some inconsistencies between objects being frozen with MRI. A few new Natalie tests have been added, I'm going to try to push those to the upstream specs.
=> Fixes for singleton classes and frozen properties

lib/set.rb
Just noticed this while I was writing  #875: The stringification methods of Set were missing the final `>`. Since the specs are pretty incomplete in this case (we're skipping the spec for the recursive case, so the only test left was just to see if the output was a String), this went unnoticed in the specs
=> Add missing ">" to Stringification of Set

bin/natalie, spec/command_line/dash_e_spec.rb, test/support/spec.rb
This did require a slight fix in the `ruby_exe` method as well, since this hit a case we didn't see before.
=> Enable passing `-e` multiple times

test/support/spec.rb
For now just ignore the value. The description does not appear to be used, and this sub implementation resolves a few crashes in the spec results.
=> Stub method SpecEvaluate#desc=

include/natalie.hpp, include/natalie/encoding/utf16be_encoding_object.hpp, include/natalie/encoding_object.hpp, include/natalie/encodings.hpp, spec/core/array/shared/inspect.rb, spec/core/hash/shared/to_s.rb, spec/core/string/ascii_only_spec.rb, src/encoding/utf16be_encoding_object.cpp, src/natalie.cpp
In my mind, this would resolve a lot of issues in the spec, but once I tried I could only enable 1 line.
=> Implement UTF16-BE encoding

spec/core/string/chop_spec.rb
* Update the non-ASCII String tests, revert them to the original code and disable the block. Update the FIXME marker to indicate the actual problem here, since utf-32be has been implemented. There is no added value in changing the encoding to UTF8, since that dances around the actual test, and does not add any value to what's already tested in this spec
* Import the "same encoding" test from upstream
* Remove some trailing whitespace
=> Update string_chop spec

bin/natalie, lib/natalie/repl/legacy.rb, lib/natalie/repl/main.rb
This is the first step in fixing #875. The default/legacy REPL now works. The experimental REPL does receive the argument, but ignores it for now.
I might have a look at the v2-repl one day, but for now this resolves a few issues I had to work around.
=> Pass -r arguments to Natalie to legacy REPL

include/natalie/module_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/basicobject/basicobject_spec.rb, spec/core/basicobject/fixtures/common.rb, spec/core/basicobject/fixtures/remove_method_missing.rb, src/module_object.cpp
This unearthed an error with include without parentheses. Support for the argument `inherit` in `Module#constants` has been added.
=> Import basicobject_spec

include/natalie/encoding_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/encoding/find_spec.rb, spec/core/encoding/inspect_spec.rb, spec/core/encoding/locale_charmap_spec.rb, src/array_packer/string_handler.cpp, src/encoding_object.cpp, src/natalie.cpp
+ Add `Encoding.locale_charmap`
+ Add `Encoding.dummy?`.  None of our active encodings are dummies, so this is not yet fully testable.
+ Fix `Encoding.find` to support special lookups for "internal", "external", "filesystem" and "locale"
+ Add support for getting/setting default_external, locale and filesystem encodings, with a static initializer.  Unclear at this point how OS dependent this is for the platforms Natalie supports.
=> Fixes for EncodingObject

include/natalie/file_object.hpp, spec/core/file/chmod_spec.rb, spec/core/file/constants/constants_spec.rb, spec/core/file/file_spec.rb, spec/core/file/null_spec.rb, spec/core/filetest/directory_spec.rb, spec/core/filetest/size_spec.rb, spec/core/filetest/zero_spec.rb, spec/core/io/constants_spec.rb, spec/core/io/io_spec.rb, src/file_object.cpp, src/natalie.cpp
-    Add `File::Constants::NULL`
-    Include `File::Constants` in `File`
-    Include `File::Constants` and `Enumerable` into `IO`
- because both File and IO now include the `File::Constants`, moving the module definition code back into natalie.cpp was convenient and felt appropriate. 
-    Fix `File.chmod` to accept object that responds to `to_int`
-    Add IO support for `FileTest.size/directory` and add specs.
=> File/FileTest Improvements

lib/natalie/compiler/macro_expander.rb, lib/rbconfig.rb, spec/library/rbconfig/rbconfig_spec.rb, test/ruby/rbconfig_test.rb
Fix `RbConfig` to use String keys (instead of Symbol keys) and enable applicable specs.
Improve error messages for load/require failures in macro_expander to note file/line for `macro_require_relative` and `macro_load`.
I added a few more entries into RbConfig in order to pass the specs, however the Natalie configure process is not the same as MRI's configure process so some of the entries in RbConfig may not make sense or could be incorrect.
I had made these edits a few weeks ago while trying to get Mspec working with Natalie, as Mspec has a dependency on several RbConfig variables.
=> RbConfig updates

spec/library/set/include_spec.rb, spec/library/set/pretty_print_spec.rb
The specs `include_spec` and `pretty_print_spec` pass with the current implementation. These issues can be closed in #840.
=> Import passing specs for Set

lib/bigdecimal.rb, spec/core/integer/coerce_spec.rb, spec/shared/rational/coerce.rb
This one is good enough to help a few tests pass that depend on a very basic BigDecimal object, but are not really related to it.
=> Add BigDecimal stub

test/support/spec.rb
I tried using this with `kernel/backtick_spec`, but that simply yielded the next error, so I removed that spec again.
This method is required in a bunch of rubyspecs, so implementing it should get some more specific error messages in the nightly runs.
I tried it with this code in a temporary spec just to see if it works:
```ruby
`#{ruby_cmd('p 1 + 2')}`.should == "3\n
```
=> Implement ruby_cmd for specs

spec/shared/rational/equal_value.rb, src/float_object.cpp, src/integer_object.cpp, src/rational_object.cpp, test/natalie/numeric_test.rb
This one has a dependency on the changes of  #897, and will crash without it. I'll leave the case as a draft for now.
The behaviour has been analyzed by reopening the classes Integer, Float, Complex and Rational, and printing debug messages whenever `coerce` or `==` is called. It turns out: these numeric classes do not use coerce, but instead flip the call sequence if the receiving object is not compatible with this class. This is even explicitly mentioned in the specs of Rational.
This has been split of from  #825 since that MR is about coercing integers, and this does not use coercion.
=> Update == method for Numeric subclasses

spec/core/string/include_spec.rb, src/string_object.cpp
Won't be fully spec compliant until we implement EUC-JP encoding, for now just fixing the simple empty string cases.
=> Fix String#include? for empty strings

test/natalie/integer_test.rb
* Add bitwise AND, this one was missing
* Fix names of mocks
* Fix coercion in mocks, it should return the argument as the first entry, and the mocked self as the second entry.
This was a big source of confusion in  #825, where the bitwise operators started to behave different from the rest.
Since these bitwise operations are commutative, the result is still the same with the current code.
=> Update Natalie specs for bitwise operations on Integers

src/kernel.rb, src/object.cpp, src/string_object.cpp, test/natalie/enum_for_with_keyword_arguments_test.rb, test/natalie/string_test.rb
I ran into this issue when working on `String#each_line`, which is one of the few occasions where you can pass on keyword arguments into an enumerator. Something breaks, but I haven't gotten to the exact cause yet. #807 was just the beginning of this quest :wink: 
This case adds a dumb example to show the issue. The spec passes in Ruby (I've used 3.1), and errors in Natalie.
The spec adds an ugly monkey patch for String, which probably should be removed at some points, but it's good enough to test and work with.
=> Make enum_for compatible with keyword arguments

src/match_data_object.cpp
These values can be nil, for example this line from the specs:
/something is( not)? (right)/.match("something is right")
#<MatchData "something is right" 1:nil 2:"right">
The output is still the same as Ruby's output.
This will probably fix a few crashes in the regexp spec
=> Remove as_string call in MatchDataObject::inspect

include/natalie/regexp_object.hpp
This prevents crashes when using multi byte group names
The code in [regexp/begin_spec](https://github.com/ruby/spec/blob/master/core/matchdata/begin_spec.rb#L99) caused another error.
=> Encode regexp match groups as UTF8

spec/core/random/random_number_spec.rb, src/random.rb
These methods are not mentioned in the documentation of the Random class of Ruby, but the specs imply they're just an alias of Random.rand / Random#rand.
=> Add Random.random_number and Random#random_number

include/natalie/match_data_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/matchdata/dup_spec.rb, spec/core/matchdata/string_spec.rb, src/object.cpp
That resolves another crashing state in the nightly spec result. I added the readers `MatchData#string` and `MatchData#regexp` as well, to fully make this spec pass
=> Implement MatchData#dup

include/natalie/block.hpp, include/natalie/method.hpp, include/natalie/method_object.hpp, include/natalie/proc_object.hpp, lib/natalie/compiler/instructions/create_lambda_instruction.rb, src/kernel_module.cpp, src/method.cpp, test/gc_lint.rb, test/natalie/define_method_test.rb
Blocks created from a method object (using #to_proc or the ampersand) do behave different than normal blocks passed to #define_method. When calling the newly defined method the "self" object should be the "self" object of the block rather than the current "self" object.
For example:
```ruby
class MethodHolder
class << self
define_method(:new, &String.method(:new))
end
end
p MethodHolder.new.class
```
This should not invoke the "new"-Method on the MethodHolder class but on the String class.
Closes #718
=> Fix #define_method with blocks converted from a Method

spec/core/string/gsub_spec.rb, src/string_object.cpp
By taking the easy route of converting the argument in a Regexp.
Imported `string/gsub_spec` and painstakingly disabled all the failing and crashing tests.
=> Add String argument support in String#gsub

spec/core/string/gsub_spec.rb, src/string_object.cpp
It is possible to call String#gsub with only one argument and no block, in that case the reply should be an enumerator. The code did not handle that case, and tried to dererence a nullptr into a string.
This change adds the extra case with a NAT_NOT_YET_IMPLEMENTED. It still halts the program, but at least now it shows what is missing, and it resolves the security issues of segfaults.
=> Prevent segfault in String#gsub

lib/set.rb, spec/library/set/shared/inspect.rb
This fixes the remaining issues of `Set#inspect` and `Set#to_s` in #840. The official specs still won't compile with Natalie, but that's due to #873 and not related to `Set`.
=> Handle self-references in Set#inspect

include/natalie/time_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/time/minus_spec.rb, spec/core/time/plus_spec.rb, spec/core/time/shared/gmt_offset.rb, src/time_object.cpp
+   Add `in:` kwarg for `Time.new`, 
+    Fix `Time.new` to set UTC mode when in/zone provided.
+   Add timezone/utc-offset support for `Time.new`, including numeric, `+/-HH:MM(:SS)` and Military TZ support,
+    Fix second handling in `Time.new` .
+    Preserve utc_offset in result for `Time#+` and `Time#-`
+    Remove resolved NATFIXMEs gmt_offset specs because more of Time.new is functional.
=> Time 20230126

spec/core/float/shared/to_s.rb, spec/core/integer/chr_spec.rb, spec/core/regexp/shared/quote.rb, spec/core/string/include_spec.rb, spec/core/string/insert_spec.rb, spec/core/string/shared/concat.rb, spec/core/string/shared/eql.rb, spec/library/stringio/external_encoding_spec.rb, spec/library/stringio/initialize_spec.rb, spec/shared/string/end_with.rb
A bunch of NATFIXMEs had been fixed, others needed an update as to why the NATFIXME marker was still needed
=> Update specs for new encodings

lib/strscan.rb, test/lib/strscan_test.rb
Currently omitting the last character from the result string. For example:
$ bin/natalie -r strscan
nat> StringScanner.new('foo bar').scan_until(/(?=\s)/)
"fo"
=> Fix StringScanner#scan_until for zero length matches

test/natalie/natfixme_test.rb, test/support/spec.rb
Based on ideas from @herwinw 👏 
This PR implements #837 with some additions:
- Able to wrap expectations/matchers inside an 'it' block without modification
- Adds a new `NatalieFixMeException` class.
- Adds optional `klass:` and `match:` keyword arguments so that the expected failure signature is captured. If the specs no longer fail or the failure is different (no longer same as the given klass / match), then it will raise `NatalieFixMeException`
Some tests were added, hopefully I haven't missed some critical use cases.  Feedback would be appreciated.
=> Add implementation of NATFIXME for review

spec/core/float/comparison_spec.rb, spec/core/float/gt_spec.rb, spec/core/float/gte_spec.rb, spec/core/float/lt_spec.rb, spec/core/float/lte_spec.rb, src/float_object.cpp, src/integer_object.cpp
These should return `nil` and `false` if either side is `NaN`
=> Make float and integer comparison methods spec compliant

src/float_object.cpp
This code path first returned Float::NaN, which made the specs fail, so these specs were disabled. Pull Request #969 updated some behaviour of Float::NaN, which means the test would now erroneously pass. At the same time, Pull Request #959 did enable the tests with a NATFIXME block. These two changes combined resulted in passing tests within a NATFIXME block.
For now, just raise an exception so it's clear this still has to be implemented, and make the specs pass again.
=> Raise argumenterror when raising negative to fractional

src/struct.rb
The old version results in a parser error in MRI.
=> Add missing comma to alias_method in Struct

test/runner.rb
This has two advantages.
First of all, this groups the compilation step, so we only have to run the compiler one. This results in a small performance boost (running the tests of `spec/library/set` on my machine drop from around 1m35 to 1m20, so that's around 15% performance increase).
Second, this does continue the run if a single test is failing, and shows a readable overview at the end of the run.
Because Natalie does not support variables in `load` or `require`, we had to jump through a few hoops to combine all the arguments into a single file.
=> Group tests in test/runner.rb

spec/core/class/dup_spec.rb, spec/core/class/fixtures/classes.rb, spec/core/struct/dup_spec.rb, src/object.cpp
In case a Class is duplicated, we need to duplicate the singleton class too. This was tested in the dup spec of Struct, but the same thing happened when you replaced `Struct.new(:foo)` with `Class.new {}` in that test.
Duplicating any other instance should not copy the singleton class, this is explicitly tested in `spec/core/hash/shared/store.rb`
=> Improve Kernel.dup

spec/core/symbol/name_spec.rb
This issue has been resolved, this file is now synced with upstream again.
This checks another box in #963, since this means there are no more NATFIXME entries left in the symbol folder.
=> Remove natfixme from symbol/name_spec

.github/workflows/build.yml, lib/natalie/compiler.rb, lib/natalie/compiler/instructions/inline_cpp_instruction.rb, lib/natalie/compiler/pass1.rb, lib/openssl.cpp, lib/openssl.rb, spec/library/openssl/random/pseudo_bytes_spec.rb, spec/library/openssl/random/random_bytes_spec.rb, spec/library/openssl/random/shared/random_bytes.rb
Which also means this adds a hard dependency on the openssl headers to be able to compile. It would probably be nice to just skip the extension if those can't be found.
I might want to look into implementing more of OpenSSL later on, since cryptography is pretty much a requirement to do anything these days.
=> Implement OpenSSL::Random.random_bytes

include/natalie/file_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/file/new_spec.rb, spec/core/file/size_spec.rb, src/file_object.cpp
Add optional 3rd argument to `File.new` (perm argument)
Enhance `File.new` to pass additional specs.
Add `File#size` instance method
Add check for `is_closed()` to some instance methods (atime, ctime, mtime, size) to prevent attempted stat on a closed file-descriptor
=> File.new, File#size

spec/core/dir/rmdir_spec.rb, src/dir.rb
I pulled in the spec for `core/dir/rmdir_spec.rb` and noticed 5 of the 6 tests were passing, but the existing C++ code looked correct by inspection.  Then I realized that we had a duplicate definition of `Dir.rmdir` in `dir.rb`.  The C++ one passed all specs; removing the slightly less-functional ruby version made the tests pass 🎉
=> Fix Dir.rmdir and add spec

include/natalie/file_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/dir/dir_spec.rb, spec/core/dir/mkdir_spec.rb, src/dir_object.cpp, src/file_object.cpp, test/natalie/file_test.rb
Fixes `Dir.mkdir` to meet the spec.
As part of this work, `File.chmod` had to be enhanced to support variable arguments.  Previously, chmod was written to take one file argument and always return `1`.  Surprisingly, the spec for `File.chmod` did not test any of the var-args, so a simple additional test was added for a mode arg with no file args, but it would be nice to add additional tests upstream for the zero-file and multi-file arg cases, though it could be argued the multi-arg case is already handled in the spec for `Dir.mkdir`.
=> Dir.mkdir and File.chmod

lib/openssl.cpp, spec/library/openssl/config/freeze_spec.rb, spec/library/openssl/shared/constants.rb
Which is good enough to make the config/freeze_spec pass, since that once doesn't do anything on OpenSSL 3.0 and above.
=> Include OpenSSL::VERSION constant

include/natalie/dir_object.hpp, include/natalie/encoding_object.hpp, lib/natalie/compiler/binding_gen.rb, src/dir.rb, src/dir_object.cpp, src/encoding_object.cpp, src/string_object.cpp
+ Add `Dir#children` and `Dir#entries`
+ Add `Dir#each_child` and `Dir#each`
+ Add `Dir.children` and `Dir.entries` (class method)
+ Add `Dir.foreach` and `Dir.each_child` on ruby side
+ Add encoding support for `DirObject`
+ Move `find_encoding_by_name` from string_object.cpp to encoding_object.cpp/hpp.
+ Refactor `find_encoding` code.
+ Remove duplicate ruby methods for `Dir`
+ I've noticed this happen a few times, whereby it's not obvious there is duplication, but I am unsure how easy it would be to add a lint check for this.
=> Dir support for collection/iteration methods

spec/core/string/modulo_spec.rb, src/string.rb
Per #869 
This is a PR to enhance capabilities of the String format function `String#%` 
+ Added support for `%c`, `%b`, `%B`, `%X`, `%o`, `%i`, and `%u`
+ Added support for `#`, `+`, ` `, `-`, `*` and `0` Flags
+ Added support for width, position and precision (though precision is not really doing much yet)
+ Implemented padding (left, right, zero) for integer-type and char/string/inspect cases
Many NATFIXMEs were removed and a lot of other xited specs were un-xited 
A lot of the code changed and several new lambdas were added to try and keep it from becoming a giant run-on function.  
I'm working under the assumption that lambdas are preferred to keep new ruby functions from being created.
IIRC Kernel.sprintf/printf are doing much the same thing, it might make sense to figure out how to …
=> String format updates

src/natalie.cpp
When running Natalie with `-d valgrind`, we weren't cleaning up NativeProfiler, so it looked like a memory leak. I don't think it's a big deal, but does clean up the output from Valgrind so it's easier to find actual memory leaks.
=> Delete NativeProfiler at exit

README.md
if you try to compile by putting ***-c hello*** at the end, it won't return executable output :) (in my case that was a problem) 
now it's ok
=> Fixed README.md Compiling part

include/natalie/env.hpp, include/natalie/io_object.hpp, spec/core/io/print_spec.rb, spec/core/io/puts_spec.rb, src/env.cpp, src/io_object.cpp
This PR mostly contains fixes for output related methods in IO:
+  `IO#write` : A method variant that takes a single `Value` was added.  This is called by the `Args` variant.
+  `IO#print` : Now supports using global record and file separators and last-line.
+  `IO#puts` : Non-ruby-side exposed C++ helper methods `putstr` and `putary` were also added.  I had initially tried to do this with polymorphism by writing functions that took `StringObject*` or `ArrayObject*` arguments, but the compiler got confused between these and `Value`, so I renamed them accordingly.
+ Note that there was a test that I had to `xit` for running `puts` on a recursively defined Array.  MRI is doing some sort of check to handle this but I was not sure what the most appropriate way to handle this is in Natalie. …
=> IO output fixes

spec/support/nightly_ruby_spec_runner.rb
This broke in #1065 because the `-c #{binary_name}` args were after the source file.
=> Fix nightly build

spec/core/string/chomp_spec.rb, spec/core/string/chop_spec.rb, src/string_object.cpp, test/natalie/string_test.rb
Previously the String chop/chomp methods were `xit`ed / `NATFIXME`d for the multi-byte encoding cases (e.g. utf-32be).
This fixes the chomp/chomp!/chop/chop! methods to pass all specs.
=> Fix String chomp/chop methods to work properly for multi-byte encodings

lib/natalie/repl/main.rb
Without this change, a syntax error in the REPL causes it to exit. This does not match up with the upstream REPL, which continues.
=> Continue after SyntaxError in REPL

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/fileno_spec.rb, spec/core/io/isatty_spec.rb, spec/core/io/shared/tty.rb, spec/core/io/to_i_spec.rb, spec/core/io/tty_spec.rb, src/io_object.cpp
+ Add `IO#isatty` and `IO#tty?`
+ Refactor the check IO closed + raise `IOError` in a few methods. Noting that this changes some of the error-messages so that they are common and slightly less specific, but I think that is okay and consistent with MRI.
+ Fix `IO#fileno` to raise when the IO is closed.
=> IO updates

Dockerfile
Docker builds weren't working because of recent breaking changes in pip that now requires system-wide package installations to be very explicit and otherwise prefer the package manager of the distro you are using.
=> Fix CI builds

lib/set.rb, spec/library/set/shared/inspect.rb
This is de default behaviour for Ruby containers. This resolves some recent issues in the specs of `Set#inspect` and `Set#to_s`.
=> Use `inspect` instead of `to_s` for Set entries stringification

spec/core/proc/binding_spec.rb, src/proc.rb
The code in the `eval` statements results in a warning and has been disabled for now.
=> Make Proc#binding public

spec/library/socket/addrinfo/protocol_spec.rb
We had some local changes to work around a missing Addrinfo.ip, but this one hase been implemented since.
=> Sync spec for Addrinfo#protocol

lib/socket.cpp, lib/socket.rb, spec/library/socket/basicsocket/send_spec.rb, test/support/spec.rb
There are still a few NATFIXMEs in the spec, they are all related to UDP sockets, TCP seems to work fine.
A script like this now works:
```ruby
s = TCPSocket.new('natalie-lang.org', 80)
s.send("GET / HTTP/1.0\r\nHost: natalie-lang.org\r\n\r\n", 0)
puts s.read
```
=> Start with BasicSocket#send

include/natalie/symbol_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/shared/to_sym.rb, spec/core/symbol/encoding_spec.rb, src/string_object.cpp, src/symbol_object.cpp
There is one issue left: the symbol strings are internally still saved as bytes, without the encoding information. This means the code can't distinguish between two symbols whose byte representation is the same but with different encodings. `spec/core/string/shared/to_sym.rb` has a disabled test for this case.
=> Implement Symbol#encoding

include/natalie/symbol_object.hpp, src/symbol_object.cpp, test/natalie/symbol_test.rb
This speeds up `Symbol#inspect` by quite a lot by reusing the regex object.
For this silly benchmark:
```ruby
10_000.times do |i|
i.to_s.to_sym.inspect
end
```
...it produces about a 15x speedup:
```
→ hyperfine ./before ./after
Benchmark 1: ./before
Time (mean ± σ):     788.0 ms ±  17.1 ms    [User: 783.7 ms, System: 4.1 ms]
Range (min … max):   757.5 ms … 815.0 ms    10 runs
Benchmark 2: ./after
Time (mean ± σ):      47.6 ms ±   0.7 ms    [User: 45.0 ms, System: 2.6 ms]
Range (min … max):    46.2 ms …  49.6 ms    61 runs
Summary
'./after' ran
16.55 ± 0.44 times faster than './before'
```
=> perf(Symbol#inspect): Reuse onigmo regex for testing if symbol should be quoted

include/natalie/match_data_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/matchdata/names_spec.rb, src/match_data_object.cpp
Since we've saved the regexp object, this suddenly is trivial. This is preparation for the actual named captures.
=> Implement Matchdata#names

spec/core/string/gsub_spec.rb, src/string_object.cpp
This replaces the NAT_NOT_YET_IMPLEMENTED, which aborts the run. This means we can use the NATFIXME block style in the specs without aborting the executable.
=> Throw a NotImplementedError im String#gsub without block

spec/shared/string/start_with.rb
The check is enclosed in a NATFIXME, so we can actually run this one.
=> Enable check in String#start_with? spec

include/natalie/env_object.hpp, src/env_object.cpp
These do not belong in the public interface, where every file that includes the EnvObject header suddenly includes those files too.
=> Move includes of EnvObject from header to implementation

src/process.rb
This is currently the first blocking issue for `Process.clock_gettime` and a number of specs in `Time`.
=> Add Process.CLOCK_* constants

test/support/spec.rb
This is seen in https://github.com/ruby/spec/blob/b8a59fda781849ddc220054d22a2750d5c5cf124/core/enumerator/chain/rewind_spec.rb#L6 where there are no arguments.
=> Make and_yield in the spec runner take any number of arguments

include/natalie/process_module.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/process/clock_gettime_spec.rb, spec/core/process/fixtures/clocks.rb, spec/core/time/now_spec.rb, spec/core/time/shared/now.rb, src/process_module.cpp
It still needs support for the second (optional) argument, but this works for most use cases.
=> Implement basic version of Process.clock_gettime

include/natalie/regexp_object.hpp, src/match_data_object.cpp, src/regexp_object.cpp
This removes a bunch of hardcoded encoding selections from the Regexp and MatchData implementations, and replaces them with a lookup to convert between the two Encoding implementations.
=> Conversions between Ruby String encondings and Regexp encodings

spec/core/fiber/resume_spec.rb, src/fiber_object.cpp, test/natalie/fiber_test.rb
And removed this check from the test/natalie folder, since it is checked in the specs folder.
=> Fix error message for double resume of Fiber

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/dir/shared/exist.rb, spec/core/matchdata/string_spec.rb, spec/core/string/gsub_spec.rb, spec/core/string/sub_spec.rb, src/string_object.cpp
Another two checks for #217 
The current implementations depend on `String#sub`/`String#gsub` and replaces its own internals with the result. It would be more efficient to reverse this logic and implement the non-mutating versions as a chain of `dup` and the mutating version. I left that one as a future work.
This resolves a grand total of 2 other dependencies in the specs, I expected that to be much higher.
=> Implement String#sub! and String#gsub!

lib/fiber.rb, spec/core/fiber/blocking_spec.rb, spec/library/fiber/alive_spec.rb, spec/library/fiber/current_spec.rb
This helps with the specs that require this file.
This feels a bit like a hack, but since support for Ruby 3.0 will probably be dropped less than a year from now, I would think this is good enough.
This really improves the overview at https://natalie-lang.org/specs, where most of the Fiber specs now simply crash on the require statement.
=> Add stub file fiber.rb to lib

include/natalie/proc_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/proc/fixtures/source_location.rb, spec/core/proc/source_location_spec.rb, spec/core/symbol/to_proc_spec.rb, src/proc_object.cpp
I had this one in a local branch for a while, but it needed the changes of https://github.com/ruby/spec/pull/1060 before we could really merge them
The line numbers are often a few lines off, but that is simply because it gets the wrong information from Env. These FIXMEs should probably be changed somewhere in the compiler itself.
Even if the line numbers are a bit off, it's still a really useful tool to debug some things.
Before anyone gets the idea of simply copy-pasting this code to `Method#source_location`: this one does not get any line information, so it would just return `nil`.
=> Implement Proc#source_location

spec/library/set/shared/inspect.rb
The parser error of the original code has been resolved, so we remove this local workaround.
=> Update spec for Set#inspect

spec/core/file/new_spec.rb
This includes some new tests, e.g. keyword arguments and access checks.
It turns out the issues mentioned in #1176 do get tested with `File.new`
=> Refresh spec for File#new

include/natalie/io_object.hpp, spec/core/file/shared/path.rb, spec/core/file/to_path_spec.rb, src/io_object.cpp
This exposes some issues in `File.new`, I'll have to check to see if these are tested in the relevant spec.
=> Fixes to IO#to_path

include/natalie/fiber_object.hpp, lib/natalie/compiler/binding_gen.rb, lib/set.rb, spec/core/fiber/storage_spec.rb, spec/library/set/shared/inspect.rb, src/fiber_object.cpp
Even though this is a Ruby 3.2 feature, it can be a very useful tool to handle some issues with cyclic data structures in our code. For example, the cycle detection of `Set#inspect` only works for 1 level depth:
```ruby
def inspect
items = to_a.map { |e| equal?(e) ? '#<Set: {...}>' : e.inspect }
"#<Set: {#{items.join(', ')}}>"
end 
```
This passes the specs because the specs are simply 1 level deep:
```ruby
it "correctly handles self-references" do
(set = Set[]) << set
set.send(@method).should be_kind_of(String)
set.send(@method).should include("#<Set: {...}>")
end
```
It would result in an infinite loop if we had a depth of more than 1:
```ruby
a = Set[]
b = Set[a]
a << b
a.inspect
```
With Fiber storage, we could resolve this with something like this:
```ruby
def inspect
if …
```
=> Implement Fiber#storage and friends

lib/base64.rb
This is in line with the Style/UnpackFirst rule of Rubocop. This is faster by removing the temporary array (except in the current state of Natalie)
=> Prefer String#unpack1 over chaining unpack and first

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/fcntl_spec.rb, src/io_object.cpp
Since I had to use `fcntl` in  #1195, the generic interface to the method was pretty easy to do.
=> Implement IO#fcntl

src/io_object.cpp, test/natalie/io_test.rb
This is similar to #1190 where we had to convert the exception in case of no write access. Two helper methods have been added to help with this check, I expect we'll be needing a lot more of them.
https://github.com/ruby/spec/pull/1068 has been added as an upstream request to add this to the specs. For the time being, a local test has has been added.
=> Add read check in IO#getbyte

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/read_spec.rb, src/io_object.cpp
This accidentally fixes an issue with `IO#read` too, where a `nil` length argument would cause an error.
=> Add length and offset parameters to IO.read

include/natalie/random_object.hpp, lib/natalie/compiler/backends/cpp_backend.rb, lib/natalie/compiler/flags.rb, spec/language/undef_spec.rb, src/array_object.cpp, src/io_object.cpp, src/struct.rb, test/natalie/assign_test.rb, test/natalie/method_test.rb, test/runner.rb, test/spec_helper.rb, test/support/spec.rb
This was quite a yak shave, and I don't have the energy to separate it into a bunch of small PRs. So this is a grab bag.
Here is my story:
1. Notice a few warnings with the release build of Natalie, e.g. `rake build_release`.
2. Fix those warnings, one of them being an integer overflow, which should have been caught by specs.
3. Notice that some specs using the `RaiseErrorExpectation` with a block aren't failing as they should. Fix that.
4. That causes several more false-positives to start failing in the suite.
5. Find a compiler bug. See #1201.
6. Cry.
=> Fix some compiler warnings, an integer overflow bug, a bug in our spec runner, document a compiler bug, and some other miscellaneous stuff

src/io_object.cpp
It turns out you can call fsync in read only streams in MRI as well.
According to fsync(2): On some UNIX systems (but not Linux), fd must be a writable file descriptor.
=> Remove incorrect TODO from IoObject::fsync

spec/core/io/read_spec.rb, src/io_object.cpp
* Return empty string instead of nil in case of explicit 0 length value.
* Simplify cleanup of allocated memory
* Handle errors in the read(2) call
=> More fixes to IO#read

include/natalie/method_info.hpp, src/method_info.cpp, src/module_object.cpp, test/gc_lint.rb
That way we can let our GC lint script do the work to catch mistakes.
=> Move responsibility of GC visiting members into MethodInfo class

include/natalie/integer.hpp, spec/core/float/coerce_spec.rb, src/array_packer/integer_handler.cpp, src/bsearch.cpp, src/float_object.cpp, src/integer_object.cpp, src/object.cpp, src/string_object.cpp
There were several places where we were pretending we could squeeze a bigint into a long long and just carrying on with the result.
Now we will panic if this is done. If you really want to do this, you can call `integer().to_bigint().to_long_long()`.
As a bonus, this work found several bugs and let us remove a NATFIXME in Float#coerce. 🎉
=> Stop silently truncating bigints

src/io_object.cpp
There is a spec for this behaviour (spec/core/io/output_spec.rb), but this spec runs fine. The code pasted in the REPL did rais the error about the conversion.
=> Fix to_s/to_str mixup in IO#<<

src/random_object.cpp
I'm currently on macOS 13 with the following:
$ gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
I'm seeing this build error:
...
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:1851:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/ranges_sample.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/sample.h:18: …
=> Fix macOS build error from RandomObject::bytes

spec/core/random/bytes_spec.rb, src/random_object.cpp
This is the future work I proposed in #1214. After playing around for a bit, it turns out that using `uint32_t` as blocks resolves the issue of #919.
=> Random bytes buffer

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/inspect_spec.rb, spec/core/proc/source_location_spec.rb, src/io_object.cpp
The specs did need a few updates to be able to run, since we don't have `IO.popen` yet.
=> Implement IO#inspect

lib/natalie/compiler/binding_gen.rb
The correct method was already available, but it just needed the right binding.
=> Fix FileTest#executable_real?

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/dir/shared/open.rb, src/io_object.cpp, test/natalie/io_test.rb
For now they're just stub values that don't actually do anything, but they're getting in the way of keyword arguments for IO creation and duplication.
=> Add IO#autoclose? and IO#autoclose=

spec/core/io/printf_spec.rb, spec/core/kernel/printf_spec.rb, src/io.rb, src/kernel.rb
@seven1m I included a call to `#to_str` in the `Kernel` module, that's what MRI does too (even though it's not in the specs of `Kernel#sprintf`. I added those specs as well, we now have support in the IO object to run those.
=> Implement IO#printf

include/natalie/file_object.hpp, include/natalie/io_object.hpp, src/dir_object.cpp, src/file_object.cpp, src/io_object.cpp
These functions are not specific to File IO, but are in use for generic IO. The io_object file seems like a better place.
This is part of the preparation for #1225
=> Rename fileutil to ioutil

include/natalie/encoding/utf8_encoding_object.hpp, spec/core/encoding/default_external_spec.rb, src/encoding_object.cpp
* Update `filesystem` when updating `default_external`
* Remove hardcoded `locale`, `external` and `filesystem` aliases from UTF-8. Add them dynamically to the aliases, based on the settings
* Add `internal` alias, also based on the settings
=> Fixes to special Encoding aliases

lib/natalie/compiler/pass1.rb, lib/natalie/parser.rb, test/natalie/regexp_test.rb
```ruby
/(?<name>\w+) rocks/ =~ 'Tim rocks'
p name
```
=> Implement regexp named capture variables

include/natalie/io_object.hpp, src/file_object.cpp, src/io_object.cpp
The old version worked at two different levels of abstraction:
* Parse the input mode and return that as a bitmask for the file descriptor
* Parse some encoding references and change these on the IoObject argument
The changing the object part is getting in the way of the keyword arguments (#1225), where it would be better to parse all the information before setting anything.
This change is a(nother) preparation for the keyword arguments: create a struct to return the parsed string as three values (the file access mode and the two encodings), and move the application of these settings to the callers.
This class will be extended with the keyword parsing.
=> Rework flags_obj_to_flags

spec/core/module/attr_spec.rb, src/module_object.cpp
Show a warning in verbose mode.
The code checking for `env->global_get("$VERBOSE"_s)->is_truthy()` is something that screams for an abstraction.
=> Make attr spec-compliant (for real this time)

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, lib/socket.cpp, spec/core/io/initialize_spec.rb, spec/core/io/read_spec.rb, spec/core/io/shared/new.rb, src/file_object.cpp, src/io_object.cpp
This code is a mess, I don't think I've ever written so many nested if-statements without a deadline. And it's only partially because the Ruby code has to keep backwards compatibility in the options and provides like 4 different ways to set the encoding, which may clash, or might just overwrite things.
Another issue is that we extract the keyword arguments in the bindings, which results in 8 extra arguments to `initialize`, and we'll have to repeat that for every other method that uses these keyword arguments. This should be refactored to pass along the complete keywords arguments structure. Next, the interpretation of these keyword arguments should be extracted or combined with `fileutil::flags_obj_to_flags`, so we can reuse this code.
=> Keyword arguments for IO.new

bin/natalie
Running `bin/natalie -d cpp foo.rb` now prints the source with syntax highlighting. :-)
*if you have [bat](https://github.com/sharkdp/bat) on your system.
=> Use bat for printing cpp source with -d cpp flag

include/natalie/file_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/file/new_spec.rb, spec/core/file/open_spec.rb, spec/core/io/puts_spec.rb, spec/core/kernel/open_spec.rb, src/file_object.cpp
And import the specs for `File.open` and `Kernel#open`, these did depend on keyword arguments in `File.new`
=> Add keyword arguments to File.new

spec/core/io/open_spec.rb
This is the upstream addition of checking for close if the block throws an exception (https://github.com/ruby/spec/pull/1082)
=> Refresh specs for IO.open

spec/core/file/printf_spec.rb
These pass, since we now support keyword arguments in File.open and have implemented IO#printf.
=> Import specs for File#printf

spec/core/kernel/open_spec.rb, src/kernel.rb
This is meant to be a way to fork a process and return an IO object to interact with its stdout/stdin, but the current tests result in a file named '|cat' that was left on your filesystem.
As this feature is a security issue that will be removed in Ruby 4.0 (https://bugs.ruby-lang.org/issues/19630), we probably shouldn't try to implement this.
=> Disable pipe in Kernel#open

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/eof_spec.rb, spec/core/io/inspect_spec.rb, spec/core/io/pipe_spec.rb, spec/core/io/read_spec.rb, src/io_object.cpp
This is one of those things that is used in a lot of specs (I see 37 occurrences in the specs folder when I exclude the `pipe_spec.rb` file). Most relevant for me is `IO.select`, which is one of the things I need for  #1184.
For now the only issue in the specs is the encoding, but that is partially because we don't acknowledge the `Encoding.default_external`/`Encoding.default_internal` in the generic code of the IO object. Since character encoding hardly works in Natalie, this shouldn't be too much of an issue for the first version.
Another issue: if you run this with a subclass of IO, and that subclass has a `close` method that throws an error, your program will probably crash. The `Defer` code has been copied from the old implementation of `File.open`, which had this issue too when I …
=> Implement IO.pipe

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/pipe_spec.rb, src/io_object.cpp
This is probably the only part that is specific to IO.pipe, the other issues probably have to be fixed at the generic IO level.
=> Set encoding in IO.pipe when arguments are given

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/binmode_spec.rb, spec/core/io/dup_spec.rb, src/io_object.cpp
A rather unrelated test uses `File#dup` which still causes an error for some reason (which I might investigate at a later point in time), but that's still an improvement over the panic that caused the test to be aborted.
This is one of those issues that causes a lot of IO specs to crash.
=> Implement IO#dup

bin/natalie, spec/core/module/deprecate_constant_spec.rb, spec/core/warning/element_reference_spec.rb, spec/core/warning/element_set_spec.rb, spec/core/warning/warn_spec.rb, src/kernel.rb, src/warning.rb, test/support/spec.rb
This adds the `Warning` module and a few other bits of functionality required to get the specs passing:
* ~`IO#sync=` which doesn't really do anything yet but is used in `spec/core/warning/warn_spec.rb`~
* The `-w` command line option which is used in `spec/core/warning/element_reference_spec.rb`
* A couple of fixes for `test/support/spec.rb`
Let me know if you want those pulling off into separate pull requests to make this easier to review! I've used NATFIXME for a couple of the specs which also depend on specific warnings that aren't implemented yet
=> Implement Warning module

src/io.rb
I was running into weird errors with the `File.open` spec, which fails at "opens a file that no exists when use 'a' mode" with a "Bad file descriptor (Errno::EBADF)", but the error was thrown in `touch` at the setup.
The man page of `close(2)` contains the following paragraph:
> A careful programmer who wants to know about I/O errors may precede
> close() with a call to fsync(2).
Adding a call to `fsync` appears to fix the issue.
=> Sync before close in IO.open

lib/openssl.cpp, lib/openssl.rb, test/natalie/openssl_digest/append_test.rb, test/natalie/openssl_digest/block_length_test.rb, test/natalie/openssl_digest/digest_length_test.rb, test/natalie/openssl_digest/digest_test.rb, test/natalie/openssl_digest/initialize_test.rb, test/natalie/openssl_digest/name_test.rb, test/natalie/openssl_digest/reset_test.rb, test/natalie/openssl_digest/shared/update.rb, test/natalie/openssl_digest/update_test.rb
This is still very much a work in progress. The final version of probably going to contain another 5 refactors of the C++ part of this implementation.
My 2 goals for this project (except for the obvious one of implementing the missing methods in Natalie):
=> Openssl digest improvements

spec/core/module/deprecate_constant_spec.rb, src/module_object.cpp, test/support/spec.rb, test/support/spec_utils/warnings.rb
This is one of the turtles on the way down from #1260. It required a bit of extra setup for the tests, since the tests are ran with different values than Ruby normally does.
=> Use value of Warning[:deprecated]

lib/strscan.rb, spec/library/stringscanner/element_reference_spec.rb, spec/library/stringscanner/scan_spec.rb
* `StringScanner#[]` can simply forward its arguments to `Matchdata#[]`
* Coerce string argument in `StringScanner#scan` into `Regexp`
=> Fixes to StringScanner

spec/core/integer/bit_and_spec.rb, spec/core/integer/bit_or_spec.rb, spec/core/integer/bit_xor_spec.rb
The upstream bugs are fixed, no need to keep references to those.
=> Sync specs for bitwise operators of Integer

test/support/spec.rb
https://github.com/ruby/spec/blob/e7c3c5396cbe0b12ce9f66f04287e64fb83fc097/command_line/feature_spec.rb#L53
I just happened to open a random failing test and bumped into this issue. It is used in two other specs as well.
=> Add env keyword to ruby_exe test helper

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, lib/socket.cpp, lib/stringio.rb, spec/core/file/new_spec.rb, spec/core/io/new_spec.rb, spec/library/socket/tcpserver/new_spec.rb, spec/library/stringio/new_spec.rb, src/file_object.cpp, src/io_object.cpp
This resolves the `NATFIXME : block form is not used` comment in `file_object.cpp` by explaining why we don't use the block.
=> Add warnings for IO.new (and subclasses) with block

spec/support/nightly_ruby_spec_runner.rb
The changes of #1263 showed the new information in a way that didn't really work well with the layout of the page. This change alters the output to fit this mold as best as it can. It's still not perfect, but this felt like the best we can do for now.
I did run a local webserver with the new stats file to actually watch the output this time :wink:
=> Improve layout for compile errors and crashes on nightly tests

test/ruby/natalie_test.rb
I was surprised to see the CI of #1287 passing, turns out we don't run tests in subfolders. So all those shiny new tests for OpenSSL::Digest are skipped now.
=> Run subfolders of test/natalie/ too

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/lineno_spec.rb, src/io_object.cpp
Which is a brittle interface by design: It gets updated with `IO#gets` and `IO#readline`, but not with `IO#read`. So `f.readline; f.lineno == 1`, but `f.read; f.lineno == 0`.
=> Implement IO#lineno and IO#lineno=

spec/core/io/read_spec.rb
* Add a call to IO#getbyte after the disabled call to IO#getc, so we still run the thing we want to test
* Enable all the xdescribe sections again. They were disabled when we did not support keyword arguments in IO#new, but they work again.
=> Update specs of IO#read

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/gets_spec.rb, spec/core/io/readline_spec.rb, spec/core/io/shared/gets_ascii.rb, src/io_object.cpp
The chomp command itself has been delegated to `String#chomp!`, since we'll have to support the `sep` argument and the `$/` value at some point.
=> Implement chomp argument in IO#gets and IO#readline

include/natalie/env.hpp, spec/core/io/gets_spec.rb, spec/core/io/lineno_spec.rb, src/env.cpp, src/io_object.cpp
Another one of those Ruby features I never knew, although I'm kind of puzzled for a use case for this one (possibly for using `ruby -p`?)
As a bonus, a bit of a rename cleanup in `Env::last_line` which didn't really deserve its own commit.
=> Implement $. (last line number)

src/io_object.cpp, test/natalie/io_test.rb
This appears to not be covered in the Ruby specs, I'll try to push that to the upstream specs soon.
=> Set $_ to nil once IO#gets returns nil

lib/openssl.cpp, lib/openssl.rb, test/natalie/openssl_kdf_test.rb
The next step towards encryption: the key derivation functions. The current code works for the happy path, but it needs a lot more tests for the failure path. And there are two more KDFs, which we can implement in separate pull requests.
https://ruby.github.io/openssl/OpenSSL/KDF.html
=> Implement OpenSSL::KDF.pbkdf2_hmac

include/natalie/class_object.hpp, include/natalie/env.hpp, include/natalie/module_object.hpp, lib/natalie/compiler/instructions/define_class_instruction.rb, lib/natalie/compiler/instructions/define_module_instruction.rb, lib/natalie/compiler/pass1.rb, src/class_object.cpp, src/env.cpp, src/module_object.cpp, test/natalie/backtrace_test.rb
Given:
```ruby
module A
class B
class C < D # D is undefined, causing an exception
end
end
end
```
**Before:**
```
src/errno.rb:398:in `<main>': uninitialized constant A::B::D (NameError)
```
Funny that `src/errno.rb` was the reported file location. 😬 
**After:**
```
3: from bt.rb:1:in `<main>'
2: from bt.rb:2:in `<module:A>'
1: from bt.rb:3:in `<class:B>'
bt.rb:3:in `const_missing': uninitialized constant A::B::D (NameError)
```
=> Build exception backtrace including module/class locations

lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb, lib/natalie/compiler/rescue.rb, lib/natalie/parser.rb
This pull request is the beginning of work to have pass1 use prism nodes directly instead of going through a sexp translation layer. It purposefully does _not_ do every node, in an effort to make this easier to review, and to make it so that other contributors can do this incrementally. This pull request migrates 11 node types.
The first four are integer, rational, imaginary, and float. In the old AST these are all `:lit` nodes. In prism's AST they are all their own node types. For the parser we alias all their visit methods to `visit_passthrough` since they are all leaves in the old AST so that they get returned directly. For pass1 we implement our new `transform_` methods for each of the node types that is effectively a copy of one of the branches in `transform_lit`.
The next commit is …
=> Use prism nodes directly for pass1

include/natalie/constant.hpp, include/natalie/module_object.hpp, include/natalie/object.hpp, lib/natalie/compiler/binding_gen.rb, lib/natalie/compiler/instructions/autoload_const_instruction.rb, lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb, src/constant.cpp, src/module_object.cpp, src/object.cpp, test/natalie/autoload_test.rb, test/support/autoload/query.rb
I was debugging something earlier and it would have been nice to have `Module#autoload?` so I added it!
Unfortunately, the `autoload_spec.rb` from ruby/spec isn't going to be useful for us because our `autoload` is a macro and cannot be called like they do here:
```ruby
ModuleSpecs::Autoload.autoload :Autoload, "autoload.rb"
autoload :X, fixture(__FILE__, "autoload_x.rb")
```
...so I opted to make our own set of tests.
=> Implement Module#autoload?

lib/natalie/compiler/pass1.rb, test/natalie/argument_test.rb
I guess we were pushing the args onto the stack more than once. Whoops!
Fixes #1307
=> Fix argument forwarding ... syntax stack mixup

spec/command_line/dash_e_spec.rb, spec/core/file/setuid_spec.rb, spec/core/kernel/fixtures/classes.rb, src/kernel.rb
This is simply a proxy into chaining `Kernel.spawn` and `Process.wait` with the arguments forwarded. This means this version has the same limitations as `Kernel.spawn`, most notably it only supports arguments to the executable as separate arguments to the method, which means `system("echo foo")` fails. For this reason, the specs have not been included.
Main rationale for adding this is the nightly spec runner. Currently pretty much every spec in `core/kernel` fails because `Kernel.system` does not exist, even though these specs don't need that one. Adding this method will fix most (or maybe all) of these crashes (currently 96), so we can see how well we actually do for the Kernel module.
=> Implement Kernel.system (it's complicated)

spec/core/file/setuid_spec.rb, spec/core/kernel/spawn_spec.rb, src/kernel_module.cpp
Support the single string argument form, split that into separate arguments.
The specs will still fail, it looks like our output_to_fd capture is broken, since running this spec with MRI using our test library fails too.
=> Improve Kernel#spawn

spec/core/warning/element_reference_spec.rb, spec/language/block_spec.rb, test/natalie/argument_test.rb, test/natalie/class_test.rb
Since Ruby 3.0 is the lowest version to be supported. These changes are in sync with the upstream version of the specs.
=> Remove guards for Ruby version <= 3.0

src/io.rb
This removes the need to manually close the file descriptor, and still closes it if an exception occurs in the block.
=> Prefer block version of File.open in io.rb

spec/core/io/gets_spec.rb, test/natalie/io_test.rb
This adds the test for setting $_ to nil after the last line has been read, so this test can be removed from our natalie test suite.
=> Refresh specs for IO#gets

spec/core/io/gets_spec.rb, spec/core/kernel/open_spec.rb, src/io_object.cpp, test/natalie/io_test.rb
This fixes the following issues:
* Accept lines of more than 1024 bytes
* Accept files not ending with a newline
* Improve performance by reading chunks instead of separate bytes
My long term plan was to fix the remaining spec incompatibilities of `IO#gets`, then implement `IO#readline` and `IO#readlines` using `IO#gets`. I may have gotten sniped by #1314 for that one. I will still try to finish this method and have another look at all the duplication we have now.
=> Rework IO#gets

include/natalie/nil_object.hpp, include/natalie/symbol_object.hpp, spec/core/kernel/remove_instance_variable_spec.rb, src/kernel_module.cpp
This includes the additional changes of making `nil` and symbols frozen, which was required to make the tests pass. We were deviating from CRuby, but it does not appear in any spec for the classes themself.
=> Add frozen check in Kernel#remove_instance_variable

lib/natalie/compiler/args.rb, lib/natalie/compiler/multiple_assignment.rb, lib/natalie/compiler/pass2.rb, spec/core/io/shared/binwrite.rb, spec/core/io/shared/write.rb, spec/core/io/write_spec.rb
The current version of Natalie is unable to compile this file: `bad var name: :ë`. This pull request does include a change to accept non-ascii variable names. I have no idea how well this works with the self hosted compiler mentioned in #1315, so this commit might have to be excluded
=> Import specs for IO#write and IO.write and allow non-ascii variable names

include/natalie/fiber_object.hpp, src/fiber_object.cpp, src/kernel_module.cpp, test/natalie/fiber/scheduler_sleep_test.rb, test/natalie/fiber/shared/scheduler.rb
This will be my work in progress for the coming time. I've gotten a very primitive (and incomplete) scheduler that switches Fibers in MRI. Next up is calling the scheduler from within Natalie, and we'll have our first actual checkbox for #1184.
=> Add Fiber scheduler hooks for Kernel.sleep

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/shared/binwrite.rb, spec/core/io/write_spec.rb, src/io_object.cpp
* Add the position argument
* Forward keyword arguments to `File.new`
* Refactor `IO.binwrite`, this now uses `IO.write` which reduces some code duplication
Two issues are still left open in this change. First is our arch nemesis encodings, second is a `:perm` keyword argument that is never documented in the `IO` class.
=> Improve IO.write

src/env.cpp
There were a lot of temporary strings that could be moved.
=> Reduce string copies in Env

src/io_object.cpp
This used the old version of IoObject::write_file, which had positional arguments. Change to an Args object.
Turns out the combination of #1352 and #1348 did not work as expected.
=> Fix compilation of IoObject::copy_stream

spec/core/string/gsub_spec.rb
=> Enable "treats \\1 sequences without corresponding captures as empty strings"

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/select_spec.rb, spec/core/io/sysread_spec.rb, spec/core/io/syswrite_spec.rb, src/io_object.cpp
This makes another issue with the IO show up: the buffered IO read implemented in #1354 is not the correct implementation. Instead, it should use `fopen(3)` and friends, and work wilt a `FILE` pointer instead of a fd `int`. This is kind of hidden in the docs of IO, where `sysread` is explained as `using low level functions instead`.
This changeset still does resolve some issues, so it adds some value.
=> Add IO#syswrite

include/natalie/dir_object.hpp, lib/date.rb, spec/core/dir/chdir_spec.rb, spec/core/dir/glob_spec.rb, spec/core/dir/shared/glob.rb, spec/core/file/shared/fnmatch.rb, src/dir.rb, src/dir_object.cpp, src/file.rb, test/support/spec.rb
There are some edge cases I'm leaving unimplemented. This is good-enough for any case I've seen where `Dir[]` and `Dir.glob` were used.
=> Implement Dir.glob

Rakefile, ext/prism-generated/lib/prism/serialize.rb
We don't have Method#parameters yet.
=> Patch Prism to use Method#arity instead of Method#parameters

lib/natalie/compiler/instructions/super_instruction.rb, lib/natalie/compiler/pass1.rb, test/natalie/super_test.rb
Previously the SuperInstruction did not know about keyword arguments that may be present. As a result of this, the keyword argument hash was passed as a positional argument which led to a "wrong number of arguments" error.
=> Fix `super` with keywords

lib/openssl.cpp, test/natalie/openssl_test.rb
I'm trying to get the specs for PBKDF2 upstream (https://github.com/ruby/spec/pull/1092), and I need these constants to detect the OpenSSL version.
=> Add OPENSSL_VERSION and OPENSSL_VERSION_NUMBER constants

spec/core/io/pwrite_spec.rb, test/natalie/io_test.rb
Our local tests have been accepted upstream, so update the spec file and remove our local tests. Fix a small copy-paste oversight in the specs of IO#ungetbyte to remove the term pwrite from these tests.
=> Refresh specs of IO#pwrite

include/natalie/fiber_object.hpp, lib/natalie/compiler/binding_gen.rb, src/fiber_object.cpp, test/natalie/fiber/shared/scheduler.rb
The default hash implementation uses the inspect string as a basis for the hash. In the case of Fibers, this includes the status, which means the hash is not stable and it breaks when we use it in a hashmap object.
We probably have the same issue with IO objects, this adds `(closed)` to the inspect string if the IO handle is closed.
Closes #1338
=> Implement Fiber#hash

spec/library/openssl/kdf/scrypt_spec.rb
This one has been accepted upstream, so use the upstream version and remove our local version.
=> Import specs for OpenSSL::KDF.scrypt

lib/natalie/compiler/pass1.rb, test/natalie/assign_test.rb
The value that might be assigned to the local variable has to be duped. Otherwise, exiting the current scope of the conditional assignment would pop of any value of the stack that was there before, potentially erasing something from the stack that's important. This broke for instance the following example:
```ruby
case 1
when 1
text ||= ""
end
```
=> Fix bug in local_variable_or_write transform

lib/openssl.cpp
Which is a best practice for C++ code.
=> Replace NULL with nullptr in OpenSSL code

spec/core/matchdata/regexp_spec.rb
This is a reaction to #1419, where @timcraft  stated "The `$~` variable is already implemented", which is true. This change should make the actual issue a bit more clear
=> Improve NATFIXME description in matchdata/regexp_spec

lib/natalie/compiler/backends/cpp_backend/transform.rb, lib/natalie/compiler/instructions/if_instruction.rb, lib/natalie/compiler/pass1.rb, test/natalie/assign_test.rb
Following from the discovery in #1411, this should fix all the variable `||=` and `&&=` transforms.
=> Fix variable ||= and &&= compilation

lib/openssl.cpp, lib/openssl.rb, spec/library/openssl/hmac/digest_spec.rb, spec/library/openssl/hmac/hexdigest_spec.rb
At least: implement enough of it to pass the specs. Once again, the specs are very lacking. We'll need to write additional specs to get this to feature parity with MRI.
=> Implement OpenSSL::HMAC

include/natalie/global_env.hpp, include/natalie/global_variable_info.hpp, src/global_env.cpp, src/global_variable_info.cpp
This seems to fix the bug compiling with GCC 13.2 described in #1425.
=> Move GlobalVariableInfo class to its own files

include/natalie/object.hpp, src/hash_object.cpp, src/kernel_module.cpp, src/object.cpp
This is the same type of coercion method as to_ary or to_str. Use this to remove some code duplication.
This is some code of  #1434 split off into a separate branch.
=> Add Object::to_hash

lib/natalie/compiler/instruction_manager.rb, lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb, lib/natalie/compiler/pass2.rb, lib/natalie/parser.rb, lib/natalie/repl/main.rb, spec/language/alias_spec.rb, test/natalie/eval_test.rb, test/support/spec.rb
This fixes `eval()` so it can see local variables like this:
```ruby
four = 4
eval('four + 5') # => 9
```
As a side effect of this work, we can remove the REPL variable hack, which is nice.
=> Eval locals

include/natalie/object.hpp, lib/natalie/compiler/instructions/inline_cpp_instruction.rb, lib/openssl.cpp, lib/openssl.rb, spec/library/openssl/x509/name/parse_spec.rb, src/object.cpp, test/natalie/openssl_test.rb
I was just trying to finish up the remaining specs for OpenSSL. It turns out this test is pretty much an integration test, it needs a bunch of additional methods implemented before I can even start working on the spec itself. And the last OpenSSL spec looks even worse in terms of functionality required to even run the test.
But at least I'm learning a lot about OpenSSL this way :partying_face:
=> Implement OpenSSL::X509::Name.parse

test/natalie/fiber/shared/scheduler.rb
This reverts commit b6b8f8c1b65e20fef2791f1ea368b5151659c098.
We now have a working `next` instruction, so we can go back to my original code.
=> Revert "Remove next from scheduler"

lib/openssl.rb, spec/library/digest/sha1/digest_spec.rb
This shall henceforth be known as the start of the great unification of digest classes.
Our current implementation of the Digest classes is to simply assign the related OpenSSL digest classes to the constant. This kind of works, but there are a lot of failing specs. Sometimes that's simply because methods are named differently, but the failures in the added specs were simply because our `OpenSSL::Digest` implementation was lacking. I've tested this by replacing `Digest` with `OpenSSL::Digest` and running the test with MRI.
I'm going to try to convert the upstream specs for `Digest` and `OpenSSL::Digest` to shared specs so we can remove some duplication and improve both test suites by merging them together.
=> Implement digest singleton methods for Digest subclasses

lib/digest.rb, lib/digest/md5.rb, lib/digest/sha2.rb
With this we can run the full test suite of `spec/library/digest` without crashes. This increases the visibility on what we're still missing for the Digest classes.
=> Add missing Digest subclasses

src/encoding_object.cpp, test/natalie/string_test.rb
In [StringIO](https://github.com/natalie-lang/natalie/blob/8e490733386cd325f5d63699d1fcb8dc23c6970b/lib/stringio.rb#L206) we call `result.encode(encoding)` with a binary encoding, but the string was already encoded as binary. This fixes the bug:
```
"\x86" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to ASCII-8BIT (Encoding::UndefinedConversionError)
```
This was the fix I needed to get the self-hosted compiler to run some actual code!
```sh
→ rake bootstrap
→ bin/nat examples/boardslam.rb 3 5 1
3   - 5^0 - 1   = 1
3   - 5^0 * 1   = 2
3   + 5^0 - 1   = 3
3   + 5^0 * 1   = 4
3   + 5^0 + 1   = 5
3^0 + 5   * 1   = 6
3   + 5   - 1   = 7
3   + 5   * 1   = 8
3   + 5   + 1   = 9
3^2 + 5^0 * 1   = 10
3^2 + 5^0 + 1   = 11
5   - 1   * 3   = 12
3^2 + 5   - 1   = 13
3   * 5   - 1   = 14
3   * 5 …
```
=> Don't try to convert encoding when encoding does not change

src/io.rb
This is required to make this code work:
```
TCPSocket.open('natalie-lang.org', 80) do |socket|
socket.print("GET / HTTP/1.1\r\nHost: natalie-lang.org\r\nConnection: close\r\n\r\n")
p socket.read
end
```
This was an issue I ran into while looking at  #1441
=> Fix Socket.open with block

include/natalie/io_object.hpp, src/io_object.cpp
...and default autoclose to true.
This fixes #1452.
=> Only close IO object on destruction if autoclose is enabled

bin/natalie
I use strace pretty often to find issues with IO or other system calls. It might conflict a bit with the changes in #1455, and it probably needs another command to work with Mac OS.
=> Add '-d strace' option to run the resulting binary with strace

lib/natalie/compiler/instructions/push_string_instruction.rb, lib/natalie/compiler/instructions/send_instruction.rb
This is a dynamically sized integer. A byte is split into 7 data bits and 1 continuation bit (the rightmost bit). If the continuation bit is set, the data bits are shifted right 7 positions and the next byte is interpreted. If the continuation bit is not set, the 7 data bits are used as they are. This can be chained for as long as the continuation bit is set. This means we now have a dynamic sized data type, which resolves the discussion about whether 16, 32 or 64 bits should be used to indicate the size.
I wrote a quick program to print the strings "hello world" and a string consisting of 200 dots. This results in the following bytecode:
```
00000000: 4849 0b68 656c 6c6f 2077 6f72 6c64 3a01  HI.hello world:.
00000010: 004f 0470 7574 7301 0000 0037 4849 8148  .O.puts....7HI.H
00000020: …
```
=> [Bytecode] Convert size elements to BER encoded integers

.gitmodules, README.md, Rakefile, include/natalie/fiber_object.hpp, lib/natalie/compiler.rb, src/fiber_object.cpp
This lets us remove some bespoke x64 and aarch64 assembly in favor of a library that is battle-tested. Also, the library already had support for AddressSanitizer, so I was able to build off of that for #1455.
https://github.com/edubart/minicoro
=> Use Eduardo Bart's minicoro library for Fibers

.github/workflows/build.yml, Rakefile, bin/natalie, examples/boardslam.rb, include/natalie.hpp, include/natalie/fiber_object.hpp, include/natalie/gc/heap.hpp, include/natalie/macros.hpp, lib/natalie/compiler.rb, lib/natalie/compiler/flags.rb, src/fiber_object.cpp, src/gc.cpp, src/main.cpp, src/object.cpp, test/natalie/file_test.rb
I'm going to try to revive an oldie but a goodie: #55
By teaching our Fibers and GC to jump through some extra hoops, we are able to run our code with AddressSanitizer enabled.
There are some failing tests, memory leaks reported, etc. but this is a good start, and we can address the remaining issues as we get time.
I don't think that we'll run the entire test suite with AddressSanitizer enabled (it will be too slow), but I'm hoping to find a good representative sample of tests that we can get running.
=> Add 'asan' build mode that enables AddressSanitizer

lib/yaml.cpp, lib/yaml.rb, spec/library/yaml/dump_spec.rb, spec/library/yaml/fixtures/example_class.rb, spec/library/yaml/to_yaml_spec.rb, test/support/spec.rb
Add support for symbol, simple numeric values, booleans and arrays. The arrays work with recursion.
The method `Object#to_yaml` has been added as well, since these tests are better tests for `YAML.dump` than the regular tests for `YAML.dump`
=> Support more types in YAML.dump

lib/yaml.cpp, spec/library/yaml/dump_spec.rb, spec/library/yaml/to_yaml_spec.rb
This adds support for `nil` and Hash objects. We should now be able to dump most data structures used in YAML.
=> Add more types to YAML.dump

lib/yaml.cpp, spec/library/yaml/dump_spec.rb, test/natalie/yaml_test.rb
Which needs a `FILE*` buffer, so this serves as a reminder to myself that I really should look at # #1395.
=> Support IO argument in YAML.dump

spec/core/kernel/Integer_spec.rb, test/natalie/kernel_integer_test.rb
And remove our local test for a base argument that cannot be coerced into an integer, these have been accepted upstream (including version guards and a spec for the fix in Ruby 3.3).
=> Refresh specs for Kernel.Integer

lib/pp.rb, lib/stringio.rb, test/natalie/pp_test.rb
We don't support instance_eval with a string, but instance_variable_get works fine here.
=> Fix PP.pp with generic object

lib/set.rb, spec/library/set/pretty_print_cycle_spec.rb
It contains a tiny bit of duplication with `#to_s`, but every possible abstraction would be a disproportional amount of work, so it didn't seem worth it doing it in any other way.
=> Implement Set#pretty_print_cycle

lib/yaml.cpp, spec/library/yaml/to_yaml_spec.rb
Which was pretty much brute forcing options until the output matched. The authors of libyaml kind of forgot to write documentation for the API.
=> Support Regexp objects in YAML.dump

lib/yaml.cpp, test/support/spec.rb
Before:
```
ruby -ryaml -e 'print YAML.dump([1,2,3])'; echo ''; bin/natalie -ryaml -e 'print YAML.dump([1,2,3])'
---
- 1
- 2
- 3
---
- 1
- 2
- 3
...
```
The `...` is an optional end marker in YAML. MRI does not add this, but we currently do.
After:
```
ruby -ryaml -e 'print YAML.dump([1,2,3])'; echo ''; bin/natalie -ryaml -e 'print YAML.dump([1,2,3])'
---
- 1
- 2
- 3
---
- 1
- 2
- 3
```
=> Remove the end document marker from YAML output

src/global_env.cpp, test/natalie/alias_test.rb
The old version resulted in a segfault. MRI's behaviour is to add the target global with the default `nil` value.
=> Fix alias to new global variable

bin/natalie
This was broken for awhile, which is sad. (On the bright side, I guess we haven't needed this in a while!)
=> Fix `-d edit` debug option
