natalie-lang/natalie

include/natalie/module_object.hpp
This removes a few copy operations.
=> Use move semantics in ModuleObject::set_class_name

spec/core/array/all_spec.rb, spec/core/array/any_spec.rb, spec/core/array/none_spec.rb, spec/core/array/one_spec.rb, spec/core/array/shared/iterable_and_tolerating_size_increasing.rb, spec/core/enumerable/all_spec.rb, spec/core/enumerable/any_spec.rb, spec/core/enumerable/none_spec.rb, spec/core/enumerable/one_spec.rb, src/enumerable.rb
Which is tested in both Array and Enumerable, so this resolves a double amount of spec failures :wink:
=> Warn for unused block in Enumerable

test/bytecode/puts_string_test.rb
Compile a very simple program into bytecode, run it and compare the expected output.
For now it's not part of any automated test, so you have to run the file manually.
I'm not really satisfied with the way we now have to run natalie twice within the test: once to generate the bytecode and once to run it. This could simply be kept in an internal buffer. Once we run the VM internally, we should be able to inspect the stack instead of having to depend on printing the output. (So running `2+3` should result in the number `5` on the stack without having the need to print it).
=> Very crude test for running the bytecode VM

spec/library/yaml/to_yaml_spec.rb, test/natalie/yaml_test.rb
Our extra tests have been accepted upstream, so we can remove them from our test.
=> Refres specs for Object#to_yaml

lib/natalie/compiler/pass1.rb, test/natalie/method_visibility_test.rb
Not sure if the explicit check for `Prism::SelfNode` is good practice, but it works :sweat_smile:
=> Fix calling private method with self.<method> syntax

src/module_object.cpp, test/natalie/constant_test.rb
Previously we were directly searching the constant list of Object which missed constants defined in included modules of Object.
One example where this failed was with constants defined in the Kernel module that is included into the Object class. This produced errors with the SprintfFormatter class defined in the Kernel module when sprintf is called inside of a class.
=> Try to resolve constants in Object

bin/natalie, lib/natalie/compiler.rb, lib/natalie/compiler/backends/cpp_backend.rb, lib/natalie/compiler/instruction_manager.rb, lib/natalie/compiler/instructions/load_file_instruction.rb, lib/natalie/compiler/loaded_file.rb, lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb
Following from #1495 I want to do some additional optimizations in the compiler, but the Compiler was in bad need some some love before I do that. This moves most of the C++ related compilation into the CppBackend, where it belongs. I also clarified some options and added a new LoadedFile class to have a place to store info about loaded Ruby files.
=> Refactor compiler backend

.github/workflows/run_all_specs.yml
[The current CI runs are crashing](https://github.com/natalie-lang/natalie/actions/runs/6924196633/job/18838675024)
I'm not sure if this is related to the Ubuntu version or something else, but it is kind of suspicious that it started crashing the day we bumped the version.
=> Switch nightly spec runner back to Ubuntu 20.04

lib/yaml.cpp, spec/library/yaml/to_yaml_spec.rb
The output of the enabled test is not exactly the same as MRI.
=> Fix YAML.dump for numbers in String format

lib/yaml.rb, spec/library/yaml/shared/load.rb, spec/library/yaml/unsafe_load_spec.rb
For now, just call `YAML.load`, which already makes half of the tests pass.
=> Scaffolding for YAML.unsafe_load

lib/natalie/compiler/pass1.rb, spec/language/fixtures/freeze_magic_comment_across_files.rb, spec/language/fixtures/freeze_magic_comment_across_files_diff_enc.rb, spec/language/fixtures/freeze_magic_comment_across_files_no_comment.rb, spec/language/fixtures/freeze_magic_comment_one_literal.rb, spec/language/fixtures/freeze_magic_comment_required.rb, spec/language/fixtures/freeze_magic_comment_required_diff_enc.rb, spec/language/fixtures/freeze_magic_comment_required_no_comment.rb, spec/language/fixtures/freeze_magic_comment_two_literals.rb, spec/language/string_spec.rb
I was trying to import the `uri` and `net` gems to see what features we needed to implement in `SSLSocket` to get it to work. This is the first of (probably) many yaks to get the gems to work in the first place.
=> Some fixes for string interpolation

lib/natalie/compiler/backends/cpp_backend/transform.rb, lib/natalie/compiler/instructions/load_file_instruction.rb, lib/natalie/compiler/pass1.rb
It was a mistake passing these in via instruction creation.
=> Access required ruby files via Transform

spec/core/string/gsub_spec.rb, spec/core/string/sub_spec.rb, src/string_object.cpp
Which is required to get `ipaddr` to work, which in turn is a dependency of `uri`, so we've gotten ourselves another bald yak.
I added a bit of cleanup to the specs, a lot of them were disabled for infinite loops, but that issue has been fixed.
=> Fix \& in String#sub and similar methods

spec/core/string/gsub_spec.rb, spec/core/string/sub_spec.rb, src/string_object.cpp
The only one left is `\k`, which is a reference to a capture group, so a little trickier to match.
=> Support more backreferences in String#sub

include/natalie/thread_object.hpp, lib/natalie/compiler/binding_gen.rb, src/thread_object.cpp, test/natalie/thread_test.rb
This also fixes a bug where the GC wasn't collecting Thread objects, ever.
=> Add Thread.list

.rubocop.yml, include/natalie.hpp, include/natalie/forward.hpp, include/natalie/object.hpp, include/natalie/object_type.hpp, include/natalie/thread/mutex_object.hpp, include/natalie/thread_object.hpp, lib/natalie/compiler/binding_gen.rb, lib/socket.cpp, spec/core/mutex/lock_spec.rb, spec/core/mutex/locked_spec.rb, spec/core/mutex/unlock_spec.rb, spec/library/socket/basicsocket/recv_spec.rb, spec/library/socket/tcpserver/accept_spec.rb, src/exception.rb, src/io_object.cpp, src/kernel_module.cpp, src/natalie.cpp, src/object.cpp, src/thread/mutex_object.cpp, src/thread_object.cpp, test/support/spec.rb
This adds `#lock`, `#unlock`, and `#locked?`.
~There is one known bug where we don't unlock a mutex when a thread holding it finishes. I'm not yet sure how to do that, so I will do some research...~ Fixed!
=> Start work on Thread::Mutex

spec/core/string/rindex_spec.rb, test/natalie/string_test.rb
Most of them had to be disabled, but all our custom specs from `test/natalie/string_test.rb` are now covered by the default specs.
=> Import specs for String#rindex

spec/library/yaml/fixtures/strings.rb, spec/library/yaml/shared/load.rb
This replaces some globals with constants
Upstream fix: https://github.com/ruby/spec/pull/1118
=> Refresh YAML specs

include/natalie/fiber_object.hpp, include/natalie/thread_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/kernel/sleep_spec.rb, spec/core/thread/fixtures/classes.rb, spec/core/thread/shared/exit.rb, spec/core/thread/shared/start.rb, spec/core/thread/shared/to_s.rb, spec/core/thread/shared/wakeup.rb, spec/core/thread/wakeup_spec.rb, src/fiber_object.cpp, src/kernel_module.cpp, src/thread_object.cpp, test/natalie/fiber/scheduler_sleep_test.rb, test/natalie/fiber/shared/scheduler.rb
This makes `Kernel#sleep` work in threads along with `Thread#wakeup`. The current Fiber::Scheduler is now also set on the current active thread.
=> Thread#wakeup and sleeping thread fixes

spec/core/integer/chr_spec.rb
The specs for SHIFT_JIS no longer cause panics, so we can selectively disable them with NATFIXME blocks.
=> Update spec for Integer#chr

bin/natalie, include/natalie/string_object.hpp, lib/natalie/compiler.rb, lib/natalie/compiler/backends/cpp_backend/transform.rb, lib/natalie/compiler/instructions/push_string_instruction.rb, lib/natalie/compiler/loaded_file.rb, lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb, lib/natalie/parser.rb, lib/natalie/repl/main.rb, lib/natalie/vm.rb, spec/core/io/shared/gets_ascii.rb, spec/core/string/count_spec.rb, spec/core/string/shared/codepoints.rb, spec/core/string/unpack/u_spec.rb, spec/language/string_spec.rb, spec/library/socket/basicsocket/recv_spec.rb, test/natalie/encoding_magic_comment_test.rb, test/natalie/encoding_test.rb, test/support/encoding_magic_comment_eucjp.rb
This honors the magic comment at the top of a file like this:
```ruby
p 'foo'.encoding # => #<Encoding:ASCII-8BIT>
```
Unfortunately this PR breaks some specs that were accidentally passing before since we don't change the encoding of individual strings based on escape sequences. The next version of Prism will help us do that. 🎉  (See ruby/prism#1990)
=> Support magic comment to set encoding

spec/core/integer/chr_spec.rb
For now this is just a reminder to myself: this part of the specs has had an update, so we should integrate that as well. Since this is going to conflict with the change for ISO-8859, I'll just leave this here as a reminder.
For some reason this whole spec is disabled, even though we can run it.
=> Refresh specs for Integer#chr

test/natalie/method_test.rb, test/natalie/method_visibility_test.rb, test/natalie/proc_test.rb, test/natalie/struct_test.rb
I don't think we can add the preview to the build matrix yet, but it works* on my local system.
\* It actually means it works using 3.3.0-preview2. When trying preview3 I ran into some issues with differences in the Prism gem, because it tried to use the default gems instead of our local version. This might be something to look into.
=> Update natalie tests for compatibility with Ruby 3.3

lib/natalie/compiler.rb, lib/natalie/compiler/comptime_values.rb, lib/natalie/compiler/const_prepper.rb, lib/natalie/compiler/loaded_file.rb, lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb, lib/natalie/parser.rb, spec/language/predefined_spec.rb
We don't need to attach the file path on every Prism node any longer. In the process of doing this work I also fixed the Parser class so it raises an error if there is bad syntax, which fixed some specs.
=> Remove path on nodes

src/match_data_object.cpp, test/natalie/matchdata_test.rb
Just one more yak remaining for the uri gem, and that one is not related to matchdata.
=> Fix behaviour with range in MatchData#[] when first result is nil

lib/openssl.cpp
This seems to fix #1575, at least for me, on my Mac with OpenSSL 3.2.0.
I'll let @herwinw decide if this is the proper fix. ❤️
=> Always reset digest

src/array_object.cpp, test/natalie/array_test.rb
Memory growth was exponential because we were effectively doubling the *capacity* of the vector on each push.
Fixes #1578
=> Fix Array#* memory problem

Rakefile, test/ruby/repl_test.rb, test/ruby/ruby_specs_test.rb
These are some specs that were already passing with the self-hosted compiler, so let's add them to CI.
I'd like to get all the specs in `spec/core/*` running, but the Onigmo issue @herwinw mentioned in 7904b894c017faf7d9e63e24f360beb8fedb4822 is also an issue for some of those. I really hate the idea that I have to import the forked Onigmo files into this repo, but I will look into it further...
=> More self-hosted tests

Rakefile, ext/onigmo.patch, test/natalie/regexp_test.rb
This enables a more relaxed group name support in Onigmo by patching the `#ifdef RUBY` line to be true. I tried defining RUBY, but that breaks a bunch of other stuff and tries to include Ruby headers, which I'd like to try to avoid.
=> Allow hyphens in regexp group names

spec/core/io/close_spec.rb
Some of this test is now working as expected, but the overall test is still failing because the message is incorrect.
=> Update IO#close spec

spec/core/thread/new_spec.rb, src/thread/mutex_object.cpp
Unlock the mutex before returning the return value.
=> Fix Mutex#synchronize

include/natalie/thread_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/thread/name_spec.rb, src/thread_object.cpp
I tried using `pthread_getname_np(3)` and `pthread_setname_np(3)`, but inspection of MRI with `strace` showed they didn't use it either. This also removes the limit of 16 characters on the name.
=> Implement Thread#name and Thread#name=

src/thread/mutex_object.cpp
This is supported in MRI as well. Since we're having issues with waking up mutexes, no test has been added.
=> Support nil argument in Mutex#sleep

src/thread_object.cpp
All tests related to this code have issues with raising warnings, so these have been skipped for now.
=> Re-raise exceptions in Thread#value

src/io_object.cpp, test/natalie/socket_test.rb
If there is data in the read buffer, we should continue to consume from it rather than block with another read(2).
I found this when trying to update [the server](https://github.com/natalie-lang/natalie-lang.org/blob/master/server.rb) for natalie-lang.org.
=> Fix bug with IO#gets

src/kernel_module.cpp, test/natalie/raise_test.rb
This is one of the issues found in  #1625
=> Fix raise with an exception where the first argument of the constructor is not the message

test/natalie/natfixme_test.rb, test/support/spec.rb
My suggestion from #1633, this makes it possible to selectively disable tests for shared specs.
=> Add optional condition keyword to NATFIXME

spec/core/mutex/sleep_spec.rb
Enable passing specs, use `xit` instead of commenting out everything for specs that hit a timeout.
=> Update specs for Mutex#sleep

test/support/spec.rb
This fixes things like https://github.com/ruby/spec/blob/18b9174287940c5c7bdab3f33889fc4640582cb1/core/kernel/caller_spec.rb#L59, which now results in a crash in the nightly specs.
=> Guard rescue

include/natalie/thread_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/thread/abort_on_exception_spec.rb, src/thread_object.cpp, test/natalie/thread_test.rb
There is scarce documentation about this, but my observation is that `Thread.abort_on_exception` is not a "default" setting for new threads, but rather a sort of "global" setting. If *either* the global or the local setting is true, then the thread causes the main thread to abort when there is an unhandled exception.
...at least, that's how it appears to work.
This is in contrast to `Thread.report_on_exception` and `Thread#report_on_exception`, which seem to behave like a "default" and a "local" as I would expect. Changing `Thread.report_on_exception` affects any threads created after that, and you can override the setting with `Thread#report_on_exception`.
Weirdly inconsistent!
=> Thread abort_on_exception settings

include/natalie/thread_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/thread/inspect_spec.rb, spec/core/thread/shared/to_s.rb, spec/core/thread/to_s_spec.rb, src/thread_object.cpp
There are a couple of specs I had to disable because of another bug with `Thread#sleep` and `Thread#stop` being called after `Thread#kill`. I can handle that bug in another PR.
=> Make Thread#inspect and Thread#to_s spec-compliant

lib/natalie/compiler/instructions/create_lambda_instruction.rb, lib/natalie/compiler/pass1.rb, spec/core/proc/source_location_spec.rb
This resolves some issues with the source location specs.
Just for fun, try this script on the current master branch:
```ruby
x = -> {}
p x.source_location
```
Because we never set the environment info before creating this lambda, the last info is used, so this is shown as if it were defined in `src/warning.rb`
=> Set file/line information when creating a lambda/proc

include/natalie.hpp, include/natalie/io_object.hpp, include/natalie/thread_object.hpp, lib/socket.cpp, src/io_object.cpp, src/main.cpp, src/natalie.cpp, src/thread_object.cpp
This is v2 of my work from #1663. This fixes a few things:
- Prior to this PR, we were doing `select()`/`read()` in a tight loop in order to allow `Thread#raise` to work. This PR teaches those select() calls to watch for a special interrupt file descriptor so they can be interrupted.
- Prior to this PR, we were not handling closed file descriptors properly. On Linux, it is undefined behavior to continue select() or read() on a closed file, so we need a way to interrupt those too.
- I also found a bug with `Thread#raise` called on a dying thread -- it was accidentally raising the exception in the main thread.
This work also sets us up to fix some issues with `Thread#kill`, but I'll save that for the next PR.
=> Thread interrupt

lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb, lib/natalie/parser.rb
This should make our line numbers more accurate where we are synthesizing Prism nodes.
```ruby
tap do
tap do
tap do
require 'not_found'
end
end
end
```
Diff:
```diff
--- before.out  2024-01-07 11:40:37.091363023 -0600
+++ after.out   2024-01-07 11:40:25.667393797 -0600
@@ -1,9 +1,9 @@
7: from wat.rb:1:in `<main>'
6: from wat.rb:1:in `tap'
5: from wat.rb:2:in `block in block'
4: from wat.rb:2:in `tap'
3: from wat.rb:3:in `block in block in block'
2: from wat.rb:3:in `tap'
-        1: from wat.rb:1:in `block in block in block in block'
-wat.rb:1:in `raise': cannot load such file not_found at wat.rb#4 (LoadError)
+        1: from wat.rb:4:in `block in block in block in block'
+wat.rb:4:in `raise': cannot load such file not_found at wat.rb#4 (LoadError)
```
=> Fix some missing location info on created nodes

bin/natalie, lib/natalie/compiler/backends/cpp_backend.rb, test/setup_pkgconfig_with_homebrew.sh
I've noticed this on my mac for awhile but I just ignored it. I don't know how it worked in CI honestly, but both libyaml and zlib would not load on my mac.
This seems to fix it for me.
I added a hacky little script for Homebrew, which I'll consider if we want to pull that logic into Natalie proper. But for now, I don't love that Natalie would "know" how Homebrew works.
=> Some fixes for loading libraries on macOS

include/natalie/thread_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/thread/thread_variable_get_spec.rb, spec/core/thread/thread_variable_set_spec.rb, spec/core/thread/thread_variable_spec.rb, spec/core/thread/thread_variables_spec.rb, src/thread_object.cpp, test/natalie/thread_test.rb
And extended the specs for those a bit, I'll try to push them upstream later today.
=> Add Thread local variables

lib/natalie/compiler/binding_gen.rb
The specs have been skipped, since they crash (just like `Thread#kill`). This means the number of crashing specs in the nightly spec result will increase by 1.
=> Add alias Thread#terminate to Thread#kill

test/support/compare_rubies.rb
This fixes the `test_self_hosted` rake task which is supposed to run tests with the self-hosted compiler but wasn't honoring the env variable.
=> Use NAT_BINARY env var for 'test' directory

src/io_object.cpp
These are low level operations that operate on bytes and don't know anything about character encodings.
=> Use String#bytesize in calls to write(2)

Dockerfile, Rakefile, include/natalie/args.hpp, include/natalie/env.hpp, include/natalie/gc/heap.hpp, include/natalie/gc_module.hpp, include/natalie/global_env.hpp, include/natalie/hash_object.hpp, include/natalie/macros.hpp, include/natalie/thread_object.hpp, spec/core/thread/kill_spec.rb, spec/core/thread/report_on_exception_spec.rb, spec/core/thread/shared/exit.rb, spec/core/thread/shared/to_s.rb, src/array_object.cpp, src/class_object.cpp, src/env.cpp, src/fiber_object.cpp, src/gc.cpp, src/global_env.cpp, src/hash_object.cpp, src/io_object.cpp, src/main.cpp, src/module_object.cpp, src/natalie.cpp, src/object.cpp, src/thread/mutex_object.cpp, src/thread_object.cpp, test/natalie/thread_test.rb, test/support/compare_rubies.rb
Originally I intended to just fix `ensure` blocks in threads. From there my life spiraled and I learned more about Linux signals and processor state than I ever wanted to know. 😆 
This PR does a lot of things -- too many actually -- but the headline feature is a stop-the-world workflow for our GC so that thread state is always in a stable place when we do our conservative stack and context scan.
I found and fixed lots of edge cases around thread birth and death, too.
The secondary feature is that `Thread#raise` now works as expected, by raising an exception at the point in the stack where the thread is running.
=> Implement stop-the-world for GC

lib/socket.cpp, spec/library/socket/tcpsocket/shared/new.rb
They were disabled for a dependency on Threads, which is no longer relevant. We do need to alter a bit to the keyword argument handling to make it pass though.
=> Enable SpecTCPServer

src/gc.cpp
This should reduce the surface area of free()/delete calls that can deadlock. There might still be some more I need to track down though...
=> Sweep unreachable cells after we wake up the world

test/support/spec_helpers/fs.rb
This resolves the crash in the specs of Kernel.test
=> Support File arguments in rm_r of specs

spec/language/predefined_spec.rb
They no longer crash (thanks to #1705), so we can run them and use NATFIXME blocks to validate the behaviour.
=> Enable specs for assignment to $stdout

include/natalie/random_object.hpp, include/natalie/string_object.hpp, lib/date.rb, lib/openssl.cpp, lib/socket.cpp, spec/library/socket/shared/pack_sockaddr.rb, src/io_object.cpp, src/random_object.cpp, src/thread_object.cpp, src/time_object.cpp
This does include an addition to the constructors of `StringObject` to make it easier to pass the encoding.
=> Mark results of Socket.pack_sockaddr_* as binary strings

README.md, include/natalie.hpp, include/natalie/thread_object.hpp, src/main.cpp, src/natalie.cpp, src/thread_object.cpp
macOS was dropping some of our signals, and the mach interface is actually pretty slick, so let's use that!
This will hopefully make the GC stop-the-world flow more stable on macOS. 🤞
=> Use mach thread interface for suspending/resuming threads on macOS

lib/socket.cpp
There was a copy-paste error that used the IPv4 structure for IPv6 addresses, and an incorrect length check for UNIX sockets (the structure may contain null padding for the path, which is not included in the output of the packed socket address).
=> Fixes to Socket#sockaddr related code

lib/pathname.rb, test/natalie/pathname_test.rb
This one had no explicit specs upstream, but it is used in a number of other specs
=> Implement Pathname.pwd

spec/library/socket/unixsocket/inspect_spec.rb
This one had a dependency on UNIXSocket.socketpair, which has been implemented.
=> Import specs for UNIXSocket#inspect

lib/natalie/compiler/pass1.rb, spec/language/optional_assignments_spec.rb, test/natalie/constant_test.rb
This resolves compilation errors with code like this:
```ruby
Foo ||= 1
Foo &&= 2
```
=> Implement transform_constant_{and,or}_write_node

lib/socket.cpp
Simply return the value of the called lower methods instead of creating a new Integer object.
=> Simplify implementation of UDPSocket#bind and UDPSocket#connect

lib/socket.cpp, spec/library/socket/basicsocket/connect_address_spec.rb, test/natalie/socket_test.rb
The method still skips some information, but this resolves the "NOT YET IMPLEMENTED" panic in the specs of `BasicSocket#connect_address`.
It does include some additional fixes regarding UNIX sockets.
=> Support UNIX sockets in BasicSocket#getsockname

lib/socket.rb, spec/library/socket/addrinfo/unix_spec.rb
Replace the pack with an array. This looks to me like the more straightforward implementation (the old one packs the path into a binary string just to immediately unpack it again), and it accidentally fixes an issue in the specs.
=> Change implementation of Addrinfo.unix

spec/core/array/rassoc_spec.rb, src/array_object.cpp
This fixes a Ruby 3.3 compatibility issue
=> Update Array#rassoc to call #to_ary

spec/library/socket/basicsocket/local_address_spec.rb, spec/library/socket/shared/address.rb, spec/library/socket/socket/local_address_spec.rb, spec/library/socket/tcpsocket/local_address_spec.rb, spec/library/socket/unixsocket/local_address_spec.rb, test/support/spec.rb
We should really fix those issues with `Addrinfo#pfamily` and `Addrinfo#socktype`
=> Import specs for BasicSocket#local_address and subclasses

lib/zlib.rb, spec/library/zlib/deflate/deflate_spec.rb, spec/library/zlib/deflate_spec.rb, spec/library/zlib/inflate_spec.rb
Which is simply forwarding the call to `Zlib::Inflate.inflate` and `Zlib::Deflate.deflate`, so I would hardly call this implementing.
=> Add Zlib.inflate and Zlib.deflate

include/natalie/regexp_object.hpp, spec/core/regexp/compile_spec.rb
This is just an alias for `Regexp.new`, no extra checks are required. This fixes 9 issues in the specs, which I think is a pretty good score for removing code :D
=> Remove type assertion in Regexp.compile

lib/zlib.cpp
This is a class method, not an instance method.
The current isuse is visible in the nightly specs of `library/zlib/inflate/set_dictionary_spec.rb`:
```
undefined method `_error' for an instance of Zlib::Inflate
```
With this change, we still raise the wrong exception, but at least the first step is fixed.
=> Fix calls to _error in Zlib_do_inflate

lib/zlib.cpp, test/natalie/zlib_test.rb
The general idea for the method `<<` is to return itself, so they can be chained.
This PR includes two new tests, the test for deflate explicitly tests for the return value, the test for deflate adds an implicit test by chaining two appends. This is done because the chaining makes sense for plaintext input, but would feel very much out of place for the binary input of deflate.
=> Fix streaming interface for Zlib

lib/zlib.cpp, lib/zlib.rb, spec/library/zlib/deflate/set_dictionary_spec.rb
The similar change in `Zlib::Inflate` caused an exception, I guess I need to read the zlib docs some more to figure out how to resolve that issue. For now, it's just the deflate.
=> Implement Zlib::Deflate#set_dictionary

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/library/io-wait/wait_readable_spec.rb, spec/library/io-wait/wait_writable_spec.rb, src/io_object.cpp
For now they're pretty much similar to using `IO.select` with itself as the read or write ids.  The next step is to include the Fiber scheduler ( #1184)
=> Add IO#wait_readable and IO#wait_writable

lib/zlib.cpp, lib/zlib.rb
This results in code that is a bit easier to understand, less repetitive, and has some `#ifdef` checks for free.
=> Use __constant__ macro in zlib to define constants

include/natalie/io_object.hpp, src/io.rb, src/io_object.cpp, src/natalie.cpp
This way we can use the constants of the libs to determine the value, instead of having to redefine them in a Ruby file
=> Move IO::SEEK_* constant definition to CPP file

lib/zlib.rb, spec/library/zlib/gzipfile/close_spec.rb, spec/library/zlib/gzipfile/closed_spec.rb, spec/library/zlib/gzipfile/comment_spec.rb, spec/library/zlib/gzipfile/orig_name_spec.rb
This is a base class for `GzipReader` and `GzipWriter`, we need this as a framework to implement those.
=> Implement Zlib::GzipFile

include/natalie/io_object.hpp, lib/io/nonblock.cpp, lib/natalie/compiler/binding_gen.rb, lib/socket.cpp, spec/core/io/write_nonblock_spec.rb, spec/library/io-wait/fixtures/classes.rb, spec/library/io-wait/wait_spec.rb, src/io_object.cpp
And refactor `IO#wait_readable` and `IO#wait_writable` to use `IO#wait` to make the code more generic (which will become useful once we actually start working on the Fiber scheduler for IO). Include some minor refactors to reduce the code duplication when setting IO objects to nonblock.
=> Implement IO#wait and IO#write_nonblock

README.md, Rakefile
* README: We need at least Ruby 3.1 to support the default hash arguments.
* Rakefile: Make Ruby 3.3 the default.
=> Updates to Ruby versions

lib/stringio.rb, spec/library/stringio/inspect_spec.rb, spec/library/stringio/path_spec.rb
* Define a `VERSION`, this is required for the specs of `each` and `each_line`
* Import passing specs.
=> Small cleanups in StringIO

lib/stringio.rb, spec/library/stringio/read_nonblock_spec.rb, spec/library/stringio/shared/sysread.rb, spec/library/stringio/sysread_spec.rb, spec/library/stringio/syswrite_spec.rb, spec/library/stringio/write_nonblock_spec.rb
Specifically the `sys` and `_nonblock` versions, which are simply the same as the regular read and write when working with an internal string buffer.
=> Add some additional read/write methods to StringIO

lib/stringio.rb, spec/library/stringio/closed_spec.rb
This should fix the crash in the specs of `StringIO#readpartial`
=> Implement StringIO#closed?

lib/zlib.cpp, lib/zlib.rb, spec/library/zlib/deflate/deflate_spec.rb
It still breaks when given huge input (the same issue is probably present in `Zlib::Deflate#<<`, but not tested in the specs), and does not support blocks.
=> Implement first version Zlib::Deflate#deflate

lib/stringio.rb, spec/library/stringio/set_encoding_spec.rb, spec/library/stringio/shared/write.rb
Which is not tested in its own specs, but the specs of `StringIO#write` depend on its behaviour.
=> Fix return value of StringIO#set_encoding

lib/stringio.rb, spec/library/stringio/each_codepoint_spec.rb, spec/library/stringio/shared/codepoints.rb
By the looks of it, we have to treat the index value as a byte based instead of character based. This might affect some other methods as well, and the other specs don't do much with multibyte characters. Fixing these last two issues is going to be nasty.
=> Implement StringIO#each_codepoint

lib/stringio.rb, spec/library/stringio/putc_spec.rb, spec/library/stringio/shared/write.rb
For now it only wraps the write operations, since those are the only one with concurrency specs. The read operations should probably use this same mutex as well.
=> Add mutex to StringIO

lib/openssl.cpp, lib/openssl.rb
For now this is limited to creating a key and exporting it to PEM.
This change is good enough to get https://github.com/ruby/spec/blob/master/library/openssl/x509/store/verify_spec.rb to pass one more line.
=> Add OpenSSL::PKey::RSA

lib/openssl.cpp, lib/openssl.rb, spec/library/openssl/x509/store/verify_spec.rb, test/natalie/openssl_test.rb
And implement the `version` accessors.
At first glance it looked very easy to add the next step (accessors for `serial`) as well, but that one has a very hairy yak called `OpenSSL::BN` in its path.
=> Add OpenSSL::X509::Certificate

lib/openssl.cpp, lib/openssl.rb, spec/library/openssl/x509/store/verify_spec.rb, test/natalie/openssl_test.rb
This includes a very crude version of `OpenSSL::BN`, which only supports `int64_t` sized input (BN is a shorthand for Bignum, so the current implementation is completely missing the point), but at least we can continue with the X509 part.
=> Add accessors for serial to OpenSSL::X509::Certificate

include/natalie/env.hpp, include/natalie/kernel_module.hpp, include/natalie/throw_catch_exception.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/exception/uncaught_throw_error_spec.rb, spec/core/kernel/catch_spec.rb, spec/core/kernel/throw_spec.rb, spec/language/throw_spec.rb, src/env.cpp, src/exception.rb, src/kernel.rb, src/kernel_module.cpp, src/throw_catch_exception.cpp
For now this is a PoC in Ruby: it does pass the tests, but we probably shouldn't use an Exception object in the throw operations. I had to play around with it a bit at first, since I didn't really know how they were supposed to work.
I've seen this in use in many of the stdgems, so implementing this would simplify the process of importing those from MRI.
=> Implement throw and catch

lib/openssl.cpp, lib/openssl.rb, test/natalie/openssl_test.rb
* Add a `#to_i` method to improve the interoperability with Ruby's native numeric format (and we needed that in some tests as well)
* Support String and Bigint type in constructor (which resulted in less code)
=> Improvements to OpenSSL::BN

lib/openssl.cpp
This makes the code more a bit more terse.
I've removed the `static` modifiers from the variables as well, there was a theoretical option that a user removes the constants from OpenSSL which would result in dangling pointers.
=> Use fetch_nested_const in OpenSSL error helpers

lib/openssl.cpp
It turns out OpenSSL had a better function to query this. This removes the allocation of a BIGNUM type.
=> Simplify check for PKey class being RSA

spec/core/kernel/Complex_spec.rb, spec/core/kernel/fixtures/Complex.rb, spec/shared/kernel/complex.rb, spec/shared/rational/Rational.rb, src/kernel_module.cpp, test/natalie/complex_test.rb, test/natalie/rational_test.rb
Special shout out to the following spec:
```ruby
it "raises ArgumentError for trailing garbage" do
-> {
Complex("79+4iruby")
}.should raise_error(ArgumentError, 'invalid value for convert(): "79+4iruby"')
end
```
So, according to the specs Ruby is garbage :thinking:
=> Use upstream specs to check if Complex/Rational is frozen

test/natalie/openssl_test.rb
We're updated the Ruby version in the CI.
=> Remove exclusion for spec of SSLSocket#initialize on Darwin

examples/sslsocket.rb, lib/openssl.cpp, lib/openssl.rb, spec/library/openssl/x509/store/verify_spec.rb, test/natalie/openssl_test.rb
I never knew there were this many hoops to jump through before OpenSSL starts to check your certificates.
Certificate validation has been added to the example script. We should be ready now to start looking at  #1781 again.
=> Certificate validation in OpenSSL

spec/core/string/inspect_spec.rb, src/encoding/us_ascii_encoding_object.cpp, src/string_object.cpp
A second attempt at the original change of  #1825. This also fixes a bug in the US-ASCII encoding object, where looping through the chars of a string with high ascii values would result in an infinite loop.
=> Add encoding awareness to String#inspect

test/support/spec.rb
This should resolve an issue with invalid YAML for a lot of specs (I've used `command_line/backtrace_limit_spec.rb` as an example).
=> Do not print diffs in specs run in CI

include/natalie/module_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/module/class_variable_defined_spec.rb, spec/core/module/class_variables_spec.rb, spec/core/module/fixtures/classes.rb, spec/core/module/remove_class_variable_spec.rb, spec/fixtures/class_variables.rb, spec/language/class_spec.rb, spec/language/class_variable_spec.rb, src/module_object.cpp
* Implement `Module#class_variable_defined?`
* Implement `Module#class_variables`
* Implement `Module#remove_class_variable`
This started as an attempt to remove some NATFIXME issues in `language/class_spec.rb`, but resulted in a stack overflow of turtles.
On the positive side: this resolved the crash of `language/class_variable_spec.rb`
=> Additional class variable methods

test/support/platform_guard.rb
This guards checks for specific Ruby implementations, we probably shouldn't try to be compatible with these corner cases.
Currently, it's only used for specific load paths in MRI.
=> Add PlatformGuard.implementation?

include/natalie/string_object.hpp, src/string_object.cpp
A tiny yak I bumped into when I was trying to fix something else.
=> Make StringObject::inspect as const

lib/openssl.rb, spec/library/digest/md5/to_s_spec.rb, spec/library/digest/sha256/to_s_spec.rb, spec/library/digest/sha384/to_s_spec.rb, spec/library/digest/sha512/to_s_spec.rb
And fix the unlikely scenarion where Digest::Instance#inspect was called on an object that was not an actual digest object.
=> Implement Digest#to_s

bin/natalie
From the package info of bat on Debian Sid:
In this package the executable and its manpage have been renamed from ‘bat’ to
‘batcat’ because of a file name clash with another Debian package.
=> Add batcat as an alternative to bat

bin/natalie, src/rbconfig.rb
And use this value in the executable, instead of hardcoding the result values and using a platform check.
=> Add RbConfig::CONFIG['LIBPATHENV']

include/natalie/global_env.hpp, include/natalie/global_variable_info.hpp, include/natalie/global_variable_info/access_hooks.hpp, src/global_env.cpp, src/global_variable_info.cpp, src/global_variable_info/access_hooks.cpp, src/natalie.cpp
This implements the idea in  #1551 (or part of it, write variables are not yet implemented, and we still have to write it in C++ instead of Ruby as the tweet says).
For now, it is only implemented for `$$`, which adds the behaviour to cache the result. The following code:
```ruby
$stdout.syswrite("before first call")
$stdout.syswrite("#{$$}")
$stdout.syswrite("after first call, before second call")
$stdout.syswrite("#{$$}")
$stdout.syswrite("after second call")
```
Now results in an `strace` log like this for both MRI and Natalie:
```
write(1, "before first call", 17)       = 17
getpid()                                = 60093
write(1, "60093", 5)                    = 5
write(1, "after first call, before second "..., 36) = 36
write(1, "60093", 5)                    = 5
write(1, "after …
```
=> Add read hook to global variables

include/natalie/file_object.hpp, lib/natalie/compiler/binding_gen.rb, lib/natalie/compiler/macro_expander.rb, spec/core/file/absolute_path_spec.rb, src/file_object.cpp
The preprocessor does not care about the file extension, and will happily include the C++ file. This preserves the file and line number of the original file, which makes debugging a lot easier.
=> Convert inline CPP source to an include statement

include/natalie/global_env.hpp, include/natalie/global_variable_info.hpp, include/natalie/global_variable_info/access_hooks.hpp, spec/language/predefined_spec.rb, spec/library/English/English_spec.rb, src/global_env.cpp, src/global_variable_info.cpp, src/global_variable_info/access_hooks.cpp, src/natalie.cpp
Once again, just a framework and an implementation for a single global variable.
With these two options combined, we can do some cool stuff like storing `$~` (the last regexp match) thread-local, and set read hooks for related variables like `$'` so they get updated automatically.
=> Write hooks for global variables

spec/language/block_spec.rb, test/support/spec.rb
Which is just an alias for suppress_warning for Ruby 2.7 and up.
=> Implement suppress_keyword_warning spec helper

include/natalie/hash_object.hpp, include/natalie/module_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/hash/ruby2_keywords_hash_spec.rb, spec/core/module/ruby2_keywords_spec.rb, src/hash_object.cpp, src/module_object.cpp
It's one of those things that I would rather not have, but a surprising number of gems depend on it (I tried to import `delegate` and this was the first error).
On the positive side: it showed two issues with `Hash#dup` that have yakshaved.
=> Implement Module#ruby2_keywords

spec/core/class/initialize_spec.rb, src/class_object.cpp
This resolves the infinite loops seen in `spec/core/class/initialize_spec.rb`
=> Raise an error when calling initialize on an initialized class

lib/natalie/parser.rb
Having the `prism` gem installed locally was causing issues for me.
=> Load Prism from build directory -- never Rubygems

include/natalie/object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/kernel/fail_spec.rb, src/object.cpp
This is a requirement to fix things like https://github.com/ruby/spec/blob/89175b222f15a7929a4f9a8b11bb67c728fc8830/core/unboundmethod/equal_value_spec.rb#L121
=> Fix aliases for methods of stdlib

spec/core/conditionvariable/wait_spec.rb
This one fails occasionally, so we cannot wrap it in a NATFIXME block. It it probably the same underlying issue as the other disabled spec in this file.
=> Disable flakey test in specs of ConditionVariable#wait

lib/natalie/compiler/instructions/push_false_instruction.rb, lib/natalie/compiler/instructions/push_float_instruction.rb, lib/natalie/compiler/instructions/push_true_instruction.rb, test/bytecode/puts_bool_test.rb, test/bytecode/puts_float_test.rb
I'm not sure on how to encode integers, so that's why that type is missing.
=> Bytecode VM: Add support for pushing bools and floats

lib/natalie/compiler/instructions/push_int_instruction.rb, test/bytecode/puts_integer_test.rb
Well, this one took forever, why are integers only trivial on the surface level?
I didn't think BER encoding to be a suitable format here: it only works for positive values, so that would add a sign byte, which results in different representations of `0` and `-0`, even though it's actually the same value.
Instead, it uses Marshal encoding with a twist. The options for the first byte (interpreted as signed) of the encoded value are:
* `0`, if we encode a `0`
* `6..127`, if we encode a value in the range `1..122`, we can decode that one by subtracting `5` from the encoded value
* `1..4`, if we encode a value in the range `123..((1 << 30) - 1)`. This means we have to read this amount of extra bytes and use some shifts/ors on the binary value to retrieve the original numer
Negative values use …
=> Bytecode VM: Support push_int

bin/natalie
To turn this:
```
$ xxd hello.bin
00000000: 4849 0548 656c 6c6f 3a01 4f05 7072 696e  HI.Hello:.O.prin
00000010: 7401 3748 4907 2c20 776f 726c 643a 014f  t.7HI., world:.O
00000020: 0470 7574 7301                           .puts.
```
Into this:
```
$ bin/natalie -d p1 --bytecode hello.bin 
push_self
push_string "Hello", 5, UTF-8
push_argc 1
send :print to self
pop
push_self
push_string ", world", 7, UTF-8
push_argc 1
send :puts to self
```
In my ideal version, there should be a strict separation between the input of instructions and the output, so we should be able to compile a bytecode file to cpp too. For now, this is really going to help with development.
=> Bytecode VM: Very hacky disassembler

lib/natalie/compiler/instructions/push_arg_instruction.rb, lib/natalie/compiler/instructions/variable_set_instruction.rb
`io.read(0)` returns a character "\x00" or "\x01" for a boolean, use getbyte instead to retrieve a 0 or 1.
=> Bytecode VM: Fix boolean flags in push_and and variable_set

lib/natalie/compiler/instructions/variable_declare_instruction.rb, lib/natalie/compiler/instructions/variable_get_instruction.rb, test/bytecode/variable_declare_test.rb, test/bytecode/variable_get_test.rb
The old code resulted in the following disassembled instruction:
```
variable_get Natalie::Compiler::VariableGetInstruction
```
This fixes it to:
```
variable_get x
```
We can now run the following piece of code
```ruby
puts ['a', '0'].map { |x| x.ord }
```
This one is also included as a unit test.
=> Bytecode VM: Fix VariableGetInstruction deserialize

lib/natalie/compiler/bytecode_loader.rb, lib/natalie/compiler/instructions/push_arg_instruction.rb, lib/natalie/compiler/instructions/variable_declare_instruction.rb, lib/natalie/compiler/instructions/variable_get_instruction.rb, lib/natalie/compiler/instructions/variable_set_instruction.rb
This removes the `getbyte == 1` pattern with something more descriptive. This might prevent issues like  #1909.
=> Bytecode VM: Add getbool to the bytecode loader

lib/natalie/compiler/instructions/array_shift_instruction.rb, lib/natalie/compiler/instructions/array_shift_with_default_instruction.rb, lib/natalie/compiler/instructions/check_args_instruction.rb, lib/natalie/compiler/instructions/check_extra_keywords_instruction.rb, lib/natalie/compiler/instructions/check_required_keywords_instruction.rb, lib/natalie/compiler/instructions/define_method_instruction.rb, lib/natalie/compiler/instructions/hash_delete_instruction.rb, lib/natalie/compiler/instructions/hash_delete_with_default_instruction.rb, lib/natalie/compiler/instructions/pop_keyword_args_instruction.rb, lib/natalie/compiler/instructions/push_args_instruction.rb, lib/natalie/compiler/instructions/push_block_instruction.rb, lib/natalie/compiler/instructions/swap_instruction.rb, test/bytecode/define_method_test.rb
Well, that one took forever, since there are so many options for argument passing. And this doesn't even add support for things like `def foo(*) = bar(*)`, but that's not supported in Natalie anyway.
We can now compile and run the fib.rb example in bytecode.
=> Bytecode VM: Support method definitions

lib/zlib.cpp, lib/zlib.rb
This resolves the crash in `library/zlib/inflate/append_spec.rb` (even though most of the specs still fail)
=> Implement Zlib::ZStream#closed?

bin/natalie, lib/natalie/compiler.rb
This writes the bytecode into an internal string buffer and executes that buffer. This is mostly useful for implementing parts of the bytecode, where running a script doesn't need an intermediate step to compile and run it.
=> Bytecode VM: Add a `--run-bytecode` switch

lib/natalie/compiler.rb, lib/natalie/compiler/bytecode_loader.rb
This header consists of a magic 32 bit value (representing `NatX`), and two bytes for the version. The current version has been set to 0.0, meaning there is zero backwards compatibility guarantee and every git pull can cause your bytecode files to become invalid.
=> Include a header for Bytecode files

.rubocop.yml, lib/date.rb
So we're getting less errors before crashing with an "invalid byte sequence in UTF-8" message
=> Small fixes to Rubocop config

lib/socket.cpp
Sometimes reading the docs is worth the effort. This change removes a little over 100 lines, fixes a few bugs, removes some superfluous method calls and removes a few `NAT_NOT_YET_IMPLEMENTED` lines.
=> Various cleanups in socket.cpp related to sockaddr structs

lib/socket.cpp, lib/socket.rb, spec/library/socket/basicsocket/recv_nonblock_spec.rb
This includes a bug fix for the other nonblock methods: check the errno type before returning a `:wait_readable` symbol, there might be a different issue. The other spec files did not include a check for this situation.
=> Implement BasicSocket#recv_nonblock

lib/socket.rb
This resolves the first issue with the nightly specs of `BasicSocket#getsockopt`, which says `Socket::UDP` is not defined.
The next issue in this test will be `Socket::Cork` being not defined. This one is a bit harder to fix, since we have choose between `UDP_CORK` and `TCP_CORK`.
=> Add Socket::UDP short constant

include/natalie/integer_object.hpp, include/nathelpers/typeinfo.hpp, lib/socket.cpp, src/io_object.cpp
Add this to IoObject::read to get a user of the new code. We should probably convert most callers of IntegerObject::convert_to_nat_int_t to use this new code.
=> Implement IntegerObject::convert_to_native_type

lib/socket.cpp, spec/library/socket/shared/address.rb
Try to autodetect the family type, and remove a few hardcoded occurrences of `AF_INET`
=> Improve IPv6 support in TCP sockets

examples/evaluate.rb
Don't try to serialize the instructions manually, but use the compile_to_bytecode method. This adds the required header.
=> Bytecode VM: Fix examples/evaluate

lib/socket.cpp, lib/socket.rb, spec/library/socket/addrinfo/canonname_spec.rb, spec/library/socket/addrinfo/getaddrinfo_spec.rb
Most of the failing specs are caused by generic issues in Addrinfo (like the pfamily attribute that currently fails in a lot of specs).
=> Implement Addrinfo.getaddrinfo

include/natalie/module_object.hpp, src/module_object.cpp, src/object.cpp
Don't allocate an intermediate ArrayObject.
Fix #1874
=> Make Object::is_a faster

include/natalie/encodings.hpp, src/encoding_object.cpp
The output should be exactly EncodingCount items, reserve that space beforehand and get rid of the array resize operations.
=> Remove Array resize in Encoding::list

lib/natalie/compiler/bytecode/ro_data.rb, lib/natalie/compiler/instructions/push_string_instruction.rb, test/bytecode/rodata_test.rb
It turns out the output of Encoding.list differs between MRI and
Natalie. This means that bytecode generated with one platform is not
compatible with the other one.
=> Bytecode VM: Save encoding object in RoData section

test/support/spec.rb
Example of this being required:: https://github.com/ruby/spec/blob/master/library/socket/ancillarydata/ip_pktinfo_spec.rb#L3
According to https://github.com/ruby/mspec/blob/b8f8f4e4922b88bb5d1641e727c96f606e54669a/lib/mspec/guards/feature.rb#L25, this is an `all` filter, not an `any`.
=> Support multiple features in with_feature spec guard

lib/socket.cpp, lib/socket.rb, spec/library/socket/basicsocket/do_not_reverse_lookup_spec.rb
Copy the value when the socket is created.
=> Fix inherited value of BasicSocket#do_not_reverse_lookup

lib/socket.cpp
This code started as a copy-paste from UNIXserver_accept, but has been changed into a generic function. This means it should use a generic socket type instead of sockaddr_un.
=> Use correct sockaddr type in Server_sysaccept

include/natalie/method_object.hpp, include/natalie/proc_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/method/compose_spec.rb, src/method_object.cpp, src/proc.rb, src/proc_object.cpp
By forwarding the calls to `Proc#<<` and `Proc#>>`. These methods have been moved from Ruby to C++ to simplify this call in C++ code.
=> Implement Method#<< and Method#>>

lib/socket.rb, spec/library/socket/ipsocket/getaddress_spec.rb
Because you can never have enough options to resolve a hostname.
=> Implement IPSocket.getaddress

lib/natalie/compiler/instructions/push_last_match_instruction.rb, test/bytecode/puts_regexp_test.rb
There are some issues with using references in the interpreter mode (and thus in running the Bytecode VM). Compare:
```
bin/natalie -e '/(?<foo>bar)/ =~ "foobar"; p $~'
#<MatchData "bar" foo:"bar">
bin/natalie -i -e '/(?<foo>bar)/ =~ "foobar"; p $~'
nil
```
I expect the interpreter mode uses some regexp internally and overwrites the global
=> Bytecode VM: Support PushLastMatchInstruction

spec/core/marshal/dump_spec.rb, src/marshal.rb
This is the first half of  #1906. We still need to be able to load them back, but we need the load spec before we can do that.
=> Fix Marshal.dump with bigint argument

spec/core/io/write_spec.rb, src/io_object.cpp
Do not check whether the file is writable.
=> Fix behaviour when for IO#write with empty string

spec/core/regexp/shared/new.rb, src/regexp_object.cpp, test/support/spec.rb
This includes some fixes for the `complain` spec helper
=> Warn for second argument in Regexp.new being an unsupported type

spec/core/file/flock_spec.rb
The threads work fine, but something with signal handling fails, so we should keep this spec inactive for now.
=> Update comment for disabled spec of File#flock

include/natalie/env.hpp, include/natalie/global_env.hpp, include/natalie/global_variable_info/access_hooks.hpp, src/global_env.cpp, src/global_variable_info/access_hooks.cpp, src/module_object.cpp, src/natalie.cpp, src/regexp_object.cpp
This closes #2001.
I'm not completely sure about the `verbose_warn` function name, it might be interpreted as "make your warning extra verbose", I'm open for suggestions on a better name.
=> Streamline the verbose warn idiom

src/array_object.cpp
Only warn in verbose mode.
This is the result of  #2007, but split into a new PR since it started to become a mess.
=> Fix warning for new array with unused block

test/bytecode/call_with_to_proc_test.rb
Still leisurely working on my C++ bytecode VM, I needed an extra test to implement this pattern:
```ruby
foo.map(&:bar)
```
=> Bytecode VM: Add specs for calling methods with to_proc

lib/natalie/compiler/instructions/with_singleton_instruction.rb, test/bytecode/with_singleton_test.rb
So, I had no idea what this instruction did, so I had to look up the usage of it in `pass1.rb`, then convert that method name back to the Prism class, and look in the Prism documentation to find an example :D
=> Bytecode VM: Add with_singleton instruction

lib/openssl.cpp, lib/openssl.rb, test/natalie/openssl_test.rb
Don't use the value until `SSLContext#setup` is called. This might result in a late `TypeError`, I'm not sure why MRI behaves this way, but keeping the behaviour as close as possible makes it easier to find bugs in our implementation.
=> Make behaviour of SSLContext#verify_mode match the MRI implementation

lib/natalie/compiler/pass1.rb, test/natalie/constant_test.rb
```ruby
Foo += 1
```
This kind of code.
This started as an attempt at getting https://github.com/ruby/spec/blob/master/language/predefined_spec.rb to compile, but that resulted in a bunch of turtles on top of each other.
=> Support Prism::ConstantOperatorWriteNode

lib/natalie/compiler/args.rb, lib/natalie/compiler/pass1.rb, test/natalie/method_test.rb
This supports method definitions like this:
```ruby
def foo(*args, **nil) = args
```
Without the `**nil`, the keywords would sneakily end up in the `args` array.
Ruby uses a separate error message for this, this change uses the generic error message for extra keywords:
```
$ ruby -e 'def foo(*a, **nil) = a; foo(1, a: 1)
> '
-e:1:in `<main>': no keywords accepted (ArgumentError)
def foo(*a, **nil) = a; foo(1, a: 1)
^^^^^^^
$ bin/natalie -e 'def foo(*a, **nil) = a; foo(1, a: 1)'
1: from -e:1:in `<main>'
-e:1:in `foo': unknown keyword: :a (ArgumentError)
```
This resolves the compile error in https://github.com/ruby/spec/blob/master/core/method/parameters_spec.rb (which causes a bunch of extra errors in the specs, since we have not implemented that method)
=> Support Prism::NoKeywordsParameterNode

lib/natalie/compiler/pass1.rb, spec/language/optional_assignments_spec.rb
```ruby
a.foo ||= b
```
This should evaluate `a` only once.
This is just the beginning, there are a lot of calls similar to this. https://kddnewton.com/2023/12/06/advent-of-prism-part-6 and https://kddnewton.com/2023/12/16/advent-of-prism-part-16 describe most (or maybe all) of them.
=> Fixes to handling CallOrWriteNode

lib/ffi.cpp
env->raise supports string formatting, there is no need to fall back to snprintf with a fixed size buffer.
=> Simplify error message creation in ffi

src/io.rb
All tests were passing because we still got the desired result, but it was reading to the end of the IO object in one go instead of a little-at-a-time.
=> Fix wrong operator used for buffer size check

lib/natalie/compiler/const_prepper.rb, lib/natalie/compiler/pass1.rb
This version got released somewhere during the development cycle of  #2018. The most relevant change for us:
> All fields named `operator` have been renamed to `binary_operator` for `*OperatorWriteNode` nodes. This is to make it easier to provide C++ support. In the Ruby API, the old fields are aliased to the new fields with a deprecation warning.
Since I want to tackle these missing operators to fix some of the current compilation issues, it would be nice to fix that compatibility issue. Everything else seems to work just fine with this upgrade.
=> Upgrade to Prism 0.29

lib/natalie/compiler/pass1.rb, spec/language/assignments_spec.rb, spec/language/optional_assignments_spec.rb, test/natalie/constant_test.rb
This supports code like this:
```ruby
Foo::Bar += 1
```
TODO:
This resolves he compile issues with https://github.com/ruby/spec/blob/master/language/assignments_spec.rb
=> Support ConstantPathOperatorWriteNode

lib/natalie/compiler/pass1.rb, test/natalie/constant_test.rb
My old implementation was very much based on https://kddnewton.com/2023/12/06/advent-of-prism-part-6#constantorwritenode, which only checks if the constant is defined. Turns out we have to check the value for being falsey too.
This was not caught in the rubyspecs, it might not be tested in the specs, but I wouldn't be surprised if the specs that tried to test it fail with a compilation error in Natalie. The `nil` does get tested in the specs for `ConstantPathOrWriteNode`, which we don't support yet.
=> Fixes to handling of ConstantOrWriteNode

lib/natalie/compiler/pass1.rb
The old code worked like this:
```ruby
if !defined?(CONST) || !CONST
CONST = value
else
CONST
end
```
With a bit of DeMorgan and flipping the bodies, we can rewrite this as:
```ruby
if defined?(CONST) && CONST
CONST
else
CONST = value
end
```
This removes two operations from the resulting code.
=> Refactor handling of ConstantOrWriteNode

lib/natalie/compiler/instructions/const_set_instruction.rb
This removes the differences in internal formatting with ConstFindInstruction, and can now use a shared symbol in the generated C++ code.
=> Use Symbol as internal data type in ConstSetInstruction

lib/natalie/compiler/pass1.rb, spec/language/optional_assignments_spec.rb
This means code like this:
```ruby
Foo::Bar ||= 1
```
=> Support Prism::ConstantPathOrWriteNode

lib/natalie/compiler/pass1.rb, spec/language/regexp/character_classes_spec.rb, spec/language/regexp/grouping_spec.rb, spec/language/regexp/modifiers_spec.rb, spec/language/regexp_spec.rb
This is one of those "do we really want this change" cases.
An invalid Regexp literal currently results in either a AOT compile error, or nothing at all in case the Regexp is not used. This changes that behaviour: an invalid Regexp literal will now generate an hardcoded exception in the output.
This fixes the compile issue with 4 language specs. Even though I kind of like the compile time error we're currently raising, I also like the fact that we're able to run more specs.
=> Raise SyntaxError for invalid regexp

include/natalie/regexp_object.hpp, spec/language/regexp/interpolation_spec.rb, src/regexp_object.cpp, test/natalie/regexp_test.rb
This rabbit hole brought to you by the CI failure here: https://github.com/natalie-lang/natalie/actions/runs/9327001578/job/25676301847
```
Regexps with interpolation
allows escape sequences in interpolated regexps
Issue has been fixed, please remove or update the NATFIXME marker
(spec/language/regexp/interpolation_spec.rb:56:in `block in block in block')
```
The NATFIXME is correct for `bin/natalie` but wrong for the self-hosted `bin/nat`. Does that mean the self-hosted compiler is doing something right?? No! Well, yes, but only by mistake.
Because we pass all Regexps through the hosting Ruby's Regexp constructor [here](https://github.com/natalie-lang/natalie/blob/1760beedea456836896eb64bc5ae3dd942a95045/lib/natalie/compiler/pass1.rb#L1939), the hosting Ruby is responsible for updating …
=> Apply FIXEDENCODING flag to Regexp with `\x` escapes

spec/language/regexp/back-references_spec.rb
I don't have it in me right now to track down more macos threading bugs, so I'm going to disable this test on macos for now.
=> Skip flaky thread + backref test on macos

lib/natalie/compiler/pass1.rb, spec/language/safe_navigator_spec.rb
This means support for code like:
```ruby
foo = nil
foo&.bar += 1
foo&.bar ||= 1
foo&.bar &&= 1
```
This fixes the remaining issues in `spec/language/safe_navigator_spec.rb`
=> Support safe navigation for special write operations

spec/language/string_spec.rb
We can freeze string literals, but they are not interned/deduplicated yet.
=> Reword some NATFIXME comments in string spec

lib/natalie/compiler/pass1.rb, spec/core/kernel/at_exit_spec.rb, spec/language/END_spec.rb, spec/shared/kernel/at_exit.rb
Well, kind of, it converts them to `at_exit` calls, which is mostly correct (and our implementation of `at_exit` is not completely spec compliant either). It's good enough for most regular cases.
=> Implement END

include/natalie/encoding_object.hpp, include/natalie/string_object.hpp, spec/core/string/capitalize_spec.rb, spec/core/string/upcase_spec.rb, src/encoding_object.cpp, src/string_object.cpp
#217
Turns out this wasn't quite as hard as I thought. The section from SpecialCasing.txt has several lines, but only a couple of them are implemented in CRuby, and I was able to code that with a couple if statements.
=> Add :turkic support for case mapping methods

lib/natalie/compiler/pass1.rb, spec/language/fixtures/rescue.rb, spec/language/fixtures/rescue/top_level.rb, spec/language/fixtures/rescue_captures.rb, spec/language/rescue_spec.rb
This resolves the compilation error in https://github.com/ruby/spec/blob/master/language/rescue_spec.rb
Known bug: we ignore the safe navigation flag, so the following code will fail:
```ruby
rescue => nil&.foo
```
There are no upstream specs for this behaviour, and I'll have to find out what it actually does, so I kept that as a future work.
=> Support some extra targets for rescue statements

spec/language/break_spec.rb
Wrap the commented code in a `xit` block, to make it show up in the skipped tests.
=> Update spec in language/break that causes a compile error

spec/core/string/casecmp_spec.rb, src/string_object.cpp
=> Make String#casecmp and casecmp? spec-compliant

lib/natalie/compiler/macro_expander.rb, spec/language/numbered_parameters_spec.rb, spec/language/regexp/back-references_spec.rb, test/natalie/eval_test.rb
This fixes #2075
Fun fact: the file where I encountered this issue has just been rewritten to get rid of the eval statements. (https://github.com/ruby/spec/pull/1155)
=> Convert heredocs in eval statements to static string where possible

spec/core/string/rstrip_spec.rb, src/string_object.cpp
This changes the behavior of String#rstrip{!} to raise an Encoding::CompatibilityError if it has invalid codepoints.
This also refreshes the spec of String#rstrip to include the new MRI behavior.
=> Fix String#rstrip with invalid encodings

Gemfile, Gemfile.lock, Rakefile, test/all.rb
I don't recall why I added this back in 753aac9b832a11811f78b8ea06f2076336b69755, and AFAICT we don't use it for anything.
(All our tests run in parallel thanks to [Minitest::Test.parallelize_me](https://docs.seattlerb.org/minitest/Minitest/Test.html#method-c-parallelize_me-21).)
=> Remove minitest-parallel_fork

.github/workflows/build.yml, .rubocop.yml, Gemfile, Rakefile, bin/natalie, spec/support/cpp_output_all_specs.rb
I thought we might be able to reduce our load on GitHub CI if we do less. Generating CPP from our compiler is relatively fast, so let's compare the output between different **Host** Ruby versions. If they are all the same, then presumably the resulting binaries from GCC and Clang should be the same.
That lets us only do a full build once for Ruby 3.3 on GCC and once on Clang.
This probably won't speed up CI, but it might allow us to run more jobs from more PRs without getting rate limited as much. :crossed_fingers:
=> Do less (smartly) with CI

spec/core/string/delete_spec.rb, src/string_object.cpp
=> Make String#delete spec-compliant

lib/natalie/compiler/pass1.rb
A message saying the specific feature is not yet supported is much more helpful than a message about a method not found on NilObject.
Actually implementing these features is probably part of  #2056 (or should at least wait until that case is completed).
=> Raise more descriptive error messages for anonymous forwarding

include/natalie/kernel_module.hpp, include/natalie/match_data_object.hpp, include/natalie/object.hpp, include/natalie/value.hpp, lib/natalie/compiler/instructions/dup_object_instruction.rb, lib/openssl.cpp, spec/core/string/dup_spec.rb, src/args.cpp, src/dir_object.cpp, src/encoding_object.cpp, src/hash_object.cpp, src/kernel_module.cpp, src/method.cpp, src/natalie.cpp, src/object.cpp, src/string_object.cpp, src/value.cpp, test/ruby/ruby_specs_test.rb
#217
I had to go down a rabbit trail on this one to figure out how `Kernel#dup` works along with `initialize_dup` and `initialize_copy`. This blog post was helpful: https://jonleighton.name/2011/initialize_clone-initialize_dup-and-initialize_copy-in-ruby/
=> Make String#dup spec-compliant

lib/natalie/compiler/pass1.rb
This is the preparation step for a for loop that declares the local variables being used. This one can simply ignore every node that does not result in a new local variable.
According to the Prism docs, a LocalVariableWriteNode is not possible.
Other target nodes (e.g. ClassVariableTargetNode) still don't work, but these failures are caused by code that is run after this code.
=> Simplify transform_for_declare_args

include/natalie/encoding/utf8_encoding_object.hpp, include/natalie/encoding_object.hpp, include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/each_grapheme_cluster_spec.rb, src/encoding/utf8_encoding_object.cpp, src/string_object.cpp
This is the bare minimum to get the spec passing.
#217
=> Implement String#each_grapheme_cluster

include/natalie/string_object.hpp, spec/core/string/shared/each_line.rb, src/string_object.cpp
=> Make String#each_line spec-compliant

include/natalie/string_object.hpp, spec/core/string/index_spec.rb, spec/core/string/match_spec.rb, spec/shared/string/end_with.rb, src/regexp_object.cpp, src/string_object.cpp
#217 
This gets most of the specs passing, except a couple encoding ones.
=> Make String#index mostly spec-compliant

lib/natalie/compiler/pass1.rb, test/natalie/pattern_matching_test.rb
This supports the following syntax:
```ruby
expression => variable
```
Which is pretty much just an assignment written the other way around.
This is the first step in a very long process to add pattern matching to Natalie
=> First step to support pattern matching

lib/natalie/compiler/pass1.rb, lib/natalie/compiler/transformers/match_required_node.rb, test/natalie/pattern_matching_test.rb
This will make it easier to rewrite this code, especially since we might be rewriting this code into something that works on a different level.
This is in preparation of the plans to generate Ruby code. Since that code will work at a totally different level than the instructions generated in Pass1, it will be cleaner to split that up. This would make it easier to add tests for the transformer as well.
=> Extract transform_match_required_node into its own class

lib/natalie/compiler/pass1.rb, lib/natalie/compiler/transformers/match_required_node.rb, test/natalie/pattern_matching_test.rb
Rewrite the `expr => var` statement into Ruby, 
The current construction with the lambda looks like overkill for something that could be written with just an assignment, but will (probably) be useful in the next steps.
=> Pattern match refactor

include/natalie/encoding/utf8_encoding_object.hpp, include/natalie/encoding_object.hpp, include/natalie/env.hpp, include/natalie/string_object.hpp, spec/core/string/encode_spec.rb, spec/core/string/shared/encode.rb, src/encoding/utf8_encoding_object.cpp, src/encoding_object.cpp, src/env.cpp, src/string_object.cpp, test/natalie/string_test.rb
What a yak shave. 😅 Adding `EncodingObject::next_codepoint()` is a big win though.
#217
=> Add :invalid and :replace options to String#encode

include/natalie/encoding_object.hpp
This is not required in C++
A small cleanup for  #2131. We have a few other occurrences of `typedef struct`, but those are all in `extern "C"` sections, I left those the way they are.
=> Remove typedef from struct EncodeOptions

include/natalie/encoding_object.hpp, include/natalie/string_object.hpp, spec/core/string/encode_spec.rb, spec/core/string/shared/encode.rb, src/encoding_object.cpp, src/string_object.cpp
=> Add :fallback and :undef options to String#encode

lib/natalie/compiler/pass1.rb, lib/natalie/compiler/transformers/match_required_node.rb, spec/language/pattern_matching/3.1.rb, spec/language/pattern_matching_spec.rb, test/natalie/pattern_matching_test.rb
Or rather: a very limited form. Only `LocalVariableTargetNodes` are supported, and the target should have a fixed size, so no rest node. This supports code like:
```ruby
[1, 2, 3] => a, b, c
```
This is good enough to get all upstream specs for `Prism::MatchRequiredNode` passing, but that might just be caused by the lack of specs for this part of the language (everything is implicitly tested in the case/in-specs.
=> Support array target in pattern matching

lib/natalie/compiler/args.rb, lib/natalie/compiler/pass1.rb, spec/language/for_spec.rb
This includes the pending spec changes in https://github.com/ruby/spec/pull/1163. I will refresh them if upstream requires any additional changes.
=> Support global variable target in for loop

lib/natalie/compiler/pass1.rb, lib/natalie/compiler/transformers/match_required_node.rb, test/natalie/pattern_matching_test.rb
```ruby
a = 1
a => b
```
This code failed due to the lack of locals information in the code generator. After this bug fix, a few code cleanups/refactors have been done to separate the Ruby code generation from the instruction generation.
=> Allow local variables of LHS in MatchRequiredNode

spec/core/string/shared/encode.rb, src/encoding_object.cpp
New specs here were upstreamed in ruby/spec#1164 and ruby/spec#1165.
=> Improve String#encode :fallback option

lib/natalie/compiler/pass1.rb, lib/natalie/compiler/transformers/match_required_node.rb, test/natalie/pattern_matching_test.rb
This started out as an easy fix for an error message, but spiraled out of control
=> Scoping fixes for pattern matching

lib/natalie/compiler/args.rb, lib/natalie/compiler/pass1.rb, spec/language/for_spec.rb
The following code is now supported:
```ruby
for foo.bar in [1,2,3]
for nil&.bar in [1,2,3]
for foo[1] in [1,2,3]
for foo[:bar] in [1,2,3]
```
Observation: the `ruby_bug` guard appears to mean we don't run the tests, I had to remove that line from the spec file to run the tests. I think we're interpreting this guard in the wrong way.
=> Additional targets in for loop

include/natalie/encoding/ibm437_encoding_object.hpp, include/natalie/object.hpp, spec/core/string/encode_spec.rb, spec/core/string/shared/encode.rb, src/encoding/ibm437_encoding_object.cpp, src/object.cpp, src/string_object.cpp
=> Honor source encoding argument in String#encode

src/encoding/utf16be_encoding_object.cpp, src/encoding/utf16le_encoding_object.cpp, test/natalie/encoding_test.rb
BTW `*index--` doesn't do what you might think 😰
=> Fix prev_char logic for UTF-16 BE and LE

include/natalie/encoding_object.hpp, include/natalie/string_object.hpp, spec/core/string/shared/encode.rb, src/encoding_object.cpp, src/string_object.cpp
#217
This is the final PR for making `String#encode` and `String#encode!` spec-compliant. There are a few specs skill skipped because of missing encodings, such as `Emacs_Mule` and `ISO_2022_JP` encodings. I don't intend to work on those right now, so I'm calling this spec done for now.
=> Add :xml option to String#encode

lib/natalie/compiler/backends/cpp_backend/transform.rb, lib/natalie/compiler/instructions/push_string_instruction.rb, lib/natalie/compiler/pass1.rb, spec/core/string/freeze_spec.rb
#217
Today I learned:
```ruby
'foo'.freeze.equal?('foo'.freeze) # => true
```
Interesting to note that it only seems to apply to string literals and doesn't work if you set a variable first:
```ruby
s = 'foo'
s.freeze.equal?('foo'.freeze) # => false
```
(Good thing too, because I have no idea how we'd do that with the compiler! 😅)
=> Make String#freeze spec-compliant

include/natalie/string_object.hpp, spec/core/string/insert_spec.rb, src/string_object.cpp
=> Make String#insert spec-compliant

lib/natalie/compiler/pass1.rb, spec/language/pattern_matching_spec.rb
This is pretty much just a rescue wrapper around around MatchRequiredNode, thus inheriting all of its current limitations.
=> Support Prism::MatchPredicateNode

include/natalie/string_object.hpp, src/string_object.cpp
I'm doing some refactoring in another branch and started getting a null dereference panic somewhere in the process. Tracking it down shouldn't be too hard, but it also made me realize we could live in a world without null, where possible. This is my first experiment with that.
=> Make StringObject::m_encoding member non-null

include/natalie/env.hpp, include/natalie/object.hpp, include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/byteindex_spec.rb, spec/core/string/shared/byte_index_common.rb, src/env.cpp, src/object.cpp, src/string_object.cpp
=> Start work on String#byteindex

include/natalie/encoding/utf32le_encoding_object.hpp, include/natalie/encodings.hpp, include/natalie/regexp_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/marshal/dump_spec.rb, spec/core/marshal/shared/load.rb, spec/core/regexp/encoding_spec.rb, spec/core/regexp/shared/new.rb, spec/core/regexp/union_spec.rb, spec/language/regexp/character_classes_spec.rb, spec/language/regexp/encoding_spec.rb, src/regexp_object.cpp, src/string_object.cpp, test/natalie/regexp_test.rb
This was a side quest to get `String#byteindex(regexp)` working like I want.
=> Choose proper encoding when compiling Regexp

lib/natalie/compiler/pass1.rb, spec/language/optional_assignments_spec.rb, spec/language/send_spec.rb
This fixes the following code patterns:
```ruby
self.foo ||= bar
self.foo &&= bar
self[foo] ||= bar
self[foo] &&= bar
```
=> Fixes to optional assignments to self

lib/natalie/compiler/multiple_assignment.rb, spec/language/send_spec.rb, test/natalie/send_test.rb
This supports code like:
```ruby
self.foo, * = bar
*self.foo = bar
```
=> Handle self nodes in multiple assignment calls

include/natalie/encoding_object.hpp, include/natalie/match_data_object.hpp, include/natalie/string_object.hpp, spec/core/string/byteindex_spec.rb, spec/core/string/shared/byte_index_common.rb, src/encoding_object.cpp, src/regexp_object.cpp, src/string_object.cpp
=> Add support for Regexp argument to String#byteindex

lib/natalie/compiler/pass1.rb, spec/language/regexp/back-references_spec.rb
Short explanation: Prism uses a 32 bit unsigned int to store the index, indices larger than that are stored as 0. So the check `node.number == 0` actually means `node.number >= 2**32`
=> Handle regexp back references with an index that is too big

lib/natalie/compiler/pass1.rb, spec/language/optional_assignments_spec.rb
Which means: code like `a.foo &&= bar` should only evaluate `a` once.
=> Evaluate receiver of CallAndWriteNode only once

spec/core/builtin_constants/builtin_constants_spec.rb, src/natalie.cpp
These are all frozen in MRI, and are not supposed to be changeable.
=> Freeze RUBY_* String constants

include/natalie/regexp_object.hpp, include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/byterindex_spec.rb, src/regexp_object.cpp, src/string_object.cpp
#217
Unfortunately there are some bits of the spec that we cannot pass with our current Onigmo library. I think we will need the patches that CRuby has for Onigmo that haven't been upstreamed.
I'm hesitant to vendor all the regex code from CRuby in our repository, as keeping it up-to-date would be a real pain. If we get ambitious someday, maybe we can try to upstream some of the Ruby changes to Onigmo... If that's even possible. I don't know if it's simply that no one has had time to upstream the changes, or if CRuby has a true fork of Onigmo at this point. :grimacing: 
In any case, I think this is good enough for now.
=> Add String#byterindex

src/kernel_module.cpp, test/natalie/module_test.rb, test/support/spec.rb
There was a bug in our spec runner that was giving faulty signals when I worked on #2194. This fixes that, and fixes the methods I "fixed" on that PR.
=> Fix public_methods et al, for real this time

include/natalie.hpp, src/natalie.cpp
* Use `pid_t` instead of `int` for pid, update callers as well.
* Make `is_read` const
* Use `STDOUT_FILENO` and `STDIN_FILENO` instead of numeric values
This one has been extracted from #2200 to split up some dependencies.
=> Cleanup of popen2

spec/core/io/close_spec.rb
The message implied we raised with a different error message, but we don't raise at all. Update the description and add a message check to make sure the description matches with the error.
=> Update NATFIXME in specs of IO#close

include/natalie/random_object.hpp, include/nathelpers/typeinfo.hpp, spec/core/kernel/srand_spec.rb
Use convert_to_native_type, which generates a readable error message instead of an assertion failure. We should still support bigint, but at least we can run this spec now without crashing.
=> Don't crash on calls to srand with bigint

Gemfile.lock
This resolves some CVE, but since rexml is only a dependency for Rubocop, this should not affect us. This does silence dependabot though.
=> Bump rexml gem to 3.3.2

lib/natalie/compiler/pass1.rb
Use MoveRelInstruction instead. This removes 1 instruction in the used case, and keeps the old instructions in the unused case.
This is a sequel to  #2043, where I commented "I could not find a way to get that to work with the stack, so we would either need something like a swap2 instruction [...]". Turns out we have this instruction, it's just under a different name.
=> Don't do a second ConstFindInstruction in ConstantPathOperatorNode

include/natalie/thread_group_object.hpp, src/thread_group_object.cpp
We're updating multiple thread groups, so this mutex should be a class variable, not an instance variable. Save the lock into a variable, so we run the critical section with a lock.
=> Fix mutex usage in ThreadGroupObject::add

lib/natalie/compiler/transformers/match_required_node.rb, test/natalie/pattern_matching_test.rb
This is code like 
```ruby
a => Integer | String
```
=> Support alternations in matches

spec/core/regexp/shared/new.rb, src/regexp_object.cpp, test/natalie/regexp_test.rb
Dollar signs should be escaped/quoted:
$ irb
irb(main):001> Regexp.escape '$'
=> "\\$"
=> Fix Regexp.escape/quote not escaping dollar signs

.github/workflows/build.yml
It currently fails with this message:
Error: Refusing to uninstall /usr/local/Cellar/ruby/3.3.5
because it is required by asciidoctor, which is currently installed.
You can override this and force removal with:
brew uninstall --ignore-dependencies ruby
=> Add some motivation to the CI job on MacOS

spec/core/regexp/shared/quote.rb, test/natalie/regexp_test.rb
This includes a spec for the escape of `$`, which means we can remove our local spec for this.
This finishes the leftovers of #2222, which depended on an upstream merge in ruby/spec.
=> Refresh shared spec for Regexp.quote/Regexp.escape

spec/core/regexp/encoding_spec.rb
This has been fixed somewhere in the past (at least: that what it looks like).
=> Enable the formerly crashing spec of Regexp#encoding again

lib/set.rb, spec/library/set/merge_spec.rb
This does include the changes of https://github.com/ruby/spec/pull/1194, marking this as draft for now, the spec might need to be imported again if upstream requires changes.
=> Update Set#merge for Ruby 3.3

spec/library/date/mon_spec.rb, spec/library/date/month_spec.rb, spec/library/date/shared/month.rb
Upstream changes in https://github.com/ruby/spec/pull/1195 which adds specs for `Date#mon`
=> Refresh specs for Date#month and Date#mon

src/data.rb, test/natalie/data_test.rb
This really helps with debugging some code.
=> Implement Data#inspect and Data#to_s

spec/core/marshal/dump_spec.rb, spec/core/marshal/shared/load.rb, src/marshal.rb
We forgot to output the `/` byte to mark it as a regexp type.
=> Basic support for regexp in Marshal.dump

spec/core/marshal/fixtures/marshal_data.rb, spec/core/marshal/fixtures/marshal_multibyte_data.rb
This removes the module_eval call and should resolve the crashes in the nightly specs runner.
=> Refresh fixtures of Marshal specs

spec/core/marshal/shared/load.rb
This one no longer crashes, so we can use a regular NATFIXME block instead of disabling the full test.
=> Update a failing spec in marshal/load

lib/stringio.rb, spec/library/stringio/print_spec.rb
This method is used in a few specs too (e.g. https://github.com/ruby/spec/blob/130f029f7403484b988a374fed897f2c868ada88/library/stringio/shared/read.rb#L112)
=> Implement StringIO#print

spec/library/stringio/read_spec.rb, spec/library/stringio/shared/codepoints.rb, spec/library/stringio/shared/each.rb, spec/library/stringio/shared/each_byte.rb, spec/library/stringio/shared/each_char.rb, spec/library/stringio/shared/getc.rb, spec/library/stringio/shared/isatty.rb, spec/library/stringio/shared/read.rb, spec/library/stringio/shared/readchar.rb, spec/library/stringio/shared/write.rb, spec/library/stringio/write_nonblock_spec.rb
Prepare for the chilled strings coming in Ruby 3.4.
=> Refresh specs for StringIO

spec/core/file/chown_spec.rb, spec/core/hash/hash_spec.rb, spec/core/integer/pow_spec.rb, spec/core/integer/remainder_spec.rb, spec/core/io/dup_spec.rb, spec/core/io/read_spec.rb, spec/language/fixtures/private.rb, spec/language/fixtures/send.rb, spec/library/socket/basicsocket/send_spec.rb, spec/library/stringio/fixtures/classes.rb
Mostly whitespace, IO#read includes some frozen string literal fixes and a few new specs.
=> Refresh some specs after upstream changes

lib/natalie/compiler/instructions/define_class_instruction.rb, test/natalie/class_test.rb
```ruby
class Kernel; end
```
This code currently crashes with an assertion error, it should raise the same TypeError as MRI.
=> Reopen module as class

spec/language/delegation_spec.rb, spec/language/fixtures/delegation.rb
Alter them a lot since we do not support class_eval with string arguments. This at least shows that we're still missing one case.
=> Import specs for language/delegation

test/natalie/encoding_test.rb, test/natalie/string_test.rb, test/support/spec_helpers/tmp.rb
This removes the warnings for chilled string literals when running under Ruby 3.4.
This was missing in #2028. I tested it locally with a build of 3.4-dev of today, it works with older versions too.
=> Use explicit mutable string literals in Natalie tests

test/natalie/encoding_test.rb, test/natalie/string_test.rb
Use `dup` instead of `(+"")`, this pattern is used in the Ruby specs.
=> Update chilled strings in Natalie tests

include/natalie/block.hpp, include/natalie/env.hpp, include/natalie/global_env.hpp, include/natalie/object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/basicobject/fixtures/classes.rb, spec/core/basicobject/instance_eval_spec.rb, spec/core/basicobject/instance_exec_spec.rb, spec/core/hash/to_proc_spec.rb, spec/language/alias_spec.rb, spec/language/execution_spec.rb, src/global_env.cpp, src/hash.rb, src/module_object.cpp, src/object.cpp
I feel like the implementation to implement the scoping requirements of instance evaling code is quite brittle now, but I didn't have a better idea on how to implement this properly.
If you have any ideas about this let me know.
=> Implement BasicObject#instance_exec and improve #instance_eval

.github/workflows/build.yml
> The macOS-12 environment is deprecated, consider switching to
> macOS-13, macOS-14 (macos-latest) or macOS-15. For more details, see
> https://github.com/actions/runner-images/issues/10721
Using the old version now occasionally fails in CI, depending on what CI runner is selected.
=> Run CI on MacOS latest

README.md, include/natalie/process_module.hpp, lib/benchmark.rb, lib/natalie/compiler/binding_gen.rb, spec/core/process/times_spec.rb, src/process_module.cpp, src/struct/process.rb
This was required to get the `Benchmark` module from CRuby to work. After copying this file, the following benchmark works (the first example in the file, have not yet tried anything else):
```ruby
require 'benchmark'
puts Benchmark.measure { "a"*1_000_000_000 }
```
Also, on my machine this takes around 0.5 seconds for CRuby and 13 seconds for Natalie
=> Implement Process.times

src/kernel_module.cpp
`abort('foo')` now adds a newline, `abort("foo\n")` does not add an extra one.
This makes the behaviour consistent with MRI.
=> Add newline in Kernel.abort

src/io.rb
fsync(2) fails with EINVAL for special file descriptors like blockdevs or sockets. Skip the fsync step on these objects. Simplify the check for socket, the `respond_to?(:setsockopt)` feels like a hack.
Easiest way to trigger an exception with the old code:
File.open('/dev/urandom') {}
=> Extend checks for fsync in File.open with block

src/string_object.cpp
Create a large enough buffer from the start, prevent all the resizes/reallocs in the old code.
puts Benchmark.measure { "a"*1_000_000_000 }
On my system, this went from 7.2 seconds to 1.5 seconds (in release build). For comparison: MRI runs this in 0.4 seconds, JRuby in 0.3 seconds, TruffleRuby in 4.5 seconds.
=> Improve String#* with large multiplier

spec/core/string/shared/concat.rb, src/string_object.cpp
In case of an argument in the range 128..255, the string encoding is converted to binary.
=> Fix String#<< with US-ASCII source and numeric argument

spec/core/string/shared/concat.rb
We no longer crash, so use a NATFIXME block instead of disabling the test.
=> Update NATFIXME block in String concat specs

spec/core/array/each_spec.rb, spec/core/array/plus_spec.rb, spec/core/float/ceil_spec.rb, spec/core/float/floor_spec.rb, spec/core/integer/ceil_spec.rb, spec/core/integer/floor_spec.rb, spec/core/integer/round_spec.rb, spec/core/integer/shared/integer_ceil_precision.rb, spec/core/integer/shared/integer_floor_precision.rb, spec/core/integer/size_spec.rb, spec/core/kernel/raise_spec.rb, spec/core/kernel/sleep_spec.rb, spec/core/process/constants_spec.rb, spec/core/range/step_spec.rb, spec/core/thread/thread_variable_set_spec.rb, spec/library/pp/pp_spec.rb, spec/library/set/hash_spec.rb, spec/library/socket/socket/connect_spec.rb, spec/library/stringscanner/check_until_spec.rb, spec/library/stringscanner/exist_spec.rb, spec/library/stringscanner/scan_until_spec.rb, spec/library/stringscanner/search_full_spec.rb, spec/library/stringscanner/skip_until_spec.rb
This is not even close to complete. This script simply imported all the files that were fully passing in last nightly CI run.
=> Refresh some specs after upstream update

include/natalie/process_module.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/process/waitpid_spec.rb, src/process.rb, src/process_module.cpp
This is probably "good enough": the Ruby docs say it's an alias for Process.wait, but the return value is different.
This implementation passes the upstream specs, but that's only a single test.
=> Implement Process.waitpid

spec/core/process/warmup_spec.rb, src/process.rb
It's hardly an implementation: the behaviour is implementation specific, and right now we have nothing to warm up. This is just an easy checkbox for the nightly specs output.
=> Add Process.warmup

lib/natalie/compiler/instructions/global_variable_defined_instruction.rb, lib/natalie/compiler/instructions/instance_variable_defined_instruction.rb, lib/natalie/compiler/instructions/is_defined_instruction.rb, lib/natalie/compiler/instructions/method_defined_instruction.rb, lib/natalie/compiler/pass1.rb, spec/language/constants_spec.rb, spec/language/defined_spec.rb, spec/language/fixtures/defined.rb, src/global_env.cpp, src/global_variable_info/access_hooks.cpp
There are probably lots of cases where this still fails and that the specs don't cover. Also I noticed an interesting bug with global regexp matches which is why we will have some NATFIXMEs in the spec.
=> Make `defined?` spec compliant

spec/core/kernel/exit_spec.rb, spec/core/process/exit_spec.rb, spec/shared/process/exit.rb
One of these is crashing, this way we have documented which one is causing the issues.
=> Import specs for Kernel.exit(!) and Process.exit(!)

spec/library/socket/ipsocket/recvfrom_spec.rb
This might be a threading issue and not be related to the method itself.
=> Disable unreliable spec for IPSocket#recvfrom

include/natalie/module_object.hpp, include/natalie/object.hpp, lib/natalie/compiler/instructions/const_find_instruction.rb, lib/natalie/compiler/pass1.rb, spec/language/optional_assignments_spec.rb, src/module_object.cpp, test/natalie/defined_test.rb
This fixes `defined?` to not call `const_missing` if it was implemented, so that missing constants actually return nil. 
Additionally this fixes conditional constant write operations, because those relied on the behavior of `defined?`. 
I also upstreamed the test from `natalie/defined_test.rb` to https://github.com/ruby/spec/pull/1215
=> Fix `defined?` to not call `const_missing`

spec/core/gc/start_spec.rb
We pass the most relevant, this way we can ensure we don't accidentally remove the method or binding.
=> Import specs for GC.start

lib/optparse.rb
Previously, empty arguments would result in a nil value value, which in turn would cause a NoMethodError. This way the optionparser ignores them.
Easiest way to trigger: `bin/natalie -e '' ''`
The sequel to https://github.com/natalie-lang/natalie/pull/2311#issuecomment-2466156814. Once again: this just turns one error into the next one, so it does not fix any of the issues.
=> Don't die on empty argument in optparse

spec/language/precedence_spec.rb
=> Enable defined?() specs in precedence_spec

include/natalie/args.hpp, include/natalie/method.hpp, include/natalie/object.hpp, src/args.cpp, src/method.cpp, src/object.cpp
This otherwise copy-constructs on many calls which calls malloc and so
on and that's not good for function call performance.
Side by side of fib(25) callgrind instructions:
Before:
summary: 2554791411
After:
summary: 2167984106
Or about 15% faster.
=> Make Args const in a couple of places

include/natalie/macros.hpp
They were used in the previous coroutine code.
=> Remove NAT_ASM_PREFIX macros

lib/natalie/compiler/instructions/redo_instruction.rb
Use a dedicated temporary object instead. Changing the flags on nil can cause nil to become invalid.
=> Don't set redo flag on NilObject singleton instance

lib/natalie/compiler/args.rb, lib/natalie/compiler/arity.rb, lib/natalie/compiler/pass1.rb, test/natalie/it_test.rb
This is a new keyword that will be the first block argument in Ruby 3.4. The Ruby 3.3 behaviour is to warn for an upcoming change, but still try to call the local `it` method. This fixes compilation errors, since the AST has been updated for the upcoming behaviour.
This change does not include the warning, with Ruby 3.4 being less than 2 months away, I think we can just wait a little longer and implement the Ruby 3.4 update.
=> Support `it` keyword

spec/core/time/comparison_spec.rb, spec/core/time/shared/gmtime.rb
The specs for `Time#<=>` have some additional checks related to time zones. The shared spec for `Time#gmtime` has related updates, but since we don't yet use this shared spec these could be updated without failing tests.
=> Refresh specs in Time

src/natalie.cpp
Fixes #2323
I'm not going to pretend I understand the undefined behavior here, but I *think* running `detach_all` while we ourselves are in one of those threads is causing something to go haywire. Only running this on the main thread seems to fix a segfault when you run code like this:
```ruby
Thread.new { Process.exit! 21 }.join
sleep
```
=> Fix SystemExit segfault for non-main threads

lib/natalie/compiler/macro_expander.rb, spec/core/basicobject/instance_eval_spec.rb, spec/language/keyword_arguments_spec.rb
Marking as draft for now, the code works but I'm not that satisfied with how it looks.
Transform instance_eval with a fixed string into a block at compile time, similar to the eval macro handling.
=> Support fixed string argument with instance_eval

include/natalie/unbound_method_object.hpp, src/array_object.cpp, src/hash_object.cpp, src/symbol_object.cpp
These calls all receive a copy of an Args object, take off the first object, and pass the remaining args to the next method. Using the instance method does skip creating a new object.
The following script:
```ruby
data = {
foo: [
{
bar: [1, 2, 3]
},
],
}
p data.dig(:foo, 0, :bar, 1)
```
under callgrind went from 57,328,985 to 57,320,725 instructions. It's not much, but it's a relative small change.
=> Replace some calls to Args::shift from the static to the instance method

lib/natalie/compiler/args.rb, lib/natalie/compiler/pass1.rb, spec/language/block_spec.rb, spec/language/send_spec.rb, test/natalie/argument_test.rb
Fixes #2056.
This is related to #2201 but doesn't fix it yet.
Rather than procedurally processing the array of args left-to-right or right-to-left, let's use the information Prism gives us: `requireds`, `optionals`, `rest`, `post`, `keywords`, and `keyword_rest`.
This makes the argument compilation easier-to-understand, and as a bonus fixes a couple bugs.
=> Redo argument compilation

include/natalie/args.hpp, src/args.cpp
=> Remove unbound Args::shift function

spec/language/block_spec.rb
A lot of disabled specs could be enabled and either fail or can be caught with a NATFIXME block. Add comments to the few remaining disabled specs to show why they are disabled.
=> Cleanup specs for language/block

spec/language/method_spec.rb, test/support/spec.rb
This is a combination of a dynamic eval and some tests wrapped in an `it` block. Since we do not support dynamic evals, we have to skip those.
Adding this method removes the need to comment big chunks of the method spec, and this makes them show up as skipped tests.
=> Add evaluate method to spec runner

lib/natalie/compiler/args.rb, spec/language/block_spec.rb, test/natalie/method_test.rb
Implement the Ruby 3.4 behaviour instead of 3.3, this is easier and more future proof. The spec has a small extra check to restore the NATFIXME blocks once we've fully switched to Ruby 3.4 compatibility.
=> Fix behaviour for circular arguments

.github/workflows/build.yml
This was failing with the error:
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/pkg-config
Target /opt/homebrew/bin/pkg-config
is a symlink belonging to pkg-config@0.29.2. You can unlink it:
brew unlink pkg-config@0.29.2
=> Force install pkg-config for macOS CI

lib/natalie/compiler/pass1.rb, spec/language/block_spec.rb
This fixes the compile issues with `language/block_spec`
=> Support local block variables

Rakefile
This was split out from #2274.
`which` is not always available, but `command -v` is.
Also, the libtool available on macos might be the GNU one, so we need to check which one is actually available vs assuming based on OS.
=> A couple small build fixes

src/enumerable.rb, test/natalie/enumerable_test.rb
We can simply shortcut this with the Guass formula for summing integers. It turns out MRI does this too
Benchmarking this with `(1..1000000).sum`, this takes roughly 1.5 seconds on master (on my machine, release build), and only 0.00003 seconds with this patch. MRI is still roughly 10 times as fast.
Inspired by https://mastodon.social/@riffraff/113503953295615142, mentioned on https://newsletter.shortruby.com/p/edition-115
MRI does not have a separate `Range#sum` method, so it looks like it is shortcutted in `Enumerable#range`.
=> Optimize Enumerable#sum for integer ranges

.gitignore, Gemfile.lock, Rakefile, include/natalie/args.hpp, include/natalie/fiber_object.hpp, include/natalie/module_object.hpp, include/natalie/thread_object.hpp, lib/natalie/compiler/backends/cpp_backend.rb, lib/natalie/compiler/flags.rb, src/args.cpp, src/fiber_object.cpp, src/io_object.cpp, src/kernel_module.cpp, src/main.cpp, src/module_object.cpp, src/natalie.cpp, src/thread_object.cpp, test/natalie/libnat_test.rb
This eliminates a Vector allocation for each call site and gives the garbage collector visibility into the full stack of arguments.
This should fix #2345.
=> Store args on a per-Fiber stack

include/natalie/thread_object.hpp, src/io_object.cpp, src/thread/conditionvariable.rb, src/thread/mutex_object.cpp, src/thread_object.cpp
`Mutex#sleep` acts like an atomic `Mutex#unlock` + `Thread#sleep`.
If some other thread sneaks in the middle of that and calls `Thread#wakeup`, the wakeup can be lost because we're not quite sleeping yet. `m_wakeup` is the "condition" for our `std::condition_variable` that allows us to check if we should immediately wake up.
Fixes #2340 and #1966.
=> Fix Mutex#sleep race condition

include/natalie/bigint.hpp, src/integer.cpp, test/natalie/integer_test.rb
Bignums should never be in the NAT_MIN_FIXNUM..NAT_MAX_FIXNUM range, so we can optimize some comparisons between the different backing types.
Fixes #2344.
I'm open to adding an assertion somewhere, but I couldn't think of a nice way of doing it. We could replace all the `m_bignum =` assignments with a setter like `set_bignum()` and add an assertion there. But when I grep for `m_bignum =` they all are in the constructors, and I figure we can easily eyeball that those are all doing the right thing. Again, open to suggestions!
=> Optimize integer comparisons between fixnum and bignum

README.md, lib/random/formatter.rb, lib/securerandom.rb, src/natalie.cpp, test/natalie/random_test.rb
This is a generic module to format random numbers. More upstream specs are planned, for now we use this in some of the specs of SecureRandom.
=> Import Random::Formatter from MRI

spec/support/test_perf.rb
Still run the tests, but just print the output and don't try to upload.
This fixes the first issue of #2369
=> Don't fail in perf_test with missing envvar

lib/securerandom.cpp, spec/library/securerandom/random_number_spec.rb, src/random.rb, test/natalie/random_test.rb
Don't update the upstream specs until https://github.com/ruby/spec/pull/1222 is merged, so we got a template on how to organize this.
=> Support negative argument in (Secure)Random.random_number

test/ruby/ruby_specs_test.rb, test/support/compare_rubies.rb
I was never able to reproduce #2365 on my local machine, but I was able to get it stuck for up to a minute at a time by running lots of thread specs at the same time. But it always finished. It is conceivable that on the smaller CI runner, it could get stuck for longer and push past the default 120 second timeout.
=> Fix timeout in spec/core/thread/list_spec.rb

.github/workflows/test.yml, Dockerfile, README.md, Rakefile
We've had some folks drop in and start benchmarking Natalie. It's counterintuitive that we would build in debug mode by default, so it's easy to miss. And now that I'm not chasing GC bugs regularly, I think it's time we switch the default build mode.
Of course, when debugging, we can easily `rake clean build_debug` to get back the debug build.
NOTE: This will slow down CI since compilation takes longer. Most of our time in CI is on compilation, since each script runs very quickly. I kept CI on Linux in debug mode because 2 hours just seemed like way too long to wait for a build. The macOS tests build in release mode and take around an hour.
=> Change default build to release mode

spec/core/marshal/dump_spec.rb, spec/core/marshal/shared/load.rb, src/data.rb, src/marshal.rb, test/natalie/data_test.rb
Where Data means the new and improved Struct from Ruby 3.2
This change includes a lot of additional yak shaves, this supports loading Structs, implements `Data#==` and fixes constant lookups for nested namespaces.
=> Support Data in Marshal

spec/core/marshal/dump_spec.rb, spec/core/marshal/shared/load.rb, src/marshal.rb
Don't add an additional '@' to the name, and make an exception for the internal encoding value of Strings.
=> Fixes to Marshal.load with ivars

spec/core/marshal/dump_spec.rb, spec/core/marshal/shared/load.rb, src/marshal.rb
The only issues related to instance variables are related to non-ascii names, that is an issue outside of Marshal.
This includes some rudimentary support for Exception and Struct dumping, the basic versions work but they still have to be refined.
=> Improve support for instance variables in Marshal.dump

spec/core/marshal/dump_spec.rb, src/marshal.rb
Always convert the input string to binary before appending it to the output.
=> Fix encoding issue in Marshal.dump

lib/natalie/compiler/macro_expander.rb
It turns out there is a `copy` method on Prism nodes that removed the need to look into its internals.
=> Simplify macro_instance_eval

lib/natalie/compiler/pass1.rb
The instructions oftain contain nested arrays, so flatten them before printing.
=> Fix debug_instructions call

lib/natalie/compiler/pass1.rb
As an example, the following code:
```ruby
a = 1
b = 2
```
Would result in the following instructions on master:
```
0 variable_declare a
1 push_int 1
2 variable_set a
3 variable_declare b
4 push_int 2
5 variable_set b
```
With this change, the `variable_declare` is moved to the start of the scope
```
0 variable_declare a
1 variable_declare b
2 push_int 1
3 variable_set a
4 push_int 2
5 variable_set b
```
This has the following advantages:
* The code is more in line with how Ruby works, this works like a stack based architecture
* This is going to help with implementing `Binding#local_variables`, which is required to get a runtime `eval`
* This simplifies the code, declaring variables is now limited to a single location in the code
* This removes an ugly hack regarding `for` loops which …
=> Move VariableDeclareInstructions to beginning of block

spec/core/marshal/dump_spec.rb, src/marshal.rb
This required a bit of inline C++, since there is no public interface to set the cause of an exception.
=> Support Exception#cause in Marshal.dump and Marshal.load

src/struct.rb, test/natalie/struct_test.rb
In the following code:
```ruby
S = Struct.new(:a, :b)
S.new(1, 1)
```
we were using the same `new` method on `Struct`. This had the additional effect that creating a Struct with the same value two or more times would be rejected because it failed the check for unique attributes.
=> Fixes to constructor of Struct

lib/ffi.cpp, test/natalie/ffi_test.rb
Backstory: I discovered there was a [ffi-mysql](https://rubygems.org/gems/ffi-mysql) gem and wanted to see if this would work. Of course we're going to need a database connector in our #roadtorails (who am I kidding, I don't think we're ever going to get there). This was the first issue I ran into (actually the second issue, I had to specifically require `ffi-mysql/mysql` to work around an issue with dynamic require statements).
Of course this doesn't work, but at least it's a start.
=> Support array argument in ffi_lib

.gitmodules, Rakefile, include/minicoro/LICENSE, include/minicoro/minicoro.h, include/natalie/fiber_object.hpp, lib/natalie/compiler/backends/cpp_backend.rb, lib/natalie/compiler/flags.rb, src/fiber_object.cpp, src/integer.cpp
Maybe we're using minicoro wrong, but for whatever reason it is not calling `__sanitizer_start_switch_fiber()` and `__sanitizer_finish_switch_fiber()` in the proper way. From the header [here][1]:
Before switching to a different stack, you must call
`__sanitizer_start_switch_fiber()` with a pointer to the bottom of the
destination stack and with its size. When code starts running on the new
stack, it must call `__sanitizer_finish_switch_fiber()` to finalize
the switch. The `__sanitizer_start_switch_fiber()` function takes a
`void**` pointer argument to store the current fake stack if there is
one (it is necessary when the runtime option
`detect_stack_use_after_return` is enabled).
When restoring a stack, this `void**` pointer must be given to the
`__sanitizer_finish_switch_fiber()` …
=> Fix AddressSanitizer housekeeping for Fiber switches

spec/support/split_specs.rb, test/ruby/natalie_test.rb, test/ruby/ruby_specs_test.rb
All the `test/natalie/**/*_test.rb` tests were running in every CI group, but now they will be divided up between the groups as well.
=> Split test/natalie/**/*_test.rb files into groups too

include/natalie/crypt.h, src/crypt.c, test/asan_test.rb
The ASan interceptor for CRYPT(3) `::crypt_r` thinks we're doing something naughty, but we have our own implementation. So to keep ASan from intercepting this function, let's rename it.
=> Rename crypt_r to fix ASan false positive

include/natalie/kernel_module.hpp, include/natalie/object.hpp, lib/natalie/compiler/binding_gen.rb, src/kernel_module.cpp, src/object.cpp
The main goal is to stop casting an Object to KernelModule, which is undefined behavior. I'm trying to get UndefinedBehaviorSanitizer to be happy. :-)
=> Change how KernelModule methods are mixed into Object

spec/library/observer/fixtures/classes.rb
Guess it was not removed in 3.4 after all.
=> Refresh observer fixtures

Gemfile.lock
The old version shows a warning when used in Ruby 3.4.
=> Upgrade minitest gem

include/natalie/file_object.hpp, include/natalie/io_object.hpp, include/natalie/object.hpp, include/natalie/object_type.hpp, src/natalie.cpp, src/object.cpp
This keeps us from having to cast an IoObject to a FileObject, which is a subclass, which is undefined behavior.
=> Add actual File object type

spec/core/range/reverse_each_spec.rb, src/enumerable.rb, src/range.rb
Implementation:
```rb
def reverse_each
raise TypeError, "can't iterate from #{self.end.class}" if self.end.nil?
return super unless self.end.respond_to?(:pred)
return enum_for(:reverse_each) { size } unless block_given?
item = self.end
item = item.pred if exclude_end?
while self.begin.nil? || item >= self.begin
yield item
item = item.pred
end
self
end
```
=> Implement Range#reverse_each

test/asan_test.rb
Nothing new here:
- GC tests don't work because the GC is disabled with ASan (for now)
- getaddrinfo "leaks" internally in glibc
=> Skip some more tests that don't play nice with ASan

spec/shared/rational/exponent.rb
This moves some specs out of the non-linux block, which makes it easier to reproduce and fix the issue on Linux systems.
=> Refresh specs for Rational#**

spec/core/io/read_spec.rb, spec/language/block_spec.rb, spec/language/constants_spec.rb
These are not supposed to be fixed, so removing them from the specs reduces the amount of clutter when searching for NATFIXME issues.
I found them by rewriting the specs runner to only run the specs for old versions, and break if it encounters a NATFIXME block. Anything else, including exceptions and failed specs, is okay.
=> Remove NATFIXME blocks from Ruby 3.3 and earlier

spec/core/enumerator/each_with_index_spec.rb, spec/core/enumerator/with_index_spec.rb
In an attempt to clean things up: this is the new and improved version of the current changes of #2153, with some upstream spec fixes. I am going to close the other PR for now.
=> Refresh specs for Enumerator#(each_)with_index

Rakefile
I did all this work to make sure the ASan fake stack was tracked correctly and it wasn't even in use in this docker container. 🤦‍♂️
=> Enable ASan use-after-return check

lib/natalie/parser.rb, test/natalie/string_test.rb
The retry of #2266, but an upgrade to 1.3 instead. The deduction of the string encoding feels kind of hacky, but I have no idea how else to fix this.
=> Upgrade to Prism 1.3

lib/yaml.cpp
This removes a memory copy operation.
=> Use move semantics for String buffer in YAML.dump

include/natalie/encoding_object.hpp, include/natalie/object.hpp, include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/bytesplice_spec.rb, src/object.cpp, src/string_object.cpp
=> Implement String#bytesplice

LICENSE, README.md, examples/about.rb, src/natalie.cpp
Which raises a bunch of new questions. Most of these have just been "copyright 2023" with a single year, but the GTK example had a "copyright 2019-2022". So I guess everything should be "copyright 2019-2025" now.
=> Happy new year

include/natalie/regexp_object.hpp, lib/natalie/compiler/instructions/push_regexp_instruction.rb, lib/natalie/compiler/instructions/string_to_regexp_instruction.rb
* Refactor the code for regexp literals, to make it easier to extend encodings
* Support interpreter mode
=> Fixes to regexp /e flag

lib/ffi.cpp, test/natalie/ffi_test.rb
Turns out you don't have to write `"libm.#{SO_EXT}"`, but `"libm"` and `"m"` work just as fine.
I tried ffi-mysql again (see #2404 for context). This is enough to load the lib. Next step: `FFI::Struct`, which resembles a C struct and needs padding.
=> Allow short names as FFI libraries

test/bytecode/call_with_to_proc_test.rb, test/bytecode/define_method_test.rb, test/bytecode/global_variables_test.rb, test/bytecode/if_test.rb, test/bytecode/monkeypatch_test.rb, test/bytecode/multiple_assignment_test.rb, test/bytecode/point_test.rb, test/bytecode/puts_array_test.rb, test/bytecode/puts_bool_test.rb, test/bytecode/puts_complex_test.rb, test/bytecode/puts_const_test.rb, test/bytecode/puts_float_test.rb, test/bytecode/puts_hash_test.rb, test/bytecode/puts_integer_test.rb, test/bytecode/puts_nil_test.rb, test/bytecode/puts_rational_test.rb, test/bytecode/puts_regexp_test.rb, test/bytecode/puts_string_test.rb, test/bytecode/variable_declare_test.rb, test/bytecode/variable_get_test.rb, test/bytecode/while_test.rb, test/bytecode/with_singleton_test.rb
Compare them with the output of Natalie running the same code, this should be equal. This resolves some issues with versions.
The boardslam test is an exception, since we would use a require statement in Ruby, and our bytecode version ignores the `$0` check.
=> Update expectations in bytecode tests

include/natalie/block.hpp, include/natalie/method_object.hpp, lib/ffi.cpp, lib/natalie/compiler/instructions/define_block_instruction.rb, src/array_object.cpp, src/dir_object.cpp, src/enumerator/arithmetic_sequence_object.cpp, src/env_object.cpp, src/hash_object.cpp, src/kernel_module.cpp, src/module_object.cpp, src/proc_object.cpp, src/range_object.cpp, src/string_object.cpp, src/symbol_object.cpp
There were a few places we were doing this:
```cpp
auto block_env = new Env {};
// ...
new Block { block_env, ... }
```
Since Block makes a copy of the passed Env anyway -- it has to because the parent scope can go away -- let's take a reference here to encourage call sites not to allocate a new Env on the heap, since it would be thrown away and collected by the GC on the next collection.
=> Make fewer throwaway Envs for Blocks

lib/natalie/compiler/macro_expander.rb, spec/core/module/module_function_spec.rb, spec/core/struct/fixtures/classes.rb, spec/core/struct/inspect_spec.rb, spec/core/struct/shared/inspect.rb, spec/language/alias_spec.rb, spec/language/constants_spec.rb, spec/language/hash_spec.rb
A few new specs have been added upstream, including calls to `class_eval` and `module_eval` with static strings. Support has been added for those, similar to `instance_eval`.
=> Refresh specs for Struct#inspect (or: does a yak shave in the woods?)

include/natalie/env.hpp
These are not used anywhere in the Natalie source.
=> Remove include statements for shared_ptr

include/natalie/array_object.hpp, src/array_object.cpp
The sequel to https://github.com/seven1m/tm/pull/18
`array/plus_spec` went down from 510,627,871 to 510,521,178 operations, `array_concat_spec` from 509,942,054 to 509,827,801 (all callgrind).
=> Utilize TM::Vector::concat

lib/natalie/compiler/backends/cpp_backend/transform.rb, test/natalie/frozen_string_test.rb, test/natalie/string_test.rb
The Rake gem has the string `"(usually '~/.rake/*.rake')."`, which produces the following compilation error from gcc:
```
/tmp/natalie.cpp20250111-1712441-ptcjol:11879:184: error: "/*" within comment [-Werror=comment]
11879 |     auto send_3915 = Value(interned_strings[165]/*"Using system wide (global) rakefiles "*/).public_send(env, symbols[91]/*:+*/, Args({ Value(interned_strings[166]/*"(usually '~/.rake/*.rake')."*/) }, false), nullptr, self);
```
=> Fix compilation error with certain frozen string literals

spec/library/rbconfig/rbconfig_spec.rb, src/natalie.cpp, src/rbconfig.rb
This fixes the two failing specs in https://www.github.com/ruby/spec/tree/master/library/rbconfig/rbconfig_spec.rb
The `RUBY_DESCRIPTION` value now looks like:
```
natalie (like ruby 3.4.0) (2025-01-12 revision b81af1f11a) [x86_64-linux]
```
I based the format on both JRuby and TruffleRuby:
```
jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 21.0.6-ea+6-Debian-1 on 21.0.6-ea+6-Debian-1 +jit [x86_64-linux]
truffleruby 24.1.1, like ruby 3.2.4, Oracle GraalVM Native [x86_64-linux]
```
I liked the `like` from TruffleRuby, but I thought it would look better in parentheses, as shown by JRuby.
=> RbConfig fixup

include/natalie/hash_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/hash/new_spec.rb, src/hash_object.cpp, test/natalie/hash_test.rb
The implementation is a bit janky, since we already constructed a TM::Hashmap object on constructing a Natalie::HashObject. Providing an explicit capacity of 10 now means your hashmap gets replaced by a new item of the same size
=> Add capacity keyword argument to Hash.new

spec/core/range/step_spec.rb, src/range_object.cpp
This is the first step in getting the Range#step method to Ruby 3.4 compatibility.
=> Use #coerce instead of to_int to convert argument of Range#step

spec/core/range/step_spec.rb, src/range_object.cpp
This cascades into the next bug, but that one needs a generic fix.
=> Move check for step == 0 in Range#step to numeric path

lib/natalie/compiler/instructions/variable_get_instruction.rb, lib/natalie/compiler/instructions/variable_set_instruction.rb
This passes `rake test RUBYOPT="--enable-frozen-string-literal`, which tests the first half of the process.
=> Allow compiler to run with frozen string literals

src/time_object.cpp
This is just some low hanging fruit. All the other int allocations in this file look to be related to Rational, which will need an overhaul before we can get rid of those.
=> Remove Integer allocations in comparisons in Time

include/natalie/object.hpp, include/natalie/object_type.hpp, src/object.cpp
The old version marked garbage collected objects with Nil, which can be very confusing when trying to track down a bug.
For a bit of context: I've been working on [define_finalizer](https://ruby-doc.org/3.4.1/ObjectSpace.html#method-c-define_finalizer) and ran into a bug where one of the objects got GC'd, but that took way too long to figure out because inspecting the structure with GDB showed `Nil`.
=> Add ObjectType::Collected

include/natalie/float_object.hpp, include/natalie/integer_object.hpp, include/natalie/value.hpp, lib/ffi.cpp, lib/natalie/compiler/instructions/inline_cpp_instruction.rb, src/float_object.cpp, src/integer_object.cpp, src/math.rb, src/method.cpp, src/object.cpp, src/process_module.cpp, src/range_object.cpp, src/string_object.cpp, src/value.cpp
...for now.
I know CRuby has some way of encoding these in the VALUE pointer, but I'd like to focus on integers for now. We can revisit floats later.
=> Make floats always heap-allocated

spec/core/process/spawn_spec.rb, src/kernel_module.cpp
Don't try to split this, that would require tokenizing the input string for quotes etc, just defer this to the shell, similar to system(3). The output of strace implies MRI works like this too.
This reactivates a couple of specs that we had to disable previously due to errors with our spec runner.
=> Fix behaviour for spawning process with single string argument

src/module_object.cpp
We know exactly how long the return array is going to be. In the unlikely case that we have more than 10 arguments, this removes  a realloc/grow in our array. In the more likely case of less than 10 arguments, we don't overallocate. (As a reminder: the array class reserves 10 places in case you call it without any arguments). It would have been even better if we could just skip this return value completely if we knew the return value would not be used (which is pretty much always).
=> Fix object size for return values of attr_reader et al

spec/shared/process/fork.rb
The code itself works fine, the issue we're facing is that the file gets created, then the forked process runs the after-hook and removes the file, then the main process tries to read the file and cannot find it. Somehow this issue does not occur if we run this with MRI using our spec runner.
=> Clarify NATFIXME markers in specs of Process.fork

src/array_packer/string_handler.cpp
This had a superfluous if statement: the path for '0' and '1' gave exactly the same result as the general path, so we can just drop that check. This opened up a few opportunities to make variables const, which often results in better code generation.
The assignment with `bit_index++` was a bit weird too: this is a post increment, which means we return the old value of bit_index, we never used the updated variable, so we can just remove that increment.
=> Rework Array#pack with b/B directives

src/encoding_object.cpp
This array currently contains 105 items, and will only grow larger if we implement additional encodings. With the default array capacity of 10 and doubling it every time we exceed that, this removes 4 reallocs.
=> Precalculate size of return value of Encoding.name_list

include/natalie.hpp, include/natalie/block.hpp, include/natalie/fiber_object.hpp, include/natalie/macros.hpp, include/natalie/object.hpp, lib/ffi.cpp, lib/natalie/compiler/instructions/redo_instruction.rb, lib/natalie/compiler/instructions/yield_instruction.rb, lib/socket.cpp, src/array_object.cpp, src/block.cpp, src/bsearch.cpp, src/dir_object.cpp, src/enumerator/arithmetic_sequence_object.cpp, src/env_object.cpp, src/fiber_object.cpp, src/hash_object.cpp, src/integer_object.cpp, src/io_object.cpp, src/kernel_module.cpp, src/module_object.cpp, src/natalie.cpp, src/object.cpp, src/proc_object.cpp, src/range_object.cpp, src/regexp_object.cpp, src/string_object.cpp, src/thread/mutex_object.cpp, src/thread_object.cpp
1. We weren't using the `Break` flag for anything any more--not since we taught the compiler to add breakpoints.
2. I used a boolean on the current fiber to denote a `redo` so we can get rid of the Redo flag. As a bonus, calling `redo` no longer allocate a new object.
Now that we only have a single flag (`Frozen`), we could remove the `Object::m_flags` integer and add a boolean `m_frozen` instead, but that can be a separate PR.
=> Remove Break and Redo flags from Object

Rakefile
The number of arguments to `ls` is over the limit on my machine.
=> Use `find` for `rake watch` task

ext/tm/include/tm/string.hpp, src/string_object.cpp
This includes the addition of  a function of `TM::String` to grow the capacity manually, which may be useful in other locations as well.
=> Use the capacity keyword in String.new

src/string_object.cpp
Move the assert_not_frozen check after we did the conversion. We do not want to see the issues with chilled strings if the duplication throws an exception.
This remove a chilled string warning from the spec.
=> Rework String#capitalize! to facilitate chilled strings

src/kernel.rb
This also removes a possible mutation of the argument.
=> Support chilled strings and frozen arguments in format strings

include/natalie/encoding_object.hpp, src/encoding_object.cpp
The hash keys were a simple list of sequential integers starting at 1. The current Hashmap does not handle integer keys very well, it defaults to pointer lookup, where the return value for non pointers is a hardcoded 0. Effectively, this hashmap was a linked list.
=> Convert internal encoding list from hashmap to vector

include/natalie/encoding/ibm437_encoding_object.hpp, src/encoding/ibm437_encoding_object.cpp
This removes a lot of boilerplate code, an inefficient hashmap, and fixes the unicode support for the higher bytes.
=> Convert IBM437 encoding object to SingleByteEncodingObject

include/natalie/gc/allocator.hpp, include/natalie/gc/heap.hpp, include/natalie/macros.hpp, src/gc.cpp, test/natalie/gc_test.rb
This reduces back-to-back GC collections when we happen to allocate objects of different sizes and each of those allocators are near empty.
This work also adds a counter so we only check free percentage every 1000 allocations.
This should speed up the ConditionVariable specs.
It also speeds up the `boardslam.rb` code by a bit:
=> GC: Check free cell percentage globally instead of per-allocator

ext/tm/include/tm/hashmap.hpp, include/natalie/symbol_object.hpp, src/string_object.cpp
These were very inefficient: calculating the hash was delegated to TM::String, which means we make a new object (including a heap allocation), calculate the hash with the data we already had, and drop the temporary object again.
Since we did not use this Hashmap specialization anywhere, removing it is much more effective than fixing it.
=> Remove support for C style string in TM::Hashmap

src/regexp_object.cpp
This uses the same logic as the encoding list in EncodingObject
=> Convert regexp encoding lookup from hashmap to vector

spec/core/marshal/dump_spec.rb, src/marshal.rb
We are slightly diverting from MRI's behaviour due to #2552: instead of comparing the bigints by identity, compare them by value. This means this code:
```ruby
Marshal.dump([2**64, 2**64])
```
will create an object link in Natalie, but not in MRI. Both versions are able to read each others output, and ints are immutable objects, so there should be no interoperability issue with this change.
=> Fix object links for Integer values in Marshal.dump

spec/core/kernel/rand_spec.rb, src/kernel.rb
But not in Random.rand, because these two methods behave differently.
=> Support negative arguments in Kernel.rand

spec/core/process/ppid_spec.rb, test/natalie/process_test.rb
This does not work as regular MRI by design. The method is a call to getppid(3), which returns the parent pid. In the case of Natalie, the regular workflow will return the pid of `bin/natalie`, wich is still running and waiting for the child process to terminate so it can clean up the temporary executable. There is no way around this without getting some RPC in place to let the child process query the parent process so it can find its grandparents pid.
If we create a binary and run that directly, Process.ppid does work as intended.
=> Add specs for Process.ppid

lib/tmpdir.cpp, lib/tmpdir.rb, spec/core/kernel/system_spec.rb, spec/library/tmpdir/dir/mktmpdir_spec.rb, src/kernel.rb
This is a very crude first version that does not support arguments or blocks.
A few specs are failing due to how our spec runner works, the `stub!` methods removes them for the duration of the file or the describe block, not the test itself (this can be reproduced by running this spec file in MRI). We should probably fix that before we continue with this lib.
The specs for Kernel.system have been added too, these had a dependency on `mktmpdir` and no longer crash.
=> Implement first version of Dir.mktmpdir

spec/core/thread/value_spec.rb
Comment out a single line that causes a timeout, and add some comments to describe the issue.
The source of the issue is the implementation of Thread#status, and is unrelated to this specific test.
Importing this spec dos document the reason for the timeout.
=> Import specs for Thread#value

spec/security/cve_2013_4164_spec.rb
This is one of the specs with a timeout. Import it to document which one of the two fails.
=> Import specs for CVE-2013-4164

include/natalie/kernel_module.hpp, spec/core/kernel/Complex_spec.rb, src/kernel_module.cpp, test/natalie/kernel_complex_test.rb
This one is now feature complete with `String#to_c`, which is helpful with all the shared specs that should behave the same.
This contains a lot of code duplication, the next step is probably to add an extra argument to specify the failure behaviour (raise an exception or return the parsed part) and delegate `String#to_c` to `Kernel.Complex`.
=> Implement parser for Kernel.Complex with String argument

src/kernel_module.cpp, test/natalie/kernel_complex_test.rb, test/natalie/kernel_integer_test.rb, test/natalie/kernel_test.rb
It turns out this only allows true and false, not truthy/falsey. This should probably be added to the upstream specs.
=> Fix exception argument in kernel coercion methods

Rakefile, ext/tm/include/tm/string.hpp, include/natalie/constants.hpp, include/natalie/integer.hpp, include/natalie/integer_methods.hpp, include/natalie/value.hpp, spec/core/random/bytes_spec.rb, spec/library/securerandom/random_number_spec.rb, src/array_object.cpp, src/array_packer/integer_handler.cpp, src/integer.cpp, src/integer_methods.cpp, test/natalie/array_test.rb, test/support/spec.rb
This is to match how MRI stores integers, thought it's only in the `Integer` class for now. In a future PR, I'll see if we can make `Value` a tagged pointer as well.
Integers that can be represented in 63 bits are encoded directly in the 64-bit pointer. Larger ints are created as BigInt and the pointer stored.
This took some adjustments to various bits of code that assumed all bigints could not be represented in a 64-bit int type. (Some bigints can fit in a `nat_int_t`.)
=> Use tagged pointer for storing Integer value

spec/core/fiber/resume_spec.rb, src/fiber_object.cpp
The underlying issue is that we only call `mco_create` when we explicitly create a fiber, and we never call this for the main fiber. This change resolves the crash of the spec, but it might not be the best solution.
=> Throw exception when trying to resume main fiber

src/kernel_module.cpp
This new calculation matches the behaviour that is mocked in the specs (https://github.com/natalie-lang/natalie/blob/371bb6809f69904ad188b321c5a49ee4afaa0ccc/spec/core/kernel/Complex_spec.rb#L203-L204)
This is in preparation for splitting up the coercion and combining of the input arguments, since `Complex(1+3i, 5-1i)` should behave the same as `Complex('1+3i', '5-1i')`
=> Alter calculation for Kernel.Complex with two complex objects

ext/tm/include/tm/hashmap.hpp, ext/tm/include/tm/string.hpp, ext/tm/include/tm/string_view.hpp, include/natalie/forward.hpp, include/natalie/hash_object.hpp, include/natalie/regexp_object.hpp, include/natalie/symbol_object.hpp, src/env_object.cpp, src/fiber_object.cpp, src/hash_object.cpp, src/kernel_module.cpp, src/method_object.cpp, src/string_object.cpp, test/gc_lint.rb
The old implementation had two major disadvantages:
* The key type and the hash/compare methods could be defined individually. This resulted in issues with integer keys and pointer type, where the hash was always 0 and the hash map was just a linked list (see #2559)
* The lookup methods required a copy of the object to look up. This is okay with a pointer, but inefficient with a string. As a side effect, it was impossible to do a lookup with a stringview or a char pointer, even though this included the exact same information as the string object.
This change extracts the hash and lookup methods into separate typed structs. A hash for an integer type will now fail to compile, until you implement a specific typed struct for integers. The hash/compare methods can now be defined …
=> Turn TM::Hashmap inside out

Rakefile, include/natalie/macros.hpp, lib/natalie/compiler/flags.rb, src/fiber_object.cpp, src/gc.cpp
I removed this in 777f32a3e6173aa098c684a153c9a29eae5ba8f1 in favor of `__builtin_frame_address(0)`, which I thought was equivalent. Apparently, it is not.
In the `HashObject(Env *, size_t, Value *)` constructor I noticed the GC was collecting the HashObject *during* the construction. Clang allocates the memory and stores the pointer in a register. We call `HashObject::put()`, which allocates memory, which can trigger a GC collection. Clang pushes the pointer onto the stack *just outside* the `__builtin_frame_address(0)` boundary.
Example:
```
stack location of HashObject pointer: 0x16fdfbee0
__builtin_frame_address(0) gives us:  0x16fdfbf30
so we think the stack is:             0x16fdfbf30 to 0x16fe00000
but the &dummy trick gives us:        0x16fdfbe08
so the real stack range is: …
```
=> Fix stack scanning by using dummy variable again

include/natalie.hpp, include/natalie/forward.hpp, include/natalie/number_parser.hpp, spec/core/string/to_f_spec.rb, src/number_parser.cpp, src/string_object.cpp
This introduces a NumberParser class with a generic framework for parsing numbers, which can be used in all other number coercion methods as well.
Next step is to use this parser in Kernel.Float as well, but it turns out this one behaves slightly different: "0x10" is a valid float according to Kernel.Float (with the value 16.0), but String#to_f does not accept the hex prefix. Ruby, I want to love you, but why? So the next step is probably going to rewrite half of it.
=> Refactor String#to_f

Dockerfile, Rakefile, include/natalie/enumerator/arithmetic_sequence_object.hpp, include/natalie/fiber_object.hpp, test/gc_lint.rb
It's faster and more accurate for our purposes. Also, ffi-clang was giving different results depending on the version of Clang, and the bindings were crashing on newer versions.
As a bonus, this new script found one potential bug.
=> Use CastXML for the gc_lint script

src/number_parser.cpp
Do not consume the token unless the next token is valid.
This is going to help when creating the parser for Kernel.Float, where a trailing E would be an error.
=> Fix parsing of scientific E in float

spec/core/regexp/last_match_spec.rb
The issue is not related to errors bubbling up, but simply because we set our regexp globals as block local, which should be treated as scope local.
A simple example:
```ruby
/foo/ =~ 'foobar'
-> { p Regexp.last_match }.call
```
This prints the MatchData object in MRI, but Natalie prints a nil.
We have the same issue the other way around:
```ruby
-> { /foo/ =~ 'foobar' }.call
p Regexp.last_match
```
Rewrite the failing specs into a form that works that is closer to the original spec.
There is some logic conserning caller scopes and outer blocks in the lookups, but that might have to be redone. This issue is not limited to this spec, but it occurs everywhere we use any global references to regex results.
=> Clarify spec error for Regexp.last_match

ext/tm/include/tm/string_view.hpp
The old code found a fallback in the TM::String& argument, which means comparing a StringView with a character creates a new TM::String object, including a memory allocation of 1 byte on the heap, compares them, and frees the memory again.
=> Implement TM::StringView::operator== for char argument

include/natalie/constant.hpp, include/natalie/global_variable_info.hpp, include/natalie/global_variable_info/access_hooks.hpp, include/natalie/module_object.hpp, include/natalie/object.hpp, include/natalie/process_module.hpp, include/natalie/range_object.hpp, include/natalie/time_object.hpp, lib/ffi.rb, lib/fiddle.rb, lib/natalie/compiler/instructions/class_variable_get_instruction.rb, lib/openssl.cpp, lib/rbconfig/sizeof.rb, lib/securerandom.cpp, lib/socket.cpp, lib/yaml.cpp, lib/zlib.cpp, src/array_object.cpp, src/constant.cpp, src/file_object.cpp, src/global_env.cpp, src/global_variable_info.cpp, src/global_variable_info/access_hooks.cpp, src/io_object.cpp, src/math.rb, src/module_object.cpp, src/object.cpp, src/process_module.cpp, src/range_object.cpp, src/time_object.cpp
This work gets all of the tests in `test/natalie` passing with `Value` having this assertion:
```cpp
Value(Object *object)
m_value { reinterpret_cast<uintptr_t>(object) } {
assert(object != nullptr);
}
```
(not committed in this PR)
=> Use Optional<Value> in place of nullptr (part 4)

ext/tm/include/tm/string.hpp
This makes it more efficient to call with a C style string by removing the allocation of a new String object.
This should make #2630 a bit more efficient, even with an empty char*, we still perform a heap allocation for the null byte. So we allocate 1 byte and use an 8 byte pointer to address that memory
=> Add TM::String::replace_bytes for char* argument

ext/tm/include/tm/string_view.hpp, src/string_object.cpp
Beside the issue found in #2630, there were two other bugs in the code, so I'm surprised we never had other issues with this operation.
Beside those bugs, the order of operation has been shuffled a bit, to make the operation more efficient and remove some duplicate checks.
=> Fixes to StringView::operator==

src/string_object.cpp
The changes in #2606 made this possible.
=> Don't convert string views to strings in character classes hash lookups

include/natalie/gc/heap.hpp, src/fiber_object.cpp, src/gc.cpp, src/thread_object.cpp
This just DRYs up some duplicate code and eliminates the temporary `roots` hashmap.
=> A bit of refactoring in the GC

lib/natalie/compiler/pass1.rb, spec/language/assignments_spec.rb
=> Fix splat usage in IndexOperatorWriteNode

spec/language/predefined/fixtures/toplevel_binding_dynamic.rb, spec/language/predefined/fixtures/toplevel_binding_dynamic_required.rb, spec/language/predefined/fixtures/toplevel_binding_id.rb, spec/language/predefined/fixtures/toplevel_binding_id_required.rb, spec/language/predefined/fixtures/toplevel_binding_required_before.rb, spec/language/predefined/fixtures/toplevel_binding_values.rb, spec/language/predefined/fixtures/toplevel_binding_variables.rb, spec/language/predefined/fixtures/toplevel_binding_variables_required.rb
These have been included in #2627 (the DATA constant), but they are not used in this spec. Remove them for now, we'll add them back once we start working on the spec they belong to.
=> Remove fixtures for toplevel_binding spec

lib/natalie/compiler/pass1.rb, spec/language/assignments_spec.rb, spec/language/constants_spec.rb
```ruby
Foo::Bar = (raise "frop"; 1)
```
Code like this should evaluate the LHS first, so this will fail because `Foo` cannot be found, and never raise
=> Fix execution order for ConstantPathWriteNode

lib/natalie/compiler/pass1.rb, spec/language/optional_assignments_spec.rb
```ruby
b[*[:foo]] ||= 1
b[*[:foo]] &&= 1
```
They're pretty much the same structure, just with the if/else bodies swapped
=> Fix splat usage in Index{And,Or}WriteNode

lib/natalie/compiler/pass1.rb, spec/language/optional_assignments_spec.rb
This is code like:
```ruby
a[x, y] += z
a[x, y] ||= z
a[x, y] &&= z
```
These all had the same bug (so at least we're consistent (or using copy/paste to write code)). Instead of pushing the arguments `x, y` on the stack, we pushed the first argument every time, so our examples ended up as if they were `a[x, x] = z`. This only happened in the read section of `||=` and `&&=`, the write section worked as intended. The code for `a[x, y] ||= z` passed the spec accidentally: instead of ending up on the designated value that was `nil`, we ended up past the actual array and that did pass the spec.
=> Fix write nodes with multiple arguments

include/natalie/gc/heap.hpp, src/gc.cpp
This shows small improvement when running a program with lots of GC runs, including the self-hosted compiler.
```
→ hyperfine --warmup 10 'bin/nat_master -c h1 examples/hello.rb' 'bin/nat -c h2 examples/hello.rb'
Benchmark 1: bin/nat_master -c h1 examples/hello.rb
Time (mean ± σ):     927.4 ms ±  32.2 ms    [User: 720.6 ms, System: 156.1 ms]
Range (min … max):   881.7 ms … 991.4 ms    10 runs
Benchmark 2: bin/nat -c h2 examples/hello.rb
Time (mean ± σ):     878.5 ms ±   5.2 ms    [User: 723.1 ms, System: 154.5 ms]
Range (min … max):   870.5 ms … 884.7 ms    10 runs
Summary
bin/nat -c h2 examples/hello.rb ran
1.06 ± 0.04 times faster than bin/nat_master -c h1 examples/hello.rb
```
=> Improve memory scanning performance a bit

spec/core/string/split_spec.rb
Only a few of the specs in the "regexp matches a zero-length string" block are infinite loops. Disable these tests, so we can run the remaining few.
=> Update specs for String#split

.rubocop.yml, Dockerfile, Rakefile, bin/natalie, lib/fileutils.rb, lib/natalie/compiler.rb, lib/natalie/compiler/advisory_lock.rb, lib/natalie/compiler/backends/cpp_backend.rb, lib/natalie/compiler/backends/cpp_backend/out_file.rb, lib/natalie/compiler/macro_expander.rb, lib/socket/constants.rb, spec/support/cpp_output_specs.rb, test/ruby/ruby_specs_test.rb, test/support/compare_rubies.rb
...so multiple processes can utilize the same build directory without stepping on each other's work.
This also adds the `--build-quietly` option and enables the build directory for our test runs.
=> Add lock for build directory

lib/natalie/compiler/backends/cpp_backend/out_file.rb
This was extracted from #2663.
=> Fix bad cpp output when source code is shorter than before

ext/tm/include/tm/recursion_guard.hpp, lib/natalie/compiler/backends/cpp_backend.rb, lib/thread_pool.rb, src/dir.rb
Extracted from #2663.
On a multi-core machine this can dramatically speed up compilation when using a build directory.
=> Build object files in parallel

include/natalie/symbol_object.hpp, lib/natalie/compiler/flags.rb, src/string_object.cpp
This was extracted from #2663.
A multi-threaded bit of code that causes the internal runtime code to intern the same symbol at roughly the same time can cause a race condition: two different threads can intern two different symbols with the same name, which obviously defeats the purpose of symbols. 😅 
Here is some code that demonstrates it:
```ruby
threads = Array.new(12) { Thread.new { File.stat('README.md').mtime } }
threads.each(&:join)
```
Result of running this a few times:
```
#<Thread:0x56599a658620 wat.rb:1 run> terminated with exception (report_on_exception is true):
1: from wat.rb:1:in 'block in block in block'
wat.rb:1:in 'mtime': unexpected unit: :nanosecond (ArgumentError)
1: from wat.rb:1:in 'block in …
```
=> Lock symbol hashmap when interning a symbol from C++ code

ext/tm/include/tm/string.hpp
Adding a negative number of characters should not be allowed.
=> Use unsigned int type for count in TM::String::append_char

lib/strscan.rb
The value is defined as the maximal value in the current upstream specs (Ruby 3.4.3).
This should resolve the crashes in the nightly spec runner and turn them into actual failed specs which we can fix.
=> Add Version constant to StringScanner

include/natalie/encoding/ascii_8bit_encoding_object.hpp, include/natalie/encoding/us_ascii_encoding_object.hpp, include/natalie/encoding_object.hpp, include/natalie/string_object.hpp, src/encoding/us_ascii_encoding_object.cpp, src/encoding/utf8_encoding_object.cpp, src/string_object.cpp, src/value.cpp
Checking whether a string is valid in its encoding can be pretty expensive; caching that validity result reduces how often we have to do it.
For this ruby code:
```ruby
s = 'x,' * 10_000
p s.encoding
def boo(arg)
end
100.times { boo s.split(',') }
```
...this produces a 1.28x speedup:
There's also an optimization for endless ranges on binary strings, which is how this rabbit trail started:
```ruby
s = 'x'.b * 10_000
p s.encoding
def boo(arg)
end
10_000.times { boo s[8000..] }
```
...this produces a 50x speedup:
=> Optimize and cache string validity checks

lib/strscan.rb, spec/library/stringscanner/charpos_spec.rb
By aliasing it to #pos. This smells fishy, either it is an alias and it should use the shared spec for #pos, or it behaves diffently but the specs don't cover those differences.
=> Implement StringScanner#charpos

ext/tm/include/tm/vector.hpp, include/natalie/global_env.hpp, include/natalie/module_object.hpp, src/module_object.cpp
Finding a method in a chain of superclasses/modules can be expensive, so let's cache that on the module.
With this code:
```ruby
module Bar
def bar
1
end
end
class Foo
include Bar
end
class Baz < Foo
end
class Buz < Baz
end
def boo(arg)
end
100_000.times { boo Buz.new.bar }
```
...the result is about 1.7x faster.
This implementation has one (known) flaw: there's a scenario where the `m_method_cache_version` integer rolls over **and** there's a collision with a previous cache version on some module, that method won't be invalidated. I think the way around that would be to check if the version int is about to overflow and then walk all modules and reset their cache, but I'll save that for another day.
=> Add per-module method cache

Gemfile, Gemfile.lock
This is required to get the specs to work in Ruby 3.5.
=> Add fiddle to Gemfile

lib/natalie/compiler/args.rb, lib/natalie/compiler/pass1.rb, spec/language/delegation_spec.rb, test/natalie/argument_test.rb
This is probably not the official name, but it's related to code like this:
```ruby
def foo(a, ...) = a
```
This populates the named arguments.
The following behaviour still needs a follow-up:
```ruby
def foo(a, ...) = bar(...)
```
Currently we still forward the full original arguments.
=> Fix partial argument extraction

src/natalie.cpp
Fetch the thread context RSP register differently on x86_64 Apple devices.
This fixes a build issue where compilation fails with a
```
error: member reference type 'struct __darwin_mcontext64 *' is a pointer; did you mean to use '->'?
```
On such platforms, `ctx->uc_mcontext` is a pointer itself.
Thus the members of the struct being pointed to need to be accessed via the arrow operator.
Also, `gregs` is not a member of the struct so the registers are accessed via the `__ss` member.
=> fix compile issue on x86 MacOS

include/natalie/string_object.hpp, src/time_object.cpp
Instead of a loop, build the prefix zeroes string in a single statement. This removes the prepend_char call from the loop, which does move the strings memory in every iteration.
=> Simplify subsecond algorithm in Time#inspect

spec/library/yaml/shared/load.rb
Include the full error message, this shows we parse the values as string instead of Time.
=> Improve checks for Time loading in YAML specs

lib/ffi.cpp, lib/ffi.rb
This keeps the name consistent with mri-ffi.
=> Rename @enums ivar to @ffi_enums

lib/ffi.rb
We had a specific error message to describe the only type we support, but that would only be printed if you passed in exactly two arguments. Any other number of arguments would result in a generic "wrong number of arguments" message.
=> Improve error messages of FFI's enum

spec/language/fixtures/class_with_class_variable.rb, spec/language/predefined_spec.rb, spec/language/string_spec.rb, src/global_env.cpp
And include a tiny error message fix for read-only globals, this was easier than adding NATFIXME blocks around all those failures.
=> Refresh specs after upstream updates

src/global_env.cpp, src/natalie.cpp
The removes the exception for these methods from `Kernel#global_variables`, which also removes the outdated comment about them being handled compile time. We've replaced this with read hooks.
For now, still treat them as readonly, even though they can be written too (I'm not sure why you would want to do that, but who am I to judge). These changes are now easier to make.
=> Register $! and $@ as global variables on init

spec/language/predefined_spec.rb
Often a very big block of code was wrapped in a NATFIXME block, even though only one line of it failed. Make these error specs more specific, so we can actually see what fails.
=> Tighten NATFIXME blocks in predefined_spec

lib/natalie/compiler/pass1.rb, spec/language/END_spec.rb
Which is actually a fix for supporting END with an empty block.
=> Fix 'it warns when END is used in a method'

lib/socket.cpp, spec/library/socket/unixsocket/recvfrom_spec.rb
We still overwrite its internal buffer because we have no access to the inner TM::String, so it's not as efficient as the MRI implementation. It does save the encoding.
=> Support buffer argument in UNIXSocket#recvfrom

lib/socket.cpp
We were overwriting the `result` pointer so it wasn't getting freed properly.
=> Fix memory leak from getaddrinfo

lib/natalie/compiler/flags.rb, src/string_object.cpp, test/natalie/string_object_test.rb
There was a typo in the method call, so instead of converting it to a float type, it was using a boolean.
This was found using `-Wsign-promo` in compilation. This flag is now added to the debug build.
=> Fix StringObject::append with float value

include/natalie/symbol_object.hpp
The syntax with space is deprecated, Clang++ 20 will warn when using this.
=> Remove space in `*operator"" _s`

ext/tm/include/tm/string.hpp
Just use the m_str buffer in place. This reduces some code duplication, and the new code uses the existing buffer in place, which removes a copy operation as well.
The following script:
```c++
TM::String str {};
str.append(static_cast<int>(1));
str.append(static_cast<size_t>(2));
str.append(static_cast<ssize_t>(3));
str.append(static_cast<double>(4.5));
str.print();
```
roughly reduced 4K operations in callgrind.
Meanwhile, compile down went down: the above script compiled 100 times in a row with G++ (14.2.0) and -O3 takes roughly 14.6 seconds on my machine when using master, and 13.5 seconds with this patch.
=> Generic solution for append+snprintf in TM::String

ext/tm/include/tm/string.hpp
Instead of a dedicated function to construct it, just use move semantics.
This will break  #2772, since that is the only place were we actually use the old name of the constructor, but that one is kind of under construction.
=> Update move constructor of TM::String

lib/socket.cpp, lib/socket.rb, spec/library/socket/basicsocket/close_read_spec.rb, spec/library/socket/basicsocket/close_write_spec.rb, spec/library/socket/shared/partially_closable_sockets.rb, src/io_object.cpp
The ivars `@read_closed` and `@write_closed` are modeled after `lib/stringio.rb`. They are read in the methods in `IO`, and open up the possibility to implement these methods on `IO` too.
=> Implement BasicSocket#close_read/close_write

src/io_object.cpp
This resolves a timeout if no full line is available (#2792). Keep in mind: this does not yet implement `IO#readpartial`.
I'm not fully satisfied with the implementation, this sets the globals for last line ans lineno, even though we don't do anything related to lines. A future is probably to move some of the logic of `gets` to `read`, and use that directly from `getc`.
=> Add limit to gets proxy in IO#getc

spec/core/warning/warn_spec.rb
This is probably fixed in #2613
=> Enable spec "Warning.warn is called by parser warnings"
