include/natalie/array_value.hpp, include/natalie/vector.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/enumerable/each_with_index_spec.rb, spec/core/enumerable/zip_spec.rb, src/array_value.cpp, src/bindings.cpp, src/enumerable.rb, test/natalie/array_test.rb, test/support/spec.rb
Progress towards #19.
Full support is blocked by #21, but I didn't feel like reading up on how exactly `Enumerator` is supposed to behave.
I'm not sure if the `Vector` changes go against the overall style of the project, please tell me if they do.
=> Enumerable#zip, Enumerable#each_with_index, Array#shift

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, src/array_value.cpp, src/bindings.cpp, test/natalie/array_test.rb
I saw a tweet about this project and I thought it was cool.
I'm not versed in cpp but I wanted to add the sample method for arrays.
My concerns are regarding how accurate is the randomness, I guess is good enough (I wouldn't use it for an online casino though). I did a script to check the distribution:
```
ary = [1,2,3,4,5,6,7,8,9,10]
ocs = []
99999.times { ocs << ary.sample }
ary.each { |e| puts e; puts ocs.select { |s| s == e }.length }
```
Output:
```$ bin/natalie /tmp/distribution.natalie
1
10037
2
9904
3
9934
4
9949
5
9979
6
10034
7
10079
8
10104
9
9975
10
10004
```
Looking for feedback.
=> Array: #sample

include/natalie/range_value.hpp, src/range_value.cpp, test/natalie/range_test.rb
Was inspired by your video to check if I could remove the duplicated code.
Could not really find much about project style so hope this is correct.
Let me know if you do not want `if constexpr` since it is not used anywhere else in the project and might thus require a higher version of c++.
(Also I have barely used ruby so hope switching the ordering slightly does not break the spec or some other assumptions)
=> Deduplicate looping logic in ranges

include/natalie/array_value.hpp, include/natalie/string.hpp, lib/natalie/compiler/binding_gen.rb, src/array_value.cpp, src/value.cpp, test/natalie/array_test.rb
I also started implementing Array#[] with sequences but that is ruby 3.
Which version do we want to emulate?
=> Fix and add Array methods

spec/core/enumerable/each_entry_spec.rb, src/enumerable.rb
Because I did not mention it in my previous PRs:
Thank you very much for this great project! I love Ruby and after watching your latest video I was finally motivated enough to contribute myself. 😅
=> Implement Enumerable#each_entry

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/sort_by_spec.rb, spec/core/enumerable/sort_by_spec.rb, src/array_value.cpp, src/enumerable.rb, test/support/spec.rb
This also fixes a small bug with Stubs and introduces Stub#once and Stub#and_yield.
=> Implement Enumerable#sort_by and Array#sort_by!

spec/core/enumerable/partition_spec.rb, src/enumerable.rb
=> Issue #19: Patchup Enumerable#partition to be spec compliant

spec/core/enumerable/reverse_each_spec.rb, src/enumerable.rb, test/natalie/reverse_each_test.rb
This attempts to implement the `Enumerable#reverse_each` method.
[#19]
=> Implement Enumerable#reverse_each

spec/core/enumerable/filter_map_spec.rb, src/enumerable.rb
=> Implement Enumerable#filter_map

spec/core/enumerable/slice_after_spec.rb
=> Remove #skip-test from slice_after_spec.rb

spec/core/enumerable/sum_spec.rb, src/enumerable.rb
The specs needed to be modified because Rational is not implemented yet.
[#19]
=> Implement Enumerable#sum

spec/core/enumerator/each_spec.rb, spec/core/enumerator/feed_spec.rb, spec/core/enumerator/fixtures/common.rb, spec/core/enumerator/next_spec.rb, spec/core/enumerator/peek_spec.rb, spec/core/enumerator/rewind_spec.rb, src/enumerator.rb, test/support/spec.rb
I'm currently fiddling with Enumerator::Lazy and discovered that I actually do not know a lot about Enumerator itself. So I decided to run some specs and try to fix some issues that came up with it.
=> Make Enumerator more spec-compliant

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/sum_spec.rb, src/array_value.cpp
Addresses Array::sum for #39 
nothing to implement as sum is already provided by Enumerable and Array includes Enumerable.
=> add Array::sum spec 

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/insert_spec.rb, src/array_value.cpp
Adding Array::insert to Array as per #39
=> add spec for Array::insert and implement it 

spec/core/enumerator/with_index_spec.rb, spec/fixtures/enumerator/classes.rb, spec/shared/enumerator/with_index.rb, src/enumerator.rb
This will hopefully lay the ground to implement `Enumerator::Lazy#with_index`
=> Implement Enumerator#with_index

spec/core/array/to_a_spec.rb, spec/core/array/to_ary_spec.rb
as per #39.
The implementation was already good so I've just added the specs, making sure to exclude recursive equality checks which would always end up in an endless loop.
=> add spec for to_a and to_ary

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/to_h_spec.rb, src/array_value.cpp
Another one down for #39 
delegates to Enumerable but changes owner of to_h to Array.
=> Add Array::to_h

spec/core/array/at_spec.rb, src/array_value.cpp
Implement Array::at from #39 
Added index to_int conversion when parameter is not an int
=> implement Array at

spec/core/enumerator/lazy/chunk_while_spec.rb, src/enumerator.rb
I guess I forgot one of these methods here :^)
=> Implement Enumerator::Lazy#chunk_while

spec/core/array/any_spec.rb
the implementation was there already, this adds the spec for #39
=> added Array::any spec

spec/core/array/append_spec.rb, spec/core/array/push_spec.rb, spec/core/array/shared/push.rb, src/array_value.cpp
Covers both append and push from #39 , adding the spec and asserting the array is not frozen or raising an error.
=> Array append and push

spec/core/array/array_spec.rb
probably the easiest one out of #39 :^)
=> add array_spec.rb

spec/core/array/assoc_spec.rb, src/array_value.cpp
=> added Array::assoc spec and fixed test

.github/workflows/build.yml, Dockerfile, Makefile, lib/natalie/compiler/method_args.rb, test/natalie/fiber_test.rb
I'm making a PR so I can check that the new CI build config works. :-)
This fixes #109.
=> Fixes for Ruby 3.0

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/allocate_spec.rb, src/array_value.cpp
and another one down from #39 , one of the hardest ones :)
=> add spec for Array::allocate

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/delete_if_spec.rb, spec/core/array/shared/delete_if.rb, src/array_value.cpp, test/support/spec.rb
add Array::delete_if from #39 
add empty array matcher
=> add Array::delete_if spec

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/delete_spec.rb, src/array_value.cpp
=> Array delete method

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/delete_at_spec.rb, src/array_value.cpp
=> implement Array::delete_at

include/natalie/array_value.hpp, include/natalie/value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/bsearch_index_spec.rb, spec/core/array/bsearch_spec.rb, src/array_value.cpp
bsearch and bsearch_index from #39 
Added is_boolean to value to simplify the type checks
=> implement Array bsearch and bsearch_index and add specs

spec/core/array/clear_spec.rb
already implemented, just added the spec for #39
=> add Array::clear spec

lib/natalie/compiler/binding_gen.rb, spec/core/array/collect_spec.rb
Added the spec and bound collect! #39  to the in place version of map which was already implemented
=> Array collect and collect!

spec/core/array/concat_spec.rb, src/array_value.cpp
add spec and make Array::concat compliant as per #39
=> fix Array::concat

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/constructor_spec.rb
Another one down from #39 , the implementation was correct but was not passing down the correct subclass as MRI does.
=> make Array constructor spec compliant

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/join_spec.rb, spec/core/array/multiply_spec.rb, src/array_value.cpp
Added array multiply and join from #39 . There was an issue with some tests causing others to cascade and break as well even when those were passing in isolation. For now I've just commented them out and added a FIXME
=> Array multiply and join

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/drop_spec.rb, spec/core/array/drop_while_spec.rb, src/array_value.cpp
=> implement Array::drop and drop_while

spec/core/array/each_spec.rb, src/array_value.cpp
Added spec for array::each and made it compliant as per #39 . I mostly had to account for the use-case where the underlying array that is being iterated change its content :)
=> make Array each spec compliant

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/each_index_spec.rb, src/array_value.cpp
implement Array each index from #39
=> implement Array each_index

spec/core/array/last_spec.rb, src/array_value.cpp
=> make Array last spec compliant

spec/core/hash/values_spec.rb
Just add the spec file, as the method itself was already implemented 😄
=> Add spec for Hash#values

spec/core/hash/each_key_spec.rb, spec/core/hash/each_pair_spec.rb, spec/core/hash/each_value_spec.rb, src/hash.rb
Implements:
* `Hash#each_key`
* `Hash#each_value`
Add spec for `Hash#each_pair`
=> Implement all Hash#each* methods

include/natalie/env.hpp, include/natalie/hash_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/hash/fetch_spec.rb, spec/core/hash/fetch_values_spec.rb, spec/shared/hash/key_error.rb, src/env.cpp, src/exception.rb, src/hash_value.cpp
A question that turned up during development of this: Do we have a generic way of printing a warning to the user? In *.rb files we just print to $stderr, so I tried to mimic this behavior. Maybe we could add a simpler helper or something?
=> Implement Hash#fetch and Hash#fetch_values

include/natalie/hash_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/hash/sort_spec.rb, src/hash_value.cpp
Hash#sort is implemented by Enumerable!
=> Remove custom Hash#sort method

spec/core/array/count_spec.rb
back to #39 by adding the spec for Array::count
=> add spec for Array::count

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/prepend_spec.rb, spec/core/array/shared/unshift.rb, spec/core/array/unshift_spec.rb, src/array.rb, src/array_value.cpp
Implement Array::unshift and add prepend as an alias as per #39
=> Array prepend and unshift

spec/core/array/shift_spec.rb, src/array_value.cpp
add spec and make it spec-compliant as per #39
=> Array shift

spec/core/array/index_spec.rb, spec/core/array/shared/index.rb, src/array_value.cpp
- Add spec for Array#Index
- Make ArrayValue::Index spec compliant
https://github.com/seven1m/natalie/issues/39
=> Array Index

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/keep_if_spec.rb, src/array_value.cpp
from #39 , uses select! under the hood
=> Array keep if

spec/core/array/shared/length.rb, spec/core/array/size_spec.rb
=> add spec for Array::size

spec/core/array/empty_spec.rb
- Add spec for Array#empty?
#39
=> Array#Empty Spec

spec/core/array/find_index_spec.rb
- Add spec for Array#find_index
#39
=> Array#find_index spec

src/array_value.cpp, test/natalie/array_test.rb
[1,1].hash should != [2,2].hash
[fixes #188]
=> Fix bug with Array#hash

spec/core/array/repeated_combination_spec.rb, src/array.rb
Another one for #39 . The current implementation is somewhat naive, even aside from the fact I'd try to avoid recursion altogether, there is still the issue of how this just returns a non-lazy iterator because I do not know how to calculate all the possible combinations.
=> Array repeated combination

include/natalie.hpp, include/natalie/hash_builder.hpp, src/array_value.cpp, test/natalie/array_test.rb
This is a follow-up to the latest issue in #188, the best issue ever on this project :^). @seven1m @richardboehme please have a look and let me know if you can break this one too ;)
=> make Array::hash more reliable on arrays containing only duplicate elements

spec/core/array/dup_spec.rb
no work to be done but add the spec for #39
=> Add spec for Array::dup

spec/core/array/length_spec.rb
=> Add Array#length spec

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/max_spec.rb, spec/core/array/min_spec.rb, spec/core/array/minmax_spec.rb, spec/shared/enumerable/minmax.rb, src/array_value.cpp
Implemented all min/max related methods in Array as per #39 . They are all pretty much similar and try to exit as eagerly as possible (probably they might be more optimised but this is already slightly better than getting a slide of a sorted array so it's probably good enough for now)
=> Array min, max, minmax methods

include/natalie/array_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/difference_spec.rb, spec/core/array/minus_spec.rb, spec/core/array/shared/difference.rb, src/array_value.cpp
Added difference and sub methods to Array from #39.
=> Array sub and difference

lib/natalie/compiler/binding_gen.rb, spec/core/array/initialize_spec.rb, src/array_value.cpp
=> make Array initialize spec compliant

include/natalie/array_value.hpp, spec/core/array/rindex_spec.rb, src/array_value.cpp
This also drys up the code to reuse code from Array#index
[#39]
=> Make Array#rindex spec-compliant

spec/core/array/shuffle_spec.rb, src/array.rb, src/integer.rb, test/support/spec.rb
This also adds a primitive version of Integer#downto and fixes a bug with spec expectations.
=> Implement Array#shuffle

spec/core/array/plus_spec.rb, src/array_value.cpp
=> Make Array#+ spec compliant

spec/support/ruby_spec_runner.rb
This gives us a detailed report about each specific spec file that can
be used to display more data on natalie-lang.org.
It should be backwards-compatible and support the current spec API.
Reference: seven1m/natalie-lang.org#2
=> Expand ruby spec runner output

include/natalie/array_packer/integer_handler.hpp, include/natalie/array_packer/packer.hpp, spec/core/array/pack/c_spec.rb, src/natalie.cpp, test/natalie/array_test.rb
This also adds an `Encoding::BINARY` constant as it's needed for one of the specs.
=> Implement Array#pack c- and C-directives

test/natalie/array_test.rb
Missed this guy. I probably need to create a linter which makes PRs fail with one of those 😅
=> Remove focused Array#pack test

include/natalie/array_value.hpp, src/enumerable.rb, test/natalie/array_test.rb, test/natalie/class_var_test.rb, test/natalie/rescue_test.rb
Didn't want this to be my first contribution, second is fine though :smile:
=> Fix a few typos

spec/core/integer/integer_spec.rb, src/integer.rb, src/module_value.cpp, src/natalie.cpp, test/natalie/module_test.rb, test/support/spec.rb
Also include Comparable in Integer so that `spec/core/integer/integer_spec.rb` passes fully.
=> Implement Integer#integer?

include/natalie/integer_value.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/ord_spec.rb
=> Implement Integer#ord

include/natalie/bignum_value.hpp, include/natalie/integer_value.hpp, spec/core/integer/uminus_spec.rb, src/bignum_value.cpp, test/support/spec.rb
Thanks to @TheGrizzlyDev's work in the last PR this was an easy one 👌 
[#201]
=> Make Integer#negate spec compliant

include/tm/hashmap.hpp
This is something I noticed while watching @awesomekling's recent video. He briefly noted that `calculate_map_size` was taking up a decent amount of time in the debug build before his `hydrate`-avoidance changes. This stood out to me since I had previously done some [optimizations in the Zig standard library](https://github.com/ziglang/zig/pull/2630) that I thought might apply here as well. It didn't end up being quite as much of a difference as I expected, but thought I'd submit a PR in case it's still desirable.
From the commit message:
Instead of doing `pow(2, i) - 1` in a loop, we can instead calculate
the target capacity and then bump it up to the next power of two.
Plus, because capacity is now always a power of two, (it was previously
always 1 less than a power of two) we can use …
=> Optimize hash map capacity calculations

lib/natalie/compiler/binding_gen.rb, spec/core/integer/next_spec.rb
Another one for #201.
Same implementation as Integer#succ.
=> Implement Integer#next

spec/core/integer/upto_spec.rb, src/integer.rb
One for #201.
Similar implementation to Integer#downto.
=> Implement Integer#upto

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/uplus_spec.rb, src/string_object.cpp
=> Implement String#+@

spec/core/integer/shared/equal.rb, test/natalie/array_test.rb
Happy to see the new CI trick working but also sorry for committing those focused specs all the time 😅
=> Remove focused specs

include/natalie/bignum_object.hpp, include/natalie/integer_object.hpp, lib/natalie/compiler/pass1b.rb, spec/core/integer/times_spec.rb, src/bignum_object.cpp, src/integer_object.cpp, test/natalie/break_test.rb, test/natalie/integer_test.rb
Please take a close look at the compiler change as I'm not sure if this is correct. The process for this fix was more of a "trial and error"-thing than understanding what's going on.
[#201]
=> Make Integer#times spec-compliant

spec/core/integer/shared/to_i.rb, spec/core/integer/to_i_spec.rb, spec/core/integer/to_int_spec.rb
=> Add specs for Integer#to_i and Integer#to_int

include/natalie/big_int.hpp, include/natalie/bignum_object.hpp, include/natalie/integer_object.hpp, spec/core/integer/shared/abs.rb, src/bignum_object.cpp
This adds support for bignums to Integer#abs
[#201]
=> Make Integer#abs spec compliant

include/natalie/big_int.hpp, include/natalie/bignum_object.hpp, include/natalie/integer_object.hpp, spec/core/integer/to_f_spec.rb, src/big_int.cpp, src/bignum_object.cpp
=> Make Integer#to_f spec compliant

include/natalie/array_object.hpp, lib/natalie/compiler/pass4.rb, src/array_object.cpp, src/encoding_object.cpp, src/float_object.cpp, src/hash_object.cpp, src/kernel_module.cpp, src/main.cpp, src/module_object.cpp, src/natalie.cpp, src/object.cpp, src/range_object.cpp, src/string_object.cpp
Following the PR #299 I sat down and tried to review all places where we initialize a new Array and set it's capacity if possible. This should speed up large array operations a bit.
=> Initialize capacity of Arrays more often

include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/denominator_spec.rb
=> Implement Integer#denominator

include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/floor_spec.rb, spec/core/integer/shared/integer_rounding.rb, src/integer_object.cpp
=> Make `Integer#floor` spec compliant

spec/core/integer/dup_spec.rb
Already passes, spec was missing.
=> Add Integer#dup spec

include/natalie/bignum_object.hpp, include/natalie/integer_object.hpp, spec/core/string/multiply_spec.rb, spec/shared/string/times.rb, src/array_object.cpp, src/big_int.cpp, src/natalie.cpp, src/string_object.cpp, test/support/spec.rb
=> Make `String#*` spec-compliant

include/natalie/encoding_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/encoding/aliases_spec.rb, spec/core/encoding/name_spec.rb, spec/core/encoding/shared/name.rb, spec/core/encoding/to_s_spec.rb, src/encoding_object.cpp
Implement static method Encoding#aliases and added specs for to_s and name.
=> Encoding spec compliance

.gitignore, include/natalie/float_object.hpp, include/natalie/value.hpp, include/tm/vector.hpp, src/float_object.cpp, src/integer_object.cpp, src/value.cpp
In the hope I did not miss anything...
I did not yet do a performance test
(this also adds .vscode to .gitignore)
=> Apply the same Value optimizations we do for integers for floats as well

include/natalie/module_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/kernel/fixtures/classes.rb, src/module_object.cpp, src/object.cpp
(Skipping specs for now until enough `Module` methods are implemented.)
=> Implement `Module#undef_method`, `#remove_method`

include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/numerator_spec.rb, src/integer_object.cpp
=> Make `Integer#numerator` spec compliant

include/natalie/module_object.hpp, include/natalie/object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/kernel/Array_spec.rb, spec/core/kernel/Float_spec.rb, spec/core/kernel/Hash_spec.rb, src/object.cpp
(Ditto for `#Float` and `#Hash`)
=> Make `Kernel#Array` private, add `Kernel.Array`

include/natalie/big_int.hpp, include/natalie/bignum_object.hpp, include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/gcd_spec.rb, src/bignum_object.cpp, src/integer_object.cpp
Closes #338 (Kudos @ryangjchandler)
=> Make `Integer#gcd` spec compliant (Closes #338)

lib/natalie/compiler/pass4.rb
The title of the PR says it all, though it is a bit *dry*
=> Avoid hydration of floats in call when possible

include/natalie/big_int.hpp, include/natalie/bignum_object.hpp, include/natalie/integer_object.hpp, spec/core/integer/bit_and_spec.rb, src/big_int.cpp, src/bignum_object.cpp, src/integer_object.cpp
=> Make Integer#& spec compliant

.gitignore, bin/natalie, examples/boardslam.rb, include/natalie.hpp, include/natalie/forward.hpp, include/natalie/native_profiler.hpp, include/tm/optional.hpp, lib/natalie/compiler.rb, lib/natalie/compiler/pass4.rb, src/gc.cpp, src/main.cpp, src/native_profiler.cpp, src/value.cpp
Spec: https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#
This profiler is based on google's tracing format https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview# . It is an extremely simple format (at least the part we use) and since it is just a json it is somewhat easy to reason about. Personally my favourite UI for this is https://ui.perfetto.dev/ but you can also use chrome's embedded tracer instead.
Though we currently only expose this format, the API is made so it can be 'easily' extended to other formats as well.
=> Implement basic profiling using the Google Trace Event format

include/natalie.hpp, include/natalie/forward.hpp, include/natalie/global_env.hpp, include/natalie/kernel_module.hpp, include/natalie/object.hpp, include/natalie/object_type.hpp, include/natalie/rational_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/kernel/Rational_spec.rb, spec/fixtures/rational.rb, spec/shared/rational/Rational.rb, src/kernel_module.cpp, src/math.rb, src/natalie.cpp, src/object.cpp, src/rational_object.cpp
=> Implement Kernel#Rational

include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/bit_or_spec.rb, spec/core/integer/bit_xor_spec.rb, src/integer_object.cpp, test/natalie/integer_test.rb
=> Make Integer#| and Integer#^ spec compliant

include/natalie/bignum_object.hpp, include/natalie/integer_object.hpp, spec/core/integer/complement_spec.rb, src/big_int.cpp, src/bignum_object.cpp
=> Add support for Bignums to Integer#~

lib/natalie/compiler2/pass1.rb
This could be merged now, but if I wait for #428 to be merged I can rebase & update test cases with some magic stuffs :)
=> Add support for `self` instructions in VM/C2

spec/core/integer/div_spec.rb, src/integer.rb, src/numeric.rb
=> Implement Integer#div

spec/core/integer/fdiv_spec.rb, src/integer.rb
=> Implement Integer#fdiv

spec/core/integer/gcdlcm_spec.rb, spec/core/integer/lcm_spec.rb, src/integer.rb
=> Implement Integer#lcm and Integer#gcdlcm

spec/core/hash/transform_keys_spec.rb, spec/core/integer/try_convert_spec.rb, spec/core/module/module_function_spec.rb, src/integer.rb, src/natalie.cpp
This also bumps our targeted ruby version to 3.1.0
=> Implement Integer::try_convert

include/natalie/range_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/range/eql_spec.rb, spec/core/range/fixtures/classes.rb, spec/core/range/shared/equal_value.rb, src/range_object.cpp
Same implementation as `RangeObject::eq` but using `eql?` instead of `==` to compare begin and end values.
=> Implement Range#eql?

include/natalie/array_object.hpp, include/natalie/hash_object.hpp, spec/core/enumerable/shared/enumeratorized.rb, src/array_object.cpp, src/enumerable.rb, src/enumerator.rb, src/hash.rb, src/hash_object.cpp
This implements the `:enumeratorized_with_unknown_size` and `:enumeratorized_with_origin_size` behavior in `spec/core/enumerable/shared/enumeratorized.rb` for Array, Hash, Enumerable, and Enumerator methods
=> Return enumerators with sizes

spec/core/basicobject/method_missing_spec.rb, spec/fixtures/basicobject/method_missing.rb, spec/shared/basicobject/method_missing.rb, src/env.cpp, src/exception.rb
Forgot to include specs in #461
=> Make BasicObject#method_missing spec compliant

spec/core/integer/rationalize_spec.rb, spec/core/integer/to_r_spec.rb, src/integer.rb
=> Implement Integer#to_r and Integer#rationalize

include/natalie/big_int.hpp, include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/sqrt_spec.rb, src/integer_object.cpp
=> Implement Integer::sqrt

spec/core/hash/shared/select.rb
Hash#reject was implemented in 109d2046
=> Remove NATFIXME from spec/core/hash/shared/select.rb

src/natalie_parser/parser.cpp, test/natalie/parser_test.rb
For example:
```rb
case 1
when 1 then :a
:b
when 2, 3 then :c
else :d
end
```
=> Parser: fix `when` followed by `then`

include/natalie_parser/lexer.hpp, include/natalie_parser/parser.hpp, include/natalie_parser/token.hpp, src/natalie_parser/parser.cpp, test/natalie/lexer_test.rb, test/natalie/parser_test.rb
As per https://ruby-doc.org/core/doc/syntax/precedence_rdoc.html
=> Parser: fix unary operator precedence

spec/core/integer/digits_spec.rb, spec/core/integer/div_spec.rb, spec/core/integer/divide_spec.rb, spec/core/integer/divmod_spec.rb, src/big_int.cpp, src/bignum_object.cpp, src/float_object.cpp, src/integer.rb, src/integer_object.cpp, src/math.rb, test/natalie/integer_test.rb, test/support/spec.rb
This also fixes a bug with divisions of BigInts and a bug in Integer#% when passed a float.
=> Implement Integer#divmod and Integer#digits

include/natalie/array_packer/packer.hpp, spec/core/array/pack/at_spec.rb
=> Implement array#pack @ directive

include/natalie/array_packer/tokenizer.hpp, spec/core/array/pack/comment_spec.rb
=> Implement array#pack comments

spec/core/string/shared/length.rb, spec/core/string/size_spec.rb
=> Add spec for String#size

include/natalie/gc/allocator.hpp, include/natalie/hash_object.hpp, include/natalie/object.hpp, include/natalie/regexp_object.hpp, include/natalie/string_object.hpp, include/natalie/symbol_object.hpp, include/tm/hashmap.hpp, include/tm/string.hpp, lib/natalie/compiler/pass4.rb, src/hash_object.cpp, src/integer_object.cpp, src/kernel_module.cpp, src/parser_c_ext/parser_c_ext.cpp, src/regexp_object.cpp, src/string_object.cpp, src/symbol_object.cpp, test/natalie/symbol_test.rb
In #495, we discussed that Symbols don't support null terminators as they should.
In support of this change, I had to make use of TM::String in more places. So yay! :-)
=> Fix symbol with null terminator

include/natalie/bignum_object.hpp, include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/truncate_spec.rb, src/bignum_object.cpp, src/integer_object.cpp, test/natalie/integer_test.rb
=> Implement Integer#truncate

include/natalie/big_int.hpp, include/natalie/integer_object.hpp, include/tm/optional.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/element_reference_spec.rb, src/big_int.cpp, src/float_object.cpp, src/integer_object.cpp
=> Implement Integer#ref

include/natalie/rational_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/rational/minus_spec.rb, src/rational_object.cpp
Also effectively implements `Numeric` methods like `#-@` and `#abs` which utilize `#-`
=> Implement Rational#-

include/natalie/integer_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/integer/pow_spec.rb, src/integer_object.cpp
This takes it most of the way - just some BigInt fun-stuff to fix.
=> Make `Integer#pow` almost spec-compliant

spec/core/string/empty_spec.rb
Is already spec-compliant, spec-file was just missing.
=> Add `String#empty` spec

include/natalie/object.hpp, src/object.cpp
Doesn't appear to be used anywhere since 88351613
=> Remove Object::identifier_str

spec/core/integer/to_s_spec.rb, src/integer.cpp, src/integer_object.cpp
=> Make Integer#to_s bignum-aware

spec/core/integer/comparison_spec.rb
=> Unskip integer comparison specs

spec/core/integer/shared/exponent.rb, src/integer_object.cpp
=> Update Integer#** (and #pow) to respect Rational

lib/csv.rb, lib/csv/parser.rb, spec/library/csv/generate_line_spec.rb, spec/library/csv/generate_spec.rb, spec/library/csv/liberal_parsing_spec.rb, spec/library/csv/parse_spec.rb, spec/library/csv/readlines_spec.rb, src/string_object.cpp, test/lib/csv/parser_test.rb
I started working on the CSV library for Natalie (implemented in pure Ruby). Sadly, the specs for this library are not that complete. Maybe we should start to create specs for it and contribute those to ruby/spec?
Currently the `CSV::Parser` class is not compatible with Ruby's `CSV::Parser` class. This is because it's really undocumented and I didn't want to reverse engineer it or look at the source code too much. It also has a note, that this class should only be used as an internal class. We can work on making it compatible later if we want to.
=> Start work on the CSV library 

lib/csv.rb, lib/csv/parser.rb, lib/stringio.rb, spec/library/stringio/external_encoding_spec.rb, spec/library/stringio/internal_encoding_spec.rb, spec/library/stringio/set_encoding_spec.rb, test/lib/csv/col_sep_spec.rb, test/lib/csv/row_sep_spec.rb, test/lib/csv/shared/add_row.rb, test/lib/stringio_test.rb
=> Add specs for CSV#col_sep and CSV#row_sep

spec/core/range/begin_spec.rb, spec/core/range/end_spec.rb, spec/core/range/equal_value_spec.rb, spec/core/range/exclude_end_spec.rb, spec/core/range/frozen_spec.rb, spec/core/range/hash_spec.rb, spec/core/range/range_spec.rb, spec/core/range/shared/end.rb
=> Add all Range specs that we already pass

lib/readline.rb
This method isn't anything special, but it does allow people to start writing some more interactive scripts with Natalie (trying to do one myself right now).
Uses `std::getline` to grab input. Future improvements here would be using a "real" readline alternative that fits the license model of Natalie.
=> Add a very basic `Readline.readline` method

include/natalie/range_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/range/initialize_spec.rb, spec/core/range/new_spec.rb, src/range_object.cpp
=> Make Range#initialize spec compliant

include/natalie/range_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/range/case_compare_spec.rb, src/range.rb, src/range_object.cpp
=> Make Range#=== spec compliant by aliasing it to #cover?

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/chomp_spec.rb, src/string_object.cpp
Created spec/core/string/chomp_spec.rb
Added binding for String#chomp to lib/natalie/compile/binding_gen.rb
Added function prototype to include/natalie/string_object.hpp
Added function implementation to src/string_object.cpp
=> Implemented String#chomp

spec/core/string/upto_spec.rb, src/string.rb
=> Implement String#upto

include/natalie/args.hpp, include/natalie/array_object.hpp, include/natalie/string_object.hpp, include/tm/vector.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/delete_prefix_spec.rb, src/args.cpp, src/string_object.cpp
=> Add String#delete_prefix and #delete_prefix! methods

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/delete_suffix_spec.rb, src/string_object.cpp
=> Implement String#delete_suffix and String#delete_suffix!

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/ascii_only_spec.rb, src/string_object.cpp
=> Implement String#ascii_only?

include/natalie/method.hpp, include/natalie/method_info.hpp, include/natalie/module_object.hpp, src/array_object.cpp, src/kernel_module.cpp, src/method.cpp, src/module_object.cpp, src/natalie.cpp, src/object.cpp
=> Eliminate an extra hashmap lookup during method call

include/natalie/value.hpp, lib/natalie/compiler/instructions/inline_cpp_instruction.rb, src/integer_object.cpp, src/method.cpp, src/value.cpp
This is a first step toward smaller values, although we will need to compromise on u64 values somehow...
It has been a long while since I did anything on this project, so feel free to roast the code as much as you want
=> Cleanup of Value

Rakefile, bin/natalie, lib/natalie/compiler.rb
=> Dymamically link libraries when running a script directly

Rakefile
I think this will fix #593. @timcraft would you be able to test this on your Mac?
=> Use more generic invocation of ctags that should work everywhere

lib/socket.rb, spec/library/socket/addrinfo/protocol_spec.rb
**Note**: I set the base branch to be @seven1m's addrinfo-init branch. Not sure if we want to manage it like that or if we want to merge `addrinfo-init` and merge this branch into main as well?
[#598]
=> Implement Addrinfo#protocol

lib/socket.rb, spec/library/socket/addrinfo/ip_address_spec.rb
=> Implement Addrinfo#ip_address

include/natalie/symbol_object.hpp, lib/socket.rb, spec/library/socket/addrinfo/initialize_spec.rb, spec/library/socket/addrinfo/ip_address_spec.rb, spec/library/socket/addrinfo/protocol_spec.rb
This is in support of #598.
Anyone can help!
=> Start work on Socket Addrinfo#initialize

include/natalie/bsearch.hpp, include/natalie/object.hpp, include/natalie/range_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/range/bsearch_spec.rb, src/array_object.cpp, src/bsearch.cpp, src/object.cpp, src/range_object.cpp, test/natalie/array_test.rb
This also adds some binary search helpers that can be used with Array#bsearch as well.
[#555]
=> Implement Range#bsearch

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/clone_spec.rb, src/object.cpp, src/string_object.cpp
=> Make `String#clone` spec compliant

.rubocop.yml, Rakefile, lib/natalie/compiler.rb, lib/natalie/compiler/backends/cpp_backend.rb, lib/natalie/compiler/instructions/inline_cpp_instruction.rb, lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb, lib/socket.cpp, lib/socket.rb, lib/stuff.cpp, src/obj_unit.cpp, test/natalie/require_test.rb, test/support/require_sub5.cpp
You format your cpp file like so...
`lib/stuff.cpp`:
```c++
#include "natalie.hpp"
using namespace Natalie;
Value init(Env *env, Value self) {
// your code here
return NilObject::the();
}
```
Then you can require it in your Ruby code like so:
```ruby
require 'stuff'
```
=> Add ability to `require` a cpp file

spec/core/complex/coerce_spec.rb, spec/core/complex/comparison_spec.rb, spec/core/complex/constants_spec.rb, spec/core/complex/eql_spec.rb, spec/core/complex/equal_value_spec.rb, spec/core/complex/finite_spec.rb, spec/core/complex/hash_spec.rb, spec/core/complex/infinite_spec.rb, spec/core/complex/marshal_dump_spec.rb, spec/core/complex/minus_spec.rb, spec/core/complex/multiply_spec.rb, spec/core/complex/negative_spec.rb, spec/core/complex/plus_spec.rb, spec/core/complex/to_s_spec.rb, src/complex.rb
(#608)
Coming back round to get some more bits ticked off the list. There should only be a few outstanding specs after this PR.
See commits for all methods that are now spec compliant.
=> Make more `Complex` methods spec compliant

spec/core/complex/divide_spec.rb, spec/core/complex/positive_spec.rb, spec/core/complex/shared/divide.rb, src/complex.rb
(#608)
I think there's a few blockers elsewhere in the code and I need to look into how `Rational` works a little more.
=> Basic support for `Complex#/`

include/natalie/object.hpp, lib/socket.cpp, lib/socket.rb, spec/library/socket/addrinfo/shared/to_sockaddr.rb, spec/library/socket/addrinfo/to_sockaddr_spec.rb, spec/library/socket/socket/tcp_spec.rb, src/object.cpp
Just a little closer to getting a working Socket!
=> Get more socket stuff working

Rakefile, include/natalie.hpp, include/natalie/enumerator/arithmetic_sequence_object.hpp, include/natalie/forward.hpp, include/natalie/object.hpp, include/natalie/object_type.hpp, include/natalie/range_object.hpp, lib/natalie/compiler/binding_gen.rb, lib/natalie/compiler/instructions/inline_cpp_instruction.rb, spec/core/enumerator/arithmetic_sequence/begin_spec.rb, spec/core/enumerator/arithmetic_sequence/each_spec.rb, spec/core/enumerator/arithmetic_sequence/end_spec.rb, spec/core/enumerator/arithmetic_sequence/eq_spec.rb, spec/core/enumerator/arithmetic_sequence/exclude_end_spec.rb, spec/core/enumerator/arithmetic_sequence/first_spec.rb, spec/core/enumerator/arithmetic_sequence/hash_spec.rb, spec/core/enumerator/arithmetic_sequence/inspect_spec.rb, spec/core/enumerator/arithmetic_sequence/last_spec.rb, spec/core/enumerator/arithmetic_sequence/new_spec.rb, spec/core/enumerator/arithmetic_sequence/size_spec.rb, spec/core/enumerator/arithmetic_sequence/step_spec.rb, spec/core/numeric/shared/step.rb, spec/core/numeric/step_spec.rb, src/enumerator/arithmetic_sequence_object.cpp, src/natalie.cpp, src/numeric.rb, src/object.cpp, src/range_object.cpp, test/natalie/enumerator_test.rb
It took me way to longer to do this than it should have 😅 
This is progress towards `Range#step` and also makes `Numeric#step` spec-compliant.
@seven1m Please have a look at the modifications I did to the `__call__` macro. I'm not sure if I used it correctly and if my changes are good to merge.
=> Implement Enumerator::ArithmeticSequence

spec/core/string/string_spec.rb
=> Add string/string_spec.rb

spec/core/range/each_spec.rb, src/time_object.cpp, test/natalie/time_test.rb
This fixes the remaining Time related spec for Range#each.
=> Add support for Time.utc and Time.local with nil arguments

spec/core/float/shared/to_i.rb, src/float_object.cpp
This gets spec/core/float/to_i_spec.rb passing.
=> Fix Float#to_i for negative numbers

include/natalie/array_packer/float_handler.hpp, include/natalie/array_packer/packer.hpp, include/natalie/object.hpp, spec/core/array/pack/d_spec.rb, src/object.cpp
=> Add support for 'd' and 'D' directive to Array#pack

include/natalie/args.hpp, include/natalie/kernel_module.hpp, include/natalie/rounding_mode.hpp, lib/natalie/compiler/binding_gen.rb, src/args.cpp, src/integer_object.cpp, src/kernel_module.cpp, src/rounding_mode.cpp
Currently only supports optional keyword args and doesn't check for unknown/invalid kwargs
=> Improve binding gen for methods with keyword arguments

spec/core/range/max_spec.rb, spec/core/range/min_spec.rb
=> Uncomment Range#max and Range#min specs related to Time

include/natalie/array_packer/integer_handler.hpp, include/natalie/array_packer/packer.hpp, spec/core/array/pack/l_spec.rb, test/natalie/array_test.rb
=> Add Array#pack 'l' and 'L' directives

include/natalie/array_packer/packer.hpp, include/natalie/array_packer/string_handler.hpp, spec/core/array/pack/m_spec.rb
Note: I made an [upstream PR](https://github.com/ruby/spec/pull/963) for ruby/spec for a couple specs that helped me here. :hugs:
=> Array#pack: make 'm' directive spec-compliant and add 'M' directive

include/natalie/array_packer/integer_handler.hpp, include/natalie/array_packer/packer.hpp, include/natalie/array_packer/string_handler.hpp, include/tm/string.hpp, spec/core/array/pack/n_spec.rb, spec/core/array/pack/p_spec.rb, spec/core/array/pack/percent_spec.rb, src/string_object.cpp
=> Add Array#pack directives 'N', 'n', 'P', and 'p'

include/natalie/array_packer/packer.hpp, include/natalie/string_unpacker.hpp, lib/base64.rb, spec/core/string/unpack/m_spec.rb, spec/core/string/unpack/shared/basic.rb, spec/core/string/unpack/shared/float.rb, spec/core/string/unpack/shared/integer.rb, spec/core/string/unpack/shared/string.rb, spec/core/string/unpack/shared/taint.rb, spec/core/string/unpack/shared/unicode.rb, spec/library/base64/decode64_spec.rb, spec/library/base64/strict_decode64_spec.rb, spec/library/base64/urlsafe_decode64_spec.rb, src/string_object.cpp
=> Add String#unpack 'm' directive (base64)

include/natalie.hpp, include/natalie/string_unpacker.hpp, spec/core/string/unpack/m_spec.rb, src/natalie.cpp, src/string_object.cpp
#667 
I also upstreamed a spec to [ruby/spec](https://github.com/ruby/spec/pull/967) that helped.
=> Add String#unpack 'M' directive

include/natalie/string_object.hpp, include/natalie/string_unpacker.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/unpack/a_spec.rb, src/string_object.cpp
=> Add String#unpack 'A' and 'a' directives

include/natalie/string_unpacker.hpp, spec/core/string/unpack/b_spec.rb
=> Add String#unpack 'B' and 'b' directives

include/natalie/string_unpacker.hpp
=> Add array include to string_unpacker.hpp

include/natalie/string_object.hpp, include/natalie/string_unpacker.hpp, spec/core/string/unpack/h_spec.rb
=> Add String#unpack 'H' and 'h' directives

spec/core/time/eql_spec.rb
Rational subsec arguments implemented in 05f4a3b3
=> Uncomment Time#eql? spec

include/natalie/string_unpacker.hpp, spec/core/string/unpack/u_spec.rb
=> Add String#unpack 'u' directive

lib/csv/parser.rb, test/lib/csv/lineno_spec.rb, test/lib/csv/parser_test.rb
Support line breaks in quoted csv values
=> Support line breaks in quoted csv values

src/string_object.cpp
Fixed String methods:
- `#chomp`
- `#succ`
- `#[]`
- `#byteslice`
- `#slice`/`#slice!`
- `#sub`
- `#split`
- `#ljust`
- `#strip!`/`#lstrip`/`#lstrip!`/`#rstrip`/`#rstrip!`
- `#downcase`
- `#upto`
- `#reverse`
- `#delete_prefix`
- `#delete_suffix`
- `#partition`
These methods might return String value in UTF-8 and ignore encoding of the original String, as far as don't set encoding explicitly and UTF-8 is used as a default one.
```ruby
"hello".encode("US-ASCII").sub("ll", "*").encoding
```
But expected one is US-ASCII.
Not sure whether RubySpec project imports spec changes made in Natalie so I will add specs to reproduce the found issues directly in RubySpec.
=> String: return string value in the same encoding

spec/core/complex/denominator_spec.rb, spec/core/complex/integer_spec.rb, spec/core/complex/numerator_spec.rb, src/complex.rb, src/natalie.cpp
Also add new specs from upstream ruby/spec.
Continues #608.
=> Add more Complex methods

include/natalie/string_unpacker.hpp, spec/core/string/unpack/a_spec.rb, spec/core/string/unpack/b_spec.rb, spec/core/string/unpack/c_spec.rb, spec/core/string/unpack/h_spec.rb, spec/core/string/unpack/m_spec.rb, spec/core/string/unpack/u_spec.rb, spec/core/string/unpack/z_spec.rb, src/string_object.cpp
=> Add String#unpack 'C' and 'c' directives

spec/core/complex/rationalize_spec.rb, spec/core/complex/to_r_spec.rb, src/complex.rb
Based on #699 since that was accepted before I added more :)
Continues #608.
=> Add more Complex methods (part 2)

include/natalie/rational_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/marshal/major_version_spec.rb, spec/core/marshal/minor_version_spec.rb, spec/core/rational/marshal_dump_spec.rb, src/marshal.rb, src/rational_object.cpp, test/natalie/marshal_test.rb
Test coverage mostly in `test/natalie/marshal_test.rb` for now... a few more details/quirks to implement before we can get the ruby/spec specs passing (float encoding, symbol links, user classes, Struct, Time zones etc)
=> Implement Marshal.dump and Marshal.load

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/try_convert_spec.rb, src/string_object.cpp
Implemented `String.try_convert`, which is structurally similar to `Array.try_convert`.
Related to #217
=> Implement String.try_convert

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/insert_spec.rb, src/string_object.cpp
#217
Skipping two specs related to encodings for now, otherwise spec compliant.
=> Implement String#insert

include/natalie/string_unpacker.hpp, spec/core/string/unpack/l_spec.rb, spec/core/string/unpack/n_spec.rb, spec/core/string/unpack/v_spec.rb
Per #667, adding or fixing the l/n/v/L/N/V directives and adding the specs.  Feels like unpack is getting close, only a few more to go!
=> Add String#unpack 'L', 'l', 'N', 'n', 'V', 'v' directives and specs

include/natalie.hpp, include/natalie/encoding/utf32le_encoding_object.hpp, include/natalie/encoding_object.hpp, include/natalie/encodings.hpp, spec/core/integer/chr/utf_32le_spec.rb, spec/core/string/encode/utf_32le_spec.rb, spec/core/string/ord/utf_32le_spec.rb, spec/core/string/valid_encoding/utf_32le_spec.rb, spec/core/string/valid_encoding_spec.rb, src/encoding/utf32le_encoding_object.cpp, src/integer_object.cpp, src/natalie.cpp, src/string_object.cpp, test/natalie/string_test.rb
Changes:
- added UTF-32LE
- fixed a minor issue with `Integer#chr` error message
- fixed a minor issue with `String#ord` error message
=> Add UTF-32LE encoding

.github/workflows/build.yml, lib/natalie/gen_errno.rb, lib/socket.cpp, src/class_object.cpp, src/errno.rb
Fix issues with socket.rb and errno.rb on macOS. Also add a macOS build to CI.
=> Fix CI failures on macOS

include/natalie/array_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/intersect_spec.rb, src/array_object.cpp
```rb
[1, 2].intersect? [2, 3] # => true
[1, 2].intersect? [3, 4] # => false
```
=> Implement Array#intersect?

lib/natalie/compiler/binding_gen.rb, src/module_object.cpp
```
nat> Foo = Class.new
#<Class:0x7ff27a005420>
nat> Foo
#<Class:0x7ff27a005420>
```
should be
```
nat> Foo = Class.new
Foo
nat> Foo
Foo
```
For the sake of simplicity, this doesn't handle the edge case of assigning an anonymous singleton class to a constant (which doesn't matter as much since renaming the original class overwrites the singleton name anyways)
```
nat> foo = Class.new
#<Class:0x7ff0c3ef5420>
nat> Foo = foo.singleton_class
Foo
nat> Bar = foo
Bar
nat> Foo
#<Class:Bar>
```
```
irb(main):001:0> foo = Class.new
=> #<Class:0x00007f969d072ac0>
irb(main):002:0> Foo = foo.singleton_class
=> #<Class:#<Class:0x00007f969d072ac0>>
irb(main):003:0> Bar = foo
=> Bar
irb(main):004:0> Foo
=> #<Class:Bar>
```
=> Set name of anonymous class if assigned to constant

spec/core/complex/fdiv_spec.rb, src/complex.rb
=> Implement Complex#fdiv

spec/shared/rational/Rational.rb
Most of the methods of Complex have been implemented, this spec now passes.
=> Enable spec for Rational "when passed a Complex"

.github/workflows/format.yml
This workflow has been failing regularly lately. Let's see if updating the action version for EndBug/add-and-commit helps.
=> Update format GitHub workflow

include/natalie/file_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/file/fixtures/file_types.rb, spec/core/file/ftype_spec.rb, spec/core/file/umask_spec.rb, spec/core/file/unlink_spec.rb, src/file_object.cpp, test/support/spec.rb
+ Fix todo for `File.unlink` to accept multiple args
+ Fix todo for `File.mkfifo` to handle mode parameter
+ Add `File.ftype` and `File.umask`
=> Fixes and additions for File class

include/natalie/big_int.hpp, spec/core/string/to_i_spec.rb, src/big_int.cpp, src/string_object.cpp
Mostly just to let people know I'm working on this, just in case somebody else would decide to take a shot at this (very small chance, I know).
I'll probably finish it tomorrow, the remainder is pretty straight forward if you take the simple solution of walking backwards, using 1 character every time and carrying over the result, but I can think of a few optimizations to do this in bigger chunks
=> Implement String#to_i for BigInt values

spec/core/string/ord_spec.rb
I just copied a random missing file from #217 and it passes.
=> Import spec for String#ord

spec/core/enumerable/none_spec.rb, spec/core/enumerable/one_spec.rb, spec/core/nil/match_spec.rb, spec/core/string/allocate_spec.rb, spec/language/case_spec.rb
A couple of them have been fixed upstream, I think I got all of them.
=> Update spec files marked with "NATFIXME: bug in spec"

spec/core/encoding/default_internal_spec.rb
=> Enable specs related to Encoding::ASCII

spec/core/enumerable/grep_spec.rb, spec/core/enumerator/lazy/grep_spec.rb, spec/core/enumerator/rewind_spec.rb
The issues have been fixed, but these specs were still disabled.
=> Enabled a few specs

spec/core/string/unpack/p_spec.rb, src/string_unpacker.cpp
Slowly getting to a complete implementation of `String#unpack`
=> Fix "reads only as far as a NUL character" in String#unpack('P')

src/encoding/utf16le_encoding_object.cpp
=> Fix buffer overrun in StringView with UTF16LE encoding

include/natalie/array_packer/integer_handler.hpp, include/natalie/string_unpacker.hpp, spec/core/array/pack/w_spec.rb, spec/core/string/unpack/w_spec.rb, src/array_packer/integer_handler.cpp, src/array_packer/packer.cpp, src/string_unpacker.cpp
Another fix for #667
The current state is very much a work in progress, I'm just pushing it here prematurely to both let people know somebody is working on this and to keep myself accountable for actually finishing it
=> Implement Array#pack('w') and String#unpack('w')

spec/core/integer/zero_spec.rb
=> Import integer/zero_spec

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/lines_spec.rb, spec/core/string/shared/each_line.rb, src/string_object.cpp
5 specs are still skipped, but I don't think I have the possibility to fix those this week.
=> Implement most of String#lines

spec/core/string/split_spec.rb, src/string_object.cpp
The last push to the result array created a String based on a `const char*` without a length. This means an embedded null byte in the last part of the String would prematurely end the last value in the result.
=> Fix null byte termination in String#split

src/string_object.cpp
We don't need the Array in case we have a block, so construct it after we checked for the block.
=> Delay Array creation in String#chars

spec/core/hash/element_reference_spec.rb, spec/core/hash/shared/store.rb, spec/core/module/fixtures/classes.rb, spec/core/string/fixtures/freeze_magic_comment.rb, spec/core/string/uplus_spec.rb, test/support/spec.rb
Most of the specs that use this method still fail for different reasons. Document those reasons with a NATFIXME comment.
=> Implement fixture method in spec runner

spec/core/integer/shared/exponent.rb, spec/core/kernel/Float_spec.rb, spec/core/numeric/div_spec.rb, spec/core/random/new_spec.rb, spec/shared/rational/coerce.rb, spec/shared/rational/exponent.rb
Mark the remaining issues with a more specific description
=> Enable specs waiting for an implementation of Complex

spec/core/integer/bit_and_spec.rb
Integer#<< has been implemented.
=> Enable specs in integer/bit_and_spec

spec/shared/file/zero.rb
The dependency on File.realpath has been resolved
=> Enable spec for file/zero

spec/core/numeric/polar_spec.rb, spec/core/numeric/real_spec.rb, spec/core/numeric/shared/conj.rb, spec/core/numeric/shared/imag.rb, spec/core/numeric/shared/rect.rb
These tests pass on the current branch. This has been split of from  #825
=> Remove some FIXME markers for Rational in spec

src/string_object.cpp, test/natalie/Integer_test.rb
This should fix the issue described in  #820
=> Fix Kernel.Integer with input with leading zeroes and explicit base

lib/set.rb, spec/library/set/add_spec.rb, spec/library/set/shared/add.rb, spec/library/set/shared/collect.rb, spec/library/set/shared/difference.rb, spec/library/set/shared/include.rb, spec/library/set/shared/inspect.rb, spec/library/set/shared/intersection.rb, spec/library/set/shared/length.rb, spec/library/set/shared/select.rb, spec/library/set/shared/union.rb
=> Start work on Set

lib/set.rb, spec/library/set/append_spec.rb, spec/library/set/clear_spec.rb, spec/library/set/constructor_spec.rb, spec/library/set/join_spec.rb, spec/library/set/length_spec.rb, spec/library/set/size_spec.rb, spec/library/set/to_a_spec.rb
Related to #840.
List of methods implemented:
* `Set#<<`
* `Set#length`
* `Set#size` (alias of `length`)
* `Set[]`
* `Set#clear`
* `Set#to_a`
* `Set#join`
=> Implement various `Set` methods

spec/core/integer/allbits_spec.rb, spec/core/integer/anybits_spec.rb, spec/core/integer/bit_or_spec.rb, spec/core/integer/bit_xor_spec.rb, spec/core/integer/chr_spec.rb, spec/core/integer/constants_spec.rb, spec/core/integer/element_reference_spec.rb, spec/core/integer/fdiv_spec.rb, spec/core/integer/nobits_spec.rb, spec/core/integer/odd_spec.rb, spec/core/integer/right_shift_spec.rb
Another something I split off from  #825
=> Sync integer specs

lib/natalie/compiler/args.rb, lib/natalie/compiler/pass1.rb, test/natalie/loop_test.rb
This handles local variables with destructuring. I didn't test instance variables or global variables yet; that will probably take some more work.
=> Add for-loop

spec/shared/rational/Rational.rb, src/kernel_module.cpp, src/rational_object.cpp
=> Fix behaviour when creating a Rational with zero as denominator

lib/set.rb, spec/library/set/each_spec.rb
I also updated the test upstream in ruby/spec#1005.
Fixes #868.
=> Add Set#each

lib/set.rb, spec/library/set/delete_spec.rb, spec/library/set/inspect_spec.rb, spec/library/set/shared/inspect.rb, spec/library/set/to_s_spec.rb
=> Couple more `Set` methods

spec/core/struct/clone_spec.rb, spec/core/struct/length_spec.rb, spec/core/struct/shared/accessor.rb, spec/core/struct/shared/dup.rb, spec/core/struct/size_spec.rb, spec/core/struct/struct_spec.rb, spec/core/struct/to_a_spec.rb, src/struct.rb
A lot of other specs depend on this behaviour.
=> Include Enumerable in Struct

spec/command_line/syntax_error_spec.rb
It passes with the changes of #877
=> Import syntax_error_spec

include/natalie/args.hpp, src/object.cpp, test/natalie/send_test.rb
And fix some keyword issues with the Args class as well.
=> Fix crash with some incantations of send

lib/set.rb, spec/library/set/case_compare_spec.rb, spec/library/set/case_equality_spec.rb
#840 (case_compare_spec.rb and case_equality_spec.rb)
=> Implement Set#===

lib/set.rb, spec/library/set/classify_spec.rb, spec/library/set/eql_spec.rb, spec/library/set/equal_value_spec.rb, spec/library/set/fixtures/set_like.rb
#840 (classify_spec.rb, eql_spec.rb, and equal_value_spec.rb)
Equality methods implemented first as those are needed for the assertions in classify_spec.rb
=> Implement Set#classify

include/natalie/object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/array/flatten_spec.rb, spec/core/enumerable/fixtures/classes.rb, spec/core/kernel/respond_to_missing_spec.rb, src/object.cpp
=> Implement Kernel#respond_to_missing?

include/natalie/object.hpp, src/object.cpp
One of the turtles mentioned in #896.
=> Make find_method const

include/natalie/env.hpp, include/natalie/method.hpp, include/natalie/module_object.hpp, src/env.cpp, src/method.cpp, src/module_object.cpp
=> Constify the Method::call method

spec/core/float/coerce_spec.rb
This way it's easier to identify the issue
=> Add NATFIXME marker to commented tests in float/coerce_spec

include/natalie/rational_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/rational/rationalize_spec.rb, src/rational_object.cpp
Quick and easy version. I'm not really sure how what the algorithm for the version with argument is (and the specs of those have a fixme marker to show that they need reviewing, so I guess I'm not the only one). It does make two tests pass though.
=> Implement basic version of Rational#rationalize

lib/set.rb, spec/library/set/difference_spec.rb, spec/library/set/exclusion_spec.rb, spec/library/set/intersection_spec.rb, spec/library/set/minus_spec.rb, spec/library/set/plus_spec.rb, spec/library/set/union_spec.rb
This will check off a few boxes in #840, but I actually needed them to run a few tests with coercion of bitwise operators in  #825
=> Implement the bitwise like operators of Set

spec/library/zlib/deflate/deflate_spec.rb, spec/library/zlib/inflate/inflate_spec.rb
And mark all remaining tests with the issues
=> Import zlib specs with passing tests

include/natalie/object.hpp, spec/shared/kernel/object_id.rb, src/object.cpp
Replicate the behaviour of MRI.
=> Fix object_id output for Fixnums

include/natalie/string_object.hpp
=> Implement move semantics in constructor of StringObject

include/natalie/random_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/random/bytes_spec.rb, spec/library/zlib/deflate/deflate_spec.rb, src/random.rb, src/random_object.cpp
The tests had to be slightly altered because our Random implementation differs from MRI. This is an issue in the base object, and does not affect the code written in this change.
=> Implement Random#bytes

lib/set.rb, spec/library/set/enumerable/to_set_spec.rb
This one was not mentioned in  #840 (probably because it's a spec in a subdirectory)
=> Implement Enumerable#to_set

src/object.cpp
Check this once before use. The resolves a segfault in struct/new_spec.
=> Move nullptr check of m_ivars in Object::instance_variables

src/struct.rb, test/natalie/struct_test.rb
I was on an airplane with my laptop and ended up fiddling around with Struct. :-)
=> Some tweaks and additions to Struct

spec/core/struct/dig_spec.rb, src/struct.rb, test/natalie/struct_test.rb
And improve `Struct#[]` to check the argument before calling a method.
=> Implement Struct#dig

lib/natalie/repl/main.rb
=> Forward -r command line options to new repl

spec/core/array/pack/shared/float.rb
=> Enable specs "converts a Rational to a Float"

lib/set.rb
Don't pass the nil block to the enumerator.
=> Cleanup in Set#each

lib/set.rb, spec/library/set/delete_if_spec.rb
=> Implement Set#delete_if

lib/set.rb, spec/library/set/empty_spec.rb
Altough I hardly dare to call this implementing ;)
=> Implement Set#empty?

lib/strscan.rb, test/lib/strscan_test.rb
https://ruby-doc.org/core-3.1.2/StringScanner.html#method-i-captures
=> Implement StringScanner#captures

spec/core/enumerable/each_cons_spec.rb, src/enumerable.rb
Return self when a block is given.
=> Make Enumerable#each_cons spec compliant

spec/core/enumerable/each_slice_spec.rb, src/enumerable.rb
Return self when a block is given.
=> Make Enumerable#each_slice spec compliant

spec/core/integer/chr_spec.rb, spec/core/integer/fdiv_spec.rb, spec/core/integer/shared/exponent.rb, spec/core/integer/size_spec.rb
A few have been left as comments, they either take too long or abort the program
=> Convert NATFIXME comments to blocks in integer specs

lib/set.rb, spec/library/set/disjoint_spec.rb, spec/library/set/intersect_spec.rb
#840 (disjoint_spec.rb and intersect_spec.rb)
=> Implement Set#intersect? and Set#disjoint?

spec/core/array/flatten_spec.rb, spec/core/array/pack/shared/numeric_basic.rb, spec/core/array/pack/shared/string.rb, spec/core/array/pack/shared/unicode.rb, spec/core/array/shared/inspect.rb, spec/core/array/shared/join.rb, spec/core/array/shared/slice.rb
=> Convert NATFIXME comments to blocks in array specs

spec/core/basicobject/basicobject_spec.rb
=> Convert NATFIXME comments in BasicObject to blocks

spec/core/class/allocate_spec.rb
Remove the NATFIXME, this method has been implemented.
This resolves another item of #963
=> Sync class/allocate_spec

spec/core/dir/chdir_spec.rb, spec/core/dir/pwd_spec.rb, spec/core/dir/shared/pwd.rb
This resolves another item of #963
=> Convert NATFIXME comments in Dir to blocks 

spec/core/math/log2_spec.rb
=> Convert NATFIXME comments in Math to blocks

spec/library/zlib/deflate/deflate_spec.rb, spec/library/zlib/inflate/inflate_spec.rb
=> Convert NATFIXME comments in Zlib to blocks

include/natalie/args.hpp, include/natalie/file_object.hpp, src/args.cpp, src/array_object.cpp, src/fiber_object.cpp, src/hash_object.cpp, src/io_object.cpp, src/kernel_module.cpp, src/method.cpp, src/natalie.cpp, src/object.cpp, src/string_object.cpp, test/natalie/shell_test.rb
=> Use explicit ownership in Args class

spec/core/float/coerce_spec.rb, spec/core/float/round_spec.rb
=> Convert NATFIXME comments in Float to blocks

spec/core/process/egid_spec.rb, spec/core/process/euid_spec.rb
=> Convert NATFIXME comments in Process to blocks

spec/core/matchdata/dup_spec.rb, spec/core/matchdata/inspect_spec.rb, spec/core/matchdata/match_length_spec.rb, spec/core/matchdata/match_spec.rb, spec/core/matchdata/post_match_spec.rb, spec/core/matchdata/pre_match_spec.rb, spec/core/matchdata/string_spec.rb, spec/core/matchdata/to_a_spec.rb
=> Convert NATFIXME comments in MatchData to blocks

spec/core/string/bytes_spec.rb, spec/core/string/chomp_spec.rb, spec/core/string/chop_spec.rb, spec/core/string/clear_spec.rb, spec/core/string/downcase_spec.rb, spec/core/string/each_byte_spec.rb, spec/core/string/element_set_spec.rb, spec/core/string/gsub_spec.rb, spec/core/string/ljust_spec.rb, spec/core/string/rjust_spec.rb, spec/core/string/shared/concat.rb, spec/core/string/shared/dedup.rb, spec/core/string/shared/each_line.rb, spec/core/string/shared/eql.rb, spec/core/string/shared/length.rb, spec/core/string/shared/slice.rb, spec/core/string/shared/to_sym.rb, spec/core/string/split_spec.rb, spec/core/string/to_i_spec.rb, spec/core/string/unpack/p_spec.rb, spec/core/string/upcase_spec.rb, spec/core/string/valid_encoding_spec.rb, spec/shared/string/end_with.rb, spec/shared/string/start_with.rb, spec/shared/string/times.rb
This includes the spec/shared/string folder
That's two for #963
=> Convert NATFIXME comments in String to blocks

lib/ostruct.rb, spec/library/openstruct/delete_field_spec.rb, spec/library/openstruct/element_reference_spec.rb, spec/library/openstruct/element_set_spec.rb, spec/library/openstruct/equal_value_spec.rb, spec/library/openstruct/fixtures/classes.rb, spec/library/openstruct/frozen_spec.rb, spec/library/openstruct/initialize_spec.rb, spec/library/openstruct/inspect_spec.rb, spec/library/openstruct/marshal_dump_spec.rb, spec/library/openstruct/marshal_load_spec.rb, spec/library/openstruct/method_missing_spec.rb, spec/library/openstruct/new_spec.rb, spec/library/openstruct/shared/inspect.rb, spec/library/openstruct/to_h_spec.rb, spec/library/openstruct/to_s_spec.rb
Mostly because I wanted to test the work flow where you start with importing all the specs, add the bare minimum to make the specs run (which in this case was just adding a class `OpenStruct` with an empty constructor) and NATFIXME-ing all the failing specs out. It does give a pretty decent indication for possible starting points, but in this case that was pretty obvious to begin with. I think in general there are too many tests to start out with importing them all.
=> Implement OpenStruct

spec/core/random/bytes_spec.rb, spec/core/random/equal_value_spec.rb, spec/core/random/rand_spec.rb
=> Convert NATFIXME comments in Random to blocks

spec/core/regexp/encoding_spec.rb, spec/core/regexp/last_match_spec.rb, spec/core/regexp/match_spec.rb
=> Convert NATFIXME comments in Regexp to blocks

include/natalie/encoding_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/encoding/name_list_spec.rb, spec/core/encoding/names_spec.rb, src/encoding_object.cpp
Import names_spec as well, it had a dependency on name_list, and passes as well.
=> Implement Encoding.name_list

spec/core/enumerable/chunk_spec.rb, spec/core/enumerable/grep_spec.rb, spec/core/enumerable/grep_v_spec.rb, spec/core/enumerable/shared/collect.rb, spec/core/enumerable/sum_spec.rb
=> Convert NATFIXME comments in Enumerable to blocks

spec/core/enumerator/lazy/grep_spec.rb, spec/core/enumerator/rewind_spec.rb
#963
This includes the `lazy` subfolder as well
=> Convert NATFIXME comments in Enumerator to blocks

spec/library/rbconfig/rbconfig_spec.rb
=> Convert NATFIXME comments in RbConfig to blocks

spec/core/file/basename_spec.rb, spec/core/file/ftype_spec.rb, spec/core/file/new_spec.rb, spec/core/file/realpath_spec.rb, spec/core/file/socket_spec.rb
#963
@nanobowers Since you've been working on the File class lately, let me know if this clashes with anything you're working on and I can delay it for a bit.
=> Convert NATFIXME comments in File to blocks

include/natalie/object.hpp, include/natalie/value.hpp, lib/natalie/compiler/instructions/send_instruction.rb, src/object.cpp, src/value.cpp, test/natalie/method_visibility_test.rb, test/support/spec.rb
=> Fix protected/private method visibility

spec/core/module/deprecate_constant_spec.rb, spec/core/module/fixtures/classes.rb, spec/core/module/module_function_spec.rb
=> Convert NATFIXME comments in Module to blocks

spec/core/range/bsearch_spec.rb
=> Convert NATFIXME comments in Range to blocks

spec/command_line/dash_e_spec.rb, spec/core/kernel/shared/sprintf.rb, spec/core/kernel/shared/sprintf_encoding.rb, spec/core/string/modulo_spec.rb, src/string.rb
[#217] [#869]
We have to start somewhere!
I found it easier at this stage to use `xit` et al to disable broken specs. We have NATFIXME now for marking known-broken tests, but when it's hundreds of broken tests at the beginning of a project, it's easier to `%s/it/xit` 😄
=> Start work on String#%

lib/natalie/compiler/instructions/push_args_instruction.rb, lib/natalie/compiler/instructions/send_instruction.rb, lib/natalie/compiler/pass1.rb, test/natalie/argument_test.rb
=> Handle ... argument forwarding syntax

spec/library/openstruct/initialize_spec.rb, src/module_object.cpp, test/natalie/method_visibility_test.rb
=> Make initialize always private unless changed by name

include/natalie/env.hpp, include/natalie/macros.hpp, lib/natalie/compiler/instructions/push_block_instruction.rb, lib/natalie/compiler/pass1.rb, test/natalie/method_test.rb
=> Fix block_given? scoping issue

lib/set.rb, spec/library/set/filter_spec.rb, spec/library/set/select_spec.rb
=> Implement Set#select! and Set#filter!

spec/core/string/modulo_spec.rb, src/string.rb
=> Add positional argument support to String#%

lib/set.rb, spec/library/set/reject_spec.rb
=> Implement Set#reject!

spec/core/string/modulo_spec.rb, src/string.rb
...and fix a few argument handling issues.
#869
=> Add %p to String format

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/fixtures/classes.rb, spec/core/io/fixtures/lines.txt, spec/core/io/output_spec.rb, src/io_object.cpp, test/support/spec.rb
+ Add `IO#<<` and `core/io/output_spec.rb`
+ Fix `output` and `output_to_fd` test methods to accept both `$stderr` and `$stdout`
This is part of peeling the onion for #867.
=> Add IO append

lib/set.rb, spec/library/set/subset_spec.rb, spec/library/set/superset_spec.rb
=> Implement Set#subset? and Set#superset?

lib/zlib.cpp, lib/zlib.rb, spec/library/zlib/crc32_spec.rb
=> Implement Zlib crc32

lib/set.rb, spec/library/set/hash_spec.rb
=> Implement Set#hash

lib/set.rb, spec/library/set/proper_subset_spec.rb, spec/library/set/proper_superset_spec.rb
=> Implement Set#proper_subset? and Set#proper_superset?

lib/set.rb, spec/library/set/subtract_spec.rb
=> Implement Set#subtract

lib/natalie/compiler/instructions/inline_cpp_instruction.rb, test/natalie/require_test.rb
=> Fix error in generated source when cpp file is required not at top level

include/natalie/process_module.hpp, lib/etc.cpp, lib/etc.rb, spec/core/process/egid_spec.rb, spec/core/process/euid_spec.rb, spec/library/etc/endgrent_spec.rb, spec/library/etc/endpwent_spec.rb, spec/library/etc/getgrent_spec.rb, spec/library/etc/getgrnam_spec.rb, spec/library/etc/getlogin_spec.rb, spec/library/etc/getpwent_spec.rb, spec/library/etc/getpwnam_spec.rb, spec/library/etc/shared/windows.rb, spec/library/etc/struct_passwd_spec.rb, spec/library/etc/sysconf_spec.rb
Adds the `Etc` library module and several methods / constants.
=> Etc module

include/natalie/false_object.hpp, include/natalie/file_stat_object.hpp, include/natalie/integer_object.hpp, include/natalie/nil_object.hpp, include/natalie/true_object.hpp, include/natalie/unbound_method_object.hpp
Just cleaning up some clang-tidy warnings
=> Const tidy

lib/set.rb, spec/library/set/comparison_spec.rb
=> Implement Set#<=>

lib/set.rb, spec/library/set/flatten_merge_spec.rb, spec/library/set/flatten_spec.rb
=> Implement Set#flatten and Set#flatten!

lib/set.rb, spec/library/set/initialize_spec.rb
=> Make Set#initialize spec compliant

spec/core/exception/fixtures/common.rb, spec/core/exception/io_error_spec.rb, spec/core/exception/key_error_spec.rb, spec/core/exception/name_error_spec.rb, spec/core/exception/new_spec.rb, spec/core/exception/shared/new.rb, spec/core/exception/standard_error_spec.rb, spec/core/exception/status_spec.rb, spec/core/exception/success_spec.rb, src/exception.rb, src/io.rb
Enhancements of `KeyError`, `NameError` and `IO::` error-classes to pass specs.
Also added in some existing passing specs for `Exception`.
=> Exception updates

lib/set.rb, spec/library/set/initialize_clone_spec.rb
=> Implement Set#initialize_clone

lib/set.rb, spec/library/set/compare_by_identity_spec.rb
=> Implement Set#compare_by_identity and #compare_by_identity?

lib/natalie/compiler/binding_gen.rb
```C++
Value Array_pack_public_binding(Env *env, Value self_value, Args args, Block *block) {
auto kwargs = args.pop_keyword_hash();
auto kwarg_buffer = kwargs ? kwargs->remove(env, "buffer"_s) : nullptr;
args.ensure_argc_is(env, 1);
env->ensure_no_extra_keywords(kwargs);
ArrayObject *self = self_value->as_array();
auto return_value = self->pack(env, args.at(0, nullptr), kwarg_buffer);
if (!return_value) return NilObject::the();
return return_value;
}
Value Array_pop_public_binding(Env *env, Value self_value, Args args, Block *block) {
args.ensure_argc_between(env, 0, 1);
ArrayObject *self = self_value->as_array();
auto return_value = self->pop(env, args.at(0, nullptr));
if (!return_value) return NilObject::the();
return return_value;
}
Value Array_product_public_binding(Env *env, Value …
```
=> Clean up formatting of generated bindings

spec/core/string/modulo_spec.rb, src/kernel.rb
=> Add String#% support for float and precision

lib/natalie/compiler/pass1.rb, test/natalie/argument_test.rb
=> Fix argument forwarding for block arguments

include/natalie/hash_object.hpp, lib/natalie/compiler/instructions/create_array_instruction.rb, lib/natalie/compiler/instructions/create_hash_instruction.rb, test/natalie/array_test.rb, test/natalie/hash_test.rb
=> Fix panic when array or hash literal raises an error

spec/core/string/modulo_spec.rb, src/kernel.rb
=> Raise better errors with String#%

spec/core/file/dirname_spec.rb, src/file.rb
Some low hanging fruit, the upstream file has had some updates and two new/updated tests were failing.
=> Updates to File#dirname

spec/core/string/dup_spec.rb
One test fails, wrap that one in a NATFIXME
=> Import string/dup_spec

spec/core/enumerator/yielder/initialize_spec.rb, spec/core/enumerator/yielder/to_proc_spec.rb, spec/library/set/divide_spec.rb, src/enumerator.rb
This fixes the arity issue from #1107.
=> Fixes to Enumerator::Yielder

spec/core/kernel/String_spec.rb, spec/core/kernel/abort_spec.rb, spec/core/kernel/extend_spec.rb, spec/core/kernel/p_spec.rb
=> Convert NATFIXME markers in Kernel to blocks

spec/library/socket/basicsocket/recv_spec.rb, spec/library/socket/fixtures/classes.rb, spec/library/socket/socket/accept_spec.rb, spec/library/socket/tcpserver/accept_spec.rb, spec/library/socket/tcpsocket/initialize_spec.rb, spec/library/socket/tcpsocket/shared/new.rb
=> Convert NATFIXME markers in Socket to blocks

spec/language/constants_spec.rb, spec/language/singleton_class_spec.rb
This should be the last one for #963
=> Convert NATFIXME markers in language to blocks

Dockerfile, Rakefile, spec/core/time/inspect_spec.rb, spec/core/time/minus_spec.rb, spec/core/time/plus_spec.rb, spec/core/time/shared/gmt_offset.rb, spec/core/time/shared/inspect.rb, src/time_object.cpp
=> Convert NATFIXME markers in Time to blocks

lib/digest.rb, lib/digest/sha1.rb, lib/digest/sha2.rb, lib/openssl.cpp, lib/openssl.rb, spec/library/digest/sha1/shared/constants.rb, spec/library/digest/sha256/shared/constants.rb, spec/library/digest/sha384/shared/constants.rb, spec/library/digest/sha512/shared/constants.rb, spec/library/openssl/digest_spec.rb
This is good enough to make the specs pass, even though there are a couple more interfaces to these objects
=> First steps of OpenSSL::Digest

spec/core/file/realpath_spec.rb, src/file_object.cpp
This feature is required for a few tests of `Proc#source_location`
=> Fix File.realpath

src/env_object.cpp
This has been tested with the changes in https://github.com/ruby/spec/pull/1056. I did not include these updated specs in this change, since they have not yet been approved upstream so they're still subject to change.
When the change in ruby/spec is merged, I will either update this PR with the updated specs, or open a new PR with those spec changes, depending on whether this change is merged or not.
=> Fix missing to_str conversions in ENV

spec/core/string/modulo_spec.rb, src/kernel.rb, test/natalie/kernel_test.rb, test/natalie/string_test.rb
I wasn't happy with the readability of the old formatting code, and decided to rewrite it with a little state machine for the parser. I hope this turns out better!
#869
=> Start over with Kernel#sprintf

spec/core/array/flatten_spec.rb, spec/core/array/hash_spec.rb, spec/core/array/shared/clone.rb, spec/core/enumerable/first_spec.rb, spec/core/enumerable/sort_spec.rb, spec/core/enumerator/lazy/grep_v_spec.rb, spec/core/enumerator/lazy/shared/collect_concat.rb, spec/core/enumerator/lazy/shared/to_enum.rb, spec/core/file/basename_spec.rb, spec/core/float/exponent_spec.rb, spec/core/float/shared/quo.rb, spec/core/hash/hash_spec.rb, spec/core/hash/shared/store.rb, spec/core/hash/to_proc_spec.rb, spec/core/string/center_spec.rb, spec/language/alias_spec.rb, spec/language/block_spec.rb, spec/language/undef_spec.rb, spec/library/stringio/initialize_spec.rb, spec/library/stringscanner/clear_spec.rb, spec/library/stringscanner/element_reference_spec.rb, spec/library/stringscanner/empty_spec.rb, spec/library/stringscanner/getbyte_spec.rb, spec/library/stringscanner/peep_spec.rb, spec/library/stringscanner/restsize_spec.rb, spec/library/stringscanner/shared/peek.rb, spec/shared/enumerator/with_index.rb, test/natalie/string_test.rb
Left those that result in compile errors or other fatal issues.
=> Convert a number of xdescribe/xit to NATFIXME

spec/core/struct/eql_spec.rb, spec/core/struct/equal_value_spec.rb, spec/core/struct/shared/equal_value.rb, spec/library/etc/getpwuid_spec.rb, src/struct.rb
It does not work for recursive structures, we need some kind of storage to fix that (e.g. #1167)
=> Add equality operations for Struct

src/exception.rb
This code contained a todo about breaking, but that has been fixed since.
=> Simplifiy initialize of NoMethodError

lib/natalie/compiler/binding_gen.rb, spec/core/symbol/next_spec.rb, spec/core/symbol/shared/succ.rb, spec/core/symbol/succ_spec.rb
Which is an alias for Symbol#succ, with all the same issues.
=> Add Symbol#next

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/dir/shared/open.rb, spec/core/io/sysopen_spec.rb, src/io.rb, src/io_object.cpp
This is a dependency for a lot of IO tests.
=> Implement IO.sysopen

spec/core/enumerator/lazy/with_index_spec.rb, src/enumerator.rb
=> Add Enumerator::Lazy#with_index

include/natalie/file_object.hpp, spec/core/io/sysopen_spec.rb, src/file_object.cpp, src/io_object.cpp
This reduces a lot of duplication in the code.
=> Extract methods to convert Flags and Mode to posix values

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/readbyte_spec.rb, spec/core/io/readline_spec.rb, src/exception.rb, src/io_object.cpp
This includes the EOFError that IO#readbyte tried to raise
=> Implement IO#readbyte

src/io_object.cpp
`fstat` reads the file system access flags, not the access flags used for this IO object.
This fixes the issue mentioned in #1194
=> Fix is_writable checks in IoObject

include/natalie/backtrace.hpp, include/natalie/regexp_object.hpp, include/natalie/string_unpacker.hpp, lib/natalie/compiler.rb, lib/stringio.rb, lib/strscan.rb
Some of these are unclear, unactionable, or I just don't agree with them any more. 😄 
I'd like to stay on top of the FIXMEs so they don't get out of control.
=> Remove some FIXMEs

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/read_spec.rb, src/io_object.cpp
The added value within Natalie is pretty limited, since most of the time we just replace the String internals with a new buffer anyway.
=> Add buffer argument to IO#read

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/pread_spec.rb, src/io_object.cpp
It matches the extended specs of https://github.com/ruby/spec/pull/1079
=> Implement IO#pread

Rakefile, lib/natalie/compiler.rb
=> Use RbConfig to set SO_EXT and DL_EXT

include/natalie/module_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/module/attr_spec.rb, src/module_object.cpp
I would think this is part of the 'et al' of  #1237 :wink:
=> Make attr spec-compliant

spec/core/file/setuid_spec.rb
The code works, we still need a bit of yak shaving for the test code to work out of the box.
=> Import specs for File.setuid?

spec/core/file/ftype_spec.rb, spec/core/file/stat/ftype_spec.rb, spec/core/process/groups_spec.rb, spec/core/string/split_spec.rb, src/string_object.cpp
This resolves some issues in unrelated specs as well
=> Suppress trailing empty fields in String#split

lib/stringio.rb, spec/library/stringio/printf_spec.rb
This should get another 140 tests passing, which is not bad for a change of 4 lines of code
=> Implement StringIO#printf

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/printf_spec.rb, spec/core/io/sync_spec.rb, src/io_object.cpp
This resolves a discussion in #1260
=> Implement IO#sync and IO#sync=

spec/support/nightly_ruby_spec_runner.rb
This should get some more information than just "Crashed" in the stats page
=> Show more information in the nightly runner results

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/binwrite_spec.rb, spec/core/io/shared/binwrite.rb, src/io_object.cpp
Still needs support for keyword arguments, but it works in the general case.
=> Implement IO#binwrite

include/natalie/io_object.hpp, include/natalie/object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/select_spec.rb, src/io_object.cpp, src/object.cpp
This should be the final shaved yak before we can work on the `io_wait` example with unblocked Fibers (#1184)
=> Implement IO#select

include/natalie/integer_object.hpp, spec/core/integer/size_spec.rb, src/integer_object.cpp
Probably not the fastest implementation, but it works
=> Fix Integer#size for bignums

spec/command_line/dash_w_spec.rb, spec/command_line/fixtures/verbose.rb, spec/command_line/shared/verbose.rb
#1260 included everything to make them pass.
=> Import specs for command_line/dash_w

spec/command_line/error_message_spec.rb
They pass, probably did so for some time.
=> Import specs for command_line/error_message

lib/rbconfig.rb, test/natalie/rbconfig_test.rb
This should be the easiest way to fix the filename issue in  #1291
=> Add DLEXT and SOEXT to RbConfig::CONFIG

spec/core/kernel/sleep_spec.rb, src/kernel_module.cpp, test/natalie/kernel_test.rb
Make it spec compliant (except for the Thread stuff), and make the code a bit more generic. This last part should help with #1287.
=> Rework Kernel.sleep

lib/natalie/compiler/macro_expander.rb, test/natalie/load_path_test.rb, test/support/load_path/from_another_file/from_another_file_works.rb, test/support/load_path/long_name/long_name_works.rb
...also fixes a bug caused by untimely PR merges on my part.
=> Allow manipulating $LOAD_PATH from a required file

lib/natalie/compiler.rb, lib/natalie/compiler/arg_consumer.rb, lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/multiple_assignment.rb, lib/natalie/compiler/pass1.rb, lib/natalie/parser.rb, lib/natalie/repl/main.rb
Following from the work in #1301, this passes a few more Prism nodes directly to pass1.
=> Consume more Prism nodes directly

include/natalie/global_env.hpp, spec/language/constants_spec.rb, src/global_env.cpp, src/module_object.cpp, src/natalie.cpp, test/natalie/constant_test.rb, test/natalie/natfixme_test.rb, test/support/spec.rb
=> Fix bug resolving constant on mixin of a superclass

examples/about.rb, spec/core/array/pack/shared/basic.rb, spec/core/env/clone_spec.rb, spec/core/fiber/blocking_spec.rb, spec/core/fiber/storage_spec.rb, spec/core/integer/constants_spec.rb, spec/core/kernel/shared/sprintf.rb, spec/core/range/size_spec.rb, spec/core/string/modulo_spec.rb, spec/core/struct/new_spec.rb, spec/core/symbol/to_proc_spec.rb, spec/core/unboundmethod/shared/to_s.rb, spec/language/constants_spec.rb, src/natalie.cpp
This does not include any changes to the behaviour of the code, all failing tests have been wrapped in NATFIXME blocks.
=> Bump Ruby target version to 3.2

include/natalie/env_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/env/clone_spec.rb, spec/core/integer/constants_spec.rb, spec/core/kernel/shared/sprintf.rb, spec/core/range/size_spec.rb, spec/core/string/modulo_spec.rb, src/env_object.cpp, src/kernel.rb, src/natalie.cpp, src/range.rb
These were the low hanging fruit of #1322
=> Various Ruby 3.2 fixups

spec/core/data/constants_spec.rb, spec/core/data/define_spec.rb, spec/core/data/fixtures/classes.rb, spec/core/data/initialize_spec.rb, src/data.rb
This is a new class in Ruby 3.2 that is kind of an immutable struct. This implementation is very bare bones: we pass all the specs, but they are very bare bones as well: I can think of a ton of cases of the constructor we don't test, and I assume we would get extra methods like `each` as we do in `Struct`.
TLDR: This is good enough for the specs, we need some more upstream specs before we can extend this class.
=> Implement Data

lib/natalie/compiler/pass1.rb, lib/natalie/parser.rb
Just fixing a couple bugs that made working incrementally really hard. Whoops!
=> Prism node fixes

lib/natalie/compiler/instructions/inline_cpp_instruction.rb, lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb, lib/natalie/parser.rb
- `RegexpNode`
- `RedoNode`
- `RetryNode`
- `ReturnNode`
- `YieldNode`
- `CallNode` (partial)
=> More prism nodes

spec/language/singleton_class_spec.rb
The comment about time out is outdated.
=> Enable specs for constant on a singleton class

lib/natalie/compiler/arity.rb, lib/natalie/compiler/instructions/push_args_instruction.rb, lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb, lib/natalie/compiler/rescue.rb, lib/natalie/parser.rb, test/natalie/loop_test.rb, test/natalie/rescue_test.rb
- Handle more target types in rescue clause
- DefNode
- ForNode
- GlobalVariableReadNode, GlobalVariableAndWriteNode, GlobalVariableOrWriteNode, GlobalVariableOperatorWriteNode
- LocalVariableAndWriteNode, LocalVariableOrWriteNode, LocalVariableOperatorWriteNode
=> More prism nodes!

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/shared/binwrite.rb, src/io_object.cpp
Now with even more divergence between binwrite and write in the shared specs
=> Fix keyword arguments in IO.binwrite

lib/openssl.cpp
This removes a lot of boilerplate code.
=> Use ensure_no_missing_keywords in OpenSSL::KDF

lib/natalie.rb, lib/natalie/parser.rb
=> Self hosting work

.github/workflows/build.yml, Dockerfile, Rakefile, lib/ffi.cpp, lib/ffi.rb, lib/natalie/compiler.rb, test/natalie/ffi_test.rb, test/support/ffi_stubs.c
This should be _just enough_ for us to execute [prism/ffi.rb](https://github.com/ruby/prism/blob/main/lib/prism/ffi.rb), which we need for Natalie to be able to use Prism at runtime. ...which is one thing we need to get Natalie able to self-host again. 🤗
=> Add very basic FFI library

spec/core/matchdata/byteoffset_spec.rb, src/match_data_object.cpp
https://github.com/natalie-lang/natalie/pull/1359 contained a pretty basic implementation, these additions make it pass the tests.
=> Finish MatchData#byteoffset

lib/natalie/compiler/pass1.rb, lib/natalie/parser.rb, test/natalie/assign_test.rb, test/ruby/ruby_specs_test.rb
Continuing the march toward consuming Prism nodes directly...
=> Leave "call operator" and "call or" write nodes in place for pass1

include/natalie/match_data_object.hpp, lib/natalie/compiler/binding_gen.rb, lib/strscan.rb, spec/core/matchdata/element_reference_spec.rb, spec/core/matchdata/to_a_spec.rb, src/match_data_object.cpp
Support Range argument and second Integer argument
=> Finish Matchdata#[]

include/natalie/match_data_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/matchdata/eql_spec.rb, spec/core/matchdata/equal_value_spec.rb, spec/core/matchdata/shared/eql.rb, src/match_data_object.cpp
Marking this as a draft for now. The code works, but it's going to cause merge conflicts with  #1368, so I will rebase it once that change is merged.
=> Implement MatchData#== and MatchData#eql?

include/natalie/match_data_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/matchdata/values_at_spec.rb, src/match_data_object.cpp
The code was pretty nice and concise before all the exceptional Range values started
=> Implement MatchData#values_at

include/natalie/match_data_object.hpp, include/natalie/regexp_object.hpp, spec/core/file/fnmatch_spec.rb, spec/core/file/shared/fnmatch.rb, src/file.rb, src/match_data_object.cpp, src/regexp_object.cpp, src/string_object.cpp, test/natalie/regexp_test.rb
~I don't know if this is a stupid way to do this (using regexps). After writing the code I learned about `fnmatch(3)` which maybe does this for us? Though I'm not sure it handles `**` ... I will do a bit more research before I work on this further!~
Indeed this was dumb. But I'm shipping it, for now at least.
=> Add a basic, incomplete, kinda-wrong implementation of File.fnmatch

lib/natalie/compiler/args.rb, lib/natalie/compiler/pass1.rb, test/natalie/argument_test.rb
I was going to implement `Method#parameters` and in so doing I found and fixed these bugs. Then I decided that `Method#parameters` is a beast of a task because we would have to start tracking that information somewhere. And I just don't have the energy right now.
Anyway, here are some fixes regardless.
=> Method parameter fixes

src/natalie.cpp
This one is being used in a lot of specs, it should help with a few crashes in the nightly tests.
=> Add $$ variable

spec/core/io/each_line_spec.rb, spec/core/io/shared/each.rb, src/io.rb
=> Fix return value of IO#each_line

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/seek_spec.rb, spec/core/io/sysseek_spec.rb, src/io_object.cpp
The changes in `IO#seek` are mostly related to the read buffer.
=> Make IO#seek spec compliant and implement IO#sysseek

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/casecmp_spec.rb, spec/core/string/count_spec.rb, src/string_object.cpp
This is probably not complete (for example it does not respect escape characters yet), but it's better than nothing and it passes all the specs!
[#217]
=> Implement String#count

spec/core/file/new_spec.rb
It works fine on my system, the comment mentions MacOS, so let's see if the CI agrees.
=> Enable test in file/new_spec

.github/workflows/build.yml, Rakefile
Would be nice for this to not break again :-)
=> Build self-hosted compiler as part of CI

lib/natalie/compiler/pass1.rb
Alphabetization is hard apparently 😄
=> Compiler::Pass1: Remove dead code, alphabetize node methods

lib/openssl.cpp, lib/openssl.rb, test/natalie/openssl_digest/shared/update.rb, test/natalie/openssl_test.rb
This also adds string coercion to the OpenSSL::Digest classes
=> Implement OpenSSL.secure_compare

src/module_object.cpp, test/natalie/class_test.rb
=> Don't reopen a class from the namespace of the superclass

lib/openssl.cpp, lib/openssl.rb, spec/library/openssl/cipher_spec.rb, test/natalie/openssl_cipher/block_size_test.rb, test/natalie/openssl_cipher/ciphers_test.rb, test/natalie/openssl_cipher/decrypt_test.rb, test/natalie/openssl_cipher/encrypt_test.rb, test/natalie/openssl_cipher/final_test.rb, test/natalie/openssl_cipher/iv_len_test.rb, test/natalie/openssl_cipher/iv_test.rb, test/natalie/openssl_cipher/key_len_test.rb, test/natalie/openssl_cipher/key_test.rb, test/natalie/openssl_cipher/new_test.rb, test/natalie/openssl_cipher/random_iv_test.rb, test/natalie/openssl_cipher/random_key_test.rb, test/natalie/openssl_cipher/update_test.rb
This is going to be a long term project. The code itself is probably not that sophisticated (validate Ruby type, convert to C type, pass data to OpenSSL function), but all the specs need to be written as well.
Documentation for the gem: https://www.rubydoc.info/stdlib/openssl/OpenSSL/Cipher
=> Implement OpenSSL::Cipher

include/natalie/args.hpp, include/natalie/block.hpp, src/args.cpp, src/natalie.cpp, src/object.cpp, test/natalie/super_test.rb, test/natalie/yield_test.rb
`super(**{})` and `yield(**{})`.
=> Fix empty keyword args on super and yield

spec/core/io/close_spec.rb
About half of them actually work, the other half has other dependency issues and is disabled for now.
=> Import specs for IO#close

spec/core/string/to_i_spec.rb, src/string_object.cpp
=> Make String#to_i spec-compliant

spec/core/complex/exponent_spec.rb, src/complex.rb
Finishes #608
I am not a math guy, so this was a struggle for me. But it does pass the specs and it allows us to close a big issue!
=> Implement Complex#**

lib/natalie/compiler/instructions/const_find_instruction.rb, lib/natalie/compiler/pass1.rb, test/natalie/backtrace_test.rb, test/natalie/constant_test.rb
=> Raise an error for unknown const, even if unused

spec/core/float/exponent_spec.rb, spec/core/integer/shared/exponent.rb, spec/shared/rational/exponent.rb, src/complex.rb, src/float_object.cpp, src/integer_object.cpp
The changes from #1438 made this one pretty easy. It did require a small fix to the logic in `complex.rb`, otherwise this code would end up with an assertion error:
```ruby
Complex(-8.0) ** Rational(1, 3)
```
=> FIx negative number raised to fractional power

include/natalie/process_module.hpp, include/natalie/regexp_object.hpp, lib/openssl.cpp, lib/socket.cpp, src/array_object.cpp, src/array_packer/packer.cpp, src/encoding_object.cpp, src/env_object.cpp, src/hash_object.cpp, src/io_object.cpp, src/ioutil.cpp, src/kernel_module.cpp, src/match_data_object.cpp, src/object.cpp, src/random_object.cpp, src/string_object.cpp, src/time_object.cpp
And reduce a whole lot of code duplication.
=> Normalize type coercion

lib/etc.cpp, lib/etc.rb, spec/library/etc/confstr_spec.rb
And shave a few yaks along the way.
=> Implement Etc.confstr

lib/digest.rb, spec/library/digest/hexencode_spec.rb
Not sure why you would want to use this though, but this was just too easy to let it go.
=> Implement Digest.hexencode

Rakefile
Our test runner gets stuck in an infinite loop somewhere, so let's run the examples for now...
=> CI: Run the examples with self-hosted compiler

include/natalie/ioutil.hpp, src/file_object.cpp, src/io_object.cpp, src/ioutil.cpp
This closes #1247 
This is one of those chores that had to be done some day, and it was getting a bit into the way of #1395.
=> Convert flags_struct into a real object

lib/openssl.cpp, lib/openssl.rb, test/natalie/openssl_test.rb
This might take a while before we get there, but I want to get the following code to work:
```ruby
TCPSocket.open('natalie-lang.org', 443) do |socket|
ssl_context = OpenSSL::SSL::SSLContext.new()
ssl_socket = OpenSSL::SSL::SSLSocket.new(socket, ssl_context)
ssl_socket.connect
ssl_socket.write("GET / HTTP/1.1\r\nHost: natalie-lang.org\r\nConnection: close\r\n\r\n")
p ssl_socket.read
ssl_socket.close
end
```
Fun fact: I have never used the SSL sockets directly (normally you would use something like net-http), so I had to look up how to do this.
Some documentation links:
* https://wiki.openssl.org/index.php/SSL/TLS_Client
* https://wiki.openssl.org/index.php/Simple_TLS_Server (shows the socket more clearly)
* https://www.rubydoc.info/stdlib/openssl/OpenSSL/SSL/SSLContext
* …
=> OpenSSL sockets

lib/yaml.cpp, lib/yaml.rb, spec/library/yaml/dump_spec.rb, spec/library/yaml/fixtures/common.rb, test/support/spec.rb
This is a very coarse start for the YAML module. It can dump strings, and that's about it.
=> Start with YAML.dump

lib/date.rb, spec/library/date/parse_spec.rb, spec/library/date/shared/parse.rb, spec/library/date/shared/parse_eu.rb, spec/library/date/shared/parse_us.rb, spec/library/yaml/to_yaml_spec.rb
It can handle most numeric based values.
=> First version of Date.parse

spec/library/date/shared/parse.rb, spec/library/date/shared/parse_eu.rb, spec/library/date/shared/parse_us.rb
There was a lot of confusion about the actual format in the test descriptions.
=> Refresh specs for Date.parse

spec/library/yaml/dump_spec.rb, spec/library/yaml/fixtures/common.rb, spec/library/yaml/to_yaml_spec.rb
=> Refresh specs for YAML

Gemfile, Gemfile.lock
This commit has been cherry-picked from #1471, it's pretty unrelated to the actual change in that PR.
=> Add rubocop to Gemfile

include/natalie/string_object.hpp, spec/core/string/comparison_spec.rb, src/string_object.cpp
Add spec for String#<=> and fix broken tests
Issue: #217
=> Add specs and fix String#<=>

lib/natalie/compiler/flags.rb, test/natalie/string_test.rb
=> Disable trigraph warnings

lib/yaml.cpp, spec/library/yaml/to_yaml_spec.rb
Once again: a lot of trial and error until it yields the desired output. But at least this can act as a blueprint for the remaining items.
=> Support Range argument in YAML.dump

lib/yaml.cpp, spec/library/yaml/dump_spec.rb, spec/library/yaml/to_yaml_spec.rb, test/natalie/yaml_test.rb, test/support/spec.rb
We're now 99% compatible with the output of MRI.
=> Implement missing types in YAML.dump

lib/openssl.cpp, lib/openssl.rb, spec/library/digest/md5/digest_bang_spec.rb, spec/library/digest/md5/digest_spec.rb, spec/library/digest/md5/hexdigest_bang_spec.rb, spec/library/digest/md5/hexdigest_spec.rb, spec/library/digest/sha2/hexdigest_spec.rb, spec/library/digest/sha256/digest_bang_spec.rb, spec/library/digest/sha256/digest_spec.rb, spec/library/digest/sha256/hexdigest_bang_spec.rb, spec/library/digest/sha256/hexdigest_spec.rb, spec/library/digest/sha384/digest_bang_spec.rb, spec/library/digest/sha384/digest_spec.rb, spec/library/digest/sha384/hexdigest_bang_spec.rb, spec/library/digest/sha384/hexdigest_spec.rb, spec/library/digest/sha512/digest_bang_spec.rb, spec/library/digest/sha512/digest_spec.rb, spec/library/digest/sha512/hexdigest_bang_spec.rb, spec/library/digest/sha512/hexdigest_spec.rb
Mostly related to when to reset the digest object, described at https://docs.ruby-lang.org/en/master/Digest/Instance.html#method-i-digest
=> Some improvements to Digest

.rubocop.yml, lib/base64.rb, lib/bigdecimal.rb, lib/csv.rb, lib/date.rb, lib/etc.rb, lib/fiddle.rb, lib/natalie.rb, lib/natalie/compiler.rb, lib/natalie/parser.rb, lib/observer.rb, lib/openssl.rb, lib/optparse.rb, lib/pathname.rb
These are just some Rubocop warnings I fixed by hand following discussion in #1508. I don't necessarily want to run Rubocop auto-correct until we're sure the rules make sense. You can see in this PR I changed some settings and disabled some rules I don't think make sense for our project.
=> Fix some rubocop warnings and disable some warnings

.github/workflows/lint.yml, .github/workflows/run_all_specs.yml, .github/workflows/self_hosted_tests.yml
Which will probably not fix the issue in #1472, it's the latest linux runner but still over a year old.
=> Use Ubuntu 22.04 in actions

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/rational/to_r_spec.rb, spec/core/string/to_r_spec.rb, spec/shared/rational/Rational.rb, src/kernel_module.cpp, src/string_object.cpp, src/time_object.cpp
=> Implement String#to_r

include/natalie/time_object.hpp, spec/core/time/shared/inspect.rb, src/time_object.cpp
The actual issue is deeper, but fixing that will take more time.
I looked into this hoping this would fix the YAML issue of Time objects, but that one is still broken.
=> Fix timezones in time stringification

src/exception.rb
...because \<eye-twitch\> that was bothering me.
=> Reorder and reindent exceptions

include/natalie/module_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/module/const_defined_spec.rb, spec/core/module/const_get_spec.rb, spec/core/module/fixtures/constant_unicode.rb, spec/core/module/fixtures/constants_autoload.rb, spec/core/module/fixtures/constants_autoload_a.rb, spec/core/module/fixtures/constants_autoload_b.rb, spec/core/module/fixtures/constants_autoload_c.rb, spec/core/module/fixtures/constants_autoload_d.rb, src/module_object.cpp
Add the `inherited` argument. Two more yaks for the URI gem.
=> Improve Module#const_defined? and Module#const_get

include/natalie/regexp_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/regexp/union_spec.rb, src/regexp_object.cpp
Another URI yak. I've just ignored the whole idea of character encodings for now, so we're skipping a lot of tests.
=> Implement Regexp.union

README.md, lib/ipaddr.rb, spec/library/ipaddr/hton_spec.rb, spec/library/ipaddr/ipv4_conversion_spec.rb, spec/library/ipaddr/new_spec.rb, spec/library/ipaddr/operator_spec.rb, spec/library/ipaddr/reverse_spec.rb, spec/library/ipaddr/to_s_spec.rb
This is a direct copy from the source, it now works with Natalie. The source file has been added to the copyright list (similar to `pp.rb`)
=> Import ipaddr gem

test/natalie/fixtures/hash_hash_key_shorthand_new.rb, test/natalie/fixtures/hash_hash_key_shorthand_old.rb, test/natalie/fixtures/method_hash_key_shorthand_new.rb, test/natalie/fixtures/method_hash_key_shorthand_old.rb, test/natalie/hash_test.rb, test/natalie/method_test.rb
This is a bit more self contained than all the fixture files.
=> Use eval in the hash key shorthand tests

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, src/string_object.cpp, test/natalie/string_test.rb
I need this for my Advent of Code day 1 solution.
=> Implement a basic version of String#rindex

include/natalie/string_object.hpp, spec/core/string/gsub_spec.rb, spec/core/string/sub_spec.rb, src/string_object.cpp
Yet another yak for the URI gem
=> Support Hash replacement in String#(g)sub

include/natalie/random_object.hpp, spec/core/kernel/srand_spec.rb
Fix argument conversion via to_int
=> Improve Kernel#srand

src/match_data_object.cpp, test/natalie/matchdata_test.rb
=> Fix MatchData#[] with Range argument and nil values in the matches

lib/natalie/compiler/instructions/break_out_instruction.rb, lib/natalie/compiler/pass1.rb, test/natalie/break_test.rb
=> Fix `break` to handle stack values consistently

src/regexp_object.cpp, test/natalie/regexp_test.rb
This should be the last yak for the URI gem (I'm going to ignore #1579 for now, that issue is only related to the kind of weird/irrelevant specs of this module). It does need some more specs though.
=> Stringification of Regexp

include/natalie/thread_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/close_spec.rb, spec/core/io/copy_stream_spec.rb, spec/core/io/gets_spec.rb, spec/core/io/read_spec.rb, spec/core/io/select_spec.rb, spec/core/mutex/sleep_spec.rb, spec/core/mutex/unlock_spec.rb, spec/core/thread/alive_spec.rb, spec/core/thread/current_spec.rb, spec/core/thread/run_spec.rb, spec/core/thread/shared/wakeup.rb, spec/core/thread/stop_spec.rb, src/io_object.cpp, src/thread_object.cpp, test/ruby/ruby_specs_test.rb
This adds:
- `Thread.stop`
- `Thread#stop?`
- `Thread#run`
...and a bunch of small fixes w.r.t. thread status and dying threads.
This also fixes a bug with non-blocking pipes on macos.
There's still more to fix, esp. with sleeping mutexes, but it's good progress.
=> Do some work on Thread.stop, Thread#alive?, Thread#stop? etc.

include/natalie/regexp_object.hpp, spec/core/string/match_spec.rb, src/regexp_object.cpp, test/natalie/regexp_test.rb
=> Support \u{...} unicode escapes in regexps

lib/uri/rfc3986_parser.rb
Hyphens are now supported in Regexp capture groups.
=> Update imported uri gem

spec/language/array_spec.rb
These were removed by mistake in #1582.
=> Put back specs I accidentally deleted

.github/workflows/build.yml, .github/workflows/self_hosted_tests.yml, Rakefile
This is still too slow to run in regular CI ... it would make our build take 2+ hours. But I'd like to see what is still failing, fix those things, and then work on the performance of the self-hosted compiler.
=> Run full test suite with self-hosted compiler nightly

include/natalie/thread_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/thread/new_spec.rb, src/thread_object.cpp
This is a three layer deep yak to get the `net` gem to work.
=> Improve Thread.new

README.md, examples/linenoise.rb, lib/linenoise.cpp, lib/linenoise.hpp
I couldn't figure out how to test this, so I just made a working example. 🤷‍♂️ 
I spent a bunch of time trying to figure out how to use the Ruby [PTY](https://ruby-doc.org/core-3.1.2/PTY.html) lib to control the prompt, but I couldn't get it to work.
=> Add a Linenoise library

src/thread/mutex_object.cpp
Sometimes I forget about Defer and fall back to using try/catch, which is a little more error prone, as we saw in #1596.
=> Simplify MutexObject::synchronize using Defer

examples/linenoise.rb, lib/linenoise.cpp, lib/linenoise/linenoise.c, lib/linenoise/linenoise.h
I just hacked this in. Seems to work ok 🤷‍♂️
=> Add Linenoise highlight support

lib/natalie/compiler/binding_gen.rb, spec/core/thread/main_spec.rb
Which was just a missing binding, the C++ method was already there.
=> Add Thread.main

lib/ffi.cpp, lib/ffi.rb, test/natalie/ffi_test.rb, test/support/ffi_stubs.c
This adds some fixes for address and null, and fixes the autorelease handling for allocated memory.
=> Fix address and null handling with FFI library

spec/core/thread/fetch_spec.rb, test/natalie/thread_test.rb
Remove the local tests, they are not needed anymore.
=> Refresh specs for Thread#fetch

.github/workflows/build.yml, .github/workflows/format.yml, .github/workflows/lint.yml, .github/workflows/run_all_specs.yml, .github/workflows/self_hosted_tests.yml, Rakefile, spec/support/nightly_ruby_spec_runner.rb
=> Update nightly all-specs runner to use Ubuntu 22.04 and to run in Docker

include/natalie/process_module.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/process/setsid_spec.rb
Once again I'm like 15 layers deep into an attempt to implement something :laughing:
=> Implement Process.setsid

spec/core/exception/cause_spec.rb, src/env.cpp, src/kernel_module.cpp
Just move the code around a bit and we've fixed another issue ;)
=> Add cause object to exceptions without explicit raise

test/support/version.rb
This file contained two NATFIXME markers for issues that have been resolved.
=> Update SpecVersion class

include/natalie/kernel_module.hpp, lib/natalie/compiler/binding_gen.rb, spec/shared/kernel/raise.rb, src/kernel_module.cpp
The only remaining issue is the backtrace. I'm not planning to look into that right now, so I guess once this is merged we should be able to start working on  #1633.
=> More fixes to Kernel.raise

include/natalie.hpp, include/natalie/backtrace.hpp, include/natalie/forward.hpp, include/natalie/kernel_module.hpp, include/natalie/object.hpp, include/natalie/object_type.hpp, include/natalie/thread/backtrace/location_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/kernel/caller_locations_spec.rb, spec/core/thread/backtrace/location/fixtures/classes.rb, spec/core/thread/backtrace/location/inspect_spec.rb, spec/core/thread/backtrace/location/lineno_spec.rb, spec/core/thread/backtrace/location/to_s_spec.rb, spec/core/thread/current_spec.rb, src/backtrace.cpp, src/kernel_module.cpp, src/natalie.cpp, src/object.cpp, src/thread/backtrace/location_object.cpp
This includes the new class `Thread::Backtrace::Location`
=> Implement Kernel#caller_locations

spec/core/exception/signal_exception_spec.rb, spec/core/process/status/termsig_spec.rb, src/process_module.cpp
=> Update Process.kill to raise SignalException for own pid

spec/core/process/status/to_i_spec.rb
They now pass with the addition of SignalException
=> Import specs for Process::Status#to_i

include/natalie/exception_object.hpp, spec/core/exception/backtrace_locations_spec.rb, src/exception_object.cpp
=> Save Exception#backtrace_locations as member variable

spec/core/enumerator/produce_spec.rb, src/enumerator.rb
Why have I never heard of this method before? This looks like an amazing generator.
=> Implement Enumerator.produce

spec/core/kernel/fail_spec.rb, src/exception_object.cpp
Reverts natalie-lang/natalie#1702
I got trigger happy with #1699 and merged with a failing test in `spec/core/thread/raise_spec.rb`.
=> Support #exception in Kernel.fail (attempt 2)

spec/core/kernel/putc_spec.rb, src/kernel.rb, test/support/formatters/default_formatter.rb
This includes a change to the formatter that might resolve some other issues with IO in the tests.
=> Implement Kernel.putc

spec/library/socket/basicsocket/setsockopt_spec.rb
=> Enable UNIX socket specs in setsockopt_spec

lib/socket.cpp, spec/library/socket/fixtures/classes.rb
This should fix a number of crashes in the spec runner.
=> Support Socket#bind for IPv6 sockets

spec/library/socket/shared/pack_sockaddr.rb
This way we get a notification whenever the issue is fixed.
=> Change NATFIXME comment in pack_sockaddr specs to block

lib/socket.cpp, test/natalie/socket_test.rb
By passing the correct keyword argument into `IO#initialize`
=> Include path in inspect output of UNIXServer

lib/socket.cpp, lib/socket.rb, spec/library/socket/shared/partially_closable_sockets.rb, spec/library/socket/unixsocket/pair_spec.rb, spec/library/socket/unixsocket/socketpair_spec.rb
This one has a few hidden dependencies in the specs, I guess this will reduce the number of crashes in the nightly test runner.
=> Implement UNIXSocket.pair

spec/library/socket/socket/socket_spec.rb
This one had a dependency on UDPSocket, and passes
=> Import socket spec

lib/socket.cpp, test/natalie/socket_test.rb
A stripped version of  #1718, let's see if the CI passes or do we need to strip even more?
=> Improvements to UNIX sockets in getsockname

lib/socket.cpp, lib/socket.rb, spec/library/socket/unixserver/listen_spec.rb
It's pretty much the same change as  #1743
=> Implement UNIXServer#listen

.github/workflows/build.yml
...and upgrade host to Ruby 3.3
=> Fix intermittent failure with macOS CI build

lib/tempfile.cpp, lib/tempfile.rb, spec/core/io/copy_stream_spec.rb, spec/library/tempfile/_close_spec.rb, spec/library/tempfile/close_spec.rb, spec/library/tempfile/delete_spec.rb, spec/library/tempfile/initialize_spec.rb, spec/library/tempfile/path_spec.rb, spec/library/tempfile/shared/unlink.rb, spec/library/tempfile/unlink_spec.rb, test/natalie/tempfile_test.rb
This should be just enough to fix the crash in `core/io/copy_stream_spec`.
=> Implement some methods of Tempfile

src/thread_object.cpp
Should fix at least one timeout issue in CI.
=> Wait for threads to resume before continuing

lib/tempfile.cpp, lib/tempfile.rb, spec/library/tempfile/initialize_spec.rb, test/natalie/tempfile_test.rb
This one is going to include a lot of extra specs, the upstream ones are kind of lacking here (they cover the base cases, but that's about it).
=> Improve Tempfile#initialize

include/natalie/thread_object.hpp, src/thread_object.cpp
Make the code more C++ and less C.
=> Replace pthread_cond_t with std::condition_variable

include/natalie/global_env.hpp, include/natalie/global_variable_info.hpp, spec/language/predefined_spec.rb, src/global_env.cpp
And provide a framework to check this.
=> Mark $" as read only

lib/natalie/compiler/pass1.rb, spec/core/string/encoding_spec.rb, spec/core/string/fixtures/iso-8859-9-encoding.rb, spec/language/encoding_spec.rb, spec/language/fixtures/coding_us_ascii.rb, spec/language/fixtures/coding_utf_8.rb
This resolves two more compilation errors in the specs
=> Add support for __ENCODING__

lib/natalie/compiler/instructions/define_class_instruction.rb, spec/language/class_spec.rb
This resolves the assertion failure in `language/class_spec.rb`.
=> Add superclass type check when creating a new class

lib/yaml.cpp, src/kernel_module.cpp, src/object.cpp, src/time_object.cpp
The result is a bit more readable, and it removes a lot of typecasting back to values.
=> More use of bool_obj method

spec/language/predefined_spec.rb, src/natalie.cpp
Source: https://docs.ruby-lang.org/en/3.3/globals_rdoc.html
=> Add some additional global aliases

lib/natalie/compiler/instructions/global_variable_get_instruction.rb
I guess I missed this one in  #1857.
=> Remove exception for $~ in the compiler

include/natalie/kernel_module.hpp, lib/natalie/compiler/binding_gen.rb, lib/natalie/compiler/pass1.rb, src/kernel_module.cpp
And remove the workaround in the compiler to rewrite this.
=> Implement Kernel#!~

lib/digest/bubblebabble.rb, spec/library/digest/bubblebabble_spec.rb
As opposed to  #1851, this is just the algorithm implemented in Ruby. I want to keep the other branch as a nice experiment, but I think this is the correct way to implement it.
=> Implement Digest.bubblebabble

lib/natalie/compiler/pass1.rb
* Remove additional whitespace
* Remove unused variable
=> Cleanup of encoding_for_string_node

examples/evaluate.rb
This is a terrible alternative to `eval`, but it's fun to see this being possible.
=> Add example script to dynamically evaluate code

include/natalie/hash_object.hpp, spec/core/hash/ruby2_keywords_hash_spec.rb, src/hash_object.cpp, test/natalie/hash_test.rb
=> Fixes to Hash#dup

include/natalie/kernel_module.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/class/initialize_spec.rb, spec/core/kernel/private_methods_spec.rb, spec/core/module/remove_const_spec.rb, src/kernel_module.cpp, test/support/spec.rb
Which includes an implementation of `Kernel#private_methods`
=> Implement have_private_method spec expectation

include/natalie/thread/backtrace/location_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/exception/backtrace_locations_spec.rb, spec/core/kernel/warn_spec.rb, spec/core/thread/backtrace/location/fixtures/main.rb, spec/core/thread/backtrace/location/path_spec.rb, src/kernel.rb
And implement `Thread::Backtrace::Location#path` as well, because yaks need shaving.
=> Add uplevel argument to Kernel.warn

README.md, lib/find.rb, spec/library/find/find_spec.rb, spec/library/find/fixtures/common.rb, spec/library/find/prune_spec.rb
=> Import find gem

Rakefile, lib/set.rb, spec/core/enumerable/fixtures/classes.rb, spec/core/enumerable/to_set_spec.rb
=> Explicitly require set in Enumerable specs

spec/core/mutex/sleep_spec.rb, spec/core/thread/report_on_exception_spec.rb, src/thread/mutex_object.cpp
It still fails a few very specific specs, but this resolves the timeout. This is the last step I needed to implement a `Queue` class.
=> Fix Mutex#sleep

Rakefile
This is a completely blind attempt at a mitigation for  #1893.
=> Run asan tests on Debian Bullseye

spec/core/kernel/printf_spec.rb, spec/core/kernel/putc_spec.rb, spec/core/kernel/warn_spec.rb, src/kernel.rb
This replicates the way the C++ bindings for this file are generated, and resolves all the "is a private method" issues.
=> Sprinkle module_function into kernel.rb

spec/library/English/English_spec.rb, src/process.rb
Support Process::Status arguments
=> Fix Process::Status#==

include/natalie.hpp, include/natalie/forward.hpp, include/natalie/object.hpp, include/natalie/object_type.hpp, include/natalie/thread_group_object.hpp, include/natalie/thread_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/thread/group_spec.rb, spec/core/thread/list_spec.rb, spec/core/threadgroup/add_spec.rb, spec/core/threadgroup/default_spec.rb, spec/core/threadgroup/enclose_spec.rb, spec/core/threadgroup/enclosed_spec.rb, spec/core/threadgroup/list_spec.rb, src/natalie.cpp, src/object.cpp, src/thread_group_object.cpp, src/thread_object.cpp
This has a dependency on Queue (#1889), so marking it as a draft for now.
=> Implement ThreadGroup

lib/natalie/compiler/instructions/send_instruction.rb
Ruby has a method `Integer#[]` to access the single bytes of an integer, which means we can reuse the code to split the flags back into separate values.
=> Bytecode VM: Pack 4 boolean flags for send in a single byte

lib/natalie/compiler/bytecode_loader.rb, lib/natalie/compiler/instructions/dup_instruction.rb, lib/natalie/compiler/instructions/while_body_instruction.rb, lib/natalie/compiler/instructions/while_instruction.rb, test/bytecode/while_test.rb
We can now run `sum-simple.rb` and `sum-block.rb` of https://ruby-compilers.com/examples/
=> Bytecode VM: Support while loops

bin/natalie
This had been added accidentally in  #1920
=> Bytecode VM: Remove debug raise line

lib/openssl.cpp, lib/openssl.rb, spec/library/openssl/x509/store/verify_spec.rb, test/natalie/openssl_test.rb
That was a ridiculous amount of code to get 2 specs to pass :wink:
=> Implement OpenSSL::X509::Store#verify

lib/socket.cpp, lib/socket.rb, spec/library/socket/unixserver/sysaccept_spec.rb
That should wrap up the UNIXServer specs.
=> Implement UNIXServer#sysaccept

Rakefile
This is the development case related to  #1893
=> Run asan tests on Debian Bookworm

lib/socket.cpp, spec/library/socket/basicsocket/read_spec.rb, spec/library/socket/basicsocket/send_spec.rb, spec/library/socket/unixsocket/recvfrom_spec.rb, test/natalie/socket_test.rb
This should resolve a lot of "Destination address required" errors in the nightly runs, and unblock the `read_nonblock` and `recv_nonblock` specs.
=> Fix BasicSocket#send

lib/socket.cpp
Use IoObject::set_nonblock instead.
=> Remove fcntl calls from socket.cpp

spec/library/socket/addrinfo/afamily_spec.rb, spec/library/socket/shared/partially_closable_sockets.rb, spec/library/socket/tcpsocket/open_spec.rb, spec/library/socket/tcpsocket/partially_closable_spec.rb, spec/library/socket/tcpsocket/recv_nonblock_spec.rb, spec/library/socket/tcpsocket/recv_spec.rb, spec/library/socket/unixsocket/partially_closable_spec.rb
This list has been generated with the following steps:
* Copy all files for this folder from ruby-specs
* Revert changes in the folder, so only new files are left
* Run every spec, git add if it passes, rm if it fails or timeouts
Okay, I cheated a little bit by updating the shared specs for partially closable.
=> Import passing specs for Socket

lib/socket.cpp, lib/socket.rb, spec/library/socket/tcpserver/accept_nonblock_spec.rb, spec/library/socket/tcpserver/sysaccept_spec.rb
This is mostly just moving some code around to make it a bit more generic.
=> Implement TCPServer#accept_nonblock and TCPServer#sysaccept

lib/natalie/compiler/instructions/array_concat_instruction.rb, lib/natalie/compiler/instructions/const_set_instruction.rb, lib/natalie/compiler/instructions/define_class_instruction.rb, lib/natalie/compiler/instructions/global_variable_get_instruction.rb, lib/natalie/compiler/instructions/instance_variable_get_instruction.rb, lib/natalie/compiler/instructions/instance_variable_set_instruction.rb, lib/natalie/compiler/instructions/next_instruction.rb, lib/natalie/compiler/instructions/push_object_class_instruction.rb, lib/natalie/compiler/instructions/push_range_instruction.rb, lib/natalie/compiler/instructions/return_instruction.rb, lib/natalie/compiler/instructions/string_append_instruction.rb, lib/natalie/compiler/instructions/to_array_instruction.rb, lib/natalie/compiler/instructions/yield_instruction.rb, test/bytecode/boardslam_test.rb, test/bytecode/point_test.rb
We can now run `point.rb` from https://ruby-compilers.com/examples/#example-program-pointrb and `boardslam.rb` from that animated gif on the Natalie page :laughing:
=> Bytecode VM: Support classes

include/natalie/module_object.hpp, src/module_object.cpp
=> Lock methods that iterate over the m_included_modules vector

test/bytecode/monkeypatch_test.rb
Another working script from https://ruby-compilers.com/examples/
=> Bytecode VM: Import monkey.rb example

lib/socket.cpp, lib/socket.rb, spec/library/socket/socket/getifaddrs_spec.rb
There is a FIXME marker left for adding information of the hardware addresses, this needs some extra support in Addrinfo. Besides that, the output is the same as MRI on my machine (the specs can't really test this deeply)
=> Implement Socket.getifaddrs

lib/socket.cpp, lib/socket.rb, spec/library/socket/socket/recvfrom_spec.rb
With still a few NATFIXMEs in the spec, but most of it works
=> Implement Socket#recvfrom

lib/natalie/compiler/instructions/create_complex_instruction.rb, lib/natalie/compiler/pass1.rb
* The `real` part is always `0`, don't use the stack for this
* Use `complex` instead of `range` as the variable name prefix
=> Small improvements to CreateComplexInstruction

lib/natalie/compiler/instructions/send_instruction.rb, lib/natalie/vm.rb, test/bytecode/puts_regexp_test.rb
This is the first yakshave for  #1988
=> Support $~ variable in bytecode/interpreted mode

spec/core/marshal/dump_spec.rb, spec/core/marshal/fixtures/classes.rb, spec/core/marshal/fixtures/marshal_data.rb
I wanted to fix the bug of  #1906, but after disabling over a 100 failing specs I'm kind of done with this for today. It still is a nice first step.
=> Import specs for Marshal.dump

spec/core/marshal/load_spec.rb, spec/core/marshal/restore_spec.rb, spec/core/marshal/shared/load.rb
Should be rebased after  #1994 is merged. And another one with 100+ skips
=> Import specs for Marshal.load

lib/natalie/compiler/binding_gen.rb, spec/core/io/write_spec.rb, src/io_object.cpp
Fixing bugs by removing code, my favourite
=> Support IO#write without arguments

lib/natalie/compiler/args.rb, lib/natalie/compiler/arity.rb, lib/natalie/compiler/pass1.rb, spec/language/numbered_parameters_spec.rb, test/natalie/argument_test.rb
This should resolve two compilation errors.
=> Support numbered parameters

examples/sslsocket.rb, lib/openssl.rb, test/natalie/openssl_test.rb
This sets some logical HTTPS defaults for the SSL socket.
=> Implement SSLContext#set_params

lib/natalie/compiler/bytecode/ro_data.rb, lib/natalie/compiler/instructions/push_string_instruction.rb, lib/natalie/compiler/pass1.rb, spec/core/proc/element_reference_spec.rb
It freezes the strings, but does not yet do any deduplication.
=> Support frozen_string_literal pragma

test/natalie/array_test.rb, test/natalie/dup_test.rb, test/natalie/marshal_test.rb, test/natalie/pp_test.rb, test/natalie/zlib_test.rb
This is the alternative and more future proof version of Ruby 3.4 compatibility
=> Fix some frozen string literals in Natalie tests

Gemfile.lock
=> Upgrade minitest gem to 5.23.0

README.md
I couldn't find any better name than `983` as the author, so I guess that's what we have to go with.
This one was missed in #2049.
=> Update bigint references in README

src/array_object.cpp, src/hash_object.cpp, test/natalie/array_test.rb, test/natalie/hash_test.rb
=> Fix Hash#replace and Array#replace with self

include/natalie/encoding_object.hpp, spec/core/string/capitalize_spec.rb, spec/core/symbol/capitalize_spec.rb, src/encoding_object.cpp, src/string_object.cpp
#217
This gets a few more specs passing.
=> Add unicode casemap in String#capitalize

lib/socket.cpp
This resolves an issue on my machine where the VPN interface didn't get an ifindex with the old implementation, but does get one with the new implementation. It reduces the complexity as well.
=> Use if_nametoindex to find the ifindex

spec/language/fixtures/for_scope.rb, spec/language/for_spec.rb
The compile time errors have been commented out
=> Import language specs for `for`

spec/language/fixtures/precedence.rb, spec/language/precedence_spec.rb
Only two compilation issues, the rest passes (which is probably just Prism fixing that for us).
=> Import language/precedence_spec

spec/core/string/element_reference_spec.rb
=> Add spec of String#[] that we are already passing

spec/language/rescue_spec.rb, test/natalie/rescue_test.rb
And remove our test for safe navigator writers, this one has been added in the upstream version.
=> Refresh specs for rescue

spec/core/string/dump_spec.rb, src/encoding/utf8_encoding_object.cpp, src/string_object.cpp
=> Make String#dump spec-compliant

include/natalie/global_env.hpp, lib/natalie/compiler/backends/cpp_backend.rb, lib/natalie/compiler/backends/cpp_backend/transform.rb, lib/natalie/compiler/instructions/push_string_instruction.rb, spec/language/hash_spec.rb, spec/language/string_spec.rb, src/global_env.cpp
A first attempt at interning frozen strings. This currently works for really basic scripts, since the garbage collector is not aware of these objects. For now, the GC is disabled in this branch.
=> Intern frozen string literals

lib/natalie/compiler/pass1.rb, spec/language/for_spec.rb
This was probably the easiest compile error fix I've ever written :rofl:
=> Support ImplicitRestNode in for statements

spec/core/string/shared/chars.rb
=> Refresh shared code for String#chars and String#each_chars specs

spec/language/for_spec.rb
This adds two new compile errors
=> Refresh specs for `for`

spec/language/numbers_spec.rb
This issue with the self hosted compiler appears to be resolved. It has probably been fixed in #2049.
=> Refresh language/numbers_spec

lib/natalie/compiler/multiple_assignment.rb, spec/language/fixtures/variables.rb, spec/language/variables_spec.rb
This resolves the compile error in https://github.com/ruby/spec/blob/master/language/variables_spec.rb
=> Support constants in splat set

lib/natalie/compiler/pass1.rb, src/exception.rb, test/natalie/pattern_matching_test.rb
This includes the first refactor of the pattern matching code (as promised :sweat_smile: ), and I'm already convinced I should extract this method into its own class, so refactor 2 is coming up
=> Support constants in pattern matching RHS

spec/core/string/encode_spec.rb, src/string_object.cpp
Just found some low hanging fruit ;)
=> Add check for frozen status in String#encode!

spec/core/marshal/dump_spec.rb, spec/core/regexp/union_spec.rb, spec/core/string/encode_spec.rb, spec/core/string/shared/encode.rb, spec/core/string/valid_encoding_spec.rb, src/encoding/utf16be_encoding_object.cpp, src/encoding_object.cpp, src/string_object.cpp, test/natalie/string_test.rb
=> Some misc. fixes for String#encode

spec/library/date/strftime_spec.rb, spec/shared/time/strftime_for_date.rb
Most of them pass with the added VERSION constant
=> Import specs for Date#strftime

spec/core/exception/detailed_message_spec.rb
This includes some extra checks for highlighting.
=> Refresh specs for Exception#detailed_message

spec/core/string/encoding_spec.rb
=> Refresh specs for String#encoding

spec/core/string/force_encoding_spec.rb
=> Refresh specs for String#force_encoding

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/grapheme_clusters_spec.rb, src/string_object.cpp
=> Add String#grapheme_clusters

lib/natalie/compiler/transformers/match_required_node.rb
Which is something I didn't even knew existed until just now.
=> Raise SyntaxError for pattern match with pinned expression

spec/core/string/valid_encoding_spec.rb
Mostly related to frozen string literals
=> Refresh valid_encoding_spec.rb

lib/natalie/compiler/pass1.rb, spec/language/assignments_spec.rb
```ruby
self.foo += bar
self[foo] += bar
```
=> Even more self assignment fixes

spec/core/complex/equal_value_spec.rb, spec/core/float/comparison_spec.rb, spec/core/hash/element_reference_spec.rb, spec/core/io/puts_spec.rb, spec/core/string/byteslice_spec.rb, spec/fixtures/constants.rb, spec/language/regexp_spec.rb, spec/library/socket/addrinfo/initialize_spec.rb
=> Import some upstream typo fixes in specs

include/natalie/io_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/io/close_spec.rb, spec/core/io/copy_stream_spec.rb, spec/core/io/lineno_spec.rb, spec/core/io/pid_spec.rb, spec/core/io/popen_spec.rb, spec/core/io/write_spec.rb, src/io_object.cpp
For now its functionality is pretty limited, but a number of unrelated specs depend on this method.
=> Implement first version of IO.popen

spec/core/exception/result_spec.rb, src/enumerator.rb, src/exception.rb
=> Implement Stopiteration#result

lib/socket.cpp
Or arguments of the wrong type.
=> Don't crash in Addrinfo.new with too short array argument

spec/core/enumerator/lazy/uniq_spec.rb, spec/core/kernel/loop_spec.rb, src/enumerator.rb, src/kernel_module.cpp
This includes an update to `StopIterator` to save the result.
=> Improve Kernel#loop

spec/core/thread/group_spec.rb
=> Refresh spec for Thread#group

spec/core/regexp/shared/new.rb, src/regexp_object.cpp
This is the first commit of #2229, this one works
=> Raise a RegexpError if less than four digits are given for \\uHHHH

spec/core/marshal/dump_spec.rb, spec/core/marshal/shared/load.rb, src/marshal.rb
This solves the infinite loop when dumping recursive structures.
=> Support object links in Marshal.dump

lib/stringio.rb, spec/library/stringio/puts_spec.rb, test/natalie/yaml_test.rb
Skip two specs for now, these look like generic issues that should be tested in other write methods and in other IO objects too. We probably need to extend some specs to get this tested.
=> Implement StringIO#puts

lib/stringio.rb, lib/time.rb, spec/library/date/time/to_date_spec.rb, spec/library/stringio/puts_spec.rb, test/natalie/yaml_test.rb
This has a few issues with calendar reform dates, but works in pretty much every normal day use case.
=> Implement Time#to_date

spec/library/stringio/each_line_spec.rb, spec/library/stringio/each_spec.rb, spec/library/stringio/shared/each.rb, spec/library/stringio/shared/read.rb
A couple of new specs have been added upstream.
=> Refresh specs for StringIO

lib/natalie/compiler/arity.rb, lib/natalie/compiler/macro_expander.rb, lib/natalie/compiler/pass1.rb, lib/natalie/parser.rb
This is going to take a while, the interface for creating the nodes has changed.
Once we've finished this one, the upgrade to Prism 1.2 should be easy again.
=> Switch to Prism 1.0

lib/ffi.cpp, lib/ffi.rb, spec/language/next_spec.rb, spec/language/redo_spec.rb, test/natalie/ffi_test.rb, test/support/ffi_stubs.c
The yak of the day: adding [enum](https://github.com/ffi/ffi/wiki/Enums) support in our FFI lib. I didn't even know FFI supported this.
=> Upgrade to Prism 1.1

spec/core/module/alias_method_spec.rb
About half of them are passing.
=> Import specs for Module#alias_method

lib/natalie/compiler/instructions.rb, lib/natalie/compiler/instructions/anonymous_block_get_instruction.rb, lib/natalie/compiler/instructions/anonymous_block_set_instruction.rb, lib/natalie/compiler/instructions/meta.rb, lib/natalie/compiler/pass1.rb, spec/language/block_spec.rb
I've implemented this in the simplest way I could think of. Let me know if adding new instructions makes sense or if there are different approaches on how we could implement anonymous forwarding. I'd also like to use this PR as a template for anonymous splat and keyword forwarding.
=> Add support for anonymous block forwarding

spec/core/io/stat_spec.rb, spec/core/unboundmethod/name_spec.rb
I guess these got imported in my local checkout with  #2297, but I missed the new files.
=> Import some new passing specs

spec/core/process/spawn_spec.rb, src/kernel_module.cpp
Which mostly mean we just throw the next error ;)
=> Some type conversion fixes in Process.spawn

spec/core/thread/element_reference_spec.rb, spec/core/thread/element_set_spec.rb, spec/core/thread/key_spec.rb, spec/core/thread/thread_variable_get_spec.rb, spec/core/thread/thread_variable_spec.rb, src/thread_object.cpp
This removes some cod duplication as well.
=> Fixes to key-value behaviour of threads

src/encoding_object.cpp, src/gc.cpp, src/thread_object.cpp, src/value.cpp
=> Initialize some variables that gcc 14 warns about

lib/natalie/compiler/pass1.rb, spec/language/for_spec.rb
This fixes the compile issues with `language/for_spec`
=> Fix scoping of variables in for loop

Rakefile, lib/libnat_api.cpp, lib/libnat_api.rb, lib/natalie.rb
Coming back to this much later had me confused about the role of each file, and I think this way is just a teensy bit better.
=> Rearrange the libnat files for clarity

lib/securerandom.cpp, lib/securerandom.rb, spec/library/securerandom/random_number_spec.rb, src/random_object.cpp
There is a lot of copy-paste going on, so this probably should be refactored at some point.
=> Implement Securerandom.random_bytes

lib/securerandom.cpp, spec/library/securerandom/random_number_spec.rb, src/random.rb, src/random_object.cpp, test/natalie/random_test.rb
Mostly just extra specs to get a baseline of the MRI behaviour
=> More fixes to argument types of Random.rand and (Secure)Random.random_number

spec/core/marshal/dump_spec.rb, spec/core/marshal/shared/load.rb, src/marshal.rb, src/time.rb
And add a stub method `Time#_dump`. This resolves the crashes in the nightly specs for Marshal.load/Marshal.restore.
=> Support _dump/_load in Marshal

test/support/spec.rb
This is required to support Time._load
=> Add include_super argument to have_private_method spec method

bin/natalie, lib/natalie/compiler/backends/cpp_backend/transform.rb, lib/natalie/compiler/bytecode/ro_data.rb, lib/natalie/compiler/instructions/create_range_instruction.rb, lib/optparse.rb
And fix some additional compiler warnings
=> Remove some unused variables

spec/core/dir/shared/exist.rb, spec/core/file/expand_path_spec.rb, src/file_object.cpp
There is one test about leading slashes that I think is stupid and don't care to support.
=> Make File.expand_path mostly spec-compliant

spec/core/marshal/dump_spec.rb, src/marshal.rb
=> Use bytesize to write number of bytes in Marshal.dump

include/natalie/class_object.hpp, include/natalie/module_object.hpp, lib/yaml.cpp, src/class_object.cpp, src/exception_object.cpp, src/kernel_module.cpp, src/module_object.cpp, src/object.cpp, src/value.cpp
This has bothered me for awhile, but I've just been too lazy to rename it until now.
=> Rename class_name => name for Modules

.github/workflows/test.yml, test/asan_test.rb, test/natalie/ffi_test.rb, test/natalie/fork_test.rb, test/natalie/libnat_test.rb, test/support/compare_rubies.rb
There are a couple tests that produce bugs, so I skipped them.
=> Add most of the test/natalie directory to ASan tests

.dockerignore, test/asan_test.rb
I also skipped `libnat_test.rb` since it's timing out.
=> Add spec/language/*_spec.rb to ASan tests

Rakefile, spec/support/test_perf.rb
This number may fluctuate more due to changes in features provided by the compiler, but also has a good chance of benefiting from improvements to the runtime.
=> Add self-hosted compiler to perf stats

.github/workflows/asan_tests.yml, .github/workflows/self_hosted_tests.yml, .github/workflows/test.yml, Rakefile, test/asan_test.rb
These take too long to run on every PR, so let's run them nightly.
I also added a check to only run it (and the self-hosted nightly workflow) if new commits are added.
=> Run all tests with AddressSanitizer nightly

spec/core/dir/home_spec.rb, src/dir_object.cpp
- Use `getpwuid(getuid())` if HOME is unset
- Return current user's home if given username is nil
- Fix error message
=> Fix Dir#home

lib/yaml.cpp, test/natalie/yaml_test.rb
=> Dynamically resize yaml output buffer as needed

lib/zlib.cpp, src/kernel_module.cpp
These were found after the changes in #2446. AddressSanitizer is very handy, but it's weird how seemingly random it is at doing it's job.
=> A couple more fixes thanks to AddressSanitizer

include/natalie/gc/allocator.hpp, include/natalie/gc/heap.hpp, include/natalie/gc/heap_block.hpp, src/gc.cpp
=> Performance improvements in garbage collector

test/natalie/string_test.rb
This one passes, so there is no need to skip this one.
=> Enable a test for String#chop! with empty string

src/file_object.cpp
There is a helper function that removes our code duplication.
=> Simplify path conversion in File.lutime

spec/core/string/shared/length.rb, src/encoding/utf8_encoding_object.cpp
=> Make String#length spec-compliant

spec/core/string/gsub_spec.rb, spec/core/string/match_spec.rb, src/string_object.cpp
=> Make String#match spec-compliant

README.md, lib/abbrev.rb, spec/library/abbrev/abbrev_spec.rb
=> Import abbrev gem

lib/natalie/compiler.rb, test/natalie/require_test.rb, test/support/require/simple.rb
=> Fix top-level variables confusion with loaded files

lib/socket.cpp, test/natalie/socket_test.rb
#2095
This seems to be what CRuby does, and eliminates the barf of EAGAIN errors from 9 of the 10 children in natalie-lang.org's [server.rb](https://github.com/natalie-lang/natalie-lang.org/blob/master/server.rb).
=> Handle EAGAIN in Server#accept

include/natalie/array_object.hpp, src/array_object.cpp
Use more concat and move instructions.
=> Optimizations in Array#[]=

test/bytecode/boardslam_test.rb
Don't hardcode the result, but run it through Natalie without bytecode too.
This was the missing file from #2478.
=> Update test for bytecode variant of boardslam

lib/ffi.cpp
This updates the ext/tm submodule, which includes some additional fixes as well.
=> Use TM::String::begins_with in FFI

src/array_object.cpp
Callgrind instructions are slightly down again
=> Use more vector concatenation in Array

lib/natalie/compiler/instructions/push_regexp_instruction.rb, lib/natalie/compiler/instructions/string_to_regexp_instruction.rb, lib/natalie/compiler/pass1.rb, lib/natalie/compiler/regexp_encoding.rb, src/regexp_object.cpp
This makes it easier to add other encodings.
=> Cleanups for regexp encoding

lib/natalie/compiler/binding_gen.rb
Every time I'm in this file I get confused about which binding method does what. So I renamed them based on how my brain works. I also eliminated some duplicate code.
=> Refactor binding_gen.rb

lib/natalie/compiler.rb, test/natalie/compiler_debug_output_test.rb
=> Fix compiler debug output

include/natalie/integer_object.hpp, include/natalie/process_module.hpp, include/natalie/thread/backtrace/location_object.hpp, include/natalie/value.hpp, lib/etc.cpp, lib/fiddle.rb, lib/openssl.cpp, lib/socket.cpp, lib/zlib.cpp, src/array_object.cpp, src/binding_object.cpp, src/dir_object.cpp, src/integer_object.cpp, src/kernel_module.cpp, src/natalie.cpp, src/nil_object.cpp, src/object.cpp, src/rational_object.cpp, src/regexp_object.cpp, src/string_object.cpp, src/string_unpacker.cpp, src/time_object.cpp
There are still a few more, but they will require some more thought...
=> Change `new IntegerObject` to `Value::integer()` where it's easy

src/string_object.cpp
Which can be used in a whopping 2 locations, so all this work is going to have zero effect at all :sweat_smile:
=> Use string views as arguments to env->raise

include/natalie/env.hpp, include/natalie/global_env.hpp, include/natalie/string_object.hpp, lib/json.rb, lib/natalie/compiler/instructions/push_string_instruction.rb, lib/natalie/compiler/pass1.rb, lib/stringio.rb, spec/core/string/chilled_string_spec.rb, src/complex.rb, src/global_env.cpp, src/marshal.rb, src/module_object.cpp, src/object.cpp, src/string_object.cpp
Next up: refactor our warning module, we should not have to do a bunch of constant lookups just to see if we did change a boolean.
=> Add support for chilled strings

src/string_object.cpp, test/natalie/kernel_integer_test.rb
This triggered an assertion error, throw a regular Ruby exception instead.
=> Fix behaviour of `Integer('-')` and `Integer('+')`

spec/core/integer/left_shift_spec.rb, spec/core/integer/right_shift_spec.rb, src/integer_object.cpp
And right is halfway there too, but I'm going to call it a day.
=> Fix timeout in spec for integer left shift

include/natalie/array_packer/integer_handler.hpp, include/natalie/bigint.hpp, include/natalie/gc/cell.hpp, include/natalie/integer.hpp, include/natalie/integer_methods.hpp, include/natalie/kernel_module.hpp, include/natalie/object.hpp, include/natalie/object_type.hpp, include/natalie/time_object.hpp, include/natalie/value.hpp, lib/natalie/compiler/binding_gen.rb, lib/yaml.cpp, src/bigint.cpp, src/gc.cpp, src/integer.cpp, src/integer_methods.cpp, src/kernel_module.cpp, src/object.cpp, src/time_object.cpp, src/value.cpp
Following on from #2591, this changes `Value` to a tagged pointer, a single 64-bit number.
=> Use same tagged-pointer approach for Value

spec/shared/kernel/complex.rb, src/kernel_module.cpp
This needed the fix of #2602 to work
=> Coerce rational String input to Complex

include/nathelpers/typeinfo.hpp, lib/ffi.cpp, test/natalie/ffi_test.rb, test/support/ffi_stubs.c
We now support all types of ffi-mysql. Still to do: enum class and ffi-struct.
=> FFI: Support unsigned long long type

spec/core/string/to_f_spec.rb
I can't believe we were missing this file
=> Import specs of String#to_f

include/natalie/string_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/string/squeeze_spec.rb, src/string_object.cpp
=> Implement String#squeeze and String#squeeze!

ext/tm/include/tm/string_view.hpp, src/string_object.cpp
And remove another unnecessary string_view->string conversion
=> Implement TM::StringView::cmp

spec/core/string/sub_spec.rb
They are passing, so I'm not sure why the block didn't complain about a lack of expected exception raises.
=> Remove NATFIXME blocks for Hash argument in String#sub

spec/language/singleton_class_spec.rb
This resolves a warning concerning chilled strings
=> Refresh specs for singleton_class

lib/natalie/compiler/comptime_values.rb
It looks like it works out of the box
=> Switch to Prism 1.4.0

src/file_object.cpp
This was extracted from #2663.
=> Fix compile error on newer clang

src/dir_object.cpp, test/natalie/dir_test.rb
This was extracted from #2663.
=> Fix Dir.chdir for use with throw/catch

include/natalie/symbol_object.hpp, src/file_object.cpp, test/ruby/ruby_specs_test.rb, test/support/command.rb
I introduced a deadlock condition in #2669 by mistake, oopsie.
My first theory was that `File#flock` was being interrupted by the GC, so I fixed that. But  that wasn't the real problem here.
=> Fix timeouts in self hosted compiler

lib/stringio.rb, spec/core/array/pack/a_spec.rb, spec/core/array/pack/z_spec.rb, spec/core/array/sample_spec.rb, spec/core/array/shuffle_spec.rb, spec/core/dir/chdir_spec.rb, spec/core/float/round_spec.rb, spec/core/kernel/fixtures/classes.rb, spec/core/kernel/open_spec.rb, spec/core/marshal/dump_spec.rb, spec/core/range/max_spec.rb, spec/core/range/shared/cover_and_include.rb, spec/core/string/shared/dedup.rb, spec/core/string/shared/slice.rb, spec/core/string/unpack_spec.rb, spec/core/struct/deconstruct_keys_spec.rb, spec/core/struct/fixtures/classes.rb, spec/core/struct/keyword_init_spec.rb, spec/core/struct/members_spec.rb, spec/core/time/now_spec.rb, spec/language/ensure_spec.rb, spec/language/numbered_parameters_spec.rb, spec/language/rescue_spec.rb, spec/library/socket/basicsocket/recv_nonblock_spec.rb, spec/library/socket/socket/gethostname_spec.rb, spec/library/stringio/shared/read.rb
This excludes the changes for stringscanner, this library has a lot of changes that are version related and are just too much to update now, this can be treated as a separate project.
=> Update specs after mass update upstream

spec/core/data/equal_value_spec.rb, test/natalie/data_test.rb
This runs into infinite recursion/stack overflow for recursive structures, disable those for now.
Remove our local tests for Data equality, these have become superfluous.
=> Import specs for Data#==

include/natalie/array_packer/float_handler.hpp, include/natalie/array_packer/integer_handler.hpp, include/natalie/array_packer/packer.hpp, include/natalie/array_packer/string_handler.hpp, include/natalie/constant.hpp, include/natalie/gc/allocator.hpp, include/natalie/gc/heap_block.hpp, include/natalie/gc_module.hpp, include/natalie/global_variable_info.hpp, include/natalie/hash_object.hpp, include/natalie/string_unpacker.hpp, include/natalie/throw_catch_exception.hpp, lib/natalie/compiler/binding_gen.rb, src/constant.cpp, src/gc.cpp, src/gc_module.cpp, test/natalie/gc_test.rb
...and add some debugging methods.
=> Fix GC arithmetic

lib/strscan.rb, spec/library/stringscanner/scan_full_spec.rb, spec/library/stringscanner/search_full_spec.rb
And refresh the specs for scan_full, since we've aliased this one. We still have a few failures in search_full, these are the steps where these two methods diverge.
=> Improve StringScanner#search_full

spec/core/time/strftime_spec.rb, spec/shared/time/strftime_for_date.rb, spec/shared/time/strftime_for_time.rb
Since part of the specs are shared with the Date class, we might have to fix them simultaneously.
=> Import specs for Time#strftime

include/natalie/array_object.hpp, include/natalie/exception_object.hpp, include/natalie/hash_object.hpp, include/natalie/io_object.hpp, include/natalie/regexp_object.hpp, include/natalie/time_object.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/time/minus_spec.rb, src/exception_object.cpp, src/file_object.cpp, src/file_stat_object.cpp, src/hash_object.cpp, src/io_object.cpp, src/string_object.cpp, src/time_object.cpp
That was far less of a chore than I expected it to be
=> Move ClassObject* argument before the method call arguments

spec/core/exception/errno_spec.rb, src/errno.rb
Quick and dirty fix, just to start working on this. I'm probably going to refactor this another 20 times
=> Fix "Errno::EINVAL can be called with no arguments"

lib/natalie/repl.rb
Catch "unexpected end-of-input" parser errors and await more input.
These errors are likely due to incomplete code such as but not limited to:
- open brackets that are yet to be closed
- module, class, method, block, loop definitions that don't yet have a corresponding `end`
- operators where an operand is specified on a subsequent line
When these errors are caught, we change the prompt from 'nat> ' to 'nat* '
to signal to the user that further input is need before we can evaluate their code.
We keep track of all the lines input by the user until the parser no longer returns an
"unexpected end-of-input" error.
At that point we either proceed with the compilation or show the user the error if there is one.
=> allow repl to accept more lines if code incomplete

lib/strscan.rb, spec/library/stringscanner/check_until_spec.rb
Most important: it fixes a timeout , so it makes the remaining failures show up on https://natalie-lang.org/specs
=> Fixes in StringScanner#check_until

spec/core/exception/exit_value_spec.rb, spec/language/rescue_spec.rb, spec/language/undef_spec.rb, spec/shared/kernel/raise.rb, test/support/spec.rb
This spec was crashing, which is a separate issue. The block based check was incorrect, it did not check the message or the exception class.
=> Import specs for LocalJumpError#exit_value

lib/socket.cpp, spec/library/socket/addrinfo/getaddrinfo_spec.rb
=> Make Addrinfo.getaddrinfo spec compliant

lib/socket.cpp, spec/library/socket/socket/recvfrom_spec.rb
=> Fixes to pfamily and socktype values in Socket#recvfrom

lib/socket.cpp, lib/socket.rb, spec/library/socket/basicsocket/connect_address_spec.rb, spec/library/socket/shared/address.rb, spec/library/socket/socket/local_address_spec.rb, spec/library/socket/socket/remote_address_spec.rb, spec/library/socket/tcpsocket/local_address_spec.rb, spec/library/socket/tcpsocket/remote_address_spec.rb, spec/library/socket/udpsocket/local_address_spec.rb, spec/library/socket/udpsocket/remote_address_spec.rb, spec/library/socket/unixsocket/local_address_spec.rb, spec/library/socket/unixsocket/remote_address_spec.rb
More split from #2761
Behold the power of copy-paste.
=> Fix pfamily/socktype in result of BasicSocket#local_address and #remote_address

include/natalie/env.hpp, lib/socket.cpp, src/dir_object.cpp, src/env.cpp, src/file_object.cpp, src/io_object.cpp, src/kernel_module.cpp
This enables us to raise a specific errno without having to assign it.
This is a future work from  #2767
=> Add raise_errno(int) function

include/natalie/random_object.hpp, lib/socket.cpp, src/time_object.cpp
This slightly speeds up some things due to less string copies.
=> Prefer move semantics over VLA for locally created string buffers

lib/natalie/compiler/macro_expander.rb, spec/fixtures/code/file_fixture.rb, spec/fixtures/code_loading.rb, spec/language/file_spec.rb, spec/language/shared/__FILE__.rb, test/support/spec.rb
This has one spec actually passing, and required a bunch of additional file to even start.
=> Import specs for __FILE__

include/natalie/kernel_module.hpp, lib/natalie/compiler/binding_gen.rb, spec/core/kernel/define_singleton_method_spec.rb, src/kernel_module.cpp
This fixes the crash in the spec
=> Fix two argument style for define_singleton_method

spec/core/time/zone_spec.rb
=> Import specs for Time#zone

.github/dependabot.yml, .github/workflows/asan_tests.yml, .github/workflows/codeql_analysis.yml, .github/workflows/format.yml, .github/workflows/lint.yml, .github/workflows/perf_test.yml, .github/workflows/run_all_specs.yml, .github/workflows/self_hosted_tests.yml, .github/workflows/test.yml, .github/workflows/tm.yml
This should help with keeping some things up to date.
=> Add Dependabot for Github actions
